- Cargo.lock
- Cargo.toml
- sqlite3/Cargo.toml
- sqlite3/build.rs
- sqlite3/cbindgen.toml
- sqlite3/examples/example.c
- sqlite3/include/sqlite3.h
- sqlite3/src/lib.rs
- sqlite3/tests/.gitignore
- sqlite3/tests/Makefile
- sqlite3/tests/check.h
- sqlite3/tests/main.c
- sqlite3/tests/test-close.c
- sqlite3/tests/test-open.c
This patch adds initial SQLite C compatibility library to Limbo to make sure we drive the Rust API in the right way that allows us to implement SQLite semantics.
> SQLite C ABI compatibility

- core/translate.rs
- core/types.rs
- core/vdbe.rs
```
Welcome to Limbo SQL shell!
> select sum(age), avg(age) from users;
504915|50.4915
>
fedora :: ~/fun/limbo » sqlite3 database.db
SQLite version 3.40.1 2022-12-28 14:03:47
sqlite> select sum(age), avg(age) from users;
504915|50.4915
```
fixes #33
> core: sum aggregation

- core/translate.rs
For now this works:
```sql
> select avg(age), 2 from users
50.4915|2
```
This case must be optimized in the future:
```sql
> select avg(age), id from users
50.4915|10000
> explain select avg(age), id from users
addr  opcode         p1    p2    p3    p4             p5  comment
----  -------------  ----  ----  ----  -------------  --  -------
0     Init           0     13    0                    0   Start at 13
1     OpenReadAsync  0     2     0                    0   root=2
2     OpenReadAwait  0     0     0                    0
3     RewindAsync    0     0     0                    0
4     RewindAwait    0     12    0                    0
5     Column         0     9     2                    0   r[2]= cursor 0 column 9
6     AggStep        0     2     0     avg            0   accum=r[0] …
```
> core: fix evaluating columns a part from agg

- core/types.rs
- core/vdbe.rs
The SQLite documentation explicitly says that P1, P2, and P3 are 32-bit signed integers. P4 is a value, and P5 is a 16-bit unsigned integer. Although we use different types for operands, the `EXPLAIN` output should be compatible with SQLite and, therefore, use those types.
> Clean up insn_to_str()

- core/io/linux.rs
The submit_and_wait command waits for `n` completion events. We were providing an incorrect argument, which caused the issue.
Fixes #74
> wait for the read completion

- core/lib.rs
- core/types.rs
This allows to avoid some unneeded copies and allocations.
> Make it possible to get row values as &str

- core/translate.rs
When the args are empty in aggregate function like
```sql
SELECT COUNT() FROM users; // This is valid
SELECT AVG() from users; // this must give error
```
The value of info.args.as_ref() is None which make the program crash due to unwrap().
All the implementation till now of aggrigate function check the args using args.len() then are assuming that the args after unwrap will be an empty array. But that not the case as we have explained before.
This pr, created an empty args vector then the args is None.
> fix: unhanded empty args in aggregate function

- cli/main.rs
- core/translate.rs
- core/vdbe.rs
- testing/all.test
Values in sqlite3, as expected, can be stored in different formats to optimize disk usage. In this case, a 79.0 float will be transformed to a u8.
sqlite3 deals with this by adding a RealAffinity op after each column that might need it. Therefore, in this pr we do exactly that :).
```sql
sqlite> explain select price from products limit 1;
addr  opcode         p1    p2    p3    p4             p5  comment
0     Init           0     10    0                    0   Start at 10
1     Integer        1     1     0                    0   r[1]=1; LIMIT counter
2     OpenRead       0     3     0     3              0   root=3 iDb=0; products
3     Rewind         0     9     0                    0
4       Column         0     2 …
```
> core: apply Real affinity on columns stored as int

- core/vdbe.rs
Fixes #112 
Apart from indenting only the opcode value:
1. Increased the space for opcode column from 13 to 17
2. Changed p4 to p4.to_string() to maintain the spacing and align columns correctly
Sample output after these changes:
```
> explain select max(price) from users, products limit 1;
0     Init               0     21    0                    0   Start at 21
1     Integer            0     1     0                    0
2     OpenReadAsync      0     2     0                    0   root=2
3     OpenReadAwait      0     0     0                    0
4     OpenReadAsync      1     3     0                    0   root=3
5     OpenReadAwait      0     0 …
```
> Align columns in EXPLAIN command

- core/translate.rs
- core/types.rs
- core/vdbe.rs
- testing/all.test
- Returns 0.0 when called on non integer / non float columns
- Always returns floating point number
- fix: default for sum() should be NULL when there is no non-NULL row per docs
related: #93
> Implement total() aggregation function

- Cargo.lock
- core/function.rs
- core/translate.rs
- core/vdbe.rs
- testing/all.test
New features:
- Adds `coalesce()`
- adds enum `Func` with variants `AggFunc` (existing) and `SingleRowFunc` (new)
---
Jump handling changes:
- Rename `ProgramBuilder.add_label()` to `ProgramBuilder.add_label_dependency()` (reflects what the method does better)
- Add `ProgramBuilder.preassign_label_to_next_insn()` (needed in e.g. the `coalesce` implementation -- we know we need to jump to "the part after coalesce", but we don't / can't know exactly where that is -- depends on the query)
- Add `ProgramBuilder.emit_insn_with_label_dependency()` (every `program.add_label()` was followed by an `.emit_insn()` so this is a helper to do those two things together)
---
EXPLAIN outputs:
limbo:
```
> explain select id, coalesce(age, 100) from users limit 1;
addr  opcode             p1    p2    p3 …
```
> Implement coalesce && refactor/rename a few things in the labeling system

- core/translate.rs
- core/vdbe.rs
addresses #122
I was exploring support for basic joins, but without this optimization it would have just added more spaghetti to `translate_expr()`.
-> add separate handling for processing AST nodes when we know the top AST node specifies a condition expression (where, join)
Limbo:
```
>  explain select id from users where first_name = 'John';
0     Init               0     13    0                    0   Start at 13
1     OpenReadAsync      0     2     0                    0   root=2
3     RewindAsync        0     0     0                    0   
4     RewindAwait        0     12    0 …
```
> Optimize where clause bytecode

- .github/workflows/rust.yml
- cli/main.rs
- core/translate.rs
- testing/all.test
- run test suite using sqlite3@3.46.0 on ubuntu
- Fix: return empty string for NULL values in limbo cli, like sqlite3 cli does
- Comment out a test temporarily
> Test with sqlite3 executable in CI as well

- testing/agg-functions.test
- testing/all.test
- testing/coalesce.test
- testing/join.test
- testing/pragma.test
- testing/select.test
- testing/where.test
Split the compat tests into separate files, allowing developers to run subset of the tests too.
> Clean up compat tests

- Cargo.lock
- core/Cargo.toml
- core/io/linux.rs
Let's switch to io_uring opcodes that are supported across all versions, but also enable direct I/O optimistically, but allow it to fail.
Tested-by: Joan Fontanals (@JoanFM)
> Fix io_uring support on older Linux kernels

- core/btree.rs
- core/sqlite3_ondisk.rs
Reading index btrees is the first step to implementing ORDER BY
> Read raw bytes for index btree pages

- Cargo.lock
- core/Cargo.toml
- core/io/common.rs
- core/io/darwin.rs
- core/io/generic.rs
- core/io/linux.rs
- core/io/mod.rs
- core/io/windows.rs
- simulator/main.rs
This PR addresses #94 by:
- Added support to prevent multiple processes from opening the same database file on Linux and Darwin.
- Implemented using POSIX advisory locks, which takes a lock on the `{pid, inode}`. However, this means multiple threads from the same process can open the file concurrently.
- Added option to disable file locking, useful for opening multiple shells during development.
> Disallow multiple processes opening same database file

- core/btree.rs
- core/sorter.rs
- core/translate.rs
- core/types.rs
- core/vdbe.rs
- testing/join.test
Left join algorithm, always using a nested loop join (reverse engineered from `sqlite3` with `pragma automatic_index = 0;` - thanks @pereman2 for the tip):
```
0     Init               0     25    0                    0   Start at 25
1     OpenReadAsync      0     2     0                    0   root=2
3     OpenReadAsync      1     3     0                    0   root=3
4     OpenReadAwait      0     0     0                    0   
5     RewindAsync        0     0     0                    0   
6     RewindAwait        0     24    0                    0   
7       Integer          0     1 …
```
> Left join initial nested loop implementation

- CHANGELOG.md
- COMPAT.md
Changed all JOIN compat entries to `Partial` because it's more accurate -- we don't support e.g. multiple joins and no guarantees that queries will yield correct results.
Which reminds me, should we have a separate compat test set with intentionally failing queries for unimplemented / incorrectly functioning features? I.e. run same test for both sqlite3 and limbo and expect the same result
> Update changelog/compat re: joins

- COMPAT.md
- core/expr.rs
- core/function.rs
- core/vdbe.rs
- testing/scalar-functions.test
This is related to the issue #144. Here is the bytecode comparison from sqlite vs limbo
sqlite:
limbo:
> implementation of scalar functions `upper` and `lower`

- COMPAT.md
- core/expr.rs
- core/function.rs
- core/vdbe.rs
- testing/scalar-functions.test
This is related to the issue https://github.com/penberg/limbo/issues/144. Add the scalar function `trim(X)` and `trim(X,Y)`
> implementation of scalar function `trim(X)` and `trim(X,Y)`

- COMPAT.md
- core/expr.rs
- core/function.rs
- core/vdbe.rs
- sqlite3/tests/Makefile
- testing/scalar-functions.test
This is related to the issue https://github.com/penberg/limbo/issues/144. Add the scalar function `round(X)` and `round(X,Y)`
> implementation of scalar function `round(X)` and `round(X,Y)`

- sqlite3/include/sqlite3.h
- sqlite3/src/lib.rs
- sqlite3/src/util.rs
Did up an attempt at the first few implementations required for [this issue](https://github.com/penberg/limbo/issues/128). Let me know if there's anything I can improve on/rework to be cleaner!
Referenced [this file](https://github.com/sqlite/sqlite/blob/master/src/main.c) when doing up this attempt, not entirely sure if `sqlite3_mutex_enter` and `sqlite3_mutex_leave` should be included at this point.
The error faced currently when backtrace is switched on should now be attributed to `sqlite3_busy_timeout` not being implemented, rather than `sqlite3_errcode`:
Thanks!
> Add implementations of sqlite3 error codes and messages for compatibility with CPython

- core/expr.rs
- core/function.rs
- core/vdbe.rs
- testing/scalar-functions.test
Refactor the match `SingleRowFunc ` and add the scalar function `length(X)` (related to the issue https://github.com/penberg/limbo/issues/144)
> implementation of scalar function `length(X)`

- Cargo.toml
- bindings/wasm/lib.rs
- cli/main.rs
- core/btree.rs
- core/lib.rs
- core/pager.rs
- core/vdbe.rs
- core/where_clause.rs
- perf/latency/limbo/Cargo.lock
- perf/latency/limbo/Cargo.toml
- perf/latency/limbo/src/main.rs
- simulator/main.rs
- sqlite3/src/lib.rs
- sqlite3/src/util.rs
In my aim to see how the `perf/latency` works,  I encountered some issues when compiling it, here I have a fix to allow compilation.
However, I miss the instructions to run it.
Is it expected for a user to `create N database files` names in a specific manner?
> perf-latency: Fixes to enable building perf/latency 

- core/function.rs
- core/translate/expr.rs
- core/vdbe.rs
- testing/scalar-functions.test
This is related to issue #144.  Currently the name of the scalar functions min and max are conflicting with the aggregated functions min and max. I am using min_arr and max_arr instead and wanted to get your input on what we can do to keep both with the same name. What comes to my mind is adding conditional logic inside AggFunc::Min/Max.
> implement min max scalar function

- core/translate/expr.rs
- core/translate/mod.rs
- core/translate/select.rs
- core/translate/where_clause.rs
- core/vdbe/builder.rs
- core/vdbe/mod.rs
- sqlite3/src/lib.rs
- testing/join.test
Features:
- Support multiple joins instead of just one
Architectural changes:
- Make all constraints a list of WhereTerms in a ProcessedWhereClause instead of separate `where_clause` and `join_clause`; gets rid of `QueryConstraint` in favor of just `ProcessedWhereClause` which is currently just a wrapper for `Vec<WhereTerm>`
- A `WhereTerm` contains an AST expression plus an indication during which loop in the join the condition should be evaluated
- Add more metadata to `LoopInfo` mainly to indicate whether that loop contains a left join and to add labels/metadata associated with that left join
- Emit condition instructions in `translate_table_open_loop` depending on which cursor it is
- In both `translate_table_open_loop` and `translate_tables_end`, emit instructions relevant to left …
> Refactor join processing / support multiway joins

- .github/workflows/rust.yml
Let's run `cargo bench` just to make sure we don't keep breaking it all the time. As a follow up, it would be cool to upload the results to Nyrkiö, for example.
> github: Add `cargo bench` to CI

- core/benches/benchmark.rs
closes issue #217. 
I separated the benchmark code into two functions one for limbo code and another for rusqlite. Now all the benchmark test are working. 
screenshot from the rusqlite tests:
> bench: fix db lock on benchmark code by splitting the scopes

- Cargo.lock
- bindings/wasm/Cargo.toml
- bindings/wasm/lib.rs
- core/Cargo.toml
- core/btree.rs
- core/datetime.rs
- core/error.rs
- core/io/common.rs
- core/io/darwin.rs
- core/io/generic.rs
- core/io/linux.rs
- core/io/mod.rs
- core/io/windows.rs
- core/lib.rs
- core/pager.rs
- core/pseudo.rs
- core/schema.rs
- core/sqlite3_ondisk.rs
- core/storage.rs
- core/translate/expr.rs
- core/translate/mod.rs
- core/translate/select.rs
- core/translate/where_clause.rs
- core/types.rs
- core/vdbe/mod.rs
- core/vdbe/sorter.rs
- simulator/Cargo.toml
- simulator/main.rs
Switch anyhow to explicit `LimboError` type using thiserror crate, which lets us make error handling more structured.
> Kill anyhow usage

- core/translate/mod.rs
- core/vdbe/mod.rs
Let's add module-level documentation for the code generator in `translate` and the virtual machine in `vdbe`, which are two major subsystems in the database engine that developers work on mostly.
> core: Add module-level docs for translate and vdbe

- core/translate/where_clause.rs
- testing/where.test
Fixes #154 
Implemented for now using as a series of OR checks (`foo IN (...)`) or AND checks (`foo NOT IN (...)`). SQLite uses a similar approach for small lists of values and starts making ephemeral indexes for larger lists. For now we just always do SQLite's "small list" approach since we don't have all the plumbing for ephemeral indexes yet.
I also refactored `translate_condition_expr` to take a `ConditionMetadata` argument always containing explicit success/failure jump labels plus `jump_on_success: bool`, which at least to my dumb ass, made the code a bit clearer. Your mileage may vary.
> core/translate: #154: implement WHERE IN (...)

- core/translate/select.rs
- core/translate/where_clause.rs
- testing/join.test
- testing/where.test
Example 1: jump immediately to halt when WHERE is always false
```
limbo> explain select first_name from users where 1 and 0;
0     Init               0     11    0                    0   Start at 11
1     OpenReadAsync      0     2     0                    0   root=2
3     RewindAsync        0     0     0                    0   
4     RewindAwait        0     -5    0                    0   
5       Goto             0     10    0                    0   
6       Column           0     1     1                    0   r[1]=users.first_name
7       ResultRow        1     1     0 …
```
> Optimize constant conditions

- core/translate/expr.rs
- core/translate/select.rs
As a cleanup, fold the columns struct member into column_info by introducing a `raw_column` in `ColumnInfo` struct.
> core: Fold columns into column_info in Select struct

- COMPAT.md
- core/datetime.rs
- core/error.rs
- core/function.rs
- core/translate/expr.rs
- core/vdbe/mod.rs
- testing/scalar-functions.test
Partially support time() scalar function tracked by #158 (not supported modifier yet).
ref: https://www.sqlite.org/lang_datefunc.html
Existing date() function support
```
limbo> explain select date();
0     Init               0     4     0                    0   Start at 4
1     Function           1     0     1     date           0   r[1]=func(r[0..])
2     ResultRow          1     1     0                    0   output=r[1]
3     Halt               0     0     0                    0
4     Transaction        0     0     0                    0
5     Goto               0     1     0                    0
```
added time()
```
limbo> explain select time(); …
```
> feat: add time() scalar function partial support without modifier #158

- core/pseudo.rs
- core/storage/btree.rs
- core/translate/select.rs
- core/translate/where_clause.rs
- core/types.rs
- core/vdbe/builder.rs
- core/vdbe/explain.rs
- core/vdbe/mod.rs
- core/vdbe/sorter.rs
- testing/join.test
- testing/where.test
The SQLite `SeekRowid` instruction tries to find a record in a B-tree table with a particular `rowid`  (or INTEGER PRIMARY KEY, if defined), and jumps if it is not found. In this PR, constraints like `tbl.id = 5` or `tbl.id = tbl2.id` are transformed into special `SeekRowid` expressions that emit `SeekRowid` VM instructions. This avoids a table scan and instead completes in `log N` time (for a table of `N` rows), because of how B-Trees work.
`LoopInfo` now contains a `Plan` which is either `Scan` or `SeekRowid` -- in the case of `SeekRowid` no `Rewind`/`Next` instructions are emitted - i.e. no looping is done.
`BTreeCursor` now implements a `btree_seek_rowid()` method that tries to find a row by `rowid`.
Our loop order is currently static, i.e. `SELECT * from a join b join c` always …
> Use SeekRowId to avoid nested scans

- Makefile
- flake.nix
this pr:
- updates the nix flake to include tcl 8.6 addressing #243 
- updates the nix flake to add the darwin "core foundation" lib
- updates the make flake to link the core foundation lib on darwin
I was previously unable to run `make test-sqlite3` with this error: https://gist.github.com/ethanniser/5b96888637da6ea9e9d56dcc3af9b573
but now it is able to run
although I am aware this might be just a me issue I have to work around, rather than something that belongs proper in the makefile so open to thoughts there
thanks as always
> update flake and add darwin link flags

- .github/workflows/release.yml
- Cargo.toml
saw you were building a windows bin but not a ps installer and thought i would turn it off. also turned on github attestations because why not.
`cargo dist plan` is basically the same as before but now also produces the PS installer.
```
announcing v0.0.3
limbo 0.0.3
source.tar.gz
[checksum] source.tar.gz.sha256
limbo-installer.sh
limbo-installer.ps1
limbo-aarch64-apple-darwin-update
limbo-aarch64-apple-darwin.tar.xz
[bin] limbo
[misc] CHANGELOG.md, LICENSE.md, README.md
[checksum] limbo-aarch64-apple-darwin.tar.xz.sha256
limbo-x86_64-apple-darwin-update
limbo-x86_64-apple-darwin.tar.xz
[bin] limbo
[misc] CHANGELOG.md, LICENSE.md, README.md
[checksum] limbo-x86_64-apple-darwin.tar.xz.sha256
limbo-x86_64-pc-windows-msvc-update
limbo-x86_64-pc-windows-msvc.zip
[bin] limbo.exe
[misc] …
```
> update cargo-dist and enable PS installer/github attestations

- Cargo.lock
- cli/Cargo.toml
- cli/main.rs
Fix #260 by ensuring `Ctrl-C` interrupts the query without terminating the process. Implement the SQLite strategy where pressing `Ctrl-C` twice exits the shell
> fix: ctrl-c stop current query execution

- core/schema.rs
- core/translate/expr.rs
- core/translate/insert.rs
This pull request addresses [issue #256](https://github.com/penberg/limbo/issues/256). 
However, it currently breaks insertions into tables that lack a row-id alias due to the NewRowId not being implemented yet. I have created an [issue](https://github.com/penberg/limbo/issues/275) to track this problem and will submit a separate pull request to resolve it soon.
> Use the correct integer PK column idx as the row-id alias

- COMPAT.md
- core/function.rs
- core/translate/expr.rs
- core/vdbe/mod.rs
- testing/scalar-functions.test
Implement (scalar) char function support 
https://github.com/penberg/limbo/issues/144
> Implement char function support

- COMPAT.md
- core/function.rs
- core/translate/expr.rs
- core/vdbe/explain.rs
- core/vdbe/mod.rs
- testing/scalar-functions.test
Add support for `ifnull` scalar function 
https://github.com/penberg/limbo/issues/144
> Add support for ifnull scalar function

- COMPAT.md
- core/function.rs
- core/translate/expr.rs
- core/vdbe/mod.rs
- testing/scalar-functions.test
Add support for concat scalar function 
https://github.com/penberg/limbo/issues/144
> Add support for concat scalar function

- bindings/wasm/lib.rs
- core/io/darwin.rs
- core/io/generic.rs
- core/io/linux.rs
- core/io/mod.rs
- core/io/windows.rs
- simulator/main.rs
Took a stab at the RNG portion of this [issue](https://github.com/penberg/limbo/issues/272), do let me know if there's anything that I can improve on/rework!
Thanks!
> Added random number generation to I/O trait for simulation

- core/translate/expr.rs
- core/vdbe/explain.rs
- core/vdbe/mod.rs
- sqlite3/src/lib.rs
Fixes: #168 
This PR adds a regex cache to `ProgramState` so that we ca re-use already constructed regexes while processing LIKE expressions. I didn't find anywhere else that seemed like a good fit to put an execution-time only cache like this, so let me know if there's a better spot.
To best match sqlite, I added the constant mask into the `Function` instruction (this indicates whether the first argument to the function was determined to be constant at compile time), and decide whether to use the cache based on its value. I've left the value for `constant_mask` as 0 on every other kind of `Function` instruction. That seemed to be the safest choice, as that appears to be what has been implicitly done up to this point. Happy to change that if you'd advise otherwise.
> Cache LIKE regexes

- core/translate/expr.rs
- testing/like.test
I found a bug in queries using a like function in the where clause, ex: `SELECT first_name, last_name FROM users WHERE like('Jas%', first_name) = 1`.  That panicked with the message:
```
thread 'main' panicked at core/vdbe/mod.rs:1226:33:
internal error: entered unreachable code: Like on non-text registers
```
This was caused by an off-by-one error in the vdbe code for executing a `ScalarFunc::Like`. However, this only happened in where-like-fn queries. Queries using the like operator (ex: `SELECT first_name, last_name FROM users WHERE first_name LIKE 'Jas%'`) did not have this problem.
I did some digging around, looked at the explains for these queries from both limbo and sqlite, and it turns out, for binary expressions, limbo positions the arguments in the register differently, which is …
> Allocate the right-hand-side register for a binary expression after translating the left-hand-side

- COMPAT.md
- core/lib.rs
- core/pseudo.rs
- core/schema.rs
- core/translate/emitter.rs
- core/translate/expr.rs
- core/translate/insert.rs
- core/translate/optimizer.rs
- core/translate/plan.rs
- core/translate/planner.rs
- core/translate/select.rs
- core/types.rs
- core/vdbe/builder.rs
- core/vdbe/explain.rs
- core/vdbe/mod.rs
- core/vdbe/sorter.rs
- testing/all.test
- testing/groupby.test
This PR implements GROUP BY (and also ordering by the groups or the aggregate expressions). See `groupby.test` for the kinds of things that are now supported.
This PR is a rabbit hole and insanely big, sorry.
---
I thought about how to explain how GROUP BY works in SQLite bytecode, and opted to go for just adding a bunch of Insn comments, so here's an example that uses both GROUP BY and ORDER BY:
**LIMBO**
```
limbo> explain select u.first_name, sum(u.age) from users u group by u.first_name order by sum(u.age);
0     Init               0     56    0                    0   Start at 56
1     SorterOpen         0     1     0     k(1,B)         0 …
```
> GROUP BY support

- core/translate/expr.rs
- core/vdbe/mod.rs
- testing/like.test
Closes #319 
1. Allow using a column as the pattern
2. Construct LIKE regexes with `^` and `$` so that eg the string `'foobar'` does not match the pattern `'fooba'` unless the pattern specifically has a wildcard
3. Support function expressions as the LIKE pattern
> Fix three issues with LIKE operator (#319)

- COMPAT.md
- core/function.rs
- core/lib.rs
- core/storage/sqlite3_ondisk.rs
- core/translate/expr.rs
- core/vdbe/explain.rs
- core/vdbe/mod.rs
- testing/scalar-functions.test
- Add support for `sqlite_version()` function 
- Update function's explain message depending on the number of arguments
> Add support for sqlite_version() scalar function

- Cargo.lock
- core/vdbe/mod.rs
- testing/like.test
Per the sqlite docs, LIKE is case-insensitive.
> The LIKE operator does a pattern matching comparison. The operand to the right of the LIKE operator contains the pattern and the left hand operand contains the string to match against the pattern. A percent symbol ("%") in the LIKE pattern matches any sequence of zero or more characters in the string. An underscore ("_") in the LIKE pattern matches any single character in the string. **Any other character matches itself or its lower/upper case equivalent (i.e. case-insensitive matching)**. Important Note: SQLite only understands upper/lower case for ASCII characters by default. The LIKE operator is case sensitive by default for unicode characters that are beyond the ASCII range. For example, the expression 'a' LIKE 'A' is TRUE but 'æ' LIKE …
> Make LIKE expressions case-insensitive

- COMPAT.md
- core/function.rs
- core/lib.rs
- core/storage/sqlite3_ondisk.rs
- core/translate/expr.rs
- core/vdbe/explain.rs
- core/vdbe/mod.rs
- Add support for `sqlite_version()` function 
- Update function's explain message depending on the number of arguments
> Add support for sqlite_version() scalar function 

- .github/workflows/stale.yml
Bump operations per run but more importantly turn "ascending" option so that we process pull requests with smaller IDs first that are more likely to be stale.
> github: Fix stale workflow

- simulator/main.rs
This is not related to any open issue (atleast from the ones I saw). This is related to an issue I saw when running the simulator as it was calling `io.run_once()` even before submitting any read/write job. This would lead to it hanging since io_uring's submit_and_wait would keep waiting for a completion event.
I've tried to improve the simulator's IO handling a bit:
We inject a fault before calling next_row() through which we'll get pread faults. Also we call io's run_once on getting RowResult::IO. This is run with a fault probability of 1%. This is less because a fault here would result us in terminating the entire loop iterating on rows, and also because realistically we'll expect less faults here.
PS: I think run_once() should not hang either when no operation is pending in io_uring. …
> Improve Simulator IO by handing RowResult::IO

- core/io/linux.rs
Add a `pending_ops` field to `InnerLinuxIO` struct which is incremented for each operation submitted to the ring and decremented when they are taken off the completion queue. With this, we can exit from run_once if there are no pending operations. Otherwise, in that case, it would hang indefinitely due to call of `ring.submit_and_wait(1)`
> Maintain pending io_uring ops count for early return on run_once

- COMPAT.md
- core/function.rs
- core/translate/expr.rs
- core/vdbe/mod.rs
- testing/scalar-functions.test
This commit adds `unhex(X)` scalar function. Function with `unhex(X,Y)` two arguments is not implemented yet.
Relates to issue #144
> Add `unhex(X)` scalar function

- core/vdbe/sorter.rs
We now just insert them one after the other in the vector. When rewind is called, the vector is sorted. Iterating is just taking elements from the vector.
Related to #191 
SQLite3:
```sh
$ time sqlite3 testing/testing.db "SELECT id FROM users ORDER BY zipcode" > /dev/null
real    0m0.020s
user    0m0.013s
sys     0m0.008s
```
Limbo without this PR:
```sh
$ time target/release/limbo testing/testing.db "SELECT id FROM users ORDER BY zipcode" > /dev/null
real    0m0.285s
user    0m0.257s
sys     0m0.014s
```
Limbo with this PR:
```sh
$ time target/release/limbo testing/testing.db "SELECT id FROM users ORDER BY zipcode" > /dev/null
real    0m0.084s
user    0m0.043s
sys     0m0.032s
```
> [sorter] Hold records in Vec instead of a BTreeMap

- core/translate/emitter.rs
- core/translate/expr.rs
- core/translate/optimizer.rs
- core/translate/plan.rs
- core/translate/planner.rs
`table` (a `Rc<BTreeTable>`) and `table_identifier` (a `String`) pretty much always go together in the current implementation, so makes sense to colocate them as a struct instead of passing around a tuple everywhere
> core/translate: (refactor) use btreetablereference struct instead of tuple

- bindings/wasm/lib.rs
- bindings/wasm/vfs.js
- core/lib.rs
- core/storage/wal.rs
was will fail if both file.db and file.db-wal doesn't exist right now because there are some missing things to implement in VFS
> use core wal file for wasm

- Cargo.lock
- bindings/python/Cargo.toml
Github's bot reports a use-after-free issue so let's bump up the version:
https://github.com/penberg/limbo/security/dependabot/4
> Bump PyO3 dependency

- Cargo.lock
- Cargo.toml
This reduces `liblimbo_sqlite3.a` binary size from 25 MB to 10 MB:
Before:
$ -lh ../target/release/liblimbo_sqlite3.a
-rw-r--r--  1 penberg  staff    25M 15 Mar 18:36 ../target/release/liblimbo_sqlite3.a
After:
$ penberg@vonneumann sqlite3 % ls -lh ../target/release/liblimbo_sqlite3.a
-rw-r--r--  1 penberg  staff   9,9M 15 Mar 18:59 ../target/release/liblimbo_sqlite3.a
> build: Enable LTO for release builds

- bindings/wasm/lib.rs
- bindings/wasm/vfs.js
We don't expect any return value from the underlying `fsync()` so fix the function signature accordingly.
Fixes the following obscure error:
```
TypeError: Cannot convert undefined to a BigInt
at wasm://wasm/00942492:wasm-function[1501]:0x1c4dc1
at wasm://wasm/00942492:wasm-function[694]:0x189586
at wasm://wasm/00942492:wasm-function[50]:0x143d7
at wasm://wasm/00942492:wasm-function[60]:0x3f91a
at new Database (/Users/penberg/src/penberg/limbo/bindings/wasm/pkg/limbo_wasm.js:162:26)
at file:///Users/penberg/src/penberg/limbo/bindings/wasm/perf/perf-limbo.js:5:12
at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
at async loadESM (node:internal/process/esm_loader:34:7)
at async handleMainPromise …
```
> bindings/wasm: Fix VFS.sync() function signature

- core/translate/expr.rs
- core/vdbe/mod.rs
- testing/select.test
> support parenthesized(single expr) in translate_expr()

- core/translate/expr.rs
- core/vdbe/explain.rs
- core/vdbe/mod.rs
- testing/select.test
> support subtract in translate_expr() (not in condition expressions yet)

- core/lib.rs
- core/schema.rs
- core/translate/emitter.rs
- core/translate/expr.rs
- core/translate/insert.rs
- core/translate/optimizer.rs
- core/translate/plan.rs
- core/translate/planner.rs
- core/translate/select.rs
- core/vdbe/builder.rs
- testing/math.test
- testing/orderby.test
- vendored/sqlite3-parser/src/parser/ast/fmt.rs
- vendored/sqlite3-parser/src/parser/ast/mod.rs
This PR rewrites our select query processing architecture by moving away from the stateful operator-based execution model, back to a more direct bytecode generation approach that, IMO, is easier to follow. A large part of the bytecode emission itself (`program.emit_insn(...)`) is just copy-pasted from the old implementation (after all, it did _work_), but just structured differently.
1. Removed the `step()` state machine from operators. Previously, each operator had internal state tracking its execution progress, and parent operators would call `.step()` on their children until they needed to do something else. Reading the code and trying to follow the execution was not very easy, and the abstraction was also too general: there was a lot of unnecessary pattern matching and special casing …
> core: (another) refactor of read path query processing logic

- COMPAT.md
- core/translate/emitter.rs
- core/translate/expr.rs
- core/translate/plan.rs
- core/translate/planner.rs
- core/types.rs
- core/vdbe/mod.rs
- testing/groupby.test
support the HAVING clause.
note that sqlite (and i think standard sql?) supports HAVING even without GROUP BY, but `sqlite3-parser` doesn't.
also fixes some issues with the PartialOrd implementation of OwnedValue and the implementations of `concat` and `round` which i discovered due to my HAVING tcl tests failing
> feat(core/translate): support HAVING

- core/vdbe/mod.rs
- testing/scalar-functions.test
`String::len()` function returns number of bytes. Here we need to use `chars().count()` to count real characters as specified in https://www.sqlite.org/lang_corefunc.html#length
> Fix: length function characters counting

- COMPAT.md
- core/function.rs
- core/lib.rs
- core/pseudo.rs
- core/storage/btree.rs
- core/translate/expr.rs
- core/types.rs
- core/vdbe/mod.rs
- core/vdbe/sorter.rs
- test/src/lib.rs
- testing/insert.test
- Changed `Cursor` trait to be able to get access to `root_page` 
- SQLite only updates last_insert_rowid for non-schema inserts. So we check if the `InsertAwait` is not for `root_page` before   updating rowid
In SQLite it looks like this:
```
sqlite> EXPLAIN SELECT last_insert_rowid();
addr  opcode         p1    p2    p3    p4             p5  comment      
0     Init           0     4     0                    0   
1     Function       0     0     1     last_insert_rowid(0) 0   
2     ResultRow      1     1     0                    0   
3     Halt           0     0     0                    0   
4     Goto           0     1     0                    0   
```
In limbo it will look like this:
```
limbo> EXPLAIN SELECT …
```
> Add last_insert_rowid() function

- Cargo.lock
- core/Cargo.toml
Github's dependabot complains that the current version has an unsoudness issue so let's bump to a newer version:
https://github.com/tursodatabase/limbo/security/dependabot/10
> Upgrade pprof to 0.14

- COMPAT.md
- core/function.rs
- core/translate/expr.rs
- core/vdbe/mod.rs
- testing/scalar-functions.test
add [soundex](https://www.sqlite.org/lang_corefunc.html#soundex) scalar function.
it seems that sqlite did not enable `soundex()` function by default unless build it with `SQLITE_SOUNDEX`, while the sqlite in the ci workflow did not enable it. this pr skipped the test over `soundex()` temporarily in the `scalar-function.test` file.
> Add support for soundex() function

- Cargo.lock
- Cargo.toml
- bindings/wasm/lib.rs
- core/Cargo.toml
- core/lib.rs
- core/storage/btree.rs
- core/storage/pager.rs
- core/storage/sqlite3_ondisk.rs
- core/storage/wal.rs
- simulator/main.rs
- sqlite3/src/lib.rs
Since we expect to ensure thread safety between multiple threads in the
future, we extract what is important to be shared between multiple
connections with regards to WAL/Pager.
This is WIP so I just put whatever feels like important behind a RwLock
but expect this to change to Atomics in the future as needed. Maybe even
these locks might disappear because they will be better served with
transaction locks.
This also includes addition of unsafe Sync/Send + UnsafeCell in Pages.
> Start multithread support

- COMPAT.md
- core/vdbe/mod.rs
- testing/scalar-functions.test
> Add two arguments version of `unhex(x, y)` function

- cli/app.rs
- cli/main.rs
After fixing the shell issue earlier I just had to revisit this. Let me know if this is too opinionated of changes or out of scope.
This PR adds several of the sqlite CLI commands to the limbo shell user interface, with their behavior matched as much as possible.
- `.show`:  displays a list of currently enabled settings
- `.open <file>` : opens a database file
- `.output <file>`: allows the user to direct shell output to a file, or stdout if left blank
- `.cd <dir>`: changes the current working directory of the shell environment
- `.mode <output_mode>`: allows the user to select between the (two) current output modes "pretty | raw"
- `.nullvalue <string>`: allows user to set the value of NULL to be displayed in the output
It also prevents a database file argument from needing to being …
> Add several cli shell commands, re-structure shell api

- Makefile
- cli/app.rs
- cli/main.rs
- core/io/memory.rs
- core/io/mod.rs
- core/lib.rs
- testing/memory-repl.tcl
https://github.com/tursodatabase/limbo/issues/53
This PR implements a (naive) in-memory option and makes it the default connection when no DB file argument is passed to the CLI. If a `:memory:` parameter is passed in place of a path to a database file, to replicate sqlite's behavior.
It's slightly more difficult to test for obvious reasons, so I added some dumb and probably temporary ones until I can craft a better solution. Let it be noted that I had never touched `tcl` previously if that wasn't obvious ;)
also cleaned up a bit of previous pr, replacing`format!` calls to writeln with `write_fmt` to prevent double allocations.
EDIT: I originally had these additional tests running with the `test-compat`, but they would hang whenever running on github actions for whatever reason.
> In-memory mode

- rust-toolchain.toml
It's annoying for the CI to trip over formatting because you happen to have a different version of Rust locally.
> Pin toolchain to Rust version 1.83

- COMPAT.md
- core/function.rs
- core/translate/expr.rs
- core/vdbe/mod.rs
- testing/math.test
- testing/tester.tcl
Add support for math scalar functions of SQLite: https://sqlite.org/lang_mathfunc.html
Since SQLite CLI and Limbo CLI present floating point numbers with different precision, I added `do_execsql_test_tolerance` which tests that floating point results close enough of the expected value. However, we probably could make Limbo's floating point presentation match to SQLite.
> Support math functions

- core/translate/mod.rs
- testing/pragma.test
- vendored/sqlite3-parser/src/parser/ast/mod.rs
This change refactors how PRAGMA statements are handled, introducing a more organized and extensible structure to simplify adding new PRAGMA properties in the future.
Previously, only the `cache_size` PRAGMA was supported. With this update, support for the `journal_mode` PRAGMA has been added.
> pragma: inital approach to handle pragma statements

- sqlite3/Cargo.toml
Static lib was built successfully  on MacOS 15.0.1 (24A348) and Linux fedora 6.12.4-orbstack-00286-g339578031cbf
> Fix limbo_sqlite3 static library build

- bindings/python/src/lib.rs
- bindings/wasm/lib.rs
- cli/app.rs
- core/benches/benchmark.rs
- core/lib.rs
- core/util.rs
- core/vdbe/mod.rs
- simulator/main.rs
- sqlite3/src/lib.rs
- test/src/lib.rs
This adds an interrupt() method to Statement that allows apps to interrupt a running statement. Please note that this is different from `sqlite3_interrupt()` which interrupts all ongoing operations in a database. Although we want to support that too, per statement interrupt is much more useful to apps.
> Add statement interruption support

- core/translate/planner.rs
- core/util.rs
- testing/join.test
- testing/select.test
This PR adds missing SQLite quoting syntax: https://sqlite.org/lang_keywords.html
Closes #483 
Closes #497 
```bash
➜  limbo git:(missing-quoting) ✗ cargo run --package limbo --bin limbo home.db
Limbo v0.0.9
limbo> select * from home limit 1;
Documents|dir|280|2024-10-13 06:26:05.605048960+02:00
limbo> select * from [home] limit 1;
Documents|dir|280|2024-10-13 06:26:05.605048960+02:00
limbo> select * from `home` limit 1;
Documents|dir|280|2024-10-13 06:26:05.605048960+02:00
limbo> select * from "home" limit 1;
Documents|dir|280|2024-10-13 06:26:05.605048960+02:00
```
> Handle all SQLite quoting syntax

- bindings/python/pyproject.toml
- bindings/python/requirements-dev.txt
- bindings/python/requirements.txt
Somehow the `make` command does not work because of the name mismatching. This PR will fix only this issue.
For reproducing the issue:
```
$ make
Checking requirements files...
mkdir -p .tmp
pip-compile pyproject.toml --quiet             --output-file=.tmp/requirements.txt
pip-compile pyproject.toml --quiet --extra=dev --output-file=.tmp/requirements-dev.txt
diff -u requirements.txt     .tmp/requirements.txt     || (echo "requirements.txt doesn't match pyproject.toml"     && exit 1)
--- requirements.txt    2024-12-17 02:19:29.887227723 +0000
+++ .tmp/requirements.txt       2024-12-17 02:19:38.046065295 +0000
@@ -1,2 +1,2 @@
typing-extensions==4.12.2
-    # via limbo (pyproject.toml)
+    # via pylimbo (pyproject.toml)
requirements.txt doesn't match pyproject.toml
make: *** [Makefile:28: …
```
> Fix Python binding packaging

- Cargo.lock
- sqlite3/Cargo.toml
- sqlite3/src/lib.rs
#479 
This is my first draft for implementing `sqlite3_get_table()`, it is highly inspired on the actual implementation found [here](https://raw.githubusercontent.com/rusqlite/rusqlite/92fdc11fea0ecea6400dfcb74c1c3ca36214a7d4/libsqlite3-sys/sqlite3/sqlite3.c), I made some basic manual testing in `example.c` and it works fine but an extensive test suite is recommended.
> Implement basic sqlite3_get_table() API

- core/translate/optimizer.rs
- testing/where.test
Rewrite `Y BETWEEN X AND Z` as `X <= Y AND Y <= Z`. And due to the support of this optimization rule, limbo should now be able to execute the `BETWEEN AND` statement.
> feat(optimizer): eliminate between statement

- bindings/python/src/lib.rs
Solving issue #494   , changes made at 5 places where todo macros were replaced with relevant errors to avoid the crashes _for now_
> Improve error reporting in Python bindings

- COMPAT.md
- Cargo.lock
- core/Cargo.toml
- core/ext/mod.rs
- core/ext/uuid.rs
- core/function.rs
- core/lib.rs
- core/translate/expr.rs
- core/vdbe/mod.rs
#509 
Started the discussion on discord about possibly supporting UUID types natively. This PR only implements the `sqlean` extension's functions and behavior, with the only changes being:
1. uuid's are returned as `blob`s by default. (that was an assumption I made considering perf, thinking this would be preferred if UUID ended up being a supported native type.  if `text` is preferred I can change it)
2.  `uuidv7` types here can accept an argument of seconds since epoch to customize the embedded timestamp. The func `uuidv7_timestamp_ms(string_or_blob_v7)` allows the user to convert their uuid7 back into the timestamp.
> UUID support

- core/io/generic.rs
`cargo test` is always failing on FreeBSD, the following is one of the errors:
```
---- tests::test_simple_overflow_page stdout ----
thread 'tests::test_simple_overflow_page' panicked at test/src/lib.rs:32:84:
called `Result::unwrap()` on an `Err` value: IOError(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```
After some digging, I found that the `open_file` function in `core/io/generic.rs` does not respect the `OpenFlags::Create` flag. This commit adds support for file creation in the `open_file` function.
`cargo test` now passes on FreeBSD.
> Fix file creation in GenericIO `open_file` function

- simulator/main.rs
Fixes https://github.com/tursodatabase/limbo/issues/545
> switch the seed, database path, and plan path prints to println instead of log::info

- simulator/main.rs
Fixes the panicking case in https://github.com/tursodatabase/limbo/issues/548
> fix empty range error when 0 interactions are produced by creating at least 1 interaction

- core/translate/insert.rs
- simulator/generation/plan.rs
- simulator/generation/query.rs
- simulator/model/query.rs
Closes #436
This PR fixes four issues:
1. Not respecting user-provided column names (e.g. `INSERT INTO foo (b,c) values (1,2);` would just insert into the first two columns regardless of what index `b` and `c` have)
2. Limbo would get in an infinite loop when inserting too many values (too many i.e. more columns than the table has)
3. False positive unique constraint error on non-primary key columns when inserting multiple values, e.g.
```
limbo> create table t1(v1 int);
limbo> insert into t1 values (1),(2);
Runtime error: UNIQUE constraint failed: t1.v1 (19)
```
as seen [here](https://github.com/tursodatabase/limbo/pull/490#issuecomment-2545545562)
4. Limbo no longer uses a coroutine for INSERT when only inserting one row. See [this …
> Fix: core/translate/insert: fix four issues with inserts

- core/storage/btree.rs
- core/types.rs
This PR's genesis is from investigating #532, but I still can't reliably reproduce it on either `main` or this branch so I don't know if this PR _fixes_ anything, but I guess it aligns us more with sqlite anyway
---
Anyway: I looked at DBs created with limbo and with sqlite using [ImHex](https://github.com/WerWolv/ImHex) and the differences seem to be:
1. SQLite uses varint according to [the spec](https://www.sqlite.org/fileformat.html#record_format), whereas limbo always encodes integers as i64
2. Limbo adds 4 bytes of zeros for overflow page pointer (even in cases where the cell doesnt overflow)
3. Limbo adds a space after `CREATE TABLE name` before the `(` even when user doesn't specify it?
I implemented the following:
- Fix 1: Varint serialization of i8, i16, i24, i32, i48 and i64 …
> core: disk serialization changes to align with sqlite

- COMPAT.md
- core/function.rs
- core/json/mod.rs
- core/json/path.rs
- core/translate/expr.rs
- core/vdbe/mod.rs
- testing/json.test
In line with [other work](#127) for JSON support, this PR adds support for [`json_array_length`](https://www.sqlite.org/json1.html#jarraylen). This includes a first pass at supporting the JSON path for accessing values within the JSON.
I've added tests in rust and tcl.
> Implement json_array_length

- bindings/python/src/lib.rs
- bindings/wasm/lib.rs
- cli/app.rs
- core/benches/benchmark.rs
- core/lib.rs
- core/util.rs
- perf/latency/limbo/src/main.rs
- simulator/generation/plan.rs
- simulator/main.rs
- sqlite3/src/lib.rs
- test/src/lib.rs
The name "row result" is confusing because it really *is* a result from a step() call. The only difference is how a row is represented as we return from VDBE or from a statement.
Therefore, rename RowResult to StepResult.
> Rename RowResult to StepResult

- core/translate/expr.rs
- testing/scalar-functions.test
- testing/tester.tcl
#560 
Changes to `translate_expr` function:
* [`core/translate/expr.rs`](diffhunk://#diff-371865d5d7b8bcaed649413c687492e61e94f21387cd9b2c47d989a033888c8bL1558-R1560): Changed the `amount` parameter in the `Insn::Copy` instruction from `1` to `0`.
Enhancements to the testing framework:
* [`testing/scalar-functions.test`](diffhunk://#diff-a046d58ab24eee8207f0ce3199f8d0a609edcef9c24b8ed7f242f7a60e6c1e61R812-R815): Added a new test `do_execsql_test_regex` to validate that the `sqlite_version` function returns a valid output.
* [`testing/tester.tcl`](diffhunk://#diff-316cca92d85df3f78558cc3e60d7420c1fd19a23ecf2bbea534db93ab08ea3ecR29-R45): Introduced a new procedure `do_execsql_test_regex` to support regex-based validation of SQL outputs.
> Fix `sqlite_version()` out of bound panics

- core/Cargo.toml
- core/vdbe/mod.rs
- testing/like.test
Fixes #552
In our construct regex function, we were not escaping the required characters properly which was causing the failure. 
Limbo output with this branch
```
limbo> select like('\%A', '\A');
1
limbo> select like('A$%', 'A$');
1
limbo> select like('%a.a', 'aaaa');
0
```
> Fixes like function when pattern has regex meta chars

- COMPAT.md
- core/vdbe/likeop.rs
- core/vdbe/mod.rs
- testing/like.test
I have added support for like function with escape i.e like(X,Y,Z) .
There is good opportunity to refactor/cleanup the like operations which can be done in another PR, as I wanted to keep the changes small .
> Support like function with escape

- core/vdbe/likeop.rs
- core/vdbe/mod.rs
- testing/glob.test
Fixes #577 
With the previous implementation we weren't escaping the regex meta characters . And in certain cases glob had a different meaning than regex.
For e.g , the below shows a glob pattern with its regex equivalent
- `[][]` translates to `[\]\[]`
- `[^][]` translates to `[^\]\[]`
> Fixes glob giving wrong results in some cases 

- core/io/linux.rs
EDIT: will continue iterating on these ideas, as discussed on discord.
for now, this has been changed to just enable `IORING_ENABLE_SQPOLL` by default. This is supported sin `5.11`, and I believe the last debian release < that reached EOL in July, so shouldn't be an issue.
> enable sqpoll by default in io_uring

- core/ext/mod.rs
- core/ext/uuid.rs
- core/function.rs
- core/lib.rs
- core/translate/delete.rs
- core/translate/emitter.rs
- core/translate/expr.rs
- core/translate/insert.rs
- core/translate/mod.rs
- core/translate/select.rs
- core/vdbe/mod.rs
This pull request adds support for external functions, which are functions provided by extensions. The main difference to how things are today is that extensions can register functions to a symbol table at runtime instead of specifying an enum variant.
> External functions

- core/vdbe/insn.rs
- core/vdbe/mod.rs
This PR cleans up a lot of the repetitive code that caused having to match the `AggFunc` cases repeatedly :smile: 
Most of the repetition was caused by the binary math operators, so I just added it for those for now.
> Refactor out repetitive agg_func code in vdbe

- core/lib.rs
- core/schema.rs
- core/translate/delete.rs
- core/translate/emitter.rs
- core/translate/expr.rs
- core/translate/optimizer.rs
- core/translate/plan.rs
- core/translate/planner.rs
- core/translate/select.rs
- core/vdbe/mod.rs
- testing/all.test
- testing/subquery.test
I will warn that this PR is quite big out of necessity, since subqueries are, as the name implies, queries within queries, so everything that works with a regular query should also work with a subquery, roughly speaking.
---
- Adds support for:
* uncorrelated subqueries in FROM clause (i.e. appear as a "table", and do not refer to outer tables). Example of this at the end of the PR description.
* column and subquery aliasing (`select sub.renamed from (select name as renamed from products) sub`)
* inner and outer filtering of subqueries (`select sub.name from (select name from products where name = 'joe') sub`, and,  `select sub.name from (select name from products) sub where sub.name = 'joe'`)
* joining between regular tables and subqueries
* joining between multiple subqueries
* in …
> Support uncorrelated FROM clause subqueries

- core/storage/btree.rs
- testing/where.test
data does not match predicate when using index, e.g: `select id, age from users where age > 90 limit 1;` will return data with age  90
the reason is that the current index seek directly uses record for comparison, but the record of the index itself is longer than the record of the key (because it contains the primary key), so Gt is invalid.
since only single-column indexes are currently supported: https://github.com/tursodatabase/limbo/pull/350, only the first value of the record is currently used for comparison.
> fix: index seek wrong on `SeekOp::LT`\`SeekOp::GT`

- CONTRIBUTING.md
- Makefile
- sqlite3/include/sqlite3.h
- sqlite3/src/lib.rs
- sqlite3/tests/Makefile
- testing/shelltests.py
* Add SQLITE_FLAGS env variable handling to compatibility tests as SQLite does not handle `-q` flag
* Fix inconsistent SQLITE_NOTFOUND error code and add SQLITE_CANTOPEN code
* Improve compatibility tests to display errors instead of hanging indefinitely
> Remove SQLite headers dependency from compat tests

- core/function.rs
- core/lib.rs
- core/translate/expr.rs
- core/vdbe/mod.rs
#525
- Adds the necessary `ScalarFunc` variants to support the `changes()` & `total_changes()` SQLite function.
- Adds the necessary fields to the `Connection` struct to track changes.
- Modify the `InsertAwait` OpCode behaviour to affect the changes counter.
> Add support for changes() and total_changes() functions

- core/translate/emitter.rs
I plan to do a series of cleanups to `emitter.rs` which is a chonker module right now. This first one is just making some variable namings more consistent and refactoring some metadata fields to function-local variables
> Code cleanups to emitter

- core/vdbe/insn.rs
- testing/math.test
We had not implemented arithmetic operations for text values. This PR implements this and aligns the behavior with sqlite3 .
> Fix arithmetic operations for text values

- core/schema.rs
- core/translate/emitter.rs
- core/translate/mod.rs
- core/translate/optimizer.rs
- core/util.rs
- core/vdbe/mod.rs
Closes #448 
Adds support for:
- Automatically creating index on the PRIMARY KEY if the pk is not a rowid alias
- Parsing the automatically created index into memory, for use in queries
* `testing/testing_norowidalias.db` now uses the PK indexes and some tests were failing -- looks like taking the index into use revealed some bugs in our codegen :) I fixed those in later commits.
Does not add support for:
- Inserting to the index during writes to the table
> Auto-create index in CREATE TABLE when necessary

- core/vdbe/insn.rs
- testing/math.test
In sqlite3, before arithmetic operation is done, it first checks if the operation dosent overflow and then does the operation. In case it overflows it would covert the arguments into floats and then does the operation as [per code](https://github.com/sqlite/sqlite/blob/ded37f337b7b2e916657a83732aaec40eb146282/src/vdbe.c#L1875)  . I have done the same behaviour for limbo.
> Fix integer overflow output to be same as sqlite3

- core/benches/benchmark.rs
- core/lib.rs
- core/translate/delete.rs
- core/translate/insert.rs
- core/translate/mod.rs
- core/translate/planner.rs
- core/translate/select.rs
- vendored/sqlite3-parser/src/parser/ast/mod.rs
- vendored/sqlite3-parser/src/parser/parse.y
- vendored/sqlite3-parser/third_party/lemon/lemon.c
- vendored/sqlite3-parser/third_party/lemon/lempar.rs
Manually vendored in some changes from [lemon-rs](https://github.com/gwenn/lemon-rs), including a merged change from @krishvishal and [an unmerged PR ](https://github.com/gwenn/lemon-rs/pull/81) from user ignatz that boxes Limit. I also boxed `OneSelect` because it also improved perf in the benchmarks. 40-50% more throughput with these changes to our existing admittedly simple benchmarks. Added a new more complex prepare benchmark that includes group by and having as well, which is also 42% faster with the new code.
**Runs on my local machine:**
```
main:
limbo/Prepare statement: 'SELECT 1'
time:   [1.2902 µs 1.2927 µs 1.2958 µs]
thrpt:  [771.73 Kelem/s 773.56 Kelem/s 775.07 Kelem/s]
change:
time:   [+0.2770% +0.6013% +0.9243%] (p = 0.00 < 0.05)
thrpt:  [-0.9158% -0.5977% -0.2762%] …
```
> Sqlite3 parser perf improvements

- core/translate/expr.rs
- testing/select.test
Previously we were not escaping the quotes properly in stirng literals as shown below. The PR fixes that
limbo output without this PR
```
limbo> select '''a';
''a
limbo>  explain select '''a';
0     Init               0     4     0                    0   Start at 4
1     String8            0     1     0     ''a            0   r[1]='''a'
2     ResultRow          1     1     0                    0   output=r[1]
3     Halt               0     0     0                    0
4     Transaction        0     0     0                    0
5     Goto               0     1     0                    0
```
sqlite3 output
```
sqlite> select '''a';
'a
sqlite> explain …
```
> Fix quote escape in literals

- bindings/java/src/main/java/org/github/tursodatabase/Main.java
- bindings/java/src/main/java/org/github/tursodatabase/core/CoreStatement.java
- bindings/java/src/main/java/org/github/tursodatabase/core/DB.java
- bindings/java/src/main/java/org/github/tursodatabase/core/LimboDB.java
- bindings/java/src/main/java/org/github/tursodatabase/core/SafeStmtPtr.java
- bindings/java/src/main/java/org/github/tursodatabase/exceptions/ErrorCode.java
- bindings/java/src/main/java/org/github/tursodatabase/limbo/Connection.java
- bindings/java/src/main/java/org/github/tursodatabase/limbo/Cursor.java
- bindings/java/src/main/java/org/github/tursodatabase/limbo/Limbo.java
- Add minimal template code that provides Limbo features. 
- Added `DB` which is an interface to DB. 
- Added 'LimboDB` which is a thin wrapper around native methods provided using jni. 
- Incrementally update the code to support jdbc. Refer to [sqlite-jdbc](https://github.com/xerial/sqlite-jdbc). 
> Add skeleton code for implementing java bindings in jdbc style 

- .gitignore
- bindings/wasm/integration-tests/package-lock.json
- bindings/wasm/integration-tests/package.json
- bindings/wasm/integration-tests/tests/test.js
- bindings/wasm/lib.rs
#514 
Introduces a new feature for lazy evaluation in the `Statement.raw().iterate()` method and includes related changes in both the test and implementation files. The most important changes include adding a test case for lazy evaluation, creating a `RowIterator` struct, and modifying the `iterate` method to use this new struct.
Everything seems to works fine, but suggestions on code improvement and test use cases are welcoming.
> Make iterate() lazily evaluated on wasm

- Cargo.lock
- cli/Cargo.toml
- cli/app.rs
- core/Cargo.toml
- core/error.rs
- vendored/sqlite3-parser/Cargo.toml
- vendored/sqlite3-parser/src/lexer/scan.rs
- vendored/sqlite3-parser/src/lexer/sql/error.rs
- vendored/sqlite3-parser/src/lexer/sql/mod.rs
- vendored/sqlite3-parser/src/lexer/sql/test.rs
I noticed that the parse errors were a bit hard to read - only the nearest token and the line/col offsets were printed.
I made a first attempt at improving the errors using [miette](https://github.com/zkat/miette).
- Added derive for `miette::Diagnostic` to both the parser's error type and LimboError.
- Added miette dependency to both sqlite3_parser and core. The `fancy` feature is only enabled for the CLI. So the overhead on the libraries (core, parser) should be minimal.
Some future improvements that can be made further:
- Add spans to AST nodes so that errors can better point to the correct token. See upstream issue: https://github.com/gwenn/lemon-rs/issues/33
- Construct more errors with offset information. I noticed that most parser errors are constructed with `None` as the offset.
- …
> Nicer parse errors using miette

- core/Cargo.toml
- core/error.rs
- core/io/io_uring.rs
- core/io/mod.rs
- core/io/unix.rs
As was suggested in #502 I have renamed the IO backends from `darwin` to `unix` and from `linux` to `io_uring`. The `unix` backend is now available to Linux platforms without io_uring.
A few things to confirm
On the topic of letting platforms disable io_uring support, the primary example is Google, which posted this [blog](https://security.googleblog.com/2023/06/learnings-from-kctf-vrps-42-linux.html) in 2023 about disabling io_uring by default in most of their servers/platforms, including Android (prime candidate user for a SQLite rewrite).
Another way to implement compatibility for platforms with io_uring disabled, without using the feature flag, would be to make a Linux PlatformIO wrapper that implements `IO` and tries to build a UringIO. If that fails, it builds a UnixIO and returns …
> Rename IO backends to support Linux platforms without io_uring

- core/translate/optimizer.rs
- core/translate/planner.rs
- testing/where.test
Closes #629
- Fix bug with column being considered rowid alias based on 'primary_key' (non INTEGER pks are not rowid aliases)
- fix logic bug in check_index_scan() that swapped lhs/rhs but not the comparison op
- Rename eliminate_between to rewrite_exprs and add true/false->1/0 case there
> Optimizer bugfixes

- core/storage/btree.rs
`balance_non_root` should be as close as possible to `balance_non_root` in SQLite. This commits extract `balance_non_root` from `balance` and renames `balance_leaf` to `balance` as it enables future work on a complete `balance_non_root` procedure.
> distinguish balance and balance_non_root

- Cargo.toml
only doc change: Just update the repo link in `Cargo.toml` to be the latest.
> chore: update repository link in Cargo.toml

- CONTRIBUTING.md
Document Python binding setup with Maturin.
> docs: add python bindings

- cli/Cargo.toml
- cli/app.rs
- core/Cargo.toml
- core/io/generic.rs
- core/io/io_uring.rs
- core/io/memory.rs
- core/io/mod.rs
- core/io/unix.rs
- core/io/windows.rs
- core/lib.rs
Give the user the option of choosing IO backend. There is only a "syscall" backend, unless built for Linux with `#[cfg(feature = "io_uring")]` which introduces `--io=io-uring`.
Right now, the choice has only been implemented for the CLI. Bindings and such default to PlatformIO, except when an "in-memory" database has been chosen.
Can be tested by running CLI with RUST_LOG=debug
> cli: Introduce a selectable IO backend with --io={syscall,io-uring} argument

- core/storage/sqlite3_ondisk.rs
This PR fixes #666 
Limbo was treating all single byte integers properly in `core/types.rs`, but when converted in `sqlite3_ondisk`, it was losing the sign for 8 bit integers, treating them all as unsigned. Sqlite3 specifies in their file format that the `1` record serial type is "Value is an 8-bit twos-complement integer."  https://www.sqlite.org/fileformat.html
We now properly match sqlite3's output
> Fix 8-bit serial type to encoding

- core/translate/delete.rs
- core/translate/emitter.rs
- core/translate/insert.rs
- core/translate/mod.rs
- core/translate/select.rs
Simplifies function signatures and allows attaching more context to ProgramStatus on `translate::translate`, useful for value binding – #607.
> Make `translate_*` functions accept `ProgramBuilder`

- core/vdbe/datetime.rs
seeing #660 made me realize I shouldn't have used `now` in any circumstances in these tests, tolerance or not ;)
they should all be deterministic now
> Fix the rest of the flaky datetime tests

- Cargo.lock
- Cargo.toml
- bindings/rust/Cargo.toml
- bindings/rust/src/lib.rs
- bindings/rust/src/params.rs
- bindings/rust/src/value.rs
This implements libSQL compatible Rust API on top of Limbo's core. The purpose of this is to allow libraries and apps that build on libSQL to use Limbo.
> Initial pass on Rust bindings

- Cargo.lock
- core/Cargo.toml
- core/io/io_uring.rs
- core/io/unix.rs
This shaves off `nix` as a dependency in core, which was only being used in the io_uring backend for the `fcntl` advisory record locking. Since a previous PR made `rustix` a dep not only for Mac but for any Unix, and `rustix` also has `fcntl`, `nix` becomes redundant.
Furthermore, it reduces `libc` usage across core. The only remaining uses are:
```rust
io_uring::opcode::Readv::new(fd, iovec as *const iovec as *const libc::iovec, 1)
io_uring::opcode::Writev::new(fd, iovec as *const iovec as *const libc::iovec, 1)
```
These two are a little ugly, but sadly the `io_uring` crate requires both opcodes to take a `libc::iovec` while it doesn't export the type. See tokio-rs/io-uring#259 for a request to use `std::io::IoSlice` or to export the type directly.
Apart from those two, there are no …
> core: Consolidate libc implementations

- bindings/java/src/main/java/org/github/tursodatabase/JDBC.java
- bindings/java/src/test/java/org/github/tursodatabase/JDBCTest.java
To maximize compatibility between limbo and sqlite, update `VALID_URL_PREFIX`
- [Issue](https://github.com/tursodatabase/limbo/issues/615)
> Change VALID_URL_PREFIX to use sqlite instead

- Cargo.lock
- core/Cargo.toml
- core/io/io_uring.rs
- core/io/unix.rs
This adds the missing parts of #668 which was just making the locks non-blocking so they fail right away on conflict. Rustix was not very clear on that, and the doc for `fcntl` didn't mention it, it was in the docs for `flock`.
I have checked that this doesn't hang the test (🤦‍♂️).
> v2 of Consolidate libc implementations

- core/translate/expr.rs
- core/translate/planner.rs
- testing/join.test
- testing/select.test
- vendored/sqlite3-parser/src/parser/ast/check.rs
- vendored/sqlite3-parser/src/parser/ast/fmt.rs
- vendored/sqlite3-parser/src/parser/ast/mod.rs
https://github.com/tursodatabase/limbo/issues/241
support keyword `rowid`
check if rowid exists when creating table
```shell
explain SELECT rowid FROM users WHERE rowid = 1;
0     Init               0     12    0                    0   Start at 12
1     OpenReadAsync      0     2     0                    0   table=users, root=2
3     RewindAsync        0     0     0                    0   
4     RewindAwait        0     11    0                    0   Rewind table users
5       RowId            0     2     0                    0   r[2]=users.rowid
6       Ne               2     3     9 …
```
> Add support for `rowid` keyword

- Cargo.lock
- extensions/uuid/src/lib.rs
- limbo_extension/Cargo.toml
- limbo_extension/src/lib.rs
- macros/Cargo.toml
- macros/src/args.rs
- macros/src/lib.rs
Per @penberg's suggestion on Discord, the `declare_scalar_functions!` declarative macro has been replaced with a procedural one, allowing for a much nicer API.
```rust
#[export_scalar]
#[args(0)]
fn uuid4_blob(_args: &[Value]) -> Value {
let uuid = uuid::Uuid::new_v4();
let bytes = uuid.as_bytes();
Value::from_blob(bytes.to_vec())
}
```
> Replace scalar function declaration in extension API with proc macro

- core/translate/expr.rs
- core/translate/group_by.rs
- core/translate/main_loop.rs
- testing/where.test
I believe this closes #682 
```
limbo> CREATE TABLE proficient_barrett (imaginative_etrebilal BLOB,lovely_wilson BLOB);
INSERT INTO proficient_barrett VALUES (X'656E67726F7373696E675F636861636F', X'776F6E64726F75735F626F75726E65');
limbo> SELECT * FROM proficient_barrett 
WHERE (
(
(
(
imaginative_etrebilal != X'6661766F7261626C655F636F726573' 
OR 
(imaginative_etrebilal > X'656E67726F7373696E675F6368616439')
) 
AND 
(
imaginative_etrebilal = X'656E676167696E675F6E6163696F6E616C' 
OR 
TRUE
)
) 
OR 
FALSE
) 
AND 
(
imaginative_etrebilal > X'656E67726F7373696E675F63686164F6' 
OR 
TRUE
)
);
engrossing_chaco|wondrous_bourne
```
@PThorpe92 I don't think we need the `parent_op` machinery at all, we just need to not jump to the `jump_target_when_true` label given by the parent if we are …
> Expr: fix recursive binary operation logic

- cli/app.rs
- core/lib.rs
- testing/insert.test
When we had multiple sql statements in cli/interactive shell, we were only running one from them as  shown below. This PR fixes them.
One added benefit of this is we can add complex sql in the tcl test files like the changes in insert.test .
sqlite3 output
```
❯ sqlite3  :memory: "select 1;select 2"
1
2
```
Limbo main branch output
```
❯ ./target/debug/limbo.exe :memory: "select 1;select 2;"
1
```
Limbos output with this PR
```
❯ ./target/debug/limbo.exe :memory: "select 1;select 2;"         
1
2
```
> Run all statements from sql argument in cli

- core/vdbe/mod.rs
- testing/insert.test
In sqlite3 , we can create primary key with only integer column and during insert we can pass any value which can be parsed into integer as shown below. When I tried the same with limbo, it failed. The cause of this was due to MustBeInt opcode behaviour not aligned with sqlite. This PR aims to fix it.
Sqlite output
```
SQLite version 3.45.3
sqlite> create table temp (t1 integer, primary key (t1));
sqlite> insert into temp values (1),(2.0),('3'),('4.0');
sqlite> select * from temp;
1
2
3
4
```
Limbo output main branch
```
limbo>     create table temp (t1 integer, primary key (t1));
limbo>     insert into temp values (1),(2.0),('3'),('4.0');
Parse error: MustBeInt: the value in the register is not an integer
limbo>     select * from temp;
1
```
Limbo output with this PR
```
limbo> create …
```
> Fix MustBeInt opcode semantics

- cli/app.rs
#711 
I followed the patterns that sqlite has, so everything after `--` is treated as a comment. A bunch of spaces and a `--` is treated as a comment also.
> Fix cli comments parsing

- .github/workflows/python.yml
The current version is getting deprecated:
https://github.blog/news-insights/product-news/get-started-with-v4-of-github-actions-artifacts/
> github: Switch to upload-artifact v4

- Cargo.toml
This reduces `liblimbo_sqlite3.a` size from 37M to 15M.
Refs #714
> Reduce `liblimbo_sqlite3.a` size

- core/translate/expr.rs
- testing/all.test
- testing/compare.test
This PR adds support for `Is` Operator which was not working as shown below. I have also added compare.test for all compare operations on which we can expand upon.
```
❯ .\target\debug\limbo.exe
Limbo v0.0.12
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database
limbo> select 1 is 2;
thread 'main' panicked at core\translate\expr.rs:613:40:
not yet implemented: Is
```
> Implement `Is` operator

- COMPAT.md
- core/lib.rs
- core/translate/mod.rs
- core/vdbe/builder.rs
- core/vdbe/mod.rs
- testing/all.test
- testing/changes.test
- testing/total-changes.test
#144 
- The previous `changes()` function returns 1 no matter what
- Modified `changes()` and `total_changes()` to be closer to the sqlite implementation
- Store local `n_change` counter in the `Program` struct 
- Update `last_change` and `total_changes` values in `Connection` struct on halt
- Add `change_cnt_on` flag to `Program` struct that is `true` for insert and delete (also need later on for update)
- Added TCL tests
> Improve changes() and total_changes() functions and add tests

- Cargo.lock
- cli/Cargo.toml
- cli/tests/test_journal.rs
- core/storage/wal.rs
- core/translate/mod.rs
- core/vdbe/explain.rs
- core/vdbe/insn.rs
- core/vdbe/mod.rs
- vendored/sqlite3-parser/src/parser/ast/mod.rs
Wire pragma wal_checkpoint to checkpoint infra
- add basic support for parsing and instruction emitting `pragma wal_checkpoint;`
- checkpoint opcode for instruction
- checkpoint execution in `virtual machine`
- cli test 
Part of #696.
Before
```
limbo> pragma wal_checkpoint;
× Parse error: Not a valid pragma name
```
After
```
limbo> pragma wal_checkpoint;
0|0|0
```
```
> Initial support for wal_checkpoint pragma

- core/lib.rs
- vendored/sqlite3-parser/src/lexer/sql/mod.rs
Currently, we are using the same `Parser` instance across multiple queries (9cc9577c91edb1ab807f6c5fb6c2deb826abfcd1).  But during this error the parser is not finalized, so parser stack is not reset, thereby triggering the assertion at https://github.com/tursodatabase/limbo/blob/15f7928551435458e2991dde3a76ce71e8a32057/vendored/sqlite3-parser/third_party/lemon/lempar.rs#L663
This PR fixes the panic by calling `sqlite3ParserFinalize()` in the case of error.
Closes https://github.com/tursodatabase/limbo/issues/742
-----------
`git bisect` FTW
> Fix parser panic when duplicate column names are given to `CREATE TABLE`

- core/translate/expr.rs
- core/translate/group_by.rs
- core/translate/main_loop.rs
- core/vdbe/builder.rs
- core/vdbe/explain.rs
- core/vdbe/insn.rs
- core/vdbe/mod.rs
- testing/where.test
Change explanation is in the code comment for `Insn::Eq`:
```
/// Jump if either of the operands is null. Used for "jump when false" logic.
/// Eg. "SELECT * FROM users WHERE id = NULL" becomes:
/// <JUMP TO NEXT ROW IF id != NULL>
/// Without the jump_if_null flag it would not jump because the logical comparison "id != NULL" is never true.
/// This flag indicates that if either is null we should still jump.
jump_if_null: bool,      
```
Closes #754 
Excerpt from SQLite bytecode documentation for e.g. `Lt`:
> If the SQLITE_JUMPIFNULL bit of P5 is set and either reg(P1) or reg(P3) is NULL then the take the jump. If the SQLITE_JUMPIFNULL bit is clear then fall through if either operand is NULL.
I didn't want to start putting these flags into a bitmask so I just added a separate boolean. …
> translate_condition_expr(): fix cases where 1. we jump on false and 2. either operand is NULL

- vendored/sqlite3-parser/src/dialect/token.rs
- vendored/sqlite3-parser/src/lexer/sql/mod.rs
> Fix `select X'1';` causes limbo to go in infinite loop

- bindings/java/rs_src/limbo_connection.rs
- bindings/java/rs_src/limbo_db.rs
- bindings/java/rs_src/limbo_statement.rs
- bindings/java/src/main/java/org/github/tursodatabase/core/LimboDB.java
- bindings/java/src/main/java/org/github/tursodatabase/core/LimboResultSet.java
- bindings/java/src/main/java/org/github/tursodatabase/core/LimboStepResult.java
- bindings/java/src/test/java/org/github/tursodatabase/jdbc4/JDBC4ResultSetTest.java
- Do not create a new `io` and instead use `io` which is used when creating `LimboDatabase`. 
- Run the loop of `step` function on the rust side(better for performance as we don't have to switch between java <-> rust) 
- Java 
- handle invalid cases 
- remove @Disabled annotation from tests 
- Rust 
- add loops in the step function 
> bindings/java: Fix failing tests 

- README.md
One of the discord links in the readme was pointing to a Chinese discord. Both links are now pointing to Limbo's discord
> Correct discord link

- .github/workflows/push_only.yml
This adds a separate push-only.yml workflow. For now pull request API wasn't integrated yet, so shouldn't run on PRs.
disable cargo color
Fixes https://github.com/nyrkio/nyrkio/issues/304
> Add Nyrkiö change point detection to 'cargo bench' workflow

- core/lib.rs
- core/translate/emitter.rs
- core/vdbe/builder.rs
- core/vdbe/mod.rs
- tests/integration/common.rs
Closes #764 
Go driver needs support for fetching the column names after `prepare`
> Support returning column names from prepared statement

- Cargo.lock
- simulator/Cargo.toml
- simulator/generation/plan.rs
- simulator/generation/property.rs
- simulator/main.rs
- simulator/model/query.rs
- simulator/model/table.rs
- simulator/runner/cli.rs
- simulator/runner/env.rs
- simulator/runner/execution.rs
- simulator/runner/mod.rs
- simulator/runner/watch.rs
The current status of the PR is halfway. The new framing of simulation runner where `setup_simulation` is separated from `run_simulation` allows for injecting custom plans easily. The PR is currently missing the functionality to update the `SimulatorEnv` ad hoc from the plan, as the environment tables were typically created during the planning phase.
The next steps will be to implement a function `fn mk_env(InteractionPlan, SimulatorEnv) -> SimulatorEnv`, add `--load` flag to the CLI for loading a serialized plan file, making a corresponding environment and running the simulation.
We can optionally combine this with a `--save` option, in which we keep a seed-vault as part of limbo simulator, corresponding each seed with its generated plan and save the time to regenerate existing seeds by …
> simulator: implement `--load` and `--watch` flags

- core/lib.rs
- core/vdbe/mod.rs
The first rule of writing fast programs: don't use dynamic memory allocation!
Brings `SELECT 1` micro-benchmark back to 70 ns, which is a bit closer to what we had before.
> core: Fix Statement::reset()

- core/lib.rs
- core/types.rs
- core/vdbe/mod.rs
- core/vdbe/sorter.rs
Current micro-optimizations:
- store single data structure for cursors in programstate, not one for every cursor type
- use vec for cursors instead of btreemap
- use knowledge of cursor amount to pre-allocate cursor vec capacity
- don't use resize in ::new() and ::reset(), instead populate directly and reset by iterating over each elem (somehow this is faster)
- use bitfield for ended_coroutine instead of hashmap
> Program state optimizations

- bindings/java/rs_src/limbo_connection.rs
- bindings/java/src/main/java/org/github/tursodatabase/core/LimboConnection.java
- bindings/java/src/main/java/org/github/tursodatabase/jdbc4/JDBC4Connection.java
- bindings/java/src/test/java/org/github/tursodatabase/jdbc4/JDBC4ConnectionTest.java
- Implement `close()` method for `LimboConnection` and `JDBC4Connection` 
- Instead of closing the database when closing connections, close the connection instead 
> bindings/java: Implement LimboConnection `close()` 

- core/translate/expr.rs
Now:
```sql
limbo> create table t (a,b,c); insert into t (a,b,c) values ("hello", 234, 432);
thread 'main' panicked at core/translate/expr.rs:1621:29:
internal error: entered unreachable code: Id should be resolved to a Column before translation
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
After fix:
```sql
limbo> create table t (a,b,c); insert into t (a,b,c) values ("hello", 234, 432);
× Parse error: no such column: "hello" - should this be a string literal in single-quotes?
limbo>
```
Closes #800
> Fix panic when double quoted strings are used for column names.

- COMPAT.md
- Cargo.lock
- Cargo.toml
- Makefile
- core/Cargo.toml
- core/ext/mod.rs
- extensions/vector/Cargo.toml
- extensions/vector/src/lib.rs
- extensions/vector/src/vector.rs
- testing/vector.test
This pull requests adds some libSQL vector extension functions such as `vector()` and `vector_distance_cos()`, which can be used for exact nearest neighbor search as follows:
```
limbo> SELECT embedding, vector_distance_cos(embedding, '[9, 9, 9]')
...> FROM movies ORDER BY vector_distance_cos(embedding, '[9, 9, 9]');
[4, 5, 6]|0.013072490692138672
[1, 2, 3]|0.07417994737625122
```
Note that libSQL also support approximate nearest neighbour search with DiskANN indexing, which is something we eventually want to port to Limbo as well.
> Initial pass on vector extension

- bindings/go/rs_src/statement.rs
- core/lib.rs
This simple patch makes sure we can operate with a reference to the string instead of being forced to transform it to a string, and makes sure that the Arc doesn't have to be cloned (which can be expensive in multi-core systems).
This doesn't really make a large difference in benchmarks, given how expensive Parse::new() is.
> bindings/go: Avoid potentially expensive operations on prepare

- bindings/java/src/main/java/org/github/tursodatabase/core/LimboResultSet.java
- bindings/java/src/main/java/org/github/tursodatabase/core/LimboStatement.java
- bindings/java/src/main/java/org/github/tursodatabase/core/LimboStepResult.java
- bindings/java/src/main/java/org/github/tursodatabase/jdbc4/JDBC4ResultSet.java
- bindings/java/src/main/java/org/github/tursodatabase/jdbc4/JDBC4Statement.java
- bindings/java/src/test/java/org/github/tursodatabase/jdbc4/JDBC4ResultSetTest.java
- Implement `JDBC4ResultSet`'s `getXXX(columnIndex)` methods 
- `JDBC4ResultSet`'s `getXXX(columnIndex)` methods are implemented 
- Add some docs for clarification(+ leaving history) 
- [Issue](https://github.com/tursodatabase/limbo/issues/615)
> bindings/java: Implement methods in `JDBC4ResultSet`

- core/function.rs
- core/json/de.rs
- core/json/json_operations.rs
- core/json/mod.rs
- core/translate/expr.rs
- core/vdbe/mod.rs
- testing/json.test
First review #820
The function follows RFC 7386 JSON Merge Patch semantics:
* If the patch is null, the target is replaced with null
* If the patch contains a scalar value, the target is replaced with that value
* If both target and patch are objects, the patch is recursively applied
* null values in the patch result in property removal from the target
> json_patch() function implementation

- .github/labeler.yml
- .github/workflows/labeler.yml
- labeler@v4 -> labeler@v5 
- GH_TOKEN -> GITHUB_TOKEN 
- add sparse checkout action(to properly read `.github/labeler.yml`) 
- fix `.github/labeler.yml` which is where the configurations go  
- Tests in my forked repository
> Fix labeler.yml 

- core/translate/expr.rs
Closes #812 
`-9223372036854775808` is `MIN_INT64`. So when we extract out the minus and try to parse the remainder it becomes greater than MAX_INT64 (9223372036854775807) and will trigger overflow, which converts the literal into `Real`. So we have to handle it as a special case.
> Fix `SELECT -9223372036854775808` result differs from SQLite

- core/error.rs
- core/vdbe/mod.rs
Now we return `RuntimeError`.  Matches SQLite behavior.
SQLite:
```sql
sqlite> SELECT ABS(-9223372036854775808);
Runtime error: integer overflow
```
Limbo after this fix:
```sql
limbo> SELECT ABS(-9223372036854775808);
Runtime error: integer overflow
```
Closes https://github.com/tursodatabase/limbo/issues/815
> Fix `SELECT ABS(-9223372036854775808)` causes limbo to panic. 

- core/translate/aggregation.rs
- core/translate/delete.rs
- core/translate/emitter.rs
- core/translate/group_by.rs
- core/translate/main_loop.rs
- core/translate/order_by.rs
- core/translate/plan.rs
- core/translate/planner.rs
- core/translate/result_row.rs
- core/translate/select.rs
- core/translate/subquery.rs
- core/vdbe/explain.rs
- core/vdbe/insn.rs
- core/vdbe/mod.rs
- testing/all.test
- testing/offset.test
#739 
Started adding support for `LIMIT...OFFSET...`
- New `OffsetLimit` opcode
- `OFFSET` is now supported for:
- `SELECT...LIMIT...OFFSET`
- `SELECT...GROUP BY...LIMIT...OFFSET`
- `SELECT...ORDER BY...LIMIT...OFFSET`
- Subqueries for `SELECT` statements
**In progress/todo**
- **(will make in separate PR)** Add support for `DELETE...LIMIT...OFFSET`
- **(will make in separate PR)** Use `limit + offset` sum register from `OffsetLimit` to constrain number of records inserted into sorter
> Add support for offset in select queries

- core/vdbe/datetime.rs
- core/vdbe/mod.rs
- core/vdbe/strftime.rs
- testing/scalar-functions-datetime.test
This PR closes #787. Chrono offers to format the string from an iterator of Format Items. I created a custom iterator that only allows formatters specified by sqlite. This approach however does not address the inefficient way that julianday is calculated. Also, with this implementation we avoid having to maintain a separate vendored package for strftime that may become incompatible with Chrono in the future.
> Strftime compatibility solved

- bindings/go/limbo_test.go
- bindings/go/limbo_unix.go
- bindings/go/rs_src/rows.rs
- bindings/go/rs_src/types.rs
- bindings/go/stmt.go
- bindings/go/types.go
This PR fixes/adds support for the Blob type and adds the appropriate tests.
Types created on the Go side will be cleaned up rather quickly if nothing is referencing them, so this approach uses `runtime.Pinner` to pin the bytes in memory so the pointers will be valid when Rust uses `from_raw_parts` and then owns a new vec. They are then cleaned up after the FFI call with `pinner.Unpin`.
> bindings/go Support blob types in query arguments, free non-gc allocations

- core/benches/benchmark.rs
More convenient side by side comparison with sqlite.  Got this idea from [criterion's documentation](https://bheisler.github.io/criterion.rs/book/user_guide/comparing_functions.html). Some examples:
> Performance test side by side comparison with rusqlite

- core/translate/mod.rs
- core/vdbe/builder.rs
- vendored/sqlite3-parser/src/parser/ast/mod.rs
Instead of always having the caller specify all instructions, this
work introduces convenience functions into the program builder,
making the code a lot cleaner.
Draft for now, as this is done on top of #841
> Simplify bytecode emitters

- flake.lock
- flake.nix
Improvements:
- Use [rust-overlay](https://github.com/oxalica/rust-overlay), better maintained than fenix and allows for:
- Use `rust-toolchain.toml` as the source of truth for the current rust version, instead of tracking with stable. Preventing conflicting versions with non-nix users.
- Add flake checks, could be useful for CI in the future, together with crane and cachix.
- Add package, allow people to add limbo as a regular nix package. Now we can `nix build .#`, `nix run .#` and `nix shell .#` (this one adds `limbo` to the current `PATH`)
- Use [new `apple-sdk` pattern](https://discourse.nixos.org/t/the-darwin-sdks-have-been-updated/55295), no need to declare each framework now.
> Full flake overhaul

- core/translate/expr.rs
This PR remove manual null-comparison optimization (introduced in #847) which replace `Eq`/`Ne` instructions with explicit `IsNull`/`NotNull`. There are few factors for this change:
1. Before, manual optimization were incorrect because it ignored `jump_if_condition_is_true` flag which is important to properly build logical condition evaluation
2. Manual optimization covered all scenarios in test cases and scenarios when both sides are non trivial expressions were not covered by tests
3. Limbo already mark literals in the initial emitted bytecode as constants and will evaluate and store them only once - so performance difference from manual optimization seems very minor to me (but I am wrong with high probability)
4. I think (but again, I am wrong with high probability) that such …
> Fix null cmp codegen

- core/translate/delete.rs
- core/translate/emitter.rs
- core/translate/expr.rs
- core/translate/group_by.rs
- core/translate/main_loop.rs
- core/translate/optimizer.rs
- core/translate/order_by.rs
- core/translate/plan.rs
- core/translate/planner.rs
- core/translate/result_row.rs
- core/translate/select.rs
- core/translate/subquery.rs
This PR refactors the way we track referenced tables and associated planner operations related to them (scans, index searches, etc).
- We have a tree data structure called `SourceOperator` which is either a `Join`, `Scan`, `Search`, `Subquery` or `Nothing`.
```rust
/**
A SourceOperator is a Node in the query plan that reads data from a table.
*/
#[derive(Clone, Debug)]
pub enum SourceOperator {
// Join operator
// This operator is used to join two source operators.
// It takes a left and right source operator, a list of predicates to evaluate,
// and a boolean indicating whether it is an outer join.
Join {
id: usize,
left: Box<SourceOperator>,
right: Box<SourceOperator>,
predicates: Option<Vec<ast::Expr>>,
outer: bool,
using: Option<ast::DistinctNames>,
},
// Scan operator
// This …
```
> core/translate: refactor query planner again to be simpler

- core/translate/expr.rs
- core/translate/optimizer.rs
- tests/integration/fuzz/mod.rs
Fix few logical codegen issues and add fuzz tests for logical expressions
-  Right now Limbo fails to recognize `false` constant in case when any unary operator is used on the AST path. This PR add unary operator option in the rewrite code and handle such cases properly.
```sql
limbo> SELECT NOT FALSE;
× Parse error: no such column: FALSE - should this be a string literal in single-quotes?
```
- `ifnull` implementation produced incorrect codegen due to "careless" management of registers
```
limbo> SELECT ifnull(0, NOT 0)
[NULL here]
```
- `like` implementation produced incorrect codegen due to "careless" management of registers
```
limbo> SELECT like('a%', 'a') = 1;
thread 'main' panicked at core/vdbe/mod.rs:1902:41:
internal error: entered unreachable code: Like on non-text registers …
```
> Fix logical codegen

- bindings/wasm/lib.rs
- core/types.rs
- tests/integration/common.rs
- tests/integration/fuzz/mod.rs
- tests/integration/query_processing/test_read_path.rs
If you have a `&str` you would need to allocate and copy the string just to pass a reference to it again. Same goes if you have a slice of bytes. In all (most?) situations, that is not what you want and sometimes impossible to satisfy. Example:
```rs
impl From<&str> for Value<'_> {
fn from(value: &str) -> Self {
Self::Text(&value.to_owned())
}
}
```
Here, there is no way to pass a reference to a `String` without making the lifetime `'static`, since the string has to be dropped by the end of the function or leaked. I would consider this a anti-pattern. There is no reason to keep a shared reference to a owned value. (And can't think of any situation where you would need such thing)
Now, this is possible:
```rs
impl<'a> From<&'a str> for Value<'a> {
fn from(value: &'a str) -> Self { …
```
> Lower ownership requirement for `Value`

- core/lib.rs
- core/translate/mod.rs
- core/vdbe/builder.rs
- core/vdbe/mod.rs
We spend a lot of time especially in `GROUP BY` queries providing helpful comments for `EXPLAIN`, even when the query is not an `EXPLAIN`. So let's not do that
Closes #784 
```sql
Prepare `SELECT first_name, count(1) FROM users GROUP BY first_name HAVING count(1) > 1 ORDER BY cou...
time:   [4.2724 µs 4.2783 µs 4.2848 µs]
change: [-6.1063% -5.7376% -5.3626%] (p = 0.00 < 0.05)
```
doesn't affect the other trivial prepare benchmarks
> dont store insn comments unless the query is EXPLAIN

- core/benches/benchmark.rs
- core/lib.rs
It's a pointless wrapper on top of `step()` that introduce additional memory allocation and deallocation.
> core: Kill Statement::query() method

- COMPAT.md
- core/function.rs
- core/json/mod.rs
- core/json/ser.rs
- core/translate/expr.rs
- core/vdbe/mod.rs
- testing/json.test
This PR implements json_pretty. At the moment, support for jsonb is being added, so this function suffers from the same limitations as in json(x). Also, I have not found a way to implement the same conversion of Blob -> String that SQLite does. From my own experimentation, I believe SQLite converts blobs to a lossy ascii representation, but I would appreciate some help on this.
> implement json_pretty

- core/io/memory.rs
Despite likely replacing this in-memory IO setup in the near future with a `mmap` implementation (#859) , in the spirit of everyone getting bitten by the perf bug lately I thought I would speed up our in-memory IO a bit.
> Improve in-memory IO performance, remove runtime borrow checking

- core/translate/delete.rs
- core/translate/planner.rs
- core/translate/select.rs
- testing/groupby.test
Closes #744 
```sql
do_execsql_test column_alias_in_group_by_order_by_having {
select first_name as fn, count(1) as fn_count from users where fn in ('Wanda', 'Whitney', 'William') group by fn having fn_count > 10 order by fn_count;
} {Whitney|11
William|111}
```
> Support column aliases in GROUP BY, ORDER BY and HAVING

- core/lib.rs
- core/storage/pager.rs
- core/storage/wal.rs
- core/vdbe/mod.rs
- tests/integration/common.rs
- tests/integration/functions/test_function_rowid.rs
- tests/integration/mod.rs
- tests/integration/query_processing/test_read_path.rs
- tests/integration/query_processing/test_write_path.rs
- tests/integration/wal/mod.rs
- tests/integration/wal/test_wal.rs
adding checkpoint result returning number of pages in wal and num pages checkpointed.
Part of #696 
SQLite returns in checkpoint result of calling `pragma wal_checkpoint;` `0|3|3` while limbo returns `0|0|0`. https://sqlite.org/pragma.html#pragma_wal_checkpoint
- 1st col: 1 (checkpoint SQLITE_BUSY) or 0 (not busy).
- 2nd col: # modified pages written to wal file
- 3rd col: # pages moved to db after checkpoint
This PR aims to add 2nd and 3rd column to the checkpoint result.
SQLite
```
sqlite3 test.db
sqlite> pragma journal_mode=wal;
wal
sqlite> pragma journal_mode;
wal
sqlite> create table t1 (id text);
sqlite> insert into t1(id) values (1),(2);
sqlite> select * from t1;
1
2
sqlite> pragma wal_checkpoint;
0|3|3
```
Limbo
```
./target/debug/limbo test.db
Limbo v0.0.13
Enter ".help" for …
```
> Adding checkpoint result

- core/benches/benchmark.rs
Fixes the following panics:
Benchmarking Execute `SELECT * FROM users LIMIT ?`/Limbo/100: Profiling for 5.0000 sthread 'main' panicked at core/benches/benchmark.rs:69:43:
called `Result::unwrap()` on an `Err` value: IOError(Os { code: 4, kind: Interrupted, message: "Interrupted system call" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> core: Fix benchmark panic if syscall is interrupted

- Cargo.lock
- core/Cargo.toml
- core/lib.rs
- core/storage/pager.rs
- core/storage/sqlite3_ondisk.rs
- core/storage/wal.rs
We really need to make the WAL lock less expensive, but switching to `parking_lot` is anyway something we should do.
Before:
```
Execute `SELECT 1`/Limbo
time:   [56.230 ns 56.463 ns 56.688 ns]
```
After:
```
Execute `SELECT 1`/Limbo
time:   [52.003 ns 52.132 ns 52.287 ns]
```
> core: Switch to parking_lot for RwLock

- core/lib.rs
- core/schema.rs
- core/translate/delete.rs
- core/translate/emitter.rs
- core/translate/main_loop.rs
- core/translate/optimizer.rs
- core/translate/order_by.rs
- core/translate/plan.rs
- core/translate/select.rs
- core/translate/subquery.rs
- core/vdbe/builder.rs
- core/vdbe/mod.rs
```bash
Prepare `SELECT 1`/Limbo/SELECT 1
time:   [765.94 ns 768.26 ns 771.03 ns]
change: [-7.8340% -7.4887% -7.1406%] (p = 0.00 < 0.05)
Prepare `SELECT * FROM users LIMIT 1`/Limbo/SELECT * FROM users LIMIT 1
time:   [1.5673 µs 1.5699 µs 1.5731 µs]
change: [-10.810% -9.7122% -8.4951%] (p = 0.00 < 0.05)
Prepare `SELECT first_name, count(1) FROM users GROUP BY first_name HAVING count(1) > 1 ORDER BY cou...
time:   [4.1331 µs 4.1421 µs 4.1513 µs]
change: [-9.3157% -9.0255% -8.7372%] (p = 0.00 < 0.05)
```
flamegraph for prepare `SELECT 1`:
> Small perf optimizations to statement preparation

- COMPAT.md
- Cargo.lock
- core/function.rs
- core/json/mod.rs
- core/translate/expr.rs
- core/vdbe/mod.rs
- testing/json.test
This PR adds support for `json_set`.
There are three helper functions added:
1. `json_path_from_owned_value`, this function turns an `OwnedValue` into a `JsonPath`.
2. `find_or_create_target`, this function is similar to `find_target` with the added bonus of creating the target if it doesn't exist. There is a caveat with this function and that is that it will create objects/arrays as it goes, meaning if you send `{}` into it and try getting the path `$.some.nested.array[123].field`, it will return `{"some":{"nested":array:[]}}` since creation of `some`, `nested` and `array` will succeed, but accessing element `123` will fail.
3. `create_and_mutate_json_by_path`, this function is very similar to `mutate_json_by_path` but calls `find_or_create_target` instead of `find_target`
Related to …
> Implement `json_set`

- core/translate/delete.rs
- core/translate/insert.rs
- core/translate/mod.rs
- core/translate/pragma.rs
- core/translate/select.rs
- core/vdbe/builder.rs
Use knowledge of query plan to inform how much memory to initially allocate for `ProgramBuilder` vectors
Some of them are exact, some are semi-random estimates
```sql
Prepare `SELECT 1`/Limbo/SELECT 1
time:   [756.93 ns 758.11 ns 759.59 ns]
change: [-4.5974% -4.3153% -4.0393%] (p = 0.00 < 0.05)
Found 7 outliers among 100 measurements (7.00%)
2 (2.00%) low severe
1 (1.00%) low mild
3 (3.00%) high mild
1 (1.00%) high severe
Prepare `SELECT * FROM users LIMIT 1`/Limbo/SELECT * FROM users LIMIT 1
time:   [1.4739 µs 1.4769 µs 1.4800 µs]
change: [-7.9364% -7.7171% -7.4979%] (p = 0.00 < 0.05)
Found 1 outliers among 100 measurements (1.00%)
1 (1.00%) high mild
Prepare `SELECT first_name, count(1) FROM users GROUP BY first_name HAVING count(1) > …
```
> prepare perf: make ProgramBuilder aware of plan to count/estimate required memory

- bindings/go/rs_src/rows.rs
- core/lib.rs
- core/schema.rs
- core/translate/emitter.rs
- core/translate/expr.rs
- core/translate/group_by.rs
- core/translate/insert.rs
- core/translate/optimizer.rs
- core/translate/order_by.rs
- core/translate/plan.rs
- core/translate/planner.rs
- core/translate/pragma.rs
- core/translate/select.rs
- core/vdbe/builder.rs
- core/vdbe/explain.rs
- core/vdbe/mod.rs
- tests/integration/common.rs
- Remove eagerly allocated `name` from `ResultSetColumn`
- `ResultSetColumn` can calculate `name()` on demand:
- if it has an alias (`foo as bar`), use that
- if it is a column reference, use that
- otherwise return none, and callers can assign it a placeholder name (like `column_1`)
- move the `plan.result_columns` and `plan.table_references` to `Program` after preparing statement is done, so that column names can be returned upon request
- make `name` in `Column` optional, not needed for pseudo tables and sorters so avoids an extra string allocation
```sql
Prepare `SELECT 1`/Limbo/SELECT 1
time:   [756.80 ns 758.27 ns 760.04 ns]
change: [-3.3257% -3.0252% -2.7035%] (p = 0.00 < 0.05)
Found 8 outliers among 100 measurements (8.00%)
2 (2.00%) low severe
3 (3.00%) …
```
> prepare perf: dont eagerly allocate result column name strings

- bindings/go/rs_src/rows.rs
- bindings/go/rs_src/statement.rs
- bindings/java/rs_src/limbo_statement.rs
- bindings/python/src/lib.rs
- bindings/wasm/lib.rs
- cli/app.rs
- cli/import.rs
- core/benches/benchmark.rs
- core/lib.rs
- core/types.rs
- core/util.rs
- core/vdbe/mod.rs
- perf/latency/limbo/src/main.rs
- simulator/generation/plan.rs
- sqlite3/src/lib.rs
- tests/integration/functions/test_function_rowid.rs
- tests/integration/fuzz/mod.rs
- tests/integration/query_processing/test_read_path.rs
- tests/integration/query_processing/test_write_path.rs
- tests/integration/wal/test_wal.rs
Move result row to `ProgramState` to mimic what SQLite does where `Vdbe` struct has a `pResultRow` member. This makes it easier to deal with result lifetime, but more importantly, eventually lazily parse values at the edges of the API.
> core: Move result row to ProgramState

- Cargo.lock
- core/lib.rs
- core/translate/main_loop.rs
- core/vdbe/builder.rs
- core/vdbe/explain.rs
- core/vdbe/insn.rs
- core/vdbe/mod.rs
- extensions/series/Cargo.toml
- extensions/series/src/lib.rs
- testing/extensions.py
Adds `quickcheck` property based tests to the recently merged `generate_series` implementation and fixes various issues in it:
- `0` for `step` should be treated as `1`
- missing `step` should be treated as `1`
- a string like `a` for `step` should be treated as `1`
- saturating overflow
- return an empty series for a variety of invalid inputs, instead of erroring
For the future:
We should have e2e/fuzz tests comparing sqlite implementation to limbo implementation
> Add quickcheck tests for generate_series() and refine implementation

- COMPAT.md
- Makefile
- core/function.rs
- core/json/mod.rs
- core/translate/expr.rs
- core/vdbe/mod.rs
- testing/json.test
Hi! This is my first PR on the project, so I apologize if I did not follow a convention from the project. 
#127 
This PR implements json_quote as specified in their source: https://www.sqlite.org/json1.html#jquote. It follows the internal doc guidelines for implementing functions. Most tests were added from sqlite test suite for json_quote, while some others were added by me. Sqlite test suite for json_quote depends on json_valid to test for correct escape control characters, so that specific test at the moment cannot be done the same way.
> Implement json_quote

- cli/app.rs
This is especially useful if you frequently run SQL query like `SELECT * ...`.
```
limbo> .mode pretty
limbo> select 123 as column1, 'Hello world' as column_2;
+-----+-------------+
| 123 | Hello world |
+-----+-------------+
```
```
limbo> .mode pretty
limbo> select 123 as column1, 'Hello world' as column_2;
+---------+-------------+
| column1 | column_2    |
+---------+-------------+
| 123     | Hello world |
+---------+-------------+
```
---
In the future, if limbo adds a method like `.decl_type()`, we can also display the data type.
```
D select 123 as column1, 'Hello world' as column_2;
┌─────────┬─────────────┐
│ column1 │  column_2   │
│  int32  │   varchar   │
├─────────┼─────────────┤
│   123   │ Hello world │
└─────────┴─────────────┘
```
> cli: Add column names in Pretty mode

- core/mvcc/database/mod.rs
- core/mvcc/database/tests.rs
Fixes three bugs:
- When a transaction commits, it should:
1. set the end timestamp of the old version to its own **end timestamp**,
2. set the begin timestamp of the new version to its own **end timestamp**
* we were erroneously setting it to the transaction's begin timestamp. see https://www.cs.cmu.edu/~15721-f24/papers/Hekaton.pdf page 299 diagram.
- When checking for write conflicts, the system should ignore versions that the transaction cannot see. We were checking for write conflicts before visibility, allowing a tx to always see the latest committed version and to always overwrite it, since latest committed versions dont have an end timestamp.
- When checking for write conflicts, the _presence_ of an end timestamp should always indicate that it is not the latest version and thus a …
> MVCC: fix write conflict handling

- Cargo.lock
- core/io/io_uring.rs
Since we are already round robin'ing our `iovecs` in the same way, and the map will never be larger than MAX_IOVECS, we can remove the cost of hashing and keep o(1) lookups.
> Replace hashmap for io_uring pending ops with static array

- vendored/sqlite3-parser/src/lexer/sql/mod.rs
- vendored/sqlite3-parser/src/lexer/sql/test.rs
Added  `had_true: bool` to `Parser` to track the state of error encounter, this will be set to `true` once we encounter an error.
If `had_error` is set to true we early return `Ok(None)`.
`FallibleIterator` works in the following way [when `next()` returns](https://docs.rs/fallible-iterator/latest/fallible_iterator/trait.FallibleIterator.html#tymethod.next):
- `Ok(Some(item))` if there's a valid next item.
- `Ok(None)` if the iteration is complete.
- `Err(e)` if there's an error. 
I have also added a unit test to check the above contract holds when parsing `SELECT FROM foo`.
After the fix:
```
limbo> SELECT FROM foo;
× near "FROM": syntax error at (1, 12)
╭────
1 │ SELECT FROM foo; 
·           ▲
·           ╰── syntax error
╰────
```
Closes #865
> Fix `Parser` continuing to parse after encountering an error

- core/lib.rs
We expose Wal trait as public, but there are three types in its signature that are private.
Notice I chose to expose limbo_core::result instead of limbo_core::result::LimboResult, since LimboResult is the only type in that module.
> Expose types in Wal

- core/translate/expr.rs
- core/vdbe/builder.rs
- testing/select.test
- tests/integration/fuzz/mod.rs
(after fixing complicated b-tree bugs - I want to end my day with the joy of fixing simple bugs)
This PR fix bug in emit (which was introduced after switch from `HashMap` to `Vec`) and also align `CASE` codegen in case of `NULL` result from `WHEN` clause with SQLite behaviour.
> Fix case and emit

- core/translate/expr.rs
- core/vdbe/builder.rs
- testing/coalesce.test
- testing/select.test
- tests/integration/fuzz/mod.rs
Add `COALESCE` function in fuzz test and fix bug (found by fuzzer with `COALESCE`) related to the resolution of labels which needs to be resolved to next emitted instruction.
Before, code assumed that no two labels will need to be resolved to next emitted instruction. But this assumption is wrong (at least in current codegen logic) for example for following expression `COALESCE(0, COALESCE(0, 0))`. Here, both `COALESCE` functions will create label and resolve it to next emitted instruction in the end of generation. So, in this case one of the labels will be actually "orphaned" and never be assigned any position in the emitted code.
> Fix coalesce

- core/translate/expr.rs
This PR make `translate_and_mark` accept target register as this is very common error in the current code when emitting code for the function code rely on the incorrect property that all arguments can be evaluated without additional intermediate registers.
I believe that this PR also fix bugs in the implementation of few scalar functions.
> translate_and_mark helper with its previous signature is error prone

- bindings/go/rs_src/rows.rs
- bindings/java/rs_src/limbo_statement.rs
- bindings/python/src/lib.rs
- bindings/wasm/lib.rs
- cli/app.rs
- core/storage/btree.rs
- core/types.rs
- core/vdbe/explain.rs
- core/vdbe/mod.rs
- core/vdbe/sorter.rs
- simulator/generation/plan.rs
- sqlite3/src/lib.rs
- tests/integration/functions/test_function_rowid.rs
- tests/integration/fuzz/mod.rs
- tests/integration/query_processing/test_read_path.rs
- tests/integration/query_processing/test_write_path.rs
- tests/integration/wal/test_wal.rs
This is an attempt to move towards #881. I am not sure this is the direction you want to take. In any case, I thought I would take a crack at converting `values` from `Record` to private and see how bad it would be. 
In the end, as you can see, it is not so bad. I think performance-wise it shouldn't be a bad hit with Rust's zero-cost abstraction. Also, during the process I noticed a couple improvements that could be made here and there but I honestly wanted to start with something small enough that wouldn't be too hard to review.
Anyway, let me know if this is really how you would like to proceed.
> Make record values private

- bindings/wasm/lib.rs
- core/io/generic.rs
- core/io/io_uring.rs
- core/io/memory.rs
- core/io/mod.rs
- core/io/unix.rs
- core/io/windows.rs
- core/lib.rs
- core/storage/btree.rs
- core/storage/database.rs
- core/storage/sqlite3_ondisk.rs
- core/storage/wal.rs
- simulator/runner/file.rs
I am on a bit of a mission to revisit a lot of the ref counting, this was an easy first win.
It seems to be a linear path of function calls or hashmaps which can own the completions directly, no cloning needed.
> Remove unnecessary reference counting from completion I/O callbacks

- COMPAT.md
- core/lib.rs
- core/translate/planner.rs
- core/translate/select.rs
- testing/subquery.test
Adds initial limited support for CTEs.
- No MATERIALIZED
- No RECURSIVE
- No named CTE columns
- Only SELECT statements supported inside CTE
Basically this kind of WITH clause can just be rewritten as a subquery, so this PR adds some plumbing to rewrite them using the existing subquery machinery.
It also introduces the concept of a `Scope` where a child query can refer to its parent, useful for CTEs like:
```
do_execsql_test nested-subquery-cte {
with nested_sub as (
select concat(name, '!!!') as loud_hat 
from products where name = 'hat'
),
sub as (
select upper(nested_sub.loud_hat) as loudest_hat from nested_sub
)
select sub.loudest_hat from sub;
} {HAT!!!}
```
I think we need to expand the use of `Scope` to all of our identifier resolutions (currently we don't explicitly have logic for …
> Initial support for WITH clauses (common table expressions)

- bindings/go/rs_src/rows.rs
- bindings/java/rs_src/limbo_statement.rs
- cli/app.rs
- core/lib.rs
- tests/integration/common.rs
Fix #926 
```
limbo> select 1, 2, 1+2*3, 'Hello';
┌───┬───┬───────────┬─────────┐
│ 1 │ 2 │ 1 + 2 * 3 │ 'Hello' │
├───┼───┼───────────┼─────────┤
│ 1 │ 2 │         7 │ Hello   │
└───┴───┴───────────┴─────────┘
```
> core: Add default column name

- cli/app.rs
- cli/main.rs
Bug: Infinite loop when parsing unclosed string literal
To reproduce:
Run query: `SELECT max(';`
Current behavior:
- Query runner enters an infinite loop when encountering an unclosed string literal and prints error
Fix:
- Throw error and stop query runner loop
Closes #988
> cli: Fix infinite loop on non-terminated literal

- Cargo.lock
- bindings/wasm/Cargo.toml
- core/Cargo.toml
- core/functions/datetime.rs
- core/io/generic.rs
- core/io/io_uring.rs
- core/io/memory.rs
- core/io/unix.rs
- core/io/windows.rs
- core/lib.rs
- core/mvcc/cursor.rs
- core/parameters.rs
- core/schema.rs
- core/storage/btree.rs
- core/storage/page_cache.rs
- core/storage/pager.rs
- core/storage/sqlite3_ondisk.rs
- core/storage/wal.rs
- core/vdbe/mod.rs
In order [experimentally compile](https://github.com/DougAnderson444/wit-limbo) `limbo_core` to a [wasm component](https://component-model.bytecodealliance.org/), limbo needed to have no reliance on `js`, `js-sys`, `wasm-bindgen`, et al. (for those who aren't familiar, there are many `wasm` runtimes and not all of them play nice with `wasm-bindgen`)
This PR simply cleans up the dependencies, and puts them behind optional flags and whatnot in order to enable this. Both `log` and `tracing` were being used, so I reduced this only to `tracing`.
End result is limbo can be used like this: https://github.com/DougAnderson444/wit-limbo 
We can open a discussion on the possibilities that running limbo as a wasm component can offer, including potentially using composable components to implement the …
> Streamline dependencies to build for all wasm targets

- core/io/io_uring.rs
- core/io/memory.rs
- core/io/mod.rs
- core/io/unix.rs
- core/io/windows.rs
This PR reworks the unix I/O backend, removing runtime reference counting/borrow checking and optimizing away the hashmap in favor of a static array, with an unlikely fallback vec.
The only reason the fallback vec is there is because unlike the `io_uring` module, we cannot simply index into the array with the fd  as the OS could theoretically give us a fd up to I believe 1024 so keeping an array of that size for a few elements is unnecessary.
> Performance improvements for Unix I/O backend

- CONTRIBUTING.md
I found invalid option while reading CONTRIBUTING.md and trying some commands in it.
error:
```
$ cargo run --package limbo --bin limbo database.db
error: no bin target named `limbo`.
$ rustc --version
rustc 1.83.0 (90b35a623 2024-11-26)
```
ref: https://github.com/tursodatabase/limbo/blob/291637cc7120303fd7337c342cf5dbc9363faa85/cli/Cargo.toml#L17
> doc: Use `limbo_cli` as package instead for running limbo cli

- core/translate/planner.rs
- testing/orderby.test
was running some clickbench queries against limbo and noticed this one
> select: fix bug with referring to a mixed-case alias

- COMPAT.md
- core/translate/pragma.rs
- vendored/sqlite3-parser/src/parser/ast/mod.rs
easy implementation, sqlite claims it is a noop now
"This pragma no longer functions. It has become a no-op. The capabilities formerly provided by PRAGMA legacy_file_format are now available using the SQLITE_DBCONFIG_LEGACY_FILE_FORMAT option to the sqlite3_db_config() C-language interface."
> Implement the legacy_file_format pragma

- core/translate/select.rs
- testing/groupby.test
We already supported this for ORDER BY but not GROUP BY - again noticed this when running against some clickbench queries
> Support numeric column references in GROUP BY

- core/vdbe/mod.rs
According to SQLite documentation, the way to use these instructions is to compare the seek key to the index key as you would with the Compare opcode. The compare opcode states:
> "Compare two vectors of registers in reg(P1)..reg(P1+P3-1) (call this vector "A") and in reg(P2)..reg(P2+P3-1) ("B")."
In other words, we should compare the same number of columns from each, not compare the entire keys.
This fixes a few Clickbench queries returning incorrect results, and so closes #1009
---
Future work: support index seek keys that use multiple columns. Our index seek is many times slower than SQLite because we're not utilizing all the possible columns -- instead we just use the first index column to seek and then make the rest of the comparisons as normal loop condition expressions.
Note that …
> Fix IdxGt, IdxGe, IdxLt, and IdxLe instructions

- core/vdbe/mod.rs
- testing/scalar-functions.test
- tests/integration/fuzz/mod.rs
Align `substr` implementation with SQLite spec (https://www.sqlite.org/lang_corefunc.html#substr):
> The substr(X,Y,Z) function returns a substring of input string X that begins with the Y-th character and which is Z characters long. If Z is omitted then substr(X,Y) returns all characters through the end of the string X beginning with the Y-th. The left-most character of X is number 1. If Y is negative then the first character of the substring is found by counting from the right rather than the left. If Z is negative then the abs(Z) characters preceding the Y-th character are returned. If X is a string then characters indices refer to actual UTF-8 characters. If X is a BLOB then the indices refer to bytes.
> Fix substr

- core/translate/expr.rs
- tests/integration/common.rs
- tests/integration/fuzz/mod.rs
This PR adds simple fuzz test with `SELECT` over data in table and fixes bug in codegen for `AND` binary operator.
The new fuzz test resembles `logical_expression_fuzz` - but right now Limbo do not support a lot of conditions (for example, `SELECT * FROM users WHERE NOT deleted` will fail with `not implemented` error) - so fuzz test written from scratch and limits `WHERE` condition structure to the features supported right now.
> Fix and predicate

- core/storage/sqlite3_ondisk.rs
- tests/integration/fuzz/grammar_generator.rs
- tests/integration/fuzz/mod.rs
For serial types 3 and 5 SQLite uses twos-complement representation of 24bit and 48bit widths integers. Limbo need to follow same
> fix 24/48 bit width serial types parsing

- testing/cli_tests/cli_test_cases.py
fixes CI failing for CLI tests after `raw` was renamed to output
> Fix cli test for new output name

- core/lib.rs
- core/util.rs
closes #977 
In order to properly get #960 merged and keep some sort of the same API we have now, we need to support URIs/query parameters for opening new databases.
This PR doesn't attempt to implement anything useful with this, it only handles parsing, but it will allow #960 to properly open a new file with a specific VFS without having to entirely re-design the `open_file` method/API. The existing option in that PR right now is less than ideal.
e.g. All of the existing methods already accept an `IO` impl
```rust
pub fn open_file(io: Arc<dyn IO>, path: &str) -> Result<Arc<Database>> {
// or
pub fn open(
io: Arc<dyn IO>,
page_io: Rc<dyn DatabaseStorage>,
wal: Rc<RefCell<dyn Wal>>,
shared_wal: Arc<RwLock<WalFileShared>>,
buffer_pool: Rc<BufferPool>,
) -> Result<Arc<Database>> {
```
Right …
> Handle parsing URI according to SQLite specification

- Makefile
- testing/cli_tests/extensions.py
- testing/cli_tests/test_limbo_cli.py
A nice python class was added in #941 for easily testing limbo's CLI output. As the tests around extensions continue to grow, we should use this as much as possible for non-Tcl/compatibility tests so they can scale more easily without getting messy. I am going to add a whole bunch of tests that will explicitly test each kind of extension both when loaded staticly/dynamically and combined with other export types and I want to get the existing ones migrated over first.
> Clean up extension python tests to use convenience CLI-test class

- core/vdbe/mod.rs
> Fix wrong count() result if the column specified contains a NULL

- core/lib.rs
- core/storage/btree.rs
- core/storage/pager.rs
- core/storage/sqlite3_ondisk.rs
- core/vdbe/mod.rs
Beep boop.
What happened you ask? I removed the dumb balancing algorithm I implemented in favor of SQLite's implementation based on B*Tree[1] where a page is 2/3 full instead of 1/2. It also tries to balance a page by taking a maximum 3 pages and distributing cells evenly between them.
I've made some changes that are somewhat related:
* Moved most operations on pages out of BTreeCursor because those operations are based on a page, not on a cursor, and it makes it easier to test.
* Fixed `write_u16` and `read_u16` cases that didn't need a implicit offset calculation. Added: `write_u16_no_offset` and `read_u16_no_offset` to counter this. 
* Added some tests with fuzz testing too.
* Fixed some important actions like: `compute_free_space`, `defragment_page` and `drop_cell`. 
[1] …
> Implement SQLite balancing algorithm

- cli/app.rs
Fixes [#1084](https://github.com/tursodatabase/limbo/issues/1084), displays blobs as blob literals for the `.dump` command:
```
limbo> CREATE TABLE IF NOT EXISTS files (
id INTEGER PRIMARY KEY AUTOINCREMENT,
data BLOB
);
INSERT INTO files (data) VALUES (X'89504E470D0A1A0A0000000D49484452000000');
limbo> .dump
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE files (id INTEGER PRIMARY KEY AUTOINCREMENT, data BLOB);
INSERT INTO files VALUES(1,X'89504e470d0a1a0a0000000d49484452000000');
COMMIT;
```
> Display blobs as blob literals in `.dump`

- cli/input.rs
These 2 were missing from the help menu and are both pretty useful. Noticed `.exit` is also missing, ambivalent about this one since it's rarely needed. 
Also removed all ending periods to make these consistent (sqlite uses this punctuation style as well)
> Add "dump" and "load" to the help menu

- Cargo.lock
- Cargo.toml
- NOTICE.md
- core/Cargo.toml
- core/ext/mod.rs
- extensions/ipaddr/Cargo.toml
- extensions/ipaddr/src/lib.rs
- licenses/extensions/ipnetwork-apache-license.md
- licenses/extensions/ipnetwork-mit-license.md
- scripts/publish-crates.sh
- testing/cli_tests/extensions.py
Relatively simple one, although I notice we don't have a lot of testing here. The extensions have all their tests in the python cli extension tests. Do we want to keep it that way or motivate inline rust tests for these modules?
> Add sqlean ipaddr extension

- core/Cargo.toml
- core/lib.rs
- core/types.rs
- core/vdbe/mod.rs
- extensions/core/Cargo.toml
- extensions/core/src/lib.rs
- extensions/core/src/types.rs
- extensions/uuid/src/lib.rs
- macros/src/lib.rs
This PR cleans up some comments in the extension API and prevents extensions themselves from calling 'free' on Value types that are exposed to the user facing traits, as well as changes the `from_ffi` method for OwnedValues to take ownership and automatically free the values to prevent memory leaks.
This PR also finds the name of the `args: &[Value]` argument for scalar functions in extensions, and uses that in the proc macro, instead of relying on documentation to communicate that the parameter must be named `args`.
> Clean up extension types API, introduce json text subtype

- core/storage/btree.rs
- core/storage/pager.rs
- core/vdbe/mod.rs
Move page allocation to pager so that we don't need to instantiate a cursor to create a B-Tree.
> core: Clean up B-Tree creation code

- bindings/rust/src/lib.rs
It's so weird that other bindings can open local file but Rust binding itself cannot.
> Enable local file connection in Rust binding

- core/benches/mvcc_benchmark.rs
- core/mvcc/cursor.rs
- core/mvcc/database/mod.rs
- core/mvcc/database/tests.rs
- core/mvcc/mod.rs
- core/mvcc/persistent_storage/mod.rs
The logging code that writes out transactions to disk needs to write out the byte array that we actually use. The code is less hairly without the generics so drop them.
> core/mvcc: Eliminate row generic types

- core/storage/wal.rs
- core/vdbe/mod.rs
- tests/integration/wal/test_wal.rs
While adding logs to our locks in `Wal` I noticed we weren't cleaning up connection's transaction state. This PR set to `TransactionState::None` once commited and calls `end_read_txn` and `end_tx` in case of write.
Fixes #1004
> Transaction finish lock fixes

- bindings/go/rs_src/lib.rs
- bindings/java/rs_src/limbo_db.rs
- bindings/python/src/lib.rs
- bindings/rust/src/lib.rs
- bindings/wasm/lib.rs
- cli/app.rs
- cli/input.rs
- core/benches/benchmark.rs
- core/lib.rs
- core/mvcc/cursor.rs
- core/mvcc/database/mod.rs
- core/mvcc/mod.rs
- core/storage/btree.rs
- core/util.rs
- core/vdbe/mod.rs
- simulator/main.rs
- simulator/runner/env.rs
- sqlite3/src/lib.rs
- tests/integration/common.rs
This pull request integrates MVCC with the VDBE.
The long term plan is to implement SQLite `BEGIN CONCURRENT` by introducing a "MV store" abstraction (that implements the Hekaton in-memory MVCC index) above the pager. Traditional SQLite transactions use the pager and the WAL, but MV store has its own transaction path that updates the in-memory multi-versioned index. If a key does not exist in the MVCC index, we read records from the pager. When a MVCC transaction commits, we emit WAL entries.
In this pull request, we wire up the MVCC transaction machinery to VDBE and multi-version cursor to the b-tree cursor. Currently, the database either runs in normal b-tree mode or in in-memory MVCC, but we need to explore if we can make it a hybrid solution where you can read from both MVCC index and …
> Integrate MVCC

- sqlite3/README.md
- sqlite3/include/sqlite3.h
- sqlite3/src/lib.rs
- sqlite3/tests/Makefile
- sqlite3/tests/main.c
- sqlite3/tests/test-wal.c
This PR introduces test for SQLite3 API implementation, adding both unit tests in Rust and maintaining existing C compatibility tests.
- Added unit tests for core SQLite3 operations in `lib.rs`:
- Database initialization and shutdown
- Memory database operations
- Error code handling and messages
- Statement preparation and execution
- Version information verification
> sqlite3: Add Rust tests for SQLite3 API implementation

- bindings/rust/src/lib.rs
- bindings/rust/src/value.rs
- core/lib.rs
Fixes the rust bindings so that `example.rs` is runnable
> bindings/rust: Fix rust bindings so example runs

- Cargo.lock
- core/Cargo.toml
- core/lib.rs
- core/storage/btree.rs
- core/storage/page_cache.rs
- core/storage/pager.rs
- core/storage/sqlite3_ondisk.rs
- core/storage/wal.rs
- core/vdbe/mod.rs
- sqlite3/src/lib.rs
- tests/integration/query_processing/test_write_path.rs
You might have guessed the `DumbLruCache` was dumb, but no, it was a reference to myself. This PR fixes some dumb mistakes of detaching nodes which failed to update `tail` and `head` properly.
Edit: This PR now fixes `Connection::execute` which funnily enough we didn't notice it was returning successfully but in reality `program.step` returned `IO` which made us think it was finished but not really.
Edit 2: This PR fixes yet another thing! Pages read from WAL where being initialized as if they were `id > 1`. By making it not this dumb thing we can read `page 1` from `WAL` without failing catastrophically
> Fix `DumbLruPageCache`, `Connection::execute` and `page 1` read from wal

- Cargo.lock
- Cargo.toml
- cli/app.rs
- cli/input.rs
- core/Cargo.toml
- core/ext/dynamic.rs
- core/ext/mod.rs
- core/io/mod.rs
- core/io/vfs.rs
- core/lib.rs
- extensions/core/Cargo.toml
- extensions/core/README.md
- extensions/core/src/lib.rs
- extensions/core/src/types.rs
- extensions/core/src/vfs_modules.rs
- extensions/kvstore/src/lib.rs
- extensions/tests/Cargo.toml
- extensions/tests/src/lib.rs
- macros/src/args.rs
- macros/src/lib.rs
- testing/cli_tests/extensions.py
- testing/cli_tests/test_limbo_cli.py
This PR implements a `VFS` module for our extension library, allowing extensions to be written that can introduce different I/O back-ends.
EDIT: there is an included plain external/sync vfs example for testing, as mentioned in #996 they can be combined after they are both merged and we can keep 1 extension crate just for testing that features can be added to, without making a new extension just to test stuff.
This PR also adds the `.vfslist` dot command, and replaces the `--io` CLI argument with `--vfs` to match sqlite.
In order to support building vfs modules at compile time, and to then support opening a brand new db file using a staticly built-in extension module, a new method was created `open_with_vfs` that will load any vfs modules before a `Database` is created, and uses that `IO` …
> Initial pass on Virtual FileSystem extension module

- core/translate/transaction.rs
- core/vdbe/explain.rs
- core/vdbe/mod.rs
- testing/transactions.test
As explained in [docs](https://sqlite.org/lang_transaction.html):
> "DEFERRED means that the transaction does not actually start until the database is first accessed. Internally, the BEGIN DEFERRED statement merely sets a flag on the database connection that turns off the automatic commit that would normally occur when the last statement finishes. This causes the transaction that is automatically started to persist until an explicit COMMIT or ROLLBACK or until a rollback is provoked by an error or an ON CONFLICT ROLLBACK clause. If the first statement after BEGIN DEFERRED is a SELECT, then a read transaction is started. Subsequent write statements will upgrade the transaction to a write transaction if possible, or return SQLITE_BUSY. If the first statement after BEGIN DEFERRED is a write …
> Implement `BEGIN DEFERRED`

- bindings/wasm/lib.rs
- core/fast_lock.rs
- core/lib.rs
- core/storage/btree.rs
- core/storage/pager.rs
- core/storage/sqlite3_ondisk.rs
- core/translate/mod.rs
- core/translate/pragma.rs
- core/vdbe/builder.rs
- core/vdbe/mod.rs
The motivation behind implementing our own lock is to not depend on any dependency as we should moving forward. This is a experiment for now as a single test obviously is not enough but I believe this is the right direction to on. 
Execute benchmarks have a performance improvement around [1.78%, 7.5%] which seems like it went okay as it was expected from removing `pthread_mutex` calls.
```
Prepare `SELECT 1`/Limbo/SELECT 1
time:   [575.63 ns 577.33 ns 580.07 ns]
change: [-1.3304% -0.8881% -0.4675%] (p = 0.00 < 0.05)
Change within noise threshold.
Prepare `SELECT * FROM users LIMIT 1`/Limbo/SELECT * FROM users LIMIT 1
time:   [1.2070 µs 1.2114 µs 1.2166 µs]
change: [-0.8670% -0.4084% -0.0252%] (p = 0.06 > 0.05)
No change in performance detected.
Prepare `SELECT first_name, count(1) FROM …
```
> Implement FastLock for DatabaseHeader

- core/benches/benchmark.rs
Easier to run now with:
```
cargo bench -- "execute_select_rows/50"
```
> fragment bench functions

- .gitignore
For example the commmand `cargo run --package limbo_cli --bin limbo database.db` will generate a `database.db` file, and it's unlikely we'll ever need to track such files **if they are placed inside the root of the project**.
> chore: gitignore files with an extension *.db

- core/storage/database.rs
- core/storage/pager.rs
- core/storage/sqlite3_ondisk.rs
- core/storage/wal.rs
Tried to keep this as small and focused as possible, just a few that I ran into while debugging the page cache
> Impl Copy on some types in the pager to prevent explicit clones

- core/vdbe/mod.rs
- testing/all.test
- testing/drop_table.test
The `p1` register points to the root page, not to a cursor.
Fixes #1136
> core: Fix Destroy opcode root page handling

- bindings/python/example.py
- bindings/python/src/lib.rs
- bindings/python/tests/test_database.py
Yet another PR to close #494.
While testing the code provided in the issue I noticed that it wasn't closing the connection as it should, leading to lifetime issues like: `Connection is unsendable, but is being dropped on another thread`. The following code works fine:
```python
import limbo
def main():
con = limbo.connect("test.db")
cur = con.cursor()
try:
cur.execute("""
CREATE TABLE IF NOT EXISTS users (
id INTEGER PRIMARY KEY AUTOINCREMENT,
username TEXT NOT NULL,
email TEXT NOT NULL,
role TEXT NOT NULL,
created_at DATETIME NOT NULL DEFAULT (datetime('now'))
)
""")
sample_users = [
("alice", "alice@example.com", "admin"),
("bob", "bob@example.com", "user"),
("charlie", "charlie@example.com", "moderator"),
("diana", "diana@example.com", "user")
]
for username, email, role in …
```
> Improve Python bindings

- core/benches/json_benchmark.rs
- core/json/json_cache.rs
- core/json/json_operations.rs
- core/json/jsonb.rs
- core/json/mod.rs
- core/vdbe/builder.rs
- core/vdbe/mod.rs
SQLite uses a similar approach for operations where up to 4 JSON objects are accessed multiple times in a single query.
`SELECT json_extact(a, 'some_path'), json_remove(a, 'some_path') json_set(a, 'some_path', 'some_value') from t;`
> JSON cache

- core/translate/expr.rs
- testing/math.test
Fixes #1154.
Unary `+` is a noop in Sqlite: <https://sqlite.org/lang_expr.html#operators_and_parse_affecting_attributes>.
> Unary `+` is a noop

- core/vdbe/insn.rs
- testing/select.test
Fixes #1156 
- Changed `compute_shl` implementation to handle negation with overflow.
- Added TCL tests.
> Fix `compute_shl` negate with overflow

- core/storage/btree.rs
- core/storage/sqlite3_ondisk.rs
- core/types.rs
- core/vdbe/mod.rs
Currently we have a Record, which is a dumb vector of cloned values. This is incredibly bad for performance as we do not want to clone objects unless needed. Therefore, let's start by introducing this type so that any record that has already been serialized will be returned from btree in the format of a simple payload with reference to payload.
> Introduce immutable record

- core/mvcc/cursor.rs
- core/mvcc/database/mod.rs
- core/mvcc/database/tests.rs
Fix memory hogging in MVCC scan cursor #1104
The current scan cursor loads all rowids at once, which blows up memory on big tables.
Added BucketScanCursor that loads rowids in configurable batches - better memory usage while keeping decent performance. It's a drop-in replacement with the same interface.
Also included LazyScanCursor as an alternative that fetches one rowid at a time, though it's less efficient due to log(n) skipmap lookups for each row.
BucketScanCursor is the recommended approach for most use cases. WDYT?
> Reduce MVCC cursor memory consumption

- bindings/go/rs_src/types.rs
- bindings/java/rs_src/limbo_statement.rs
- bindings/javascript/src/lib.rs
- bindings/python/src/lib.rs
- bindings/rust/src/lib.rs
- bindings/wasm/lib.rs
- cli/app.rs
- core/functions/datetime.rs
- core/functions/printf.rs
- core/json/json_operations.rs
- core/json/mod.rs
- core/types.rs
- core/vdbe/insn.rs
- core/vdbe/mod.rs
- core/vector/mod.rs
- core/vector/vector_types.rs
- simulator/generation/plan.rs
- sqlite3/src/lib.rs
- tests/integration/fuzz/mod.rs
OwnedValue has become a powerhouse of madness, mainly because I decided
to do it like that when I first introduced AggContext. I decided it was
enough and I introduced a `Register` struct that contains `OwnedValue`,
`Record` and `Aggregation`, this way we don't use `OwnedValue` for
everything make everyone's life harder.
This is the next step towards making ImmutableRecords the default
because I want to remove unnecessary allocations. Right now we clone
OwnedValues when we generate a record more than needed.
> Introduce Register struct 

- Cargo.lock
- NOTICE.md
- cli/app.rs
- core/Cargo.toml
- core/functions/datetime.rs
- core/functions/printf.rs
- core/types.rs
- core/vdbe/insn.rs
- core/vdbe/mod.rs
- licenses/core/libm-mit-license.md
- testing/math.test
Closes #1206
Closes #447
Closes #1117
Issues:
1. Rust floating point math fucntions are non deterministic.
2. SQLite have complex floating point display rules.
I changed rust functions to libm for math ops and implemented Display trait for OwnedValue:Float. A lot of float formatting SQLite probably inherits from C have to be handcrafted.
> Fixes probably all floating point math issues and floating point display issues.

- core/vdbe/mod.rs
We never hit bugs due to these because of 1. not having multi column indexes in our TCL test databases, 2. otherwise not really having Rust tests involving indexes, and 3. `IdxLt` and `IdxLe` not actually being used anywhere yet
Also as @PThorpe92 pointed out there are some nuances to the comparison logic we may need to eventually implement regarding comparisons with uneven number of keys: https://github.com/sqlite/sqlite/blob/master/src/vdbeaux.c#L4719
> Fix IdxCmp insn comparisons

- core/storage/btree.rs
`seek` can return I/O but we never looped until it finished. I also added test to ensure we don't repeat keys for now.
> Fuzz test btree fix seeking.

- core/storage/btree.rs
Newly added divider cells to parent of an interior page must point to
the page in question. Moreover rightmost pointer of the page will point
to previous divider cell pointer.
> Fix propagation of divider cell balancing interior page 

- core/storage/btree.rs
- core/translate/emitter.rs
- core/translate/main_loop.rs
- core/translate/optimizer.rs
- core/translate/plan.rs
- core/translate/update.rs
- core/vdbe/mod.rs
- testing/cli_tests/cli_test_cases.py
- testing/update.test
closes #1186, or at least works towards it by implementing an actual Plan for update queries instead of translating everything inline. This allows for actually using index's, rewriting const expressions, pushing predicates instead of hardcoding a full scan in the translation.
1.  `RETURNING` clause/result columns
2.  `OFFSET` clauses
3. on conflict
By supporting `LIMIT` directly in update queries, we'll have to put the tests outside of the compatibility tests, maybe in the CLI tests.
> Create plan for Update queries

- core/translate/expr.rs
Alongside with #1227, this PR closes #1226 
Before:
After:
> Reuse register in binary expressions if they're equal 

- core/lib.rs
- core/storage/pager.rs
- core/storage/sqlite3_ondisk.rs
- core/storage/wal.rs
Fixes #780
WalShared state can be shared without having to wrap everything with a lock, and instead use atomics on some places and rwlock on others -- for now.
From:
----
```
Execute `SELECT 1`/limbo_execute_select_1
time:   [34.125 ns 34.218 ns 34.324 ns]
Execute `SELECT 1`/sqlite_execute_select_1
time:   [28.124 ns 28.254 ns 28.385 ns]
```
To:
----
```bash
Execute `SELECT 1`/limbo_execute_select_1
time:   [31.919 ns 32.113 ns 32.327 ns]
Execute `SELECT 1`/sqlite_execute_select_1
time:   [29.662 ns 29.900 ns 30.139 ns]
```
And with `begin_read_tx` inlined:
----
```bash
Execute `SELECT 1`/limbo_execute_select_1
time:   [30.543 ns 30.585 ns 30.632 ns]
```
> Remove RWLock from Shared wal state

- core/storage/btree.rs
- core/storage/page_cache.rs
- core/storage/pager.rs
We assumed page was loaded because before inserting we would move there. `NewRowId` unfortunately moves cursor to the rightmost page causing eviction of root page -- this arose the issue with `insert_into_page` not loading the page we were supposed to have loaded so I added `return_if_locked_maybe_load` which is a utility macro to check if the page is locked and if not, load it if needed.
> Request load page on `insert_into_page`

- core/translate/schema.rs
- core/util.rs
- core/vdbe/execute.rs
- testing/cli_tests/extensions.py
- testing/cli_tests/test_limbo_cli.py
closes #1240 
some idiot (read: me) had the init label of `CREATE VIRTUAL TABLE` translation completely in the wrong place :thinking:
> Fix virtual table translation issues

- core/translate/insert.rs
- core/vdbe/insn.rs
- testing/all.test
- testing/default_value.test
While working on #494 I noticed that default values defined in schemas weren't being applied.
Before:
Now:
> Add support for default values in INSERT statements

- bindings/rust/src/lib.rs
Derive `Clone` for the Rust binding's `Database` and implement `Debug`.
Closes #1238
> Implement Clone and Debug for Rust binding's Database

- core/translate/insert.rs
- testing/cli_tests/cli_test_cases.py
`INSERT INTO products DEFAULT VALUES` previously wasn't supported. Quick and easy
> Support insert default values syntax

- COMPAT.md
- core/schema.rs
- core/storage/btree.rs
- core/translate/index.rs
- core/translate/insert.rs
- core/translate/main_loop.rs
- core/translate/mod.rs
- core/translate/schema.rs
- core/vdbe/builder.rs
- core/vdbe/execute.rs
- core/vdbe/explain.rs
- core/vdbe/insn.rs
- core/vdbe/mod.rs
- testing/cli_tests/extensions.py
Closes #1193  
```console
│limbo> explain create index idxp on products(price);                                                                                                                        
│addr  opcode             p1    p2    p3    p4             p5  comment
│----  -----------------  ----  ----  ----  -------------  --  -------
│0     Init               0     39    0                    0   Start at 39
│1     CreateBtree        0     1     2                    0   r[1]=root iDb=0 flags=2
│2     OpenWriteAsync     0     1     0                    0
│3     OpenWriteAwait     0     0     0                    0
│4     NewRowId           0     2     0                    0
│5     String8            0     3     0     index          0   r[3]='index'
│6     String8            0     4 …
```
> Support Create Index

- core/translate/emitter.rs
- core/translate/group_by.rs
- core/translate/main_loop.rs
- core/translate/optimizer.rs
- core/translate/result_row.rs
- core/translate/subquery.rs
- testing/agg-functions.test
Closes #954
Before:
After:
SQLite:
> Aggregation without group by produces incorrect results for scalars

- COMPAT.md
- core/function.rs
- core/translate/expr.rs
- core/vdbe/execute.rs
- testing/scalar-functions.test
This patch implements the "likely(x)" scalar function, which simply returns the original value provided to it as it's result.
> Added 'Likely' Scalar Function

- core/types.rs
- testing/select.test
Numeric values outside the range of what f64 can represent are formatted to strings as "Inf" or "-Inf" in sqlite, but they are "inf" and "-inf" in limbo.
```
sqlite> SELECT 1.7976931348623157E+309;
Inf
```
```
limbo> SELECT 1.7976931348623157E+309;
┌─────────────────────────┐
│ 1.7976931348623157E+309 │
├─────────────────────────┤
│                     inf │
└─────────────────────────┘
```
closes #1248
> Format infinite float as "Inf"/"-Inf"

- core/ext/dynamic.rs
- core/lib.rs
- core/translate/emitter.rs
- core/util.rs
- core/vdbe/execute.rs
- core/vdbe/mod.rs
- testing/cli_tests/extensions.py
closes #1239 
warns the user if a .db file is opened that contains a schema entry of a vtab created with a module that is no longer loaded.
If the module is loaded for that connection, the user can properly query the table.
> VTabs: Proper handling of re-opened db files without the relevant extensions loaded

- .gitignore
- Cargo.lock
- cli/Cargo.toml
- cli/app.rs
- cli/input.rs
- cli/main.rs
- docs/testing.md
- scripts/limbo-sqlite3
- testing/cli_tests/test_limbo_cli.py
Sometimes you want to run the tests _and_ look at logs, and previously that wasn't possible because all the tests relied on stdout/stderr.
Setup `tracing-appender` to automatically log to a designated `testing/test.log` when `RUST_LOG` is set.
This PR also starts a `testing.md` file describing testing in limbo. My hope is that people who know stuff about DST and the fuzzing setup will fill in the TODOs :)
> Setup tracing to allow output during test runs

- Makefile
- testing/cli_tests/memory.py
My PR #972 always keeps breaking when there are changes in how Btree works lol. I'm extracting the memory tests I created there here, so we can track problems earlier.
> Memory tests to track large blob insertions

- core/io/mod.rs
- core/lib.rs
Fix the syscall VFS on Linux not to use `PlatformIO`, which is just an alias for `io_uring`.
> core: Fix syscall VFS on Linux

- stress/main.rs
- stress/opts.rs
run with: `RUST_BACKTRACE=1 cargo run -p limbo_stress -- -t 1 -l`
and then if you want to repeat same plan: `RUST_BACKTRACE=1 cargo run -p limbo_stress -- -t 1 -L`
> Add support to load log file with stress test

- core/storage/btree.rs
We cannot simply paste a new payload into a cell with a payload with less size because we need to track fragmentation + free blocks. Let's keep it simple by only overwriting if size is the same.
Btw I feel like update is not re-entrant.
> Fix overwrite cell with size less than cell size

- COMPAT.md
- core/function.rs
- core/functions/datetime.rs
- core/translate/expr.rs
- core/vdbe/execute.rs
- testing/scalar-functions-datetime.test
This PR implemets the `timediff(A,B)` function, which returns a string that describes the amount of time that must be added to B in order to reach time A. I used sqlite's timediff function for format reference: https://github.com/sqlite/sqlite/blob/master/src/date.c#L1694
Op-codes seems to be in order:
```
limbo> explain SELECT timediff('12:30:45.123', '12:30:44.987');
0     Init               0     6     0                    0   Start at 6
1     String8            0     2     0     12:30:45.123   0   r[2]='12:30:45.123'
2     String8            0     3     0     12:30:44.987   0   r[3]='12:30:44.987'
3     Function           0     2     1 …
```
> feat: Add timediff data and time function

- COMPAT.md
- core/function.rs
- core/translate/expr.rs
- core/vdbe/execute.rs
- testing/scalar-functions.test
The `likelihood(X,Y)` function returns argument X unchanged. The value Y in likelihood(X,Y) must be a floating point constant between 0.0 and 1.0, inclusive.
```
sqlite> explain SELECT likelihood(42, 0.0);
addr  opcode         p1    p2    p3    p4             p5  comment
0     Init           0     6     0                    0   Start at 6
1     Once           0     3     0                    0
2     Integer        42    2     0                    0   r[2]=42
3     Copy           2     1     0                    0   r[1]=r[2]
4     ResultRow      1     1     0                    0   output=r[1]
5     Halt           0     0     0                    0
6     Goto           0     1     0                    0
```
```
limbo> …
```
> Added 'likelihood' scalar function

- .gitignore
- Cargo.lock
- docs/testing.md
- simulator/Cargo.toml
- simulator/README.md
- simulator/generation/plan.rs
- simulator/generation/property.rs
- simulator/main.rs
- simulator/runner/bugbase.rs
- simulator/runner/cli.rs
- simulator/runner/env.rs
- simulator/runner/execution.rs
- simulator/runner/mod.rs
Previously, simulator used `tempfile` for storing the resulting interaction plans, database file, seeds, and all relevant information. This posed the problem that this information became ephemeral, and we were not able to properly use the results of previous runs for optimizing future runs. This PR removes the CLI option `output_dir`, bases the storage infrastructure on top of `BugBase` interface.
> simulator: Add Bug Database(BugBase)

- core/translate/emitter.rs
- core/translate/main_loop.rs
- core/translate/optimizer.rs
- core/translate/plan.rs
- core/translate/select.rs
- core/vdbe/explain.rs
- tests/integration/fuzz/mod.rs
I would say mostly you should just focus on the content of `optimizer.rs` and `plan.rs` because the rest is just small type changes, or in the case of `main_loop.rs`, a bunch of logic was just moved out of there and rewritten.
This PR adds support for utilizing multi-column indexes properly, i.e. using as many columns in the seek key as possible. Previously, we only used max one column per index. I've modified the existing compound index seek fuzz test to use this functionality.
This PR moves a lot of index seek related logic out of `main_loop.rs` into `optimizer.rs` and `plan.rs` and introduces a bunch of helper structures to model finding and using an index to perform a seek + scan.
Here are some examples of multi-column seeks:
```sql
sqlite> CREATE TABLE t(a,b,c,d,e);
sqlite> CREATE …
```
> Multi column indexes + index seek refactor

- simulator/main.rs
- simulator/runner/bugbase.rs
- simulator/runner/cli.rs
- simulator/runner/env.rs
Previously, the simulator only generated and ran a single run with the given configurations, and anyone was free to implement retrial or looping on top, which is still possible.
I still wanted to start adding some higher level commands on top, especially now that we have access to bug base, so this PR adds the following options;
- loop: run the simulator in a loop `n` times, with the option to short circuit if any run fails.
- list: list all the bugs in the bug base.
- test: run the simulator against a specific bug by providing a `filter`, this is useful when debugging a certain issue so you can first run a bunch of tests in a `loop`, and rerun them using `test` when you think you have a fix.
> simulator: provide high level commands on top of a single runner

- Cargo.lock
- Cargo.toml
- cli/app.rs
- vendored/sqlite3-parser/sqlparser_bench/Cargo.toml
- vendored/sqlite3-parser/src/lexer/scan.rs
- vendored/sqlite3-parser/src/lexer/sql/error.rs
- vendored/sqlite3-parser/src/lexer/sql/mod.rs
On my journey of improving DX, I thought it would be a good idea to improve a bit the Diagnostics that `miette` provides. This is the first step to provide better errors in the CLI. I want to do better errors for tables and columns afterwards by giving suggestions of possible names to choose from, like we have in the Rust compiler or Clippy.
- `Scanner` now passes its offset to Errors allowing `miette` to correctly point to error in the sql statement.
- Some personalized help messages for `MalformedHexInteger`
- Help message for `BadNumber` printing the offending `String`
Examples: 
| Before | After |
|--------|--------|
| <img width="458" alt="image" src="https://github.com/user-attachments/assets/a9d62add-66fc-42c0-b5e9-8b1ef3c436d0" /> | <img width="263" alt="image" …
> Better diagnostics

- core/translate/main_loop.rs
- core/translate/optimizer.rs
- testing/where.test
Fixes bug where e.g. `SELECT age FROM users WHERE age > NULL` would return all rows, since NULL is lower than anything else in index keys, but in comparison expressions it returns NULL.
Solution: check whether index seek key members can be null, and if they are null, do not seek and instead exit the loop.
Example bytecode on a table with an index on (a,b,c):
```sql
sqlite> explain select * from t where a = 5 and b = 6 and c > NULL;
addr  opcode         p1    p2    p3    p4             p5  comment      
0     Init           0     18    0                    0   Start at 18
1     OpenRead       0     2     0     5              0   root=2 iDb=0; t
2     OpenRead       1     3     0     k(4,,,,)       0   root=3 iDb=0; abc …
```
> Check that index seek key members are not null

- core/error.rs
- core/vdbe/execute.rs
- core/vdbe/mod.rs
> Return null when parameter is unbound

- COMPAT.md
- core/storage/btree.rs
- core/translate/emitter.rs
- core/translate/index.rs
- core/translate/insert.rs
- core/translate/main_loop.rs
- core/translate/schema.rs
- core/vdbe/builder.rs
- core/vdbe/execute.rs
- core/vdbe/explain.rs
- core/vdbe/insn.rs
- core/vdbe/mod.rs
Seems to me like these are not needed -- we wait for completions in `io.run_once()` as soon as anything returns a `StepResult::IO`, and practically all of the `*Await` opcodes either explicitly do nothing or call `cursor.wait_for_completion()` which does nothing
> refactor: fold Async/Await insns into a single instruction

- core/translate/optimizer.rs
- core/translate/planner.rs
- testing/where.test
- tests/integration/fuzz/mod.rs
Fixes #1298
- Fixes Limbo trying to use an index using a WHERE clause constraint that refers to the same table on both sides, e.g. `WHERE t.x = t.x`
- Fixes not using indexes when the relevant expression is paren wrapped, e.g.
- `SELECT * FROM t WHERE (indexcol) > 5`
- `SELECT * FROM t WHERE (indexcol > 5)`
- Changes existing table logical expr fuzz test to have primary keys (which helped me find both issues above)
> Fix two issues with indexes

- fuzz/fuzz_targets/expression.rs
Currently, to run the fuzz test you need to remove an assert statement.
EDIT: @diegoreis42 pointed it out to me that the method had just changed actually. Made the change to use `row.len()` instead
```
cargo +nightly fuzz run --target=aarch64-apple-darwin expression
Compiling limbo_core v0.0.19-pre.4 (/Users/pedro/Projects/limbo/core)
Compiling limbo-fuzz v0.0.0 (/Users/pedro/Projects/limbo/fuzz)
error[E0599]: `&limbo_core::vdbe::Row` is not an iterator
--> fuzz_targets/expression.rs:198:36
|
198 |                     assert_eq!(row.count(), 1, "expr: {:?}", expr);
|                                    ^^^^^
|                                    |
|                                    `&limbo_core::vdbe::Row` is not an iterator
|                                    private field, not a method …
```
> Fix: comment out incorrect assert in fuzz

- COMPAT.md
- core/schema.rs
- core/vdbe/execute.rs
- core/vdbe/explain.rs
- core/vdbe/insn.rs
I'm working on an optimization of `WHERE .. IN (..)` statements that requires these bytecodes.
```sh
sqlite> explain select * from users where first_name in ('alice', 'bob', 'charlie');
addr  opcode         p1    p2    p3    p4             p5  comment      
0     Init           0     35    0                    0   Start at 35
1     OpenRead       0     2     0     10             0   root=2 iDb=0; users
2     Rewind         0     34    0                    0   
3       Noop           0     0     0                    0   begin IN expr
4       BeginSubrtn    0     1     0                    0   r[1]=NULL <---- Here
5         Once           0     17    0                    0   
6         OpenEphemeral  1     1     0 …
```
> Add `BeginSubrtn`, `NotFound` and `Affinity` bytecodes

- core/schema.rs
- core/storage/btree.rs
- core/translate/main_loop.rs
- core/translate/optimizer.rs
- core/translate/plan.rs
- core/types.rs
- core/vdbe/execute.rs
- tests/integration/fuzz/mod.rs
- Adds support for descending indexes
- Augments existing compound key index seek fuzz test to test for various combinations of ascending and descending indexed columns. To illustrate, the test runs 10000 queries like this on 8 different tables with all different asc/desc permutations of a three-column primary key index:
```sql
query: SELECT * FROM t WHERE x = 2826  LIMIT 5
query: SELECT * FROM t WHERE x = 671 AND y >= 2447 ORDER BY x ASC, y DESC LIMIT 5
query: SELECT * FROM t WHERE x = 2412 AND y = 589 AND z >= 894 ORDER BY x DESC LIMIT 5
query: SELECT * FROM t WHERE x = 1217 AND y = 1437 AND z <= 265 ORDER BY x ASC, y ASC, z DESC LIMIT 5
query: SELECT * FROM t WHERE x < 138 ORDER BY x DESC LIMIT 5
query: SELECT * FROM t WHERE x = 1312 AND y = 2757 AND z > 39 ORDER BY x DESC, y ASC, z …
```
> Feat: add support for descending indexes

- core/lib.rs
- core/translate/emitter.rs
- core/translate/main_loop.rs
- core/translate/plan.rs
- core/translate/subquery.rs
- core/util.rs
- core/vdbe/execute.rs
- core/vdbe/insn.rs
- extensions/completion/src/lib.rs
- extensions/core/src/lib.rs
- extensions/core/src/vtabs.rs
- extensions/series/src/lib.rs
- extensions/tests/src/lib.rs
- macros/src/lib.rs
- testing/cli_tests/extensions.py
closes #1185 
The underlying schema of virtual tables is hidden from the query planner, and it currently has no way of optimizing select queries with vtab table refs by using indexes or removing non-constant predicates. All vtabs are currently rewound completely each time and any conditional filtering is done in the vdbe layer instead of in the `VFilter`.
Add xBestIndex to the vtab module API to let extensions return some `IndexInfo` that will allow the query planner to make better optimizations and possibly omit conditionals
table `t`: vtab: (key, value)
table `t2`: table: (a,b)
Properly pushes predicate to VFilter, which receives the idx_str `key_eq` arg, telling it that there is a useable where clause on the key "index"
Constraint is not sent because it is marked as unusable
Pushed …
> Support xBestIndex in vtab API

- core/translate/emitter.rs
- core/translate/expr.rs
- core/translate/main_loop.rs
- core/translate/optimizer.rs
- core/translate/plan.rs
- tests/integration/fuzz/mod.rs
Closes #364 
Covering indexes mean being able to read all the necessary data from an index instead of using the underlying table at all. This PR adds that functionality.
This PR can be reviewed commit-by-commit as the first commits are enablers for the actual covering index usage functionality
Example of a scan where covering index can be used:
```sql
limbo> .schema
CREATE TABLE t(a,b,c,d,e);
CREATE INDEX abc ON t (a,b,c);
limbo> explain select b+1,concat(a, c) from t;
0     Init               0     12    0                    0   Start at 12
1     OpenRead           0     3     0                    0   table=abc, root=3
2     Rewind             0 …
```
> Feat: Covering indexes

- core/storage/btree.rs
- core/translate/main_loop.rs
- testing/join.test
In left joins, even if the join condition is not matched, the system must emit a row for every row of the outer table:
```
-- this must return t1.count() rows, with NULLs for all columns of t2
SELECT * FROM t1 LEFT JOIN t2 ON FALSE;
```
To achieve this, we set a "null flag" on the right table cursor which tells our VDBE to emit NULLs for any columns of that cursor until the flag is cleared.
Our logic for clearing the null flag was to do it in Next/Prev. However, this is problematic for a few reasons:
- If the inner table of the left join is using SeekRowid, then Next/Prev is never called on its cursor, so the null flag doesn't get cleared.
- If the inner table of the left join is using a non-covering index seek, i.e. it iterates its rows using an index, but seeks to the main table to …
> Fix bug: left join null flag not being cleared

- Cargo.lock
- core/Cargo.toml
- testing/scalar-functions-datetime.test
The previous version of `julian_day-converter` had precision issues, potentially causing loss of precision when converting between `julianday` and `datetime`
> Bump julian_day_converter to 0.4.5

- bindings/java/rs_src/limbo_statement.rs
- bindings/rust/src/lib.rs
- core/lib.rs
- core/translate/plan.rs
- tests/integration/common.rs
This PR adds the statement.columns() function, inspired from Rusqlite: https://docs.rs/rusqlite/latest/rusqlite/struct.Statement.html#method.columns
Note that the rusqlite documentation says
> If associated DB schema can be altered concurrently, you should make sure that current statement has already been stepped once before calling this method.
Do we have this requirement as well?
The first commit is just the rust binding. The second commit implements the column name for the rowid column.
> bindings/rust: Add Statement.columns() support

- COMPAT.md
- core/translate/expr.rs
I was reading through the `translate_expr` function and `COMPAT.md` to see what was not implemented yet. I saw that `Expr::Between` was marked as a `todo!` so I set trying to implement it only to find that it was being rewritten in the optimizer haha. This PR just adjusts the docs and add an `unreachable` in the appropriate locations.
> Fix incorrect between expression documentation

- core/schema.rs
- core/translate/index.rs
- core/translate/main_loop.rs
- core/translate/optimizer.rs
- core/translate/plan.rs
- core/vdbe/builder.rs
- core/vdbe/execute.rs
Closes #747 
- Creates an automatic ephemeral (in-memory) index on the right-side table of a join if otherwise a nested table scan would be selected.
- This behavior is not hardcoded; instead this PR introduces a (quite dumb) cost estimator that naturally deincentivizes building ephemeral indexes where they don't make sense (e.g. the outermost table). I will probably build this estimator to be smarter in the future when working on join reordering optimizations
Example query with no persistent indexes to choose from. Without ephemeral index it's a nested scan:
```sql
limbo> explain select * from t1 natural join t2;
0     Init               0     13 …
```
> Create an automatic ephemeral index when a nested table scan would otherwise be selected

- Makefile
- PERF.md
- testing/cli_tests/vfs_bench.py
- testing/pyproject.toml
This PR adds a python script that uses the `TestLimboShell` setup to run some semi naive benchmarks/comparisons against `io_uring` and `syscall` IO back-ends.
```sh
make bench-vfs SQL="insert into products (name, price) values ('testing', randomblob(1024*4));" N=50
```
The script will execute the given `SQL` `N` times with each back-end, get the average/mean and display them. 
:grimacing:
> Python script to compare vfs performance

- core/translate/main_loop.rs
- core/translate/optimizer.rs
This avoids redundant `IsNull` instructions during index seeks if the seek key columns are primary keys of other tables, which they often are.
> expr.is_nonnull(): return true if col.primary_key || col.notnull

- core/storage/btree.rs
- tests/integration/fuzz/mod.rs
Followup to #1357 which did the same treatment for table btrees only. After this PR, all of our seeks use binary search for both interior and leaf pages.
using TPC-H 1GB db for this query:
```sql
limbo> explain select count(1) from lineitem join partsupp on l_partkey = ps_partkey and l_suppkey = ps_suppkey;
0     Init               0     18    0                    0   Start at 18
1     OpenRead           0     10    0                    0   table=lineitem, root=10
2     OpenRead           1     7     0                    0   table=sqlite_autoindex_partsupp_1, root=7
3     Rewind             0     14    0                    0   Rewind lineitem
4 …
```
> perf/btree: use binary search for Index seek operations

- cli/app.rs
> Bugfix: Explain command should display syntax errors in CLI

- Cargo.toml
- Dockerfile.antithesis
- antithesis-tests/bank-test/anytime_validate.py
- antithesis-tests/bank-test/eventually_validate.py
- antithesis-tests/bank-test/finally_validate.py
- antithesis-tests/bank-test/first_setup.py
- antithesis-tests/bank-test/parallel_driver_generate_transaction.py
- antithesis-tests/stress-composer/first_setup.py
- antithesis-tests/stress-composer/parallel_driver_delete.py
- antithesis-tests/stress-composer/parallel_driver_insert.py
- antithesis-tests/stress-composer/parallel_driver_update.py
- antithesis-tests/stress-composer/utils.py
- antithesis-tests/stress/singleton_driver_stress.sh
- stress/docker-compose.yaml
- stress/docker-entrypoint.sh
- stress/main.rs
This PR adds 2 autonomous test suites for use with Antithesis: `bank-test` and `stress-composer`. It also modifies the existing `limbo_stress` test to run as a singleton and modifies other Antithesis-related configuration files.
**bank-test**
- `first_setup.py`
- initializes a DB table with columns accounts and balance
- generates random balances for each account
- stores initial state of the table
- `parallel_driver_generate_transaction.py`
- selects 2 accounts from the table as sender and receiver
- generates a random value which is subtracted from sender and added to receiver
- `anytime/eventually/finally_validate.py`
- checks that sum of initial balances == sum of current balances
**stress-composer**
- Breaks `limbo_stress` into component parts
- `first_setup.py` 
- creates up to 10 …
> Add Antithesis Tests

- Makefile
- core/schema.rs
- core/translate/insert.rs
- core/vdbe/builder.rs
- core/vdbe/execute.rs
- core/vdbe/explain.rs
- core/vdbe/insn.rs
- testing/cli_tests/constraint.py
- testing/pyproject.toml
Closes #1384 . This PR implements Primary Key constraint for inserts. As can be seen in the issue, if you created an Index with a Primary Key constraint, it could trigger `Unique Constraint` error, but still insert the record. Sqlite uses the opcode `NoConflict` to check if the record already exists in the Btree. As we did not have this Opcode yet, I implemented it. It is very similar to `NotFound` with the difference that if any value in the Record is Null, it will immediately jump to the offset. The added benefit of implementing this, is that now we fully support Composite Primary Keys. Also, I think with the current implementation, it will be trivial to implement the Unique opcode for Insert. To support Updates, I need to understand more of the plan optimizer to and find where we are …
> Feature: Composite Primary key constraint

- core/storage/sqlite3_ondisk.rs
- core/storage/wal.rs
Related to #1379 
I guess there are more hard-coded values.
> Give name to hard-coded page_size values

- Cargo.lock
- cli/Cargo.toml
- cli/app.rs
- cli/main.rs
This is small nitpick, but it will be useful for #1258. If we are testing or just piping some sql through stdin, we can just not initialize `Rustyline` and save some execution time. 
On `Select 1` bench, I got a minor performance bump, but it starts to become less apparent on more complex queries.
> Optimization: only initialize `Rustyline` if we are in a tty

- core/storage/btree.rs
- core/translate/delete.rs
- core/translate/emitter.rs
- core/translate/plan.rs
- core/vdbe/execute.rs
- core/vdbe/explain.rs
- core/vdbe/insn.rs
- tests/integration/query_processing/test_write_path.rs
Previously `DELETE FROM ...` only emitted deletes for main table, but this is incorrect as we want to remove entries from index tables as well.
> Emit `IdxDelete` instruction and some fixes on seek after deletion

- core/storage/btree.rs
- core/types.rs
- core/vdbe/execute.rs
- core/vdbe/mod.rs
DeleteState had a bit too many unnecessary states so I removed them. Usually we care about having a different state when I/O is triggered requiring a state to be stored for later.
Furthermore, there was a bug with op_idx_delete where if balance is triggered, op_idx_delete wouldn't be re-entrant. So a state machine was added to prevent that from happening.
> Add state machine for op_idx_delete + DeleteState simplification

- cli/app.rs
Before this change, the history was only saved when the shell was interrupted (e.g., Ctrl-C pressed twice). With this change, history is now also saved when the `.exit` or `.quit` commands are used.
I attempted to add shell tests to cover the changes introduced in this PR, but emulating a terminal/TTY that would work cross-platform seems to require significant changes to `TestLimboShell` and `LimboShell`. For example, the `pty` module [currently doesn't support Windows](https://bugs.python.org/issue41663). I'm open to experimenting, but I’m unsure if complicating these classes is worthwhile, as saving history doesn't seem to be critical. 
Additionally, it might be worth considering a refactor of the CLI so that exit and cleanup operations are performed in one place.
> Save history on exit

- core/vdbe/execute.rs
- testing/pragma.test
This issue was introduced in #819. However, I believe the solution is suboptimal because `pragma page_count` can never return 1, which is inconsistent with SQLite.
To align with SQLite's behavior, we should allocate the first page when the first schema object is created, rather than immediately after creating database. And it's always preferable to return an accurate page count.
> Fix `page_count`  pragma

- core/lib.rs
- core/storage/btree.rs
- core/storage/pager.rs
- core/storage/sqlite3_ondisk.rs
- core/storage/wal.rs
- core/translate/pragma.rs
- core/vdbe/execute.rs
Since `page_size` in `DatabaseHeader` can be 1 representing 65526 bytes, it can't be used it directly.  Additionally, we should use `u32` instead of `u16` or `usize` in other contexts.
> Fix: allow page_size=65536

- core/storage/sqlite3_ondisk.rs
- core/translate/pragma.rs
- core/vdbe/execute.rs
- vendored/sqlite3-parser/src/parser/ast/mod.rs
This PR adds `PRAGMA schema_version` to get the value of the schema-version integer at offset 40 in the database header.
> Add PRAGMA schema_version

- core/translate/emitter.rs
- core/translate/plan.rs
- core/translate/update.rs
- core/vdbe/mod.rs
- tests/integration/query_processing/test_write_path.rs
Previously columns that were indexed were updated only in the BtreeTable, but not on Index table. This commit basically enables updates on indexes too if they are needed.
> update index on updated indexed columns

- core/translate/group_by.rs
- core/translate/index.rs
- core/translate/optimizer.rs
- core/translate/order_by.rs
- core/translate/plan.rs
- core/translate/select.rs
- core/translate/update.rs
- core/types.rs
- core/vdbe/execute.rs
- core/vdbe/explain.rs
- core/vdbe/insn.rs
- core/vdbe/sorter.rs
- testing/groupby.test
we had an incorrect optimization in `eliminate_orderby_like_groupby()` where it could remove e.g. the first term of the ORDER BY if it matched the first GROUP BY term and the result set was naturally ordered by that term. this is invalid. see e.g.:
```sql
main branch - BAD: removes the `ORDER BY id` term because the results are naturally ordered by id.
However, this results in sorting the entire thing by last name only!
limbo> select id, last_name, count(1) from users GROUP BY 1,2 order by id, last_name desc limit 3;
┌──────┬───────────┬───────────┐
│ id   │ last_name │ count (1) │
├──────┼───────────┼───────────┤
│ 6235 │ Zuniga    │         1 │
├──────┼───────────┼───────────┤
│ 8043 │ Zuniga    │         1 │
├──────┼───────────┼───────────┤
│  944 │ Zimmerman │         1 │ …
```
> Fix bug: we cant remove order by terms from the head of the list

- core/translate/pragma.rs
This PR removes an unnecessary read transaction.
Bytecode before this PR:
```
0     Init               0     5     0                    0   Start at 5
1     Transaction        0     0     0                    0   write=false
2     ReadCookie         0     1     6                    0
3     ResultRow          1     1     0                    0   output=r[1]
4     Halt               0     0     0                    0
5     Transaction        0     0     0                    0   write=false
6     Goto               0     1     0                    0
```
Bytecode after this PR:
```limbo> explain PRAGMA user_version;
addr  opcode             p1    p2    p3 …
```
> Eliminate a superfluous read transaction when doing PRAGMA user_version

- bindings/rust/src/lib.rs
`Statement` and `Rows` both have a private Arc, implementing clone avoids users needing to Arc<Mutex> it again.
> implement Clone for Arc<Mutex> types

- core/storage/btree.rs
closes  #1417
Man chasing this down was much much harder than it should have been.
We very frequently call `read_page` then push the return value onto the page stack, or otherwise use it without it necessarily needing to not be 'in progress' of IO, so it was tricky to figure out where this was happening and it had me thinking that it was something wrong with the changes to `io_uring` on my branch.
> Fix panic on async io due to reading locked page

- testing/drop_table.test
These test were commented out, maybe they were written before CREATE INDEX was added.
> Test that DROP TABLE also deletes the related indices

- Cargo.lock
- core/Cargo.toml
- core/error.rs
- core/io/generic.rs
- core/io/io_uring.rs
- core/io/mod.rs
- core/io/unix.rs
- core/io/vfs.rs
- core/io/windows.rs
- core/lib.rs
- core/vdbe/execute.rs
- tests/integration/common.rs
- tests/integration/fuzz/mod.rs
Closes #1413 . Basically, SQLite emits a check in a transaction to see if it is attempting to write. If the db is in read only mode, it throws an error, else the statement is executed. Mirroring how Rusqlite does it, I modified the `OpenFlags` to use bitflags to better configure how we open our VFS. This modification, will enable us to run tests against the same database in parallel.
> Read only mode

- bindings/go/types.go
The Limbo Go driver currently throws an "unsupported type" error when trying to bind `time.Time` values as query parameters. This requires applications to manually convert datetime values to strings before passing them to queries.
Added `time.Time` support to the `buildArgs` function in `types.go`. The implementation:
- Converts `time.Time` to RFC3339 format strings 
- Uses the existing `textVal` type for storage
- Maintains compatibility with Limbo's datetime handling
```go
// Previously failed with "unsupported type: time.Time"
now := time.Now()
db.Exec("INSERT INTO events (timestamp) VALUES (?)", now)
// Now works as expected
```
I tested with various datetime operations:
- Parameter binding with time.Time
- Round-trip storage and retrieval
- Compatibility with existing datetime …
> Add time.Time support to Go driver parameter binding

- core/lib.rs
- core/vdbe/mod.rs
- extensions/core/src/vtabs.rs
- macros/src/lib.rs
The following code reproduces the leak (memory usage increases over time):
```rust
#[tokio::main]
async fn main() {
let db = Builder::new_local(":memory:").build().await.unwrap();
let conn = db.connect().unwrap();
conn.execute("SELECT load_extension('./target/debug/liblimbo_series');", ())
.await
.unwrap();
loop {
conn.execute("SELECT * FROM generate_series(1,10,2);", ())
.await
.unwrap();
}
}
```
After switching to the system allocator, the leak becomes detectable with Valgrind:
```
32,000 bytes in 1,000 blocks are definitely lost in loss record 24 of 24
at 0x538580F: malloc (vg_replace_malloc.c:446)
by 0x62E15FA: alloc::alloc::alloc (alloc.rs:99)
by 0x62E172C: alloc::alloc::Global::alloc_impl (alloc.rs:192)
by 0x62E1530: allocate (alloc.rs:254)
by 0x62E1530: …
```
> Fix memory leak caused by unclosed virtual table cursors

- core/translate/aggregation.rs
- core/translate/emitter.rs
- core/translate/group_by.rs
- core/translate/main_loop.rs
- core/translate/order_by.rs
- core/translate/plan.rs
- core/translate/result_row.rs
- core/translate/select.rs
Right now we have the following problem with GROUP BY:
- it always allocates a sorter and sorts the input rows, even when the rows are already sorted in the right order
This PR is a refactor supporting a future PR that introduces a new version of the optimizer which does 1. join reordering and 2. sorting elimination based on plan cost. The PR splits GROUP BY into multiple subsections:
1. Initializing the sorter, if needed
2. Reading rows from the sorter, if needed
3. Doing the actual grouping (this is done regardless of whether sorting is needed)
4. Emitting rows during grouping in a subroutine (this is done regardless of whether sorting is needed)
For example, you might currently have the following pseudo-bytecode for GROUP BY:
```
SorterOpen (groupby_sorter)
OpenRead (users)
Rewind …
```
> GROUP BY: refactor logic to support cases where no sorting is needed

- bindings/go/types.go
PR #1442 added support for using time.Time as query parameters.
Scanning time.Time values from query results still fails:
`sql: Scan error on column index 4, name "mod_time": unsupported Scan, storing driver.Value type string into type *time.Time`
This change modifies the `toGoValue` function to detect RFC3339 formatted datetime strings and convert them back to time.Time objects when reading from the database. This provides complete roundtrip support for time.Time values.
Also added boolean support by converting Go bool values to integers (0 for false, 1 for true) when binding parameters, following SQLite's convention for representing boolean values.
> Add time.Time and bool data types support in Go adapter

- bindings/go/go.mod
- bindings/go/go.sum
Go 1.23.9 introduced a change with to it's linker that caused a `duplicate symbol` error with purego 1.82
this is the recommended fix per https://github.com/golang/go/issues/73617
> bindings/go: Upgrade ebitengine/purego to allow for use with go 1.23.9

- bindings/wasm/package.json
This pull request includes a small change to the `bindings/wasm/package.json` file. The change adds a `types` field pointing to the TypeScript declaration file for the package (`[bindings/wasm/package.jsonR15](diffhunk://#diff-1f41234b939ba148924b9bbfedd557853ebcd22351a9c300e568ce7af0291babR15)`).
> bindings/wasm: add types property for typescript setting

- core/translate/emitter.rs
- core/translate/insert.rs
- core/translate/schema.rs
- core/vdbe/execute.rs
- core/vdbe/explain.rs
- core/vdbe/insn.rs
After this commit EXPLAIN should show a comment for `Insert`.
```
limbo> explain insert into t (age, name, id) values (20, 'max', 1);
0     Init               0     9     0                    0   Start at 9
1     OpenWrite          0     2     0                    0
2     Integer            1     2     0                    0   r[2]=1
3     String8            0     3     0     max            0   r[3]='max'
4     Integer            20    4     0                    0   r[4]=20
5     NewRowId           0     1     0                    0
6     MakeRecord         2     3     5                    0   r[5]=mkrec(r[2..4])
7     Insert             0     5     1 …
```
> EXPLAIN should show a comment for the Insert opcode

- bindings/java/src/test/java/tech/turso/jdbc4/JDBC4StatementTest.java
Since limbo now supports UPDATE and DELETE, I'm planning to implement the rest of the features for integrating JDBC and limbo. 
Since limbo's [total_changes() function seems to work differently in compared to the sqlite's](https://discord.com/channels/1258658826257961020/1321869557459058778/1368830400985563176), let's remove the `@Disabled` annotation from `execute_update_should_return_number_of_updated_elements` test  after the issue is handled. 
https://github.com/tursodatabase/limbo/issues/615
> bindings/java: Remove disabled annotation for UPDATE and DELETE 

- core/schema.rs
- core/translate/index.rs
- core/translate/mod.rs
- core/vdbe/execute.rs
- core/vdbe/explain.rs
- core/vdbe/insn.rs
- testing/all.test
- testing/drop_index.test
This commit adds suport for DROP INDEX.
Bytecode produced by this commit differs from SQLITE's bytecode, main
reason we don't do autovacuum or repacking of pages like SQLITE does.
Closes #1280
> Add drop index

- core/benches/benchmark.rs
- core/storage/btree.rs
- core/translate/emitter.rs
- core/translate/plan.rs
- core/translate/select.rs
- core/vdbe/execute.rs
- core/vdbe/explain.rs
- core/vdbe/insn.rs
After reading #1123, I wanted to see what optimizations I could do. Sqlite optimizes `count` aggregation for the following case: `SELECT count() FROM <tbl>`. This is so widely used, that they made an optimization just for it in the form of the `COUNT` opcode. 
This PR thus implements this optimization by creating the `COUNT` opcode, and checking in the select emitter if we the query is a Simple Count Query. If it is, we just emit the Opcode instead of going through a Rewind loop, saving on execution time. 
The screenshots below show a huge decrease in execution time. 
- **Main**
- **Count Optimization**
> Count optimization

- core/translate/schema.rs
- testing/cli_tests/extensions.py
This PR fixes two bugs in `CREATE VIRTUAL TABLE` (see individual commits for details).
I added a test in `extensions.py` instead of the TCL test suite because it's currently more convenient - there’s no existing framework for loading extensions in TCL tests. However, I believe the test should eventually be moved to TCL, as it verifies behavior expected to be compatible with SQLite and is independent of any specific extension.
I've seen a PR proposing to migrate TCL tests to Rust, so please let me know if moving this test to TCL would still be valuable.
> CREATE VIRTUAL TABLE fixes

- docs/testing.md
- testing/cli_tests/extensions.py
- testing/cli_tests/test_limbo_cli.py
I wasted a few minutes staring at #1471 because I thought `limbo.debug_print()` just prints the sql, but it actually executes it too
> testing/py: rename debug_print() to run_debug()

- bindings/javascript/__test__/better-sqlite3.spec.mjs
- bindings/javascript/__test__/limbo.spec.mjs
- core/lib.rs
When `prepare()` is called with an empty string it should throw an error (e.g `ApiMisuse` in rusqlite). I'm testing only in JS but it should throw to any bind.
> Fix handling of empty strings in prepared statements

- core/translate/insert.rs
- testing/insert.test
Due to constant instruction reshuffling introduced in #1359, it is advisable not to do either of the following:
1. Use raw offsets as jump targets
2. Use `program.resolve_label(my_label, program.offset())` when it is uncertain what the next instruction will be
Instead, if you want a label to point to "whatever instruction follows the last one", you should use `program.preassign_label_to_next_insn(label)`, which will work correctly even with instruction rerdering
> Fix infinite loop when inserting multiple rows

- core/parameters.rs
- core/translate/insert.rs
- core/translate/mod.rs
- core/translate/optimizer.rs
- core/translate/plan.rs
- tests/integration/query_processing/test_read_path.rs
closes #1467 
Previously as explained in #1449, our parameter binding wasn't working properly because we would essentially 
assign the first index of whatever was translated first
```console
limbo> create table t (id integer primary key, name text, age integer);
limbo> explain select * from t where name = ? and id > ? and age between ? and ?;
0     Init               0     20    0                    0   Start at 20
1     OpenRead           0     2     0                    0   table=t, root=2
2     Variable           1     4     0                    0   r[4]=parameter(1) # always 1
3     IsNull             4     19    0                    0   if …
```
> Redesign parameter binding in query translator

- core/schema.rs
- core/translate/group_by.rs
- core/translate/optimizer/join.rs
- core/translate/order_by.rs
- core/translate/plan.rs
- core/translate/schema.rs
- core/util.rs
- core/vdbe/mod.rs
- testing/insert.test
- tests/integration/fuzz/mod.rs
- vendored/sqlite3-parser/src/parser/ast/mod.rs
Closes #1457 .
```sql
limbo> CREATE table t2 (x INTEGER PRIMARY KEY, y INTEGER UNIQUE);
limbo> SELECT * FROM sqlite_schema;
┌───────┬───────────────────────┬──────────┬──────────┬───────────────────────────────────────────────────────────┐
│ type  │ name                  │ tbl_name │ rootpage │ sql                                                       │
├───────┼───────────────────────┼──────────┼──────────┼───────────────────────────────────────────────────────────┤
│ table │ t2                    │ t2       │        2 │ CREATE TABLE t2 (x INTEGER PRIMARY KEY, y INTEGER UNIQUE) │
├───────┼───────────────────────┼──────────┼──────────┼───────────────────────────────────────────────────────────┤
│ index │ sqlite_autoindex_t2_1 │ t2       │        3 │ …
```
> Fix: unique contraint in auto index creation

- core/storage/btree.rs
- core/translate/emitter.rs
- core/translate/index.rs
- core/translate/insert.rs
- core/translate/main_loop.rs
- core/translate/order_by.rs
- core/translate/schema.rs
- core/vdbe/execute.rs
- core/vdbe/explain.rs
- core/vdbe/insn.rs
- flake.nix
- testing/cli_tests/constraint.py
This PR attempts to implement Primary Key and Indexes. It supports Update for Primary Keys as a RowId Alias, Composite Primary Keys, and Indexes. I tried to resemble as much as possible how SQLite emits the Opcodes.
~Additionally, to support this I had to fix a bug in the how we searched for the next records in the `Next` opcode, by introducing a Set of seen row id's. The problem was that, you need to delete the previous record and then insert the new record to update. When we did that in a `Rewind` loop, the current cell index in the cursor was always pointing to the incorrect place because we were searching for the next record without checking if we had seen it before. However, I am not sure how this affects the Btree.~
EDIT: After seeing how bad my fix was, I tried a different approach …
> Update Unique constraint for Primary Keys and Indexes

- .github/workflows/napi.yml
The setup-node fails sporadically with the following error:
```
Error: Could not get yarn cache folder path for /home/runner/work/limbo/limbo/bindings/javascript/docs
```
This seems to be a known issue that's not fixed despite the issue being closed: https://github.com/actions/setup-node/issues/887
Let's disable yarn caching for setup-node in an attempt to reduce CI failing randomly.
> github: Disable setup-node yarn cache

- CONTRIBUTING.md
This PR adds documentation on how to get tests to successfully pass on Linux (Ubuntu 24.04.2 LTS)
Without these additional steps `cargo test` complains about missing missing dev files and can't complete the compatibility tests.
> Document how to run `cargo test` on Ubuntu

- .github/workflows/rust_perf.yml
(Yes, I changed the name of the repo.)
Also switch back to 'cargo' for the parser, which is the original upstream code. I created 'criterion' because I didn't realize cargo bench spitz half of the text to stdout the other half to stderr.
> Update Nyrkiö change detection to newest version

- core/lib.rs
```
Execute `SELECT count() FROM users`/limbo_execute_select_count
time:   [12.867 µs 12.958 µs 13.104 µs]
change: [-91.233% -91.178% -91.120%] (p = 0.00 < 0.05)
```
also extracted it to a constant
> pager: bump default page cache size from 10 to 2000 pages

- core/schema.rs
- core/translate/schema.rs
Primary keys that are marked as unique constraint, do not need to have separate indexes, one is enough. In the case primary key is integer, therefore rowid alias, we still need an index to satisfy unique constraint.
> Fix autoindex of primary key marked as unique

- core/translate/schema.rs
- testing/all.test
- testing/create_table.test
- vendored/sqlite3-parser/src/parser/ast/mod.rs
Closes #1508 . There were two small issues to fix:
1. We were not checking in the IndexMap of columns, if the unique column name is declared in the composite declaration exists in the IndexMap. This solved the first this statement `create table t4(a, unique(b));`.
2. The second thing was that we forgot to add the column_name to the HashSet of columns. 
```rust
Some(PrimaryKeyDefinitionType::Simple { column, .. }) => {
let mut columns = HashSet::new();
columns.insert(std::mem::take(column));
// Have to also insert the current column_name we are iterating over in primary_key_column_results
columns.insert(column_name.clone()); <-- Fix here
primary_key_definition =
Some(PrimaryKeyDefinitionType::Composite { columns });
}
```
The rest of the modifications are just some small simplifications …
> Autoindex fix

- core/storage/btree.rs
This PR adds a new function `read_write_payload_with_offset` to support reading and writing payload data at specific offsets, handling both local content and overflow pages. This is a port of SQLite's `accessPayload` function in `btree.c` and will be essential for supporting incremental blob I/O in the coming PRs.
- Added a state machine called `PayloadOverflowWithOffset` to make the procedure reentrant. 
- Correctly processes both local payload data and payload stored in overflow pages
Testing:
- Reading and writing to a column with no overflow pages.
- Reading and writing at an offset with overflow pages (spanning 10 pages)
> (btree): Implement support for handling offset-based payload access with overflow support

- core/translate/optimizer/order.rs
1. `group_by_contains_all` was incorrect - it was not checking that all order by columns are in group by; it was instead checking that all group by columns are in order by, which is absolutely incorrect for the intended purpose.
2. remove ORDER BY clause if GROUP BY clause can sort the rows in the same way.
Test failures are not related
> optimizer: fix order by removal logic

- Cargo.lock
- core/Cargo.toml
- core/storage/btree.rs
Various things to improve speed of long fuzz test execution time:
* remove unnecessary debug_validate_cell calls
* Add SortedVec for keys in fuzz tests
* Validate btree's depth in fuzz test every 1K inserts to not overload test with validations. We add `VALIDATE_BTREE`  env variable to enable validation on every insert in case it is needed.
> Improve debug build validation speed

- core/storage/btree.rs
- core/translate/aggregation.rs
- core/translate/emitter.rs
- core/translate/group_by.rs
- core/translate/main_loop.rs
- core/translate/plan.rs
- core/translate/planner.rs
- core/translate/select.rs
- core/vdbe/builder.rs
- core/vdbe/execute.rs
- core/vdbe/explain.rs
- core/vdbe/insn.rs
- testing/agg-functions.test
- testing/groupby.test
Reviewable commit by commit. CI failures are not related.
Adds support for e.g. `select first_name, sum(distinct age), count(distinct age), avg(distinct age) from users group by 1`
Implementation details:
- Creates an ephemeral index per distinct aggregate, and jumps over the accumulation step if a duplicate is found
> Add support for DISTINCT aggregate functions

- core/translate/expr.rs
- core/translate/optimizer/lift_common_subexpressions.rs
- core/translate/optimizer/mod.rs
- perf/tpc-h/queries/19.sql
```sql
-- This PR does effectively this transformation:
select
sum(l_extendedprice* (1 - l_discount)) as revenue
from
lineitem,
part
where
(
p_partkey = l_partkey
and p_brand = 'Brand#22'
and p_container in ('SM CASE', 'SM BOX', 'SM PACK', 'SM PKG')
and l_quantity >= 8 and l_quantity <= 8 + 10
and p_size between 1 and 5
and l_shipmode in ('AIR', 'AIR REG')
and l_shipinstruct = 'DELIVER IN PERSON'
)
or
(
p_partkey = l_partkey
and p_brand = 'Brand#23'
and p_container in ('MED BAG', 'MED BOX', 'MED PKG', 'MED PACK')
and l_quantity >= 10 and l_quantity <= 10 + 10
and p_size between 1 and 10
and l_shipmode in ('AIR', 'AIR REG')
and l_shipinstruct = 'DELIVER IN PERSON'
)
or
(
p_partkey = l_partkey
and p_brand = 'Brand#12'
and p_container in ('LG CASE', 'LG BOX', 'LG PACK', 'LG PKG')
and …
```
> Optimization: lift common subexpressions from OR terms

- bindings/rust/examples/example.rs
- bindings/rust/src/lib.rs
- core/error.rs
- core/lib.rs
I tried to be the most similar to rusqlite as possible. The only thing that's bothering me is `Vec<Vec<Value>>` which I think can be improved but not so sure how, any inputs on this are welcomed.
> bindings/rust: Add pragma methods

- Cargo.lock
- Cargo.toml
- core/Cargo.toml
- core/ext/mod.rs
- core/lib.rs
- core/translate/emitter.rs
- core/translate/insert.rs
- core/translate/schema.rs
- core/util.rs
- core/vdbe/explain.rs
- core/vdbe/insn.rs
- extensions/completion/src/lib.rs
- extensions/core/README.md
- extensions/core/src/lib.rs
- extensions/core/src/vtabs.rs
- extensions/csv/Cargo.toml
- extensions/csv/src/lib.rs
- extensions/series/src/lib.rs
- extensions/tests/src/lib.rs
- macros/src/ext/vtab_derive.rs
- macros/src/lib.rs
- scripts/publish-crates.sh
- testing/cli_tests/extensions.py
This PR adds a port of [SQLite's CSV virtual table extension](https://www.sqlite.org/csv.html).
Planned follow-ups:
* Pass detailed error messages from `VTabModule::create`, not just `ResultCode`s.
* Address the TODO in `VTabModuleImpl::create_schema`.
> CSV virtual table extension

- cli/app.rs
I was trying to run the TPC-H 9.sql in the CLI, but it kept truncating my input due to a comment that is present in the query. After removing it, I can just copy and paste the query and it works. @PThorpe92 is it safe to remove this? Or is there a particular reason that was included that I am not aware of?
> remove detection of comments in the middle of query in cli

- core/lib.rs
- core/translate/delete.rs
- core/translate/emitter.rs
- core/translate/index.rs
- core/translate/insert.rs
- core/translate/mod.rs
- core/translate/pragma.rs
- core/translate/schema.rs
- core/translate/select.rs
- core/translate/transaction.rs
- core/translate/update.rs
- core/vdbe/builder.rs
This PR introduces some modifications to the Program Builder to allow us to use nested parsing. By focusing the emission of Init and the last Goto (prologue and epilogue), inside the ProgramBuilder, we can just not emit them if we are parsing/translating in a nested context. For this PR, I only migrated insert to use these functions as I need them to support Insert statements that use `SELECT FROM` syntax. Nested parsing overall enables code reuse for us and arguably is one of the only ways to parse deeply nested queries without a lot of code duplication. 
#1528
> Initial Support for Nested Translation

- vendored/sqlite3-parser/src/lexer/scan.rs
It spams the logs like no tomorrow, and is mostly useless.
> sqlite3-parser: Remove scanner trace-logging

- core/storage/btree.rs
- core/translate/schema.rs
- core/vdbe/execute.rs
In SQLite, when [AUTOVACUUM](https://www.sqlite.org/lang_vacuum.html) is enabled (in SQLite, the `SQLITE_OMIT_AUTOVACUUM` flag is used), and a table is dropped, if the root page of the table is destroyed and *it is not the last page*, then the last root page is transferred here to avoid empty gaps.
At this point, the old root page value is copied into a register and SQLite will copy over all rows using the old root page from the schema table into an ephemeral table. Later, it copies over the rows from the ephemeral table back into the schema table with the new root page number to "patch" the row.
This PR introduces the same semantics to Limbo. It doesn't perform the AUTOVACUUM functionality of moving the last root page into the empty page currently, so it no-ops that by returning 0. This …
> Drop Table OpCodes Use Ephemeral Table As Scratch Table

- bindings/wasm/lib.rs
In binding/wasm `generate_random_number`'s implementation depends on an external function `Math_random` which does not exist
A related error can be observed when viewing `limbo-opfs-test.html` without an existing database. (Note: it will execute successfully if the wal file already exists, so you may wish view the html in a private/incognito session to ensure an existing file from a previous run is not used)
This error occurs upon wal file creation as it uses `generate_random_number` for `salt_1` and `slat_2` in the header
https://github.com/tursodatabase/limbo/blob/main/core/storage/wal.rs#L764-L773) 
This PR uses the same implementation as other platforms
`core/io/unix.rs`
https://github.com/tursodatabase/limbo/blob/main/core/io/unix.rs#L259-L263
`core/io/windows.rs` …
> fix bindings/wasm wal file creation by implementing `generate_random_number`

- core/storage/btree.rs
- testing/orderby.test
- tests/integration/fuzz/mod.rs
Closes #1562 
Existing "fuzz test" (not really fuzz, but kinda) didn't catch this due to `LIMIT 3` clause
> btree: fix infinite looping in backwards iteration of btree table

- Cargo.lock
- bindings/rust/Cargo.toml
- bindings/rust/src/lib.rs
- core/fast_lock.rs
- core/storage/btree.rs
- core/storage/sqlite3_ondisk.rs
- core/storage/wal.rs
- tests/integration/common.rs
Fixes #1567 
Probably also fixes #1485 
Currently we are simply unable to read any WAL frames from disk once a fresh process w/ Limbo is opened, since we never try to read anything from disk unless we already have it in our in-memory frame cache.
This commit implements a crude way of reading entire WAL into memory as a single buffer and reconstructing the frame cache.
> Reconstruct WAL frame cache when WAL is opened

- core/lib.rs
- core/translate/delete.rs
- core/translate/expr.rs
- core/translate/group_by.rs
- core/translate/main_loop.rs
- core/translate/optimizer/access_method.rs
- core/translate/optimizer/constraints.rs
- core/translate/optimizer/join.rs
- core/translate/optimizer/lift_common_subexpressions.rs
- core/translate/optimizer/mod.rs
- core/translate/optimizer/order.rs
- core/translate/order_by.rs
- core/translate/plan.rs
- core/translate/planner.rs
- core/translate/select.rs
- core/translate/update.rs
- core/util.rs
- core/vdbe/builder.rs
- vendored/sqlite3-parser/src/parser/ast/mod.rs
Closes #1557 
Currently our "table id"/"table no"/"table idx" references always use the direct index of the `TableReference` in the plan, e.g. in `SelectPlan::table_references`. For example:
```rust
Expr::Column { table: 0, column: 3, .. }
```
refers to the 0'th table in the `table_references` list.
This is a fragile approach because it assumes the table_references list is stable for the lifetime of the query processing. This has so far been the case, but there exist certain query transformations, e.g. subquery unnesting, that may fold new table references from a subquery (which has its own table ref list) into the table reference list of the parent.
If such a transformation is made, then potentially all of the Expr::Column references to tables will become invalid. Consider this example: …
> Refactor: add stable internal_id property to TableReference

- core/lib.rs
- core/storage/btree.rs
- core/storage/pager.rs
- core/storage/wal.rs
- core/vdbe/execute.rs
- core/vdbe/mod.rs
- tests/integration/common.rs
- Instead of using a confusing `CheckpointStatus` for many different things, introduce the following statuses:
* `PagerCacheflushStatus` - cacheflush can result in either:
- the WAL being written to disk and fsynced
- but also a checkpoint to the main DB file, and fsyncing the main DB file
Reflect this in the type.
* `WalFsyncStatus`
- previously `CheckpointStatus` was also used for this, even though fsyncing the WAL doesn't checkpoint.
* `CheckpointStatus`/`CheckpointResult` is now used only for actual checkpointing.
- Rename `HaltState` to `CommitState` (program.halt_state -> program.commit_state)
* `HaltState`'s only variant was `HaltState::Checkpointing` but it wasn't necessarily reflective of checkpoint being in progress.
* Now the variants are `CommitState::Ready` and …
> Small cleanups to pager/wal/vdbe - mostly naming

- core/vdbe/execute.rs
If we don't reset the state of `IdxDelete`, next `IdxDelete` will start in `Deleting` state which is completely wrong since it should seek from the start.
> Reset idx delete state after successful finish

- core/translate/main_loop.rs
- core/translate/optimizer/join.rs
- core/translate/optimizer/lift_common_subexpressions.rs
- core/translate/optimizer/mod.rs
- core/translate/plan.rs
- core/translate/planner.rs
Currently in the main translation logic after planning and optimization, we don't _really_ need to pass a `&mut Vec<WhereTerm>` around anymore, except for the fact that virtual table constraint resolution is done ad-hoc in `init_loop()`. 
Even there, the only thing we mutate is `WhereTerm::consumed` which is a boolean indicating that the term has been "used up" by the optimizer and shouldn't be evaluated as a normal where clause condition anymore.
In the upcoming branch for WHERE clause subqueries, I want to store immutable references to WHERE clause expressions in `Resolver`, but this is unfortunately not possible if we still use the aforementioned mutable references.
Hence, we can temporarily make `WhereTerm::consumed` a `Cell<bool>` which allows us to pass an immutable reference to …
> Make WhereTerm::consumed a Cell<bool>

- Cargo.lock
- simulator/Cargo.toml
- simulator/generation/plan.rs
- simulator/generation/property.rs
- simulator/generation/query.rs
- simulator/main.rs
- simulator/model/query/mod.rs
- simulator/model/query/update.rs
- simulator/runner/bugbase.rs
- simulator/runner/cli.rs
- simulator/runner/differential.rs
- simulator/runner/execution.rs
- simulator/runner/file.rs
- simulator/runner/io.rs
- simulator/runner/watch.rs
- simulator/shrink/plan.rs
* Without tracing crate we cannot log anything that happens in limbo_core
* IO never ran in step loop inside simulator.
* Added update queries (which currently loop forever for some reason I'm debugging).
> simulator: switch to tracing, run io.run_once and add update queries

- core/lib.rs
- core/translate/mod.rs
In preparation for `CREATE VIEW`, we need to have the original sql query that was used to create the view. I'm using the scanner's offset to slice into the original input, trimming the newlines, and passing it to the translate function.
> Pass input string to `translate` function

- cli/app.rs
- core/vdbe/mod.rs
Instrument trace_insn to debug print its the stack pc and instruction. Also, disable rustyline logs for the CLI as it is too noisy to work with.
> Small tracing enhancement

- core/storage/btree.rs
- core/vdbe/execute.rs
- testing/cli_tests/memory.py
- testing/cli_tests/write.py
- testing/update.test
Closes #1628.  Every function that calls `process_overflow_read` needs to be reentrant. I did not change it here, but it would include `get_prev_record` and `get_next_record`. Maybe `tablebtree_move_to` did not need to use the state machine, but I included it as a safeguard.
Edit: Closes #1625 . When I implemented `restore_context`, I forgot to add a `return_if_io` after calling it in `next` 🤦‍♂️
Edit: Closes #1617 . Just tested it and it also solves this bug.
> Make cursor seek reentrant

- core/lib.rs
- core/pragma.rs
- core/translate/planner.rs
- core/types.rs
- core/util.rs
- core/vdbe/execute.rs
- core/vdbe/mod.rs
- core/vtab.rs
- testing/cli_tests/extensions.py
- testing/pragma.test
This PR adds support for table-valued functions for PRAGMAs (see the [PRAGMA functions section](https://www.sqlite.org/pragma.html)).
Additionally, it introduces built-in table-valued functions. I considered using extensions for this, but there are several reasons in favor of a dedicated mechanism:
* It simplifies the use of internal functions, structs, etc. For example, when implementing `json_each` and `json_tree`, direct access to internals was necessary: https://github.com/tursodatabase/limbo/pull/1088
* It avoids FFI overhead. [Benchmarks](https://github.com/piotrrzysko/limbo/blob/pragma_vtabs_bench/core/benches/pragma_benchmarks.rs) on my hardware show that `pragma_table_info()` implemented as an extension is 2.5× slower than the built-in version.
> Add support for pragma table-valued functions

- core/storage/sqlite3_ondisk.rs
- core/storage/wal.rs
Closes #1622
I did an A/B test between SQLite and Limbo and they can restart the db from each other, indicating that there isn't something very wrong with our file format. Turns out it was with our reset logic without truncating the file. I assumed it's safe to don't reset if we're in `PASSIVE` mode, given the [docs](https://www.sqlite.org/c3ref/wal_checkpoint_v2.html) and [source code](https://github.com/sqlite/sqlite/blob/2bd9f69d40dd240c4122c6d02f1ff447e7b5c098/src/wal.c#L2193).
It also does some small clean ups and fixes.
> Fix WAL frame checksum mismatch

- simulator/generation/property.rs
- simulator/generation/query.rs
- simulator/runner/cli.rs
- simulator/runner/env.rs
Some additional cli options and some adjustments to determine if a query statement is disabled for this run. This enables us to at least run the simulator to completion when other parts of the system cause infinite loops almost every time. I'm looking at you UPDATE
> simulator: options to disable certain query types

- core/lib.rs
- core/storage/sqlite3_ondisk.rs
- core/translate/mod.rs
- core/translate/pragma.rs
- testing/pragma.test
According to [the document](https://www.sqlite.org/pragma.html#pragma_cache_size): 
```
When you change the cache size using the cache_size pragma, the change only endures for the current session. The cache size reverts to the default value when the database is closed and reopened.
```
so, we shouldn't persist cache_size to database header.
this PR also addresses two minor issues:
1. Sets the default cache_size to -2000 to align with SQLite's default
2. Uses the actual page size to calculate the cache size.
> Fix:  ensure `PRAGMA cache_size` changes persist only for current session

- core/Cargo.toml
- core/pragma.rs
- core/storage/btree.rs
- core/storage/pager.rs
- core/storage/sqlite3_ondisk.rs
- core/translate/pragma.rs
- core/vdbe/execute.rs
- core/vdbe/explain.rs
- core/vdbe/insn.rs
- vendored/sqlite3-parser/src/parser/ast/mod.rs
This PR adds the beginnings of [AUTOVACUUM](https://www.sqlite.org/lang_vacuum.html) to Limbo. It adds a feature flag called `omit_autovacuum` which is analogous to `SQLITE_OMIT_AUTOVACUUM`. It is off by default, same as SQLite.
It introduces the concept of [pointer map pages](https://www.sqlite.org/fileformat.html#pointer_map_or_ptrmap_pages) which are reverse index pages used to map pages to their parents. This is used to swap pages (when a table is deleted for instance) to keep root pages clustered at the beginning of the file. It's also used while creating a table to ensure that root pages are clustered at the beginning (although, this isn't completely implemented yet)
Finally, it also adds a couple of missing instructions like `Int64` that are required for `PRAGMA` commands related …
> Beginnings of AUTOVACUUM

- vendored/sqlite3-parser/src/dialect/mod.rs
This PR fixes an unsound usage of unsafe { str::from_utf8_unchecked(word) } in the public function keyword_token in mod.rs.
The function now uses std::str::from_utf8(word).ok()? to safely handle invalid UTF-8, eliminating the unsoundness.
No logic or API changes.
Code compiles and tests pass (where possible).
Closes: https://github.com/tursodatabase/libsql/issues/1859
> fix: make keyword_token safe by validating UTF-8 input

- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- simulator/Cargo.toml
- simulator/main.rs
- simulator/runner/bugbase.rs
- simulator/runner/cli.rs
- tests/Cargo.toml
Adds a Sqlite integrity check after the simulator completes a run. Also changed error handling in the simulator to use `anyhow` to lazily add context to error methods instead of eagerly using `.or` and losing the original error.
> Simulator integrity_check

- simulator-docker-runner/docker-entrypoint.simulator.ts
- simulator-docker-runner/github.ts
- simulator-docker-runner/logParse.ts
- Entire stdout+stderr was passed to both title and body for the github issue, resulting in a failure due to github's validation
Fixes:
- Pass only the line containing "simulation failed:" as title
- Pass max 50 lines following title as body
- Truncate title and body to 255 and 65536 chars respectively before posting github issue, just to be sure
> sim/aws: fix vibecoding errors in logic

- simulator/generation/plan.rs
- simulator/generation/property.rs
- simulator/model/query/mod.rs
- simulator/shrink/plan.rs
This PR attempts to get the specific query that failed in the simulator and get the correct tables that were used in the Query. Also, implements a fix where after clearing miscellaneous queries, we did not check again if the the interaction still referenced any of the tables that were involved in the failure.
> Simulator: Better Shrinking

- core/vdbe/execute.rs
- tests/integration/common.rs
Closes #1717
We were incorrectly setting `moved_before` as `false` after checking for unique constraint violation, but the reality is that after the uniqueness check, we are already correctly positioned -- if no match was found, the cursor is positioned at either:
a) no row, or
b) at the first entry that is greater than the key we are inserting.
This means we don't have to move anymore and can just insert.
> Fix large inserts to unique indexes hanging

- core/translate/delete.rs
- core/translate/insert.rs
This is more in line with SQLite:
```sql
sqlite> insert into t values (randomblob(1024*1024 * 6));
Parse error: no such table: t
```
> Return parse error instead of corrupt error for `no such table`

- core/pragma.rs
- core/storage/btree.rs
- core/translate/integrity_check.rs
- core/translate/mod.rs
- core/translate/pragma.rs
- core/vdbe/execute.rs
- core/vdbe/explain.rs
- core/vdbe/insn.rs
- core/vdbe/mod.rs
- testing/all.test
- testing/integrity_check.test
- vendored/sqlite3-parser/src/parser/ast/mod.rs
This PR adds support for the instruction `IntegrityCk` which performs an integrity check on the contents of a single table. Next PR I will try to implement the rest of the integrity check where we would check indexes containt correct amount of data and some more.
> Simple integrity check on btree

- core/vdbe/execute.rs
Hey 👋
I admire the work that you guys are doing here, great job so far!
`Value::Blob::encode_hex` incorrectly does a lossy conversion of the blob's underlying byte vector into a utf8 String, incorrectly displaying the underlying hex in the process.
This PR fixes issue #1751
> Fix incorrect lossy conversion of `Value::Blob` to a utf-8 `String`

- antithesis-tests/bank-test/anytime_validate.py
- antithesis-tests/bank-test/eventually_validate.py
- antithesis-tests/bank-test/finally_validate.py
- antithesis-tests/bank-test/first_setup.py
- antithesis-tests/bank-test/parallel_driver_generate_transaction.py
- antithesis-tests/stress-composer/first_setup.py
- antithesis-tests/stress-composer/parallel_driver_delete.py
- antithesis-tests/stress-composer/parallel_driver_insert.py
- antithesis-tests/stress-composer/parallel_driver_update.py
If multiple processes access the same database file concurrently, Limbo fails with:
```
LockingError("Failed locking file. File is locked by another process
```
Make test driver robust against that.
> antithesis-tests: Make test drivers robust when database is locked

- core/vdbe/execute.rs
- tests/integration/fuzz/mod.rs
It is easy to chalk this fuzzer issue to erratic floating point behaviour, but this is not the case here.
Currently, `exec_math_log` calculates log with arbitrary bases by using the following formula: `log_a(b) ~= ln(b) / ln(a)`. This calculation is an approximation with lots of its floating point precision lost to dividing the results of natural logarithms.
By using the specialized versions of the log functions (`log2` & `log10`), we can avoid this loss of precision.
SQLite also uses these specialized log functions when possible, so it doesn't hurt to do the same thing when aiming for parity.
This PR fixes #1763
> Fix fuzz issue #1763 by using the `log2` & `log10` functions where applicable

- bindings/rust/src/lib.rs
A simple change to implement the `Debug` trait for the `Connection`, similar to how it is implemented for `Database`.  This should help users in their application code with wrapping the connection.
> bindings/rust: Implement Debug for Connection

- Cargo.lock
- bindings/javascript/src/lib.rs
- bindings/wasm/lib.rs
- core/Cargo.toml
- core/lib.rs
- core/storage/btree.rs
- core/storage/buffer_pool.rs
- core/storage/database.rs
- core/storage/header_accessor.rs
- core/storage/mod.rs
- core/storage/page_cache.rs
- core/storage/pager.rs
- core/storage/sqlite3_ondisk.rs
- core/storage/wal.rs
- core/translate/mod.rs
- core/translate/pragma.rs
- core/vdbe/builder.rs
- core/vdbe/execute.rs
- core/vdbe/mod.rs
- simulator/generation/plan.rs
- simulator/runner/cli.rs
- simulator/runner/env.rs
This PR makes limbo read the database header and schema via the regular pager `read_page()` route, instead of always reading it from the database file. This is very important for correctness as modifications to page 1 (containing header and schema) may exist in WAL frames, not just the main database file. Without this, practically any real use of the database would very quickly corrupt the DB as limbo would read the incorrect page count from the stale page 1 copy in the database file, and e.g. allocate the same rootpage for multiple tables and so on.
This issue has been so far hidden due to lack of tests and the fact that `Connection::close()` checkpoints the DB by default, which has delayed discovering this incredibly basic issue since most manual testing has happened via CLI, and if …
> Fix database header initialization

- simulator/generation/plan.rs
- simulator/runner/cli.rs
- simulator/runner/env.rs
Add fault type that reopens the DB and reconnects the connections. It purposefully does not call conn.close(), as the default behavior of that method is to checkpoint the database.
This easily exposes multiple manifestations of DB/WAL corruption caused by this issue: https://github.com/tursodatabase/limbo/issues/1725
in fact, in my testing, every run fails when this fault is enabled. Hence I've added the --disable-reopen-database flag if you want to try to find some other bugs.
> sim: add Fault::ReopenDatabase

- cli/app.rs
- core/lib.rs
- core/storage/btree.rs
- core/storage/pager.rs
- core/storage/wal.rs
- core/translate/mod.rs
- core/translate/rollback.rs
- core/vdbe/builder.rs
- core/vdbe/execute.rs
- core/vdbe/mod.rs
- testing/all.test
- testing/rollback.test
Support for simple interactive rollback like:
```sql
create table t (x);
insert into t values (1);
begin;
insert into t values (2);
rollback;
select * from t;
```
This PR also fixes some other issues I found while debugging:
* Checkpoint would never `clear_dirty` on pages in page cache.
* Auto commit for interactive transactions was not respected so any `insert` after `begin` would flush frames regardless of `auto_commit` state.
* `max_frame` on wal shared state was being updated after every `append_frame` which was incorrect, as another transaction would be able to use that new `max_frame` even tho the transaction could've rolled back. Instead we update the private copy of `max_frame` and only update it at the end.
Follow up for later are savepoints which require implementing a …
> `Rollback` simple support

- core/lib.rs
- core/storage/btree.rs
- core/storage/header_accessor.rs
- core/storage/pager.rs
- core/vdbe/execute.rs
- core/vdbe/mod.rs
Page 1 must be initialized and written as soon as possible without marking page as dirty.
OpenEphemeral now requires a state machine to accomodate new begin_write_tx semantics.
> write page1 on database initialization

- bindings/javascript/src/lib.rs
- bindings/wasm/lib.rs
- core/io/generic.rs
- core/io/io_uring.rs
- core/io/memory.rs
- core/io/mod.rs
- core/io/unix.rs
- core/io/vfs.rs
- core/io/windows.rs
- core/lib.rs
- core/storage/btree.rs
- core/storage/database.rs
- core/storage/sqlite3_ondisk.rs
- core/storage/wal.rs
- simulator/runner/cli.rs
- simulator/runner/env.rs
- simulator/runner/file.rs
- simulator/runner/io.rs
This PR introduces the ability to introduce latency (e.g thread::sleep) in every File IO operation. There is a new cli option that configures the probability of introducing latency. Currently, this probability defaults to 0, as this change has already detected an infinite loop in `checkpoint`. To see this bug in action run the following command: `cargo run -p limbo_sim -- --seed 3961479079923545111 --latency_prob 5`
EDIT: Investigating the bug further, I see that it is returning to the simulator after the disconnect checkpoint, but I have not yet seen this test end. Maybe it is just taking too long? Something to look further at
> Simulator: add latency to File IO

- core/storage/pager.rs
Profiling revealed that `usable_space()` calls were consuming 60% of total execution time for simple SELECT queries, making Limbo approximately `6x` slower than SQLite for SELECT operations.
The bottleneck was caused by `usable_space()` performing expensive I/O operations on every call to read `page_size` and `reserved_space` from the database header, despite `page_size` values being effectively immutable after database initialization. Only `reserved_space` is allowed to increase in SQLite.
Evidence: https://share.firefox.dev/44tCUIy
Implemented OnceCell-based caching for both page_size and reserved_space values in the Pager struct:
`page_size: OnceCell<u16>` - Page size is immutable after database initialization per SQLite specification
`reserved_space: OnceCell<u8>` - Reserved space …
> Cache `reserved_space` and `page_size` values at Pager init to prevent doing redundant IO

- Cargo.lock
- core/Cargo.toml
- core/ext/dynamic.rs
- testing/cli_tests/extensions.py
- uv.lock
To prevent having to publish the crate on crates.io
> Remove dependency on test extension pkg

- stress/main.rs
Stress runs have bunch of errors like this caused by reconnect in the middle of a transaction:
```
Error executing query: Transaction error: cannot rollback - no transaction is active
```
This is fine, but let's add some logging that it's obvious why this happens.
> stress: Log reopen and reconnect

- core/storage/pager.rs
- core/storage/sqlite3_ondisk.rs
- core/storage/wal.rs
- tests/integration/query_processing/test_write_path.rs
`db_size` is `>0` in case of last frame written of a transaction. This is necessary as we need to know -- while recovering wal contents -- that we have read a transaction fully instead of treating every frame as its own transaction.
> WAL record db_size frame on commit last frame

- Cargo.lock
- bindings/rust/Cargo.toml
- bindings/rust/examples/example.rs
- bindings/rust/src/lib.rs
- bindings/rust/src/params.rs
- bindings/rust/src/row.rs
- bindings/rust/src/statement.rs
- bindings/rust/src/value.rs
- bindings/rust/tests/integration_tests.rs
- stress/main.rs
This PR aims to add some more comments and documentation to the Rust binding. It also fixes an issue where you could not reuse the statement after it ran to completion or errored. Now the statement resets in those cases. Also implemented `Stream` for the Rows struct allowing users to leverage the built-in iterator like methods for better ergonomics.
> Rust binding improvements

- cli/config/mod.rs
- cli/config/terminal.rs
I just tried turso and couldn't read the last column. Turns out I guess Pekka's taste is not the best, at least not for everybody.
Auto-detect if terminal is light or dark mode and select colors accordingly.
> automatically select terminal colors for pretty mode

- bindings/python/pyproject.toml
https://pypi.org/project/pyturso/0.1.1/ is still showing the old name:
> Turso, not Limbo, in pyproject.toml

- Cargo.lock
- core/Cargo.toml
- core/storage/page_cache.rs
We should recreate original box to drop it properly
Also made a fast path for hashing. When key div by 2. It should decrease cpu cycles on hot path by x10 approximately 
This thing is tricky, made a long running test that verify bug, put #[ignore] on it to not slow down CI
> Fix boxed memory leaks

- .github/workflows/rust_perf.yml
- testing/cli_tests/collate.py
- testing/cli_tests/constraint.py
- testing/cli_tests/extensions.py
- testing/cli_tests/memory.py
- testing/cli_tests/update.py
- testing/cli_tests/vfs_bench.py
- testing/cli_tests/write.py
When we renamed the Python imports, we forgot to rename the `test_limbo_cli` to `test_turso_cli`. Also adds a vfs-bench-compile github ci to compile and test that the bench-vfs scripts works
> Fix Python test import naming

- core/translate/emitter.rs
- testing/update.test
When an `UPDATE` statement modifies a table's `INTEGER PRIMARY KEY` (which acts as a `rowid` alias) alongside other indexed columns, the index entries were incorrectly retaining the old `rowid`. This led to stale index references, causing subsequent queries to return incorrect results.
This change ensures that when the `rowid` alias is part of the `SET` clause in an `UPDATE` statement, the new `rowid` value is used for generating and updating index records. This guarantees that all index entries correctly point to the updated row, resolving the data inconsistency.
Fixes #1897
> Fix index update when INTEGER PRIMARY KEY (rowid alias)

- COMPAT.md
- core/lib.rs
- core/schema.rs
- core/storage/btree.rs
- core/storage/pager.rs
- core/translate/alter.rs
- core/translate/index.rs
- core/translate/mod.rs
- core/translate/rollback.rs
- core/translate/schema.rs
- core/vdbe/execute.rs
- core/vdbe/mod.rs
- stress/main.rs
- testing/all.test
- testing/rollback.test
Fixes #1890
Once rollback was implement we quickly saw that it lacked support for schema changes so we had to re-estructure things a bit.
```bash
turso> begin;
turso> create table t(x);
turso> rollback;
turso> pragma integrity_check;
thread 'main' panicked at core/storage/sqlite3_ondisk.rs:386:36:
called `Result::unwrap()` on an `Err` value: Corrupt("Invalid page type: 83")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This happened because it thought table `t` existed because we didn't rollback that schema.
* The most important change: now every connection has a private copy of schema. On write txn commit we update a global schema shared between connections in order for new connections to get updated version from there. In case of rollback, we simply …
> Rollback schema support

- bindings/javascript/README.md
- bindings/javascript/__test__/dual-test.mjs
- bindings/javascript/__test__/limbo.spec.mjs
- bindings/javascript/__test__/sync.spec.mjs
- bindings/javascript/package.json
- bindings/javascript/wrapper.js
This PR imports the `sync` test suite from libSQL, and modifies the export structure match `better-sqlite3`, so that at least a few tests from the new test suite are passing.
I also changed the `package.json` to expose `wrapper.js` as an entrypoint. I think the plain `index.js` was probably never meant to be exposed directly to clients, because the wrapper does some important transformation. It's also how libSQL-js is [structured](https://github.com/tursodatabase/libsql-js/blob/main/package.json#L20).
The test suite that I imported was previously run twice, with different environment variables: one run for libSQL-js, one run for better-sqlite3. This worked well with libSQL, because it's compatible with better-sqlite3. But Turso isn't there yet, so even though all tests need to run on …
> Import JavaScript bindings test suite from libSQL

- core/vdbe/execute.rs
- testing/glob.test
Previously `ScalarFunc::Glob` only handled Text based values. After this fix it will be able to handle all types of values. 
Now:
```SQL
turso> CREATE TABLE IF NOT EXISTS  t0 (c0 REAL ); 
turso> UPDATE t0 SET c0='C2IS*24', c0=0Xffffffffbfc4330f, c0=0.6463854797956918 WHERE ((((((((t0.c0)AND(t0.c0)))AND(0.23913649834358142)))OR(CASE t0.c0  WHEN t0.c0 THEN 'j2' WHEN t0.c0 THEN t0.c0 WHEN t0.c0 THEN t0.c0 END)))OR(((((((((t0.c0)AND(t0.c0)))AND(t0.c0)))OR(t0.c0)))AND(t0.c0)))); 
turso> INSERT INTO t0 VALUES (NULL);
INSERT INTO t0 VALUES ('0&');
UPDATE t0 SET c0=2352448 WHERE ((((t0.c0)GLOB(t0.c0))) NOT NULL);
turso> SELECT * from t0;
┌───────────┐
│ c0        │
├───────────┤
│           │
├───────────┤
│ 2352448.0 │
└───────────┘
```
Fixes: https://github.com/tursodatabase/turso/issues/1953
> Fix `ScalarFunc::Glob` to handle NULL and other value types

- bindings/rust/src/lib.rs
- core/translate/planner.rs
- core/translate/select.rs
- testing/cli_tests/extensions.py
We're now mixing different error messages, which makes compatibility testing pretty hard. Unify on a single, SQLite compatible error message "no such table".
> core/translate: Unify no such table error messages

- .github/workflows/rust.yml
- Makefile
- scripts/limbo-sqlite3
- scripts/limbo-sqlite3-index-experimental
- testing/cli_tests/cli_test_cases.py
- testing/cli_tests/test_turso_cli.py
- testing/cli_tests/vfs_bench.py
Should fix CI issues right now and decrease some of the time it takes to execute the tests.
> remove experimental_flag from script + remove -q flag default flag from `TestTursoShell`

- antithesis-tests/bank-test/parallel_driver_generate_transaction.py
- antithesis-tests/stress-composer/parallel_driver_schema_rollback.py
- bindings/python/pyproject.toml
- perf/connection/gen-database.py
- perf/connection/plot.py
- testing/cli_tests/test_turso_cli.py
I added some `reachable` assertions in the `parallel_driver_generate_transaction` so that Antithesis can log when we reach them, so it is easier to debug the `page_cache` panic we are getting there
> Reachable assertions in Antithesis Python Test for better logging

- Cargo.lock
- vendored/sqlite3-parser/Cargo.toml
- vendored/sqlite3-parser/third_party/lemon/lemon.c
- vendored/sqlite3-parser/third_party/lemon/lempar.rs
sqlite uses [fixed-size](https://github.com/sqlite/sqlite/blob/7fc6e6a2726e650d3b82c6d3683bdbdc10e02467/tool/lempar.c#L238) array for `yystack` and grow stack if needed. Let replace `vec` with `smallvec` in rust version.
after:
```sh
sqlparser-rs parsing benchmark/sqlparser::select
time:   [564.19 ns 565.63 ns 567.18 ns]
change: [-11.514% -11.288% -11.067%] (p = 0.00 < 0.05)
Found 4 outliers among 100 measurements (4.00%)
1 (1.00%) low mild
3 (3.00%) high mild
sqlparser-rs parsing benchmark/sqlparser::with_select
time:   [1.9812 µs 1.9861 µs 1.9914 µs]
change: [-7.5226% -7.3080% -7.0858%] (p = 0.00 < 0.05)
Found 5 outliers among 100 measurements (5.00%)
1 (1.00%) low mild
4 (4.00%) high mild
```
> parser: use YYSTACKDEPTH

- bindings/python/src/lib.rs
- core/lib.rs
- core/vdbe/mod.rs
Due to how `execute` is implemented, it returns a `Connection` clone
which internally shares a turso_core::Connection with every other
Connection. Since `execute` returns `Connection` and immediatly it is
dropped, it will close connection, checkpoint and leave database in
weird state.
Let's make sure we don't keep using a connection after it was dropped.
In case of executing a query that was closed we will try to rollback and
return early.
> bindings/python: close connection only when reference count is one

- bindings/python/src/lib.rs
- bindings/python/tests/test_database.py
We need to start transaction implicitly in execute() for DML statements to make sure first transaction is actually started.
Fixes #2002
> bindings/python: Start transaction implicitly in execute()

- Cargo.lock
- core/function.rs
- core/translate/expr.rs
- core/translate/planner.rs
- core/translate/select.rs
We need to return the original function name, not normalized one to be compatible with SQLite.
Spotted by SQLite TCL tests.
> core: Fix resolve_function() error messages

- core/storage/btree.rs
- core/storage/sqlite3_ondisk.rs
we were providing the same damn arguments to `.cell_get()` and `.cell_get_raw_region()` over and OVER and **OVER** and `O V E R`
> btree/chore: remove unnecessary parameters to .cell_get()

- core/storage/sqlite3_ondisk.rs
- core/storage/wal.rs
- tests/integration/query_processing/test_write_path.rs
We store `last_checksum` to do cumulative checksumming. After reading wal for recovery, we didn't set last checksum properly in case there were no frames so this cause us to not initialize last_checksum properly.
> properly set last_checksum after recovering wal

- .github/workflows/rust_perf.yml
I noticed on instance of the nyrkio github action was still using the old name. Updating to nyrkio/change-detection@HEAD. All other entries are already updaeted,
> github: Update to newest Nyrkiö Github action

- core/vdbe/execute.rs
- testing/agg-functions.test
- tests/integration/fuzz/mod.rs
Removes the error prints described in #2033 but doesn't fix the issue. Instead as a result of this PR I opened https://github.com/tursodatabase/turso/issues/2040 and https://github.com/tursodatabase/turso/issues/2041 after I added a fuzz test 😂 
we _need_ to fuzz _everything_.
> vdbe: fix some issues with min() and max() and add ignored fuzz test

- core/storage/btree.rs
Closes #2047 
the validation code was assuming that:
- if the parent has overflow cells after inserting a divider cell
- the exact divider we are validating MUST be in those overflow cells
However, this is not necessarily the case. Imagine:
- First divider gets inserted at index `n`. It is too large to fit, so it gets pushed to `parent.overflow_cells()`. Parent usable space does not decrease.
- Second divider gets inserted at index `n+1`. It is smaller, so it still fits in usable space.
Hence:
Provide information to the validation function about whether the inserted cell overflowed, and use that to find the left pointer and assert accordingly.
> btree/balance/validation: fix divider cell insert validation

- simulator/main.rs
This inhibits ANSI color codes on non-TTY stdouts. It should fix logs with mangled color codes such as https://github.com/tursodatabase/turso/issues/2046.
On this branch:
If I don't pipe or redirect, on this branch, the color is displayed.
On main:
> Simulator - only output color on terminal

- core/benches/benchmark.rs
- core/lib.rs
- core/schema.rs
- core/util.rs
- Also added a benchmark for opening databases, the main thing that is slowing `Database::open_file` is `parse_schema_rows`.
- `to_uppercase` was being called multiple times, leaving a relevant mark on stack traces due to multiple allocations. `make_ascii_upper` reuses the memory and is faster due to not handling unicode characters (still compatible with sqlite).
- Do direct btree calls instead of creating a program for updating `Schema` with `Schema::make_from_btree`.
- Faster type substr comparison using fixed size `u8` slices.
> `parse_schema_rows` optimizations

- core/function.rs
- core/json/mod.rs
- core/lib.rs
- core/storage/sqlite3_ondisk.rs
- core/translate/emitter.rs
- core/translate/expr.rs
- core/translate/insert.rs
- core/translate/pragma.rs
- core/types.rs
- core/vdbe/execute.rs
- core/vdbe/mod.rs
- tests/integration/functions/test_cdc.rs
This PR adds few functions to the `turso-db` in order to simplify exploration of CDC table. Later we will also add API to work with changes from the code - but SQL support is also useful.
So, this PR adds 2 functions:
1. `table_columns_json_array('<table-name>')` - returns list of current table column **names** as a single string in JSON array format
2. `bin_record_json_object('<columns-array>', x'<bin-record>')` - convert record in the SQLite format to the JSON object with keys from `columns-array`
So, this functions can be used together to extract changes in human-readable format:
```sql
turso> PRAGMA unstable_capture_data_changes_conn('full');
turso> CREATE TABLE t(a INTEGER PRIMARY KEY, b);
turso> INSERT INTO t VALUES (1, 2), (3, 4);
turso> UPDATE t SET b = 20 WHERE a = 1;
turso> …
```
> CDC functions

- bindings/wasm/lib.rs
- core/io/mod.rs
- core/io/unix.rs
- core/io/windows.rs
- core/storage/sqlite3_ondisk.rs
- core/storage/wal.rs
- simulator/runner/file.rs
Let's assert **for now** that we do not read/write less bytes than expected. This should be fixed to retrigger several reads/writes if we couldn't read/write enough but for now let's assert.
> Assert I/O read and write sizes

- Cargo.lock
- core/storage/btree.rs
- core/types.rs
- core/vdbe/execute.rs
- core/vdbe/mod.rs
- testing/select.test
- tests/Cargo.toml
- tests/integration/query_processing/mod.rs
- tests/integration/query_processing/test_btree.rs
- tests/integration/query_processing/test_multi_thread.rs
Current table B-Tree seek code rely on the invariant that if key `K` is present in interior page then it also must be present in the leaf page.
This is generally not true if data was ever deleted from the table because leaf row which key was used as a divider in the interior pages can be deleted. Also, SQLite spec says nothing about such invariant - so `turso-db` implementation of B-Tree should not rely on it.
This PR introduce 3 options for B-Tree `seek` result: `Found` / `NotFound` and `TryAdvance` which is generated when leaf page have no match for `seek_op` but DB don't know if neighbor page can have matching data.
There is an alternative approach where we can move cursor in the `seek` itself to the neighbor page - but I was afraid to introduce such changes because analogue `seek` …
> b-tree: fix bug in case when no matching rows was found in seek in the leaf page

- tests/integration/fuzz/mod.rs
The original `rowid_seek_fuzz` test had a design flaw: it inserted contiguous non-random integers (so not really fuzzing), which prevented issues such as the one fixed in #2065 from being discovered.
Further, the test has at some point also been neutered a bit by only inserting 100 values which makes the btree very small, hiding interactions between interior pages and neighboring leaf pages.
This should not be merged until #2065 is merged.
> test/fuzz: fix rowid_seek_fuzz not being a proper fuzz test

- core/lib.rs
- core/storage/btree.rs
- core/storage/header_accessor.rs
- core/storage/pager.rs
- core/storage/sqlite3_ondisk.rs
- core/storage/wal.rs
- core/translate/pragma.rs
- core/vdbe/execute.rs
- testing/pragma.test
Closes: #1379
This PR consists of three main changes:
1. Rebuild `Pager` to set the correct page size for `buffer_pool`, `wal` and other components when the database is uninitialized.
2. Persist the latest page size when allocate page 1.
3. Ensure all pragmas emit the correct transaction instructions, preventing even a `page_size`  read from triggering database initialization.
> Support page_size pragma setting

- core/ext/mod.rs
- core/pragma.rs
- core/schema.rs
- core/series.rs
- core/translate/insert.rs
- core/translate/main_loop.rs
- core/translate/optimizer/join.rs
- core/translate/optimizer/mod.rs
- core/translate/plan.rs
- core/translate/planner.rs
- core/translate/pragma.rs
- core/translate/schema.rs
- core/translate/select.rs
- core/translate/update.rs
- core/util.rs
- core/vtab.rs
- extensions/completion/src/lib.rs
- extensions/tests/src/lib.rs
- testing/cli_tests/extensions.py
- testing/pragma.test
- testing/sqlite_test_ext/src/kvstore.c
First step toward resolving https://github.com/tursodatabase/limbo/issues/1643.
With this change, the following two queries are considered equivalent:
```sql
SELECT value FROM generate_series(5, 50);
SELECT value FROM generate_series WHERE start = 5 AND stop = 50;
```
Arguments passed in parentheses to the virtual table name are now matched to hidden columns.
Additionally, I fixed two bugs related to virtual tables.
Column references are still not supported as table-valued function arguments. The only difference is that previously, a query like:
```sql
SELECT one.value, series.value
FROM (SELECT 1 AS value) one, generate_series(one.value, 3) series;
```
would cause a panic. Now, it returns a proper error message instead.
Adding support for column references is more nuanced for two main …
> Treat table-valued functions as tables

- core/storage/btree.rs
- core/vdbe/execute.rs
- core/vdbe/mod.rs
PR #2065 fixed a bug with table btree seeks concerning boundaries of leaf pages.
The issue was that if we were e.g. looking for the first key greater than (GT) 100, we always assumed the key would either be found on the left child page of a given divider (e.g. divider 102) or not at all, which is incorrect. #2065 has more discussion and documentation about this, so read that one for more context.
We already had similar handling for index btrees as #2065 introduced for table btrees, but it was baked into the `BTreeCursor` struct's seek handling itself, whereas #2065 handled this on the VDBE side.
This PR unifies this handling for both table and index btrees by always doing the additional cursor advancement in the VDBE.
Unfortunately, unlike table btrees, index btrees may also need to do an …
> btree: unify table&index seek page boundary handling

- core/types.rs
- testing/insert.test
- remove assumptions that record header size fits into 1 byte or serial type fits into 1 byte
- add tests for record header size calculation
```sql
turso> CREATE TABLE t(x TEXT, y);
CREATE INDEX t_idx ON t(x);
INSERT INTO t VALUES (replace(zeroblob(1000), x'00', 'a') || 'a', 1); -- 1000 bytes of 'a'
INSERT INTO t VALUES (replace(zeroblob(1000), x'00', 'a') || 'b', 2);
INSERT INTO t VALUES (replace(zeroblob(1000), x'00', 'a') || 'c', 3);
INSERT INTO t VALUES (replace(zeroblob(1000), x'00', 'a') || 'd', 4);
INSERT INTO t VALUES (replace(zeroblob(1000), x'00', 'a') || 'e', 5);
INSERT INTO t VALUES (replace(zeroblob(1000), x'00', 'a') || 'f', 6);
INSERT INTO t VALUES (replace(zeroblob(1000), x'00', 'a') || 'g', 7);
INSERT INTO t VALUES (replace(zeroblob(1000), x'00', 'a') || 'h', 8);
SELECT …
```
> fix record header size calculations and incorrect assumptions

- core/lib.rs
- core/schema.rs
- core/storage/btree.rs
- core/storage/header_accessor.rs
- core/storage/pager.rs
- core/storage/wal.rs
- core/types.rs
- core/vdbe/execute.rs
- core/vdbe/mod.rs
- tests/integration/common.rs
This PR unify the concept of a result that either have something done or yields to IO, into a single type.
> refactor: Changes CursorResult to IOResult

- cli/commands/import.rs
- perf/clickbench/.gitignore
- testing/cli_tests/cli_test_cases.py
- testing/test_files/test_w_header.csv
- Fix not being able to create table while importing
* The behavior now aligns with SQLite so that if the table already exists, all the rows are treated as data. If the table doesn't exist, the first row is treated as the header from which column names for the new table are populated.
- Insert in batches instead of one at a time
This was a pretty quick vibecoding effort tbh :]
Closes #2079
> Fix CSV import in the shell

- core/storage/btree.rs
When a divider cell is deleted from an index interior page, the following algorithm is used:
1. Find predecessor: Move to largest key in left subtree of the current page. This is always a leaf page.
2. Create replacement: Convert this predecessor leaf cell to interior cell format, using original cell's left child page pointer
3. Replace: Drop original cell from parent page, insert replacement at same position
4. Cleanup: Delete the taken predecessor cell from the leaf page
The error in our logic was that we always expected to only traverse down one level of the btree:
```rust
let parent_page = self.stack.parent_page().unwrap();
let leaf_page = self.stack.top();
```
This meant that when the deletion happened on say, level 1, and the replacement cell was taken from level 3, we actually …
> btree: fix interior cell replacement in btrees with depth >=3

- core/functions/datetime.rs
- core/vdbe/execute.rs
See no reason why it will be string
```
sqlite> select abs(unixepoch());
1752660221
turso> select abs(unixepoch());
┌────────────────────┐
│ abs (unixepoch ()) │
├────────────────────┤
│                0.0 │
└────────────────────┘
```
> make unixepoch to return i64

- core/storage/btree.rs
- core/storage/page_cache.rs
- core/storage/pager.rs
This PR fixes an issue with BTree upwards traversal logic where we would try to go up to a parent node in `next()` even though we are at the very end of the btree. This behavior can leave the cursor incorrectly positioned at an interior node when it should be at the right edge of the rightmost leaf.
This bug is masked on `main` by every table `insert()` (wastefully) calling `find_cell()`:
- `op_new_rowid` called, let's say the current max rowid is `666`. Cursor is left pointing at `666`.
- `insert()` is called with rowid `667`, cursor is currently pointing at `666`, which is incorrect.
- `find_cell()` does a binary search every time, and hence somewhat accidentally positions the cursor correctly _after_ `666` so that the insert goes to the correct place
in #1988, I am removing …
> btree: fix trying to go upwards when we are already at the end of the entire btree

- bindings/rust/src/lib.rs
- bindings/rust/tests/integration_tests.rs
- core/lib.rs
- core/storage/pager.rs
- core/vdbe/mod.rs
- tests/integration/common.rs
Cacheflush should only spill pages to WAL as non-commit frames, without checkpointing nor syncing.
- [docs](https://sqlite.org/c3ref/db_cacheflush.html)
- [sqlite3PagerFlush](https://github.com/sqlite/sqlite/blob/625d0b70febecb0864a81b2a047a961a59e8c17e/src/pager.c#L4669)
> Separate user-callable cacheflush from internal cacheflush logic

- core/storage/btree.rs
Aftermath of seek-related refactor in #2065, which you can read for background. The change in this PR is documented pretty well inline - if we receive a `TryAdvance` seek result when seeking after balancing, we need to - well - try to advance.
Closes #2116
> btree: fix post-balancing seek bug in delete path

- core/translate/emitter.rs
- core/translate/pragma.rs
- tests/integration/functions/test_cdc.rs
This PR renames CDC table column names to use "change"-centric terminology and avoid using `operation_xxx` column names.
Just a small refactoring to bring more consistency as `turso-db` refer to the feature as capture data **changes** - and there is no word operation here.
> rename operation_xxx to change_xxx to make naming more consistent

- core/ext/mod.rs
- core/lib.rs
- core/storage/pager.rs
- core/util.rs
- core/vdbe/execute.rs
We were copying the schema preemptively on each `Database::connect`, now the schema is shared until a change needs to be made by sharing a single `Arc` and mutating it via `Arc::make_mut`. This is faster as reduces memory usage.
> core: Copy-on-write for in-memory schema

- core/storage/btree.rs
- core/types.rs
- core/vdbe/execute.rs
- core/vdbe/sorter.rs
These are nearly always used together in some form, so it makes sense to colocate them, and it also makes many code paths simpler, as we don't separately pass `collations` and `key_sort_order` around
As a side effect, as the bitfield-based `IndexKeySortOrder` is removed, we now remove the arbitrary 64 column restriction for indexes, see e.g. this sim failure which fails to 64+ index columns (not sure why it uses an index if they are disabled):
https://github.com/tursodatabase/turso/actions/runs/16339391964/job/46158045158
> refactor/btree&vdbe: fold index key info (sort order, collations) into a single struct

- .github/workflows/rust.yml
- bindings/javascript/src/lib.rs
- bindings/wasm/lib.rs
- core/io/clock.rs
- core/io/generic.rs
- core/io/io_uring.rs
- core/io/memory.rs
- core/io/mod.rs
- core/io/unix.rs
- core/io/vfs.rs
- core/io/windows.rs
- core/storage/btree.rs
- core/storage/database.rs
- core/storage/pager.rs
- core/storage/sqlite3_ondisk.rs
- core/storage/wal.rs
- simulator/runner/cli.rs
- simulator/runner/clock.rs
- simulator/runner/env.rs
- simulator/runner/file.rs
- simulator/runner/io.rs
- simulator/runner/mod.rs
- tests/integration/query_processing/test_btree.rs
Closes #1998. Now I am queuing IO to be run at some later point in time. Also Latency for some reason is slowing the simulator a looot for some runs. 
This PR also adds a StateMachine variant in Balance as now `free_pages` is correctly an asynchronous function. With this change, we now need a state machine in the `Pager` so that `free_pages` can be reentrant. 
Lastly, I removed a timeout in `checkpoint_shutdown` as it was triggering constantly due to the slightly increased latency.
> Implement IO latency correctly in simulator

- core/translate/index.rs
We were passing the table columns' collations (all of them) in order, instead of the index column collations. Two issues:
1. This is wrong
2. There's now an assertion in the Sorter that actually panics if the length of sort order and collations is not the same
> translate/create index: fix wrong collations

- simulator/generation/property.rs
If we use `Assumption` here, the simulator just goes to the next property instead of halting here.
> Property `FaultyQuery` should fail if we encounter an error that is not expected

- core/Cargo.toml
- core/storage/sqlite3_ondisk.rs
- core/vdbe/execute.rs
- core/vdbe/sorter.rs
Closes #91
Replaces #1771 since the previous PR went stale and had too many conflicts.
The maximum size of the in-memory buffer is determined by the settings that configure the page-cache size.
In scope:
- Spill the in-memory buffer to a temporary file on disk if its size exceeds the threshold
- When iterating over the sorter, the next record is picked using heap populated from sorted chunk files
- Flushing the in-memory buffer and reading from chunk files occur asynchronously.
> Core: Introduce external sorting

- core/vdbe/mod.rs
- testing/rollback.test
- tests/integration/query_processing/mod.rs
- tests/integration/query_processing/test_transactions.rs
Fixes #2153. 
Not so sure if SQLite doesn't rollback in more cases, we should definitively check this out.
> Fix rollback for TxErrors

- simulator/runner/execution.rs
This helps e.g. when you hit some infinite loop
> sim: show seed in 'execute_interaction()' trace

- core/storage/btree.rs
Another fix extracted from running simulations on the #1988 branch.
When interior cell replacement happens as described in #2108, we use the `cursor.prev()` method to locate the largest key in the left subtree.
There was an error during backwards traversal in the `get_prev_record()` method where the parent's cell index was set as `i32::MAX` but not properly set to `cell_count + 1` (indicating that rightmost pointer has been visited).
This meant that if the child page we took the replacement cell from underflowed and needed balancing, the parent page would now have `i32::MAX` as its cell index and crash at the point where we determine based on the parent page which page is going to undergo balancing.
This PR fixes the issue by setting the cell index of the parent properly when visiting the …
> Fix parent page stack location after interior node replacement

- cli/app.rs
- cli/commands/args.rs
- cli/commands/mod.rs
- core/translate/expr.rs
- core/translate/optimizer/mod.rs
- core/translate/planner.rs
- testing/insert.test
- testing/select.test
- testing/tester.tcl
- testing/values.test
I ended up hitting #1974 today and wanted to fix it. I worked with Claude to generate a more comprehensive set of queries that could fail aside from just the insert query described in the issue. He got most of them right - lots of cases were indeed failing. The ones that were gibberish, he told me I was absolutely right for pointing out they were bad.
But alas. With the test cases generated, we can work on fixing it. The place where the assertion was hit, all we need to do there is return true (but we assert that this is indeed a string literal, it shouldn't be anything else at this point).
There are then just a couple of places where we need to make sure we handle double quotes correctly. We already tested for single quotes in a couple of places, but never for double quotes.
There is one …
> improve handling of double quotes

- core/vdbe/sorter.rs
Closes #2165 
The following sequence of events is possible:
- init_chunk_heap() called
- flush() gets called, and all chunks start writing to disk
- chunk A status is WriteComplete, so chunk.read() gets called on chunk A
- chunk A sets its status to WaitingForRead
- some other chunk B is still in WaitingForWrite status after flush()
- for this reason, init_chunk_heap() returns IOResult::IO
- init_chunk_heap() is called again
- we panic because chunk A is in WaitingForRead status
So - we just allow WaitingForRead status in init_chunk_heap() instead.
This panic was caught thanks to Pedro's IO latency enhancement to the sim!
> sorter: fix sorter panic on SortedChunkIOState::WaitingForRead

- COMPAT.md
- core/translate/pragma.rs
It is insane that SQLite even allows this.
They actually don't if "defensive mode" is enabled:
"It is always safe to read the schema_version, but changing the schema_version can cause problems. For this reason, attempts to change the value of schema_version are a silent no-op when defensive mode is enabled for a database connection.
Warning: Misuse of this pragma can result in database corruption."
We also update the compat table, which was not updated to reflect the read version of this pragma being implemented.
> implement write side of pragma schema_version

- Makefile
In Rust 1.84.0, the support for the named target `wasm32-wasi` was removed in favor of `wasm32-wasip1` ([Release Notes](https://releases.rs/docs/1.84.0/#compatibility-notes)).
I missed that in https://github.com/tursodatabase/turso/pull/1807.
I got the following error when I tried to run `make`:
```
> make 
Checking Rust version...
Rust version 1.88.0 is acceptable.
Checking wasm32-wasi target...
Installing wasm32-wasi target...
error: toolchain '1.88.0-aarch64-apple-darwin' does not support target 'wasm32-wasi'; did you mean 'wasm32-wasip1'?
note: you can see a list of supported targets with `rustc --print=target-list`
note: if you are adding support for a new target to rustc itself, see https://rustc-dev-guide.rust-lang.org/building/new-target.html
make: *** [check-wasm-target] Error 1 …
```
> use `wasm32-wasip1` target instead of `wasm32-wasi`

- core/lib.rs
- core/storage/page_cache.rs
Very useful in printing data structures containing databases, like maps
Example output:
Connecting to Database { path: "sq.db", open_flags: OpenFlags(1), db_state: "initialized", mv_store: "none", init_lock: "unlocked", wal_state: "present", page_cache: "( capacity 100000, used: 0 )" }
> implement Debug for Database

- core/storage/sqlite3_ondisk.rs
- core/vdbe/sorter.rs
Currently, each record header is decoded at least twice: once to determine the record size within the read buffer (in order to construct the `ImmutableRecord` instance), and again later when decoding the record for comparison. This redundant decoding can have a noticeable negative impact on performance when records are wide (eg. contain multiple columns).
This update modifies the (de)serialization format for sorted chunk files by prepending a record size varint to each record payload. As a result, only a single varint needs to be decoded to determine the record size, eliminating the need to decode the full record header during reads.
> Avoid redundant decoding of record headers when reading sorted chunk files

- README.md
Small README cleanup:
1. Updated the contribution guide and license link to point to the local CONTRIBUTING.md and LICENSE.md file instead of GitHub’s default page.
2. Linked each language in the bindings list to its respective subdirectory for easier navigation.
> doc: fix intra-repo links for contribution guide and license, and expand binding links

- tests/integration/common.rs
Turns out #2192 was just me implementing a test wrong -- `BEGIN` is ofc an alias for `BEGIN DEFERRED` so just executing `BEGIN` won't start a tx yet. In short: `tursodb` does what you'd expect under snapshot isolation, at least in this specific instance.
In any case, let's not waste the test -- I've now unignored it and fixed it.
> fix/test: fix and unignore incorrectly implemented test

- core/lib.rs
- tests/integration/query_processing/test_multi_thread.rs
- tests/integration/query_processing/test_write_path.rs
maybe_shared_wal's lock is held for a limited time increasing the chance
of initializing the shared wal twice.
>  core/lib: init_pager lock shared wal until filled 

- perf/clickbench/benchmark.sh
- perf/clickbench/run.sh
- enable indexes, otherwise it doesnt work at all
- rename limbo to tursodb
- use mode=list instead of mode=pretty for less bulky tursodb results
Closes #1925
> test/clickbench: fix clickbench

- core/schema.rs
- testing/all.test
- testing/alter_table.test
Closes #2186 
```git
commit 2095e5dde13ee7d089744304ff45d718ddd67db7 (HEAD -> fix-alter-table, origin/fix-alter-table, main)
Author: Jussi Saurio <jussi.saurio@gmail.com>
Date:   Tue Jul 22 11:12:02 2025 +0300
test/tcl: run alter_table.test in all.test
commit 58f98391d00ba3648a04142fb85e824e432d9361
Author: Jussi Saurio <jussi.saurio@gmail.com>
Date:   Tue Jul 22 11:11:50 2025 +0300
test/tcl: fix alter table test assertions and require index flag on some tests
commit 13d40c6a732590de93f1d284ca226a94271a1f39
Author: Jussi Saurio <jussi.saurio@gmail.com>
Date:   Tue Jul 22 11:11:08 2025 +0300
schema: fix extra whitespace in BTreeTable::from_sql
```
> Fix issues in alter table tests and fix a small error in BTreeTable::to_sql

- core/ext/mod.rs
- core/io/unix.rs
- core/lib.rs
- core/util.rs
- core/vdbe/execute.rs
When compiling with features disabled, there are lots of clippy warnings. This PR silences them.
For the utils file, I am using a bit of a hammer and just allowing unused stuff in the whole file. Due to the box of utilities nature of this file, it'll always be the case that things will be unused depending on the feature-set.
> silence clippy errors with features disabled

- core/types.rs
This PR truncates the Debug output of ImmutableRecord so that blobs and texts only show the first 20 bytes or chars respectively. Debugging gets much better when we don't print a huge blob or text a million times.
> types: less noisy Debug implementation for ImmutableRecord

- core/storage/pager.rs
The `balance_non_root` procedure can end up freeing a page if the pages to be balanced can fit the required combined number of cells in less pages, even if the page that triggered balancing is overfull. This can then free the originally overfull pages, leaving a non-zero `overflow_cells` on the in-mem representation of the page.
```rust
balance_non_root: page=305, overflow_cells=0
balance_non_root: page=304, overflow_cells=0
balance_non_root: page=302, overflow_cells=1
pre_edit_page(page=304, page_idx=0, new_cells=4, old_cells=1, cells_per_page_old=[1, 3, 9, 0, 0], cells_per_page_new=[4, 9, 9, 0, 0], cell_array_count=9)
edit_page start_old_cells=0 start_new_cells=0 number_new_cells=4 cell_array=9 end_old_cells=1 end_new_cells=4
pre_edit_page(page=305, page_idx=1, new_cells=4, old_cells=1, …
```
> Pager: clear overflow cells when freeing page

- core/types.rs
- core/vdbe/execute.rs
- tests/integration/fuzz/mod.rs
Fixes #2133
The SUM aggregate function was returning incorrect results when processing tables with mixed numeric and non-numeric values. According to SQLite documentation:
> "If any input to sum() is neither an integer nor a NULL, then sum() returns a floating point value" [*](https://sqlite.org/lang_aggfunc.html)
Now both SQLite and Turso yield the same output of 44.0.
--
I modified `Sum` to increment only for numeric values, skipping non-numeric values. However, if we have mixed numeric values or non-numeric values, we return a float output. Added a flag to keep track of it.
as pointed out by @FHaggs , If there are no non-NULL input rows then sum() returns NULL but total() returns 0.0. I decided to include it in this PR as well. Empty was such a natural test case.
> fix: SUM returns correct float for mixed numeric/non-numeric types & return value on empty set

- core/vdbe/sorter.rs
Before this update, the entire immutable record was **fully** deserialized **every** time it was compared in the sorter.
This PR extends the sorter with incremental deserialization of record keys, only when needed and only if they weren’t already deserialized in a previous iteration.
I hate that we panic on failed deserialization in `cmp`, but unfortunately, I can’t return `Result` as part of this interface. Looking for feedback around a better way to handle this.
Alternatively, I could store the deserialization error as part of `SortableImmutableRecord` and check it before returning the record in `next`, thereby deferring the error handling. The downside of this approach is that it complicates debugging, since the error will be completely decoupled from the place where it occurs.
> Deserialize keys only once when sorting immutable records

- core/translate/insert.rs
- testing/insert.test
This PR adds support for `INSERT` queries with explicit value for `rowid` column (not thought rowid alias):
```
turso> create table t(x, y, z);
turso> insert into t(rowid, x, y, z) values (10, 1, 2, 3);
turso> select rowid, * from t;
┌───────┬───┬───┬───┐
│ rowid │ x │ y │ z │
├───────┼───┼───┼───┤
│    10 │ 1 │ 2 │ 3 │
└───────┴───┴───┴───┘
```
> Explicit rowid insert

- perf/connection/limbo/src/main.rs
The current code includes creating the database object, which is slow.
Unfortunately the same cannot be done on the standard SQLite.
> measure only the time it takes to open the actual connection

- core/translate/schema.rs
The SetCookie opcode is used, among other things, to notify the transaction of schema changes. We are not issuing it on DropTable.
Without it, the transaction thinks the schema hasn't changed, and does not update the schema of the connection back to the database.
SQLite will, of course, issue it:
35    DropTable      0     0     0     foo            0
36    SetCookie      0     1     2                    0
Unfortunately I don't have a unit test that breaks with this, because the one that is supposed to break is having, let's put it this way, bigger problems.
> emit SetCookie after DropTable

- core/storage/pager.rs
- core/storage/wal.rs
- tests/integration/common.rs
SQLite behavior is: if another connection has modified the DB when a read tx starts, the connection beginning the transaction must clear its page cache due to the potentiality of there being stale versions of pages in it. Evidence of this here: https://github.com/sqlite/sqlite/blob/ded1959/src/pager.c#L3258-L3260 and here: https://github.com/sqlite/sqlite/blob/master/src/wal.c#L3368-L3370
In the future, we may want to do either:
1. a more granular invalidation logic for per-conn cache, or
2. a shared versioned page cache
But right now we must follow SQLite to make our current behavior not corrupt data
Closes #2248
> pager: Clear stale page cache if database changed

- core/storage/btree.rs
Closes #2241
When an index interior cell is deleted, it steals the leaf cell with the largest key in its left subtree, deletes the old interior cell and then replaces it with the stolen cell. This ensures the binary-search-tree aspect of the btree remains correct. However, this can cause a situation where both are true:
1. The leaf page is now UNDERFULL and must be rebalanced
2. The leaf's IMMEDIATE parent page is now OVERFULL and must be rebalanced
We simply didn't support the case where:
- Leaf page P is unbalanced and rebalancing starts on it
- Its immediate parent is ALSO unbalanced and _overflows_.
We had an assertion against this happening (see #2241)
Allow exactly 1 overflow cell in the parent under very particular conditions:
1. The parent page must be an index interior page
2. …
> btree/balance: support case where immediate parent page of unbalanced child page also overflows

- cli/app.rs
- cli/commands/import.rs
- core/lib.rs
- core/schema.rs
- core/storage/btree.rs
- core/storage/pager.rs
- core/vdbe/execute.rs
- testing/pragma.test
Closes: #1415
1. Removes database initialization from the `read_tx` function. 
2. Adds checks for database initialization when executing `.schema`, `.indexes`, `.tables` and `.import` commands, as they rely on `sqlite_schema` table.
I think we have another solution for the second issue: create the `sqlite_schema` table in `Schema` only during page1 initialization,  rather than during `Schema` initialization. 
This approach has the advantage of unifying the logic for the `sqlite_schema` table with other user tables when running `select` statements
- we still need to check error codes for commands like  `.schema`.  
- this approach may increase the complexity of the `pager` implementation. 
I'd like to hear your thoughts and feedback.
> Fix page_count pragma

- core/schema.rs
- core/translate/alter.rs
- core/translate/delete.rs
- core/translate/display.rs
- core/translate/expr.rs
- core/translate/index.rs
- core/translate/insert.rs
- core/translate/mod.rs
- core/translate/optimizer/mod.rs
- core/translate/plan.rs
- core/translate/planner.rs
- core/translate/pragma.rs
- core/translate/schema.rs
- core/translate/select.rs
- core/translate/update.rs
- core/util.rs
- core/vdbe/builder.rs
- core/vdbe/execute.rs
- simulator/generation/expr.rs
- simulator/generation/predicate/binary.rs
- simulator/model/query/predicate.rs
- simulator/model/query/select.rs
- vendored/sqlite3-parser/src/lexer/sql/test.rs
- vendored/sqlite3-parser/src/parser/ast/fmt.rs
- vendored/sqlite3-parser/src/parser/ast/mod.rs
- vendored/sqlite3-parser/src/parser/parse.y
- vendored/sqlite3-parser/third_party/lemon/lempar.rs
Closes: #1947 
This PR replaces the `Name(pub String)` struct with a `Name` enum that explicitly models how the name appeared in the source either as an unquoted identifier (`Ident`) or a quoted string (`Quoted`).
In the process, the separate `Id` wrapper type has been coalesced into the `Name` enum, simplifying the AST and reducing duplication in identifier handling logic.
While this increases the size of some AST nodes (notably `yyStackEntry`).
cc: @levydsa
> parser: Distinguish quoted identifiers and unify Id into Name enum

- core/lib.rs
- core/util.rs
- core/vdbe/execute.rs
- tests/integration/functions/test_wal_api.rs
`maybe_reparse_schema` function introduced in the #2246 was incorrect as it didn't update `schema_version` for internal schema representation and basically updated only schema for connection which called `maybe_reparse_schema`.
This PR fixes this issue by reading schema and cookie value within a single transaction and updating both schema content and its version for internal representation.
> Fix schema reparse logic

- core/types.rs
- core/vdbe/execute.rs
This refactors AggContext::Sum by removing the extra bool flag and simplifying type handling during aggregation:
> Simplify sum() aggregation logic

- COMPAT.md
Honestly, I didn't even notice we had a compat entry for it because it seems so trivial. But it was done as part of ATTACH.
> mark detach as supported

- core/types.rs
- core/vdbe/execute.rs
- tests/integration/fuzz/mod.rs
This PR updates the `SUM` aggregation logic to follow the [Kahan–Babushka–Neumaier summation algorithm](https://en.wikipedia.org/wiki/Kahan_summation_algorithm), consistent with SQLite’s implementation. It improves the numerical stability of floating-point summation.This fixes issue #2252 . I added a fuzz test to ensure the compatibility of the implementations
I also fixed the return types for `SUM` to match SQLite’s documented behavior. This was previously discussed in [#2182](https://github.com/tursodatabase/turso/pull/2182), but part of the logic was later unintentionally overwritten by [#2265](https://github.com/tursodatabase/turso/pull/2265).
I introduced two helper functions, `apply_kbn_step` and `apply_kbn_step_int`, in `vbde/execute.rs` to handle floating-point and integer …
> Fix sum() to follow the SQLite semantics

- core/storage/wal.rs
- sqlite3/tests/compat/mod.rs
I know I have #2179 and now #2278 open both working on checkpointing, but I discovered during async IO benchmarks that once we hit `should_checkpoint` (there are greater than 1000 frames in the WAL), we will trigger checkpoint on cache flush every single write, and since we don't update `nbackfills` in the case that everything was backfilled, every checkpoint will backfill every single frame to the db file :skull:
At least this can be reviewed+merged faster and easier. 
This also fixes the return value of `pragma wal_checkpoint;` to match sqlite. 
Sqlite returns the # of possible frames (`shared.max_frame - shared.nbackfills`, and then the number of frames we successfully checkpointed `ongoing_checkpoint.max_frame - ongoing_checkpoint.min_frame + 1`)
If `pragma wal_checkpoint;` is called …
> Stop checkpointing the entire WAL after every write when wal frame size > threshold

- core/translate/index.rs
I am running into issues when creating indexes and made this PR with a possible fix.
`Error: cannot use expressions in CREATE INDEX`
In my setup, running on `wasm32-unknown-unknown` (not in the browser), I can reproduce the issue like this. First, creating a table:
```rust
conn.execute(
r#"
CREATE TABLE IF NOT EXISTS users (
name TEXT,
created DATETIME DEFAULT CURRENT_TIMESTAMP
)
"#,
(),
)
.await
.unwrap();
```
Here, creating an index for that table:
```rust
conn.execute(
"CREATE INDEX IF NOT EXISTS idx_users_name ON users(name)",
(),
)
.await
.unwrap();
```
I had a closer look at `resolve_sorted_columns`. In this bit, it checks the expression of the sorted column. 
https://github.com/tursodatabase/turso/blob/a2a31a520ff6e228a00e785026dae19b5b2cced7/core/translate/index.rs#L252-L257 …
> core/translate: Handle Expr::Id in `CREATE INDEX`

- core/translate/plan.rs
```
Execute `SELECT count() FROM users`/limbo_execute_select_count
time:   [15.635 µs 15.676 µs 15.730 µs]
change: [-96.011% -95.991% -95.972%] (p = 0.00 < 0.05)
```
Closes #2313
> perf: fix logic error in is_simple_count()

- .github/workflows/rust.yml
- bindings/javascript/src/lib.rs
- bindings/rust/src/lib.rs
- bindings/wasm/lib.rs
- core/io/generic.rs
- core/io/io_uring.rs
- core/io/memory.rs
- core/io/mod.rs
- core/io/unix.rs
- core/io/vfs.rs
- core/io/windows.rs
- core/storage/btree.rs
- core/storage/database.rs
- core/storage/pager.rs
- core/storage/sqlite3_ondisk.rs
- core/storage/wal.rs
- core/types.rs
- core/vdbe/execute.rs
- core/vdbe/sorter.rs
- simulator/runner/file.rs
- simulator/runner/io.rs
- tests/integration/query_processing/test_btree.rs
Changes a couple of function signatures to return `Completion`. Also, I changed `Completion` to be internally `Arc` to abstract the `Arc` implementation detail, and to be able to attach a `#[must_use]` to the `Completion` struct, so that cargo check can show us where we are not tracking completions in the code. I also attached a `#[must_use]` to `IOResult` so that we can see the places that we are not propagating or waiting for I/O, demonstrating locations where functions should be reentrant and are not. 
Also, while we are with this refactor in progress I want to relax the Clippy CI lint on unused_variables.
> Change function signatures to return IO Completions

- COMPAT.md
- core/function.rs
- core/translate/expr.rs
- core/types.rs
- core/vdbe/execute.rs
- core/vector/mod.rs
- core/vector/vector_types.rs
Closes: #2323 
This PR adds support for two new vector functions:
* vector_concat(x, y) – Concatenates two vectors of the same type.
* vector_slice(x, start_index, end_index) – Extracts a subvector from the input vector.
Notes:
* Negative start_index or end_index is not supported
> Add vector_concat and vector_slice support

- core/vdbe/execute.rs
- tests/integration/fuzz/mod.rs
closes: #2101
Refactors exec_concat_ws to skip null and blob arguments instead of inserting separators for them. Also adds a fuzz test.
> Fix concat_ws to match sqlite behavior

- COMPAT.md
$ egrep -rI "define OP" sqlite3.c | grep Cookie
sqlite3.c:#define OP_ReadCookie     99
sqlite3.c:#define OP_SetCookie     100
> remove non-existent opcode

- core/storage/wal.rs
Closes #2361 (already been reopened once)
Only `max_frame` check is not enough -- connections can have the same max frame but the DB has still changed. Compare checksums and checkpoint sequences too.
> fix/wal: make db_changed check detect cases where max frame happens to be the same

- core/lib.rs
- core/storage/pager.rs
- core/storage/wal.rs
Closes #2363 
The following sequence of actions is possible:
```
Some committed frames already exist in the WAL. shared.pages_in_frames.len() > 0.
Brand new connection does this:
BEGIN 
^-- deferred, no read tx started yet, so its `self.start_pages_in_frames` is `0`
because it's a brand new WalFile instance
ROLLBACK   <-- calls `wal.rollback()` and truncates `shared.pages_in_frames` to length `0`
PRAGMA wal_checkpoint();
^-- because `pages_in_frames` is empty, it doesnt actually
checkpoint anything but still sets shared.max_frame to 0, causing effectively data loss
```
- Only call `wal.rollback()` for write transactions
- Set `start_pages_in_frames` correctly so that this doesn't happen even if a regression starts calling `wal.rollback()` again
> fix/wal: only rollback WAL if txn was write + fix start state for WalFile

- COMPAT.md
* Affinity is already present
* InsertInt is not a thing
* String is never generated directly, it is a second-execution optimization for String8 so the size doesn't have to be recomputed, but we always store the size anyway.
> more compat police

- core/benches/benchmark.rs
Resolves #2312.
```
Open/Connect/limbo_schema/
time:   [11.669 ms 11.683 ms 11.700 ms]
change: [-4.3350% -1.8204% +0.2040%] (p = 0.11 > 0.05)
No change in performance detected.
Found 9 outliers among 100 measurements (9.00%)
5 (5.00%) high mild
4 (4.00%) high severe
Open/Connect/sqlite_schema/
time:   [10.479 ms 10.693 ms 10.969 ms]
change: [+0.3783% +2.4616% +5.2808%] (p = 0.02 < 0.05)
Change within noise threshold.
Found 8 outliers among 100 measurements (8.00%)
3 (3.00%) high mild
5 (5.00%) high severe
```
> Force Sqlite to parse schema on connection benchmark

- core/storage/wal.rs
The following sequence of actions is possible:
```sql
-- TRUNCATE checkpoint fails during WAL restart,
-- but OngoingCheckpoint.state is still left at Done for conn 0
Connection 0(op=23): PRAGMA wal_checkpoint(TRUNCATE)
Connection 0(op=23) Checkpoint TRUNCATE: OK: false, wal_page_count: NULL, checkpointed_count: NULL
-- TRUNCATE checkpoint succeeds for conn 1
Connection 1(op=26): PRAGMA wal_checkpoint(TRUNCATE)
Connection 1(op=26) Checkpoint TRUNCATE: OK: true, wal_page_count: 0, checkpointed_count: 0
-- Conn 0 now does a PASSIVE checkpoint, and immediately thinks
-- it's in the Done state, and thinks it checkpointed 17 frames.
-- since mode is PASSIVE, it now thinks both the WAL and the DB have those 17 frames
-- so the first 17 frames of the WAL can be ignored from now on.
Connection …
```
> fix/wal: reset ongoing checkpoint state when checkpoint fails

- .github/workflows/rust.yml
- bindings/python/src/lib.rs
- bindings/rust/Cargo.toml
- cli/app.rs
- core/translate/alter.rs
- core/translate/delete.rs
- core/translate/insert.rs
- core/translate/schema.rs
- core/translate/update.rs
- perf/clickbench/benchmark.sh
- perf/clickbench/run.sh
- perf/tpc-h/run.sh
- stress/Cargo.toml
- testing/agg-functions.test
- testing/alter_table.test
- testing/create_table.test
- testing/delete.test
- testing/drop_index.test
- testing/drop_table.test
- testing/groupby.test
- testing/insert.test
- testing/join.test
- testing/orderby.test
- testing/rollback.test
- testing/select.test
- testing/subquery.test
- testing/update.test
- testing/where.test
Enables indexes by default in Rust and Python bindings + the CLI, while leaving the feature flag in place.
Comments out a single ALTER TABLE test that fails due to #2390
> Enable indexes by default

- core/translate/alter.rs
- testing/alter_table.test
Close #2390
Single quotes inside a string literal have to be doubled
> Single quotes inside a string literal have to be doubled in `translate_alter_table`

- core/vdbe/execute.rs
- core/vdbe/insn.rs
- core/vdbe/mod.rs
This will save some work when yielding to IO. Previously, on every invocation, if the record was a packed record, we parsed it and iterated through the values to check for nulls. Now, the pre-seeking work is done only once.
> use state machine for NoConflict opcode

- bindings/rust/src/lib.rs
- bindings/rust/src/rows.rs
- bindings/rust/src/transaction.rs
- bindings/rust/tests/integration_tests.rs
- core/error.rs
- core/types.rs
While working on #2151 I saw myself forced to do things like:
```rust
assert_eq!(
6,
*result
.next()
.await?
.unwrap()
.get_value(0)?
.as_integer()
.unwrap()
);
```
Just to get a simple value from a row, now with this PR users can just do: 
```rust
assert_eq!(6, result.get::<i32>(0)?);
```
(Thanks libsql devs, this is so much better!)
> bindings/rust: Enhance API by removing verbosity

- core/storage/pager.rs
This should be safe to do as:
1. page cache is private per connection
2. since this connection wrote the flushed pages/frames, they are up to date from its perspective
3. multiple concurrent statements inside one connection are not snapshot-transactional even in sqlite
> perf/pager: dont clear page cache on commit

- core/storage/btree.rs
- core/vdbe/execute.rs
When we get a new rowid using `op_new_rowid()`, we move to the end of the btree to look at what the maximum rowid currently is, and then increment it by one.
This requires a btree seek.
If we were already on the rightmost page, this is a lot of unnecessary work, including potentially a few page reads from disk (although to be fair the ancestor pages are very likely to be in cache at this point.)
Cache the rightmost page id whenever we enter it in `move_to_rightmost()`, and invalidate it whenever we do a balancing operation.
```sql
Insert rows in batches/limbo_insert_1_rows
time:   [23.333 µs 27.718 µs 35.801 µs]
change: [-7.7924% +0.8805% +12.841%] (p = 0.91 > 0.05)
No change in performance detected.
Insert rows in batches/limbo_insert_10_rows
time:   [38.204 µs 38.381 µs 38.568 µs] …
```
> perf/btree: skip seek in move_to_rightmost() if we are already on rightmost page

- bindings/rust/src/lib.rs
- core/lib.rs
- core/storage/pager.rs
- core/storage/sqlite3_ondisk.rs
- core/storage/wal.rs
- core/types.rs
- packages/turso-sync/src/database_inner.rs
- packages/turso-sync/src/sync_server/test.rs
- sqlite3/src/lib.rs
- tests/integration/functions/test_wal_api.rs
This PR extends raw WAL API with few methods which will be helpful for offline-sync:
1. `try_wal_watermark_read_page` - try to read page from the DB with given WAL watermark value\
* Usually, WAL max_frame is set automatically to the latest value (`shared.max_frame`) when transaction is started and then this "watermark" is preserved throughout whole transaction
* New method allows to simulate "read from the past" by controlling frame watermark explicitly
* There is an alternative to implement some API like `start_read_session(frame_watermark: u64)` - but I decided to expose just single method to simplify the logic and reduce "surface" of actions which can be executed in this "controllable" manner
* Also, for simplicity, now `try_wal_watermark_read_page` always read data from disk and …
> extend raw WAL API with few more methods

- core/storage/btree.rs
- core/storage/sqlite3_ondisk.rs
Change original code from doing a full copy of the original buffer to modify the buffer in-place using a temporary vector with offsets.
> Update defragment page to defragment in-place

- core/io/mod.rs
- core/storage/sqlite3_ondisk.rs
After #2258, we no longer need to clone/deep copy `PageContent` or `Buffer`.
We can remove the implementation to make any copying of page data explicit.
> Remove Clone impl for Buffer and PageContent

- bindings/javascript/src/lib.rs
- core/io/generic.rs
- core/io/io_uring.rs
- core/io/memory.rs
- core/io/mod.rs
- core/io/unix.rs
- core/io/vfs.rs
- core/io/windows.rs
- core/lib.rs
- core/storage/btree.rs
- core/storage/database.rs
- core/storage/page_cache.rs
- core/storage/pager.rs
- core/storage/sqlite3_ondisk.rs
- core/storage/wal.rs
- core/vdbe/sorter.rs
- simulator/runner/file.rs
- tests/integration/query_processing/test_btree.rs
We are doing unsafe mut borrowing in `PageContent` currently, and when new BufferPool is merged, it will be all pointers into an arena anyway. We just need to be sure to clone the Arc and reference the buffers in the completion callbacks so they are ensured to live for async IO.
naturally in true spirit of all my previous PR's, I needed to introduce one while another is open that causes an absurd amount of conflicts.
> Remove RefCell from Buffer in IO trait methods and PageContents

- core/storage/btree.rs
- core/types.rs
We currently clone `WriteState` on every iteration of `insert_into_page()`,
presumably for _Borrow Checker Reasons (tm)_.
There was a bug in `WriteState::Insert` handling where if `fill_cell_payload()`
returned IO, the `fill_cell_payload_state` was not updated in
`write_info.state`, leading to an infinite loop of allocating new pages. Further, the `new_payload` vector was also always deep-cloned.
Update the state if `fill_cell_payload()` returns IO. Because of `WriteState` cloning we also need to `Arc<Mutex>` wrap the vector so that the underlying data buffer doesn't get cloned the next time `WriteState` gets cloned, since `fill_cell_payload` relies on raw pointers to work. Left a couple of prominent FIXMEs about this.
This bug was surfaced by, but not caused by, …
> core/btree: fix re-entrancy bug in insert_into_page()

- core/storage/btree.rs
Removes cloning of `WriteState` in `balance_non_root()` and removes the `Clone` implementation from `WriteState`.  Not only is it unnecessary to clone the state, but even having the `Clone` implementation available is a real regression risk in `insert_into_page()` as it will deep clone vectors that we require stable raw pointers to in `fill_cell_payload()`
In removing the cloning of `WriteState` in `balance_non_root()`, this replaces the `next_write_state` logic with a plain loop, which ends up looking like a lot of changes, but it's really not. Main things that were changed:
- Loop and mutate state instead of create new state and return
- Make `WriteInfo` an `Option` in `WriteState` for ergonomics so it can be `.take()`:n instead of `.clone()`:d
- Clone a `Rc<Pager>` in …
> refactor/btree: don't clone WriteState during balancing

- core/translate/emitter.rs
- core/translate/index.rs
- core/translate/insert.rs
- core/translate/main_loop.rs
- core/translate/mod.rs
- core/translate/pragma.rs
- core/translate/schema.rs
- packages/turso-sync/src/database_tape.rs
- tests/integration/functions/test_cdc.rs
This PR emit CDC entries as changes in `sqlite_schema` table for DDL statements: `CREATE TABLE` / `CREATE INDEX` / etc.
The logic is a bit tricky as under the hood `turso` can do some implicit DDL operations like:
1. Creating auto-indexes in case of `CREATE TABLE`
2. Deletion of all attached indices in case of `DROP TABLE`
```
turso> PRAGMA unstable_capture_data_changes_conn('full');
turso> CREATE TABLE t(x, y, z UNIQUE, q, PRIMARY KEY (x, y));
turso> CREATE INDEX t_xy ON t(x, y);
turso> CREATE TABLE q(a, b, c);
turso> ALTER TABLE q DROP COLUMN b;
turso> SELECT
change_id, 
id,
change_type, 
table_name,
bin_record_json_object(table_columns_json_array(table_name), before) AS before,
bin_record_json_object(table_columns_json_array(table_name), after) AS after
FROM turso_cdc; …
```
> cdc: emit entries for schema changes

- core/benches/benchmark.rs
- core/translate/alter.rs
- core/vdbe/execute.rs
- core/vdbe/explain.rs
- core/vdbe/insn.rs
**86%** performance improvement. We are **25x** faster than SQLite. 
```
ALTER TABLE _ DROP COLUMN _`/limbo_drop_column/
time:   [1.8821 ms 1.8929 ms 1.9047 ms]
change: [-86.850% -86.733% -86.614%] (p = 0.00 < 0.05)
Found 5 outliers among 100 measurements (5.00%)
3 (3.00%) high mild
2 (2.00%) high severe
Benchmarking `ALTER TABLE _ DROP COLUMN _`/sqlite_drop_column/: Warming up for 3.0000 s
`ALTER TABLE _ DROP COLUMN _`/sqlite_drop_column/
time:   [46.227 ms 46.258 ms 46.291 ms]
change: [-1.3202% -1.0505% -0.8109%] (p = 0.00 < 0.05)
Change within noise threshold.
Found 15 outliers among 100 measurements (15.00%)
10 (10.00%) high mild
5 (5.00%) high severe
```
> Direct schema mutation – add `DropColumn` instruction

- core/ext/dynamic.rs
- core/ext/mod.rs
- core/ext/vtab_xconnect.rs
- core/vtab.rs
- extensions/core/src/vtabs.rs
- macros/src/ext/vtab_derive.rs
Closes #2478 
```console
turso>create table t(a,b);
turso>insert into t select 1,2 from generate_series(1,20);
turso>create index idxa on t(a);
turso>create index idxb on t(b);
```
The issue was the `turso_ext::Conn` pointer was stored on the `VirtualTable`, which lives longer than necessary and the underlying core `Connection` is not guaranteed pinned. Moving the `turso_ext::Conn` on to the cursor fixes this issue because it's independent of the Schema.
This also fixes the issue that comes up when that issue is fixed, and some of the relevant code for this hadn't been updated when other surrounding changes had been made.
> Fix segfault on schema update for virtual tables

- sqlite3/include/sqlite3.h
- sqlite3/src/lib.rs
- sqlite3/tests/Makefile
- sqlite3/tests/compat/mod.rs
- sqlite3/tests/sqlite3_tests.c
Add support for more of the SQLite C API.
Bind functions:
* bind_parameter_count
* bind_parameter_name
* bind_null
* bind_int
* bind_int64
* bind_double
Column functions:
* column_count
* column_name
* column_int
* column_double
* last_insert_rowid
> SQLite C API improvements: add basic bind and column functions

- bindings/javascript/src/lib.rs
- cli/app.rs
- cli/commands/args.rs
- cli/commands/mod.rs
- cli/input.rs
- core/io/mod.rs
- core/lib.rs
- core/storage/database.rs
- testing/cli_tests/cli_test_cases.py
- testing/cli_tests/test_turso_cli.py
This PR adds support for the  `.clone file.db` sqlite3 CLI command
> Add .clone CLI command to copy database files

- core/storage/btree.rs
- core/types.rs
Built on top of #2502 
```rust
/// Cached value of the usable space of a BTree page, since it is very expensive to call in a hot loop via pager.usable_space().
/// This is OK to cache because both 'PRAGMA page_size' and '.filectrl reserve_bytes' only have an effect on:
/// 1. an uninitialized database,
/// 2. an initialized database when the command is immediately followed by VACUUM.
usable_space_cached: usize,
```
> Btree cache usable space

- core/translate/main_loop.rs
- testing/join.test
This fix ensures that `WHERE` conditions are emitted after the `LEFT JOIN` match flag is set, so rows from the right table are properly filtered, even when they are `NULL` due to the outer join.
Previously, the query below would return rows where `products.price` was `NULL`:
```sql
SELECT users.id, price
FROM users
LEFT JOIN products ON users.id = products.id
WHERE products.price IS NOT NULL;
```
> Evaluate WHERE conditions after LEFT JOIN

- core/storage/sqlite3_ondisk.rs
- core/storage/wal.rs
This PR rewrites the `LimboRwLock`, which previously used 3 separate `AtomicU32` values to store the lock state, in favor of a single, packed, cache friendly `AtomicU64`.
The previous impl has some complexity and rather hairy edge cases/issues because we are not updating the lock state together. This PR also adjusts it to use `Acquire`/`Release` for `load`/`store` operations, and tries to improve the API of using the locks.
> Reimplement LimboRwLock in the WAL

- core/translate/emitter.rs
- core/translate/index.rs
- core/translate/schema.rs
- core/vdbe/execute.rs
- core/vdbe/explain.rs
- core/vdbe/insn.rs
When building views (soon), it will be important to know which table is being deleted. Getting from the cursor id is very cumbersome.
What we are doing here is symmetrical to op_insert, and sqlite also passes table information in one of the registers (p4)
> Add table name to the delete bytecode

- sqlite3/include/sqlite3.h
- sqlite3/src/lib.rs
- sqlite3/tests/compat/mod.rs
- sqlite3/tests/sqlite3_tests.c
Add support for more of the SQLite C API.
Bind functions:
- sqlite3_bind_text (with destructor callback)
- sqlite3_bind_blob
Column functions:
- sqlite3_column_text
- sqlite3_column_blob
- sqlite3_column_bytes
> SQLite C API improvements: add bind_text and bind_blob

- COMPAT.md
- core/pragma.rs
- core/storage/pager.rs
- core/translate/pragma.rs
- vendored/sqlite3-parser/src/parser/ast/mod.rs
Implements `PRAGMA freelist_count` to return the current number of free pages in the database.
> Add support for PRAGMA freelist_count

- core/translate/emitter.rs
- core/vdbe/execute.rs
- core/vdbe/insn.rs
- core/vdbe/mod.rs
1. Introduce state machines to insert and delete to make sure IO is handled properly
2. When `rowid` is changed in `UPDATE`, it is handled as a combination of delete and insert, so `op_insert` doesn't need to update the incremental view with the deleted old column since the preceding `op_delete` instruction should already do it.
> Fix view processing in the VDBE

- core/lib.rs
- core/translate/alter.rs
- core/translate/emitter.rs
- core/translate/index.rs
- core/translate/insert.rs
- core/translate/mod.rs
- core/translate/plan.rs
- core/translate/pragma.rs
- core/translate/schema.rs
- core/translate/update.rs
- packages/turso-sync-engine/src/database_sync_operations.rs
- packages/turso-sync-engine/src/database_tape.rs
- packages/turso-sync-engine/src/types.rs
- tests/integration/functions/test_cdc.rs
- tests/integration/query_processing/test_multi_thread.rs
Add support for schema changes and granular updates in the `DatabaseTape` and turso-sync-engine
Now, schema changes made locally will be replicated to the remote too.
Also, `UPDATE`s made locally will touch only changed columns (before we did `DELETE` + `INSERT` which can overwrite non-conflicting changes from another device to the same row).
Note, that schema changes replication for now can be pretty dangerous, as we can't extract proper schema at some moment in time from turso_cdc and always use latest schema columns. This means that it's better to avoid `ALTER TABLE ...` to be executed locally, but basic DDL like `CREATE TABLE / CREATE INDEX / DROP TABLE / DROP INDEX` will work fine (as columns only appear/disappear for schema in this case).
> turso-sync: support updates and schema changes

- core/types.rs
- core/vdbe/execute.rs
Mainly the performance impact here comes from removing some unnecessary checks and inlining `read_integer_fast()` directly into `op_column()`, but I also added some fiddly nano-optimizations for fun
On main, we are roughly 3.4x slower than sqlite on `SELECT * FROM users LIMIT 100`, and here we are roughly 3.2x slower, which ain't much, but it's honest work.
A more impactful optimization, but a much more annoying refactor, would be #2304
> perf/btree: optimize op_column

- core/lib.rs
- core/mvcc/database/mod.rs
- core/storage/btree.rs
- core/storage/pager.rs
- core/vdbe/execute.rs
- core/vdbe/mod.rs
- tests/integration/common.rs
- tests/integration/query_processing/test_multi_thread.rs
We have to update the Transaction State before checking for the Schema Cookie so that we can rollback the transaction later on correctly.
Closes #2535
> Reprepare fix on write statement

- cli/app.rs
Resolves issue #1833.
**Before:**
**After:**
> Reset interrupt count each time a new line is entered in CLI

- core/lib.rs
- core/storage/wal.rs
- core/vdbe/execute.rs
- packages/turso-sync-engine/src/database_sync_engine.rs
- packages/turso-sync-engine/src/database_sync_operations.rs
- packages/turso-sync-engine/src/database_tape.rs
This PR fixes few issues in turso-sync-engine implementation:
1. One step of `pull` implementation works like this:
a. Start write WAL session
b. Revert local changes in WAL
c. Replay WAL frames from remote DB
d. Replay WAL frames produced by local changes applied to the remote DB copy (`synced`)
My initial thinking was that by executing step (d) we will get the same schema as before (with same schema cookie) and everything will be fine. With more deep thinking we can see that it's not fine - as after step (d) tables created locally can change their root pages (if they were created locally, for example) - and DB will have "broken" schema
2. Sync engine execute few SQL statements and do not run them to completion - which basically created "orphaned" locks
In order to fix (1) I decided to …
> turso-sync: fix schema bug

- core/storage/wal.rs
- packages/turso-sync-engine/src/database_sync_engine.rs
- packages/turso-sync-engine/src/database_sync_operations.rs
- packages/turso-sync-engine/src/test_sync_server.rs
remote protocol can require client to perform checkpoint of the WAL. This PR supports that need in the sync-engine implementation
> turso-sync: support checkpoint

- core/incremental/view.rs
- core/translate/mod.rs
- core/translate/view.rs
- vendored/sqlite3-parser/src/parser/ast/fmt.rs
- vendored/sqlite3-parser/src/parser/ast/mod.rs
- vendored/sqlite3-parser/src/parser/parse.y
We will implement normal SQLite-style view-as-an-alias for compatibility, and will call our incremental views materialized views.
> move our dbsp-based views to materialized views

- Cargo.lock
- core/io/memory.rs
- core/lib.rs
- core/mvcc/database/mod.rs
- core/storage/pager.rs
- core/storage/wal.rs
- core/vdbe/mod.rs
- packages/turso-sync-engine/src/database_sync_engine.rs
- packages/turso-sync-engine/src/database_sync_operations.rs
- packages/turso-sync-engine/src/lib.rs
- packages/turso-sync-engine/src/test_context.rs
- sqlite3/src/lib.rs
This PR change semantic of `wal_disable_checkpoint` flag and make it disable only "automatic" checkpoint behaviour which at the moment includes:
1. Checkpoint on shutdown
2. Checkpoint when WAL reach certain size
sync-engine needs checkpoint to be in full control but it also will issue `TRUNCATE` checkpoint at some certain moments of time - so complete disablement of checkpoints will not suffice.
> disable checkpoint: adjust semantic

- Makefile
- core/vdbe/execute.rs
- scripts/limbo-sqlite3
- testing/materialized_views.test
The op_insert function was incorrectly trying to capture an "old record" for fresh INSERT operations when a table had dependent materialized views. This caused a "Cannot delete: no current row" error because the cursor wasn't positioned on any row for new inserts.
The issue was introduced in commit f38333b3 which refactored the state machine for incremental view handling but didn't properly distinguish between:
- Fresh INSERT operations (no old record exists)
- UPDATE operations without rowid change (old record should be captured)
- UPDATE operations with rowid change (already handled by DELETE)
This fix checks if cursor.rowid() returns a value before attempting to capture the old record. If no row exists (fresh INSERT), we correctly set old_record to None instead of erroring out.
I am …
> fix: Handle fresh INSERTs in materialized view incremental maintenance

- cli/app.rs
- core/storage/pager.rs
Sequential is very rarely actually needed, we can very safely use Acquire / Release for loads/stores, and some of these aren't guarding anything and can use Relaxed.
> Refactor: atomic ordering

- core/io/mod.rs
- core/lib.rs
- core/storage/buffer_pool.rs
- core/storage/page_cache.rs
- core/vdbe/execute.rs
There are several problems with our current statically allocated `BufferPool`.
1. You cannot open two databases in the same process with different page sizes, because the `BufferPool`'s `Arena`s will be locked forever into the page size of the first database. This is the case regardless of whether the two `Database`s are open at the same time, or if the first is closed before the second is opened.
2. It is impossible to even write Rust tests for different page sizes because of this, assuming the test uses a single process.
Make `Database` own `BufferPool` instead of it being statically allocated, so this problem goes away.
Note that I didn't touch the still statically-allocated `TEMP_BUFFER_CACHE`, because it should continue to work regardless of this change. It should only be a problem …
> Use BufferPool owned by Database instead of a static global

- bindings/javascript/src/lib.rs
- core/lib.rs
- core/storage/btree.rs
- core/storage/database.rs
- core/storage/pager.rs
- core/storage/sqlite3_ondisk.rs
- core/storage/wal.rs
- core/translate/pragma.rs
- core/vdbe/execute.rs
- tests/integration/pragma.rs
Closes #2555 
The main problem we had with the current implementation of `init_pager()` was that the WAL header was eagerly allocated and written to disk with a page size, and a potential already-set page size on an initialized database was not checked. Given this scenario:
- Initialized database with e.g. page size 512 but no WAL
- Tursodb connects to DB
It would not check the database file for the page size and instead would initialize the WAL header with the default 4096 page size, plus initialize the `BufferPool` similarly with the wrong size, and then panic when reading pages from the DB, expecting to read `4096` instead of `512`, as demonstrated in the reproduction of #2555.
1. Add `Database::read_page_size_from_db_header()` method that can be used in the above cases
2. Initialize …
> Fix non-4096 page sizes

- core/translate/optimizer/mod.rs
- core/translate/plan.rs
Closes #2598
Forbids using an index as the iteration cursor for an `UPDATE` statement unless either of these is true:
1. The index is not affected by the `UPDATE` statement
2. The search condition on the index is guaranteed to return a maximum of 1 row, so no iteration will happen
I have created a follow-up issue about handling this a bit better: https://github.com/tursodatabase/turso/issues/2600
> Fix UPDATE: Do not use an index for iteration if that index is going to be updated

- simulator/generation/query.rs
we spend a shitload of time doing very complex selects in the simulator, and i'm not sure there has been a lot of gain from them. using up a lot of the runtime of a simulator run on these can mask other issues.
> sim: reduce frequency of compound selects and complex joins

- core/io/vfs.rs
- extensions/core/src/lib.rs
- extensions/core/src/vfs_modules.rs
- extensions/tests/src/lib.rs
- macros/src/ext/vfs_derive.rs
bringing #1127 back to life, except better because this doesn't add Tokio as a dependency for extension lib just for tests.
> Revive async io extension PR

- bindings/javascript/src/lib.rs
- cli/app.rs
- cli/input.rs
- core/io/mod.rs
- core/lib.rs
- core/storage/database.rs
- testing/cli_tests/cli_test_cases.py
Closes #2588 
SQLite internally implements `.clone` by doing something like piping `.dump` into a new connection to a database attached to the file you want. This PR implements that by adding an `ApplyWriter` that implements `std::fmt::Write`, and refactors our current `.dump` plumbing to work with any `Write` interface, so we can `.dump` to stdout or `.dump` to a new connection, therefore cloning the database.
> Properly implement `.clone` CLI command

- simulator/generation/predicate/binary.rs
- simulator/generation/predicate/mod.rs
- simulator/generation/predicate/unary.rs
- simulator/generation/query.rs
- simulator/model/query/predicate.rs
- simulator/model/query/select.rs
- simulator/model/table.rs
#2609 fixed compound selects incorrectly, introducing another bug: now the sim can SELECT a different number of columns per subselect, which is illegal. this PR forces the sim to select the same number of cols per subselect.
Depends on #2614 , otherwise the sim constantly fails whenever it decides to do a compound select with DISTINCT.
Closes #2611 
The simulator has a construct called `JoinTable` which is really a `JoinContext` that includes all the columns from the so-far joined tables, so that the next table to be joined can refer to columns from any of those tables. @pedrocarlo 's commit fixes an issue where `JoinTable` would incorrectly generate predicates with empty table names. Related: #2618
> Fix two issues in simulator

- .github/workflows/rust.yml
- extensions/tests/src/lib.rs
- testing/README.md
- testing/all.test
- testing/cli_tests/extensions.py
- testing/tester.tcl
- testing/vtab.test
There is a distinction between tests that verify extension-specific behavior and those that verify interactions between the database engine and extensions. Previously, both types of tests were kept in `extensions.py`. With this new framework, we can extract the latter type of tests from `extensions.py` into TCL. This cleans up `extensions.py` and enables compatibility testing with SQLite at no extra cost.
I’m currently working on supporting outer joins involving TVFs and planning to add more tests that exercise the database’s handling of virtual tables, so I decided to do this refactoring first. 
In the future, we may consider moving extension-specific tests to TCL as well, especially those that have counterparts in SQLite or sqlean.
> Add framework for testing extensions in TCL

- core/functions/printf.rs
This continues the work for `printf` support from from tthe issue https://github.com/tursodatabase/turso/issues/885.
This PR adds support for `%i` operands in the printf function. An example of a command that works now and didn't before:
```sql
SELECT PRINTF("Decimals: %d %i", 200, 300);
```
This is Just an initial very simple contribution to get my feet wet and learn the basics about the project and how contributions here work. I intend to do something more meaningful in next contributions. Probably will try to finish support for missing `printf` functionality also.
> core/printf: support for the %i operand

- simulator/generation/plan.rs
- simulator/main.rs
- simulator/runner/cli.rs
- simulator/runner/env.rs
- simulator/runner/execution.rs
- simulator/runner/watch.rs
Also fixes an issue where since the old Database wasn't `Drop`d, it caused an issue with the static Registry :tm: that had broken `--doublecheck` mode.
> Add --keep-files flag to allow for inspection of files for successful simulator runs 

- bindings/go/rs_src/rows.rs
- bindings/go/rs_src/types.rs
- bindings/python/src/lib.rs
- core/functions/datetime.rs
- core/functions/printf.rs
- core/json/jsonb.rs
- core/json/mod.rs
- core/json/ops.rs
- core/types.rs
- core/vdbe/execute.rs
- core/vdbe/mod.rs
- core/vector/mod.rs
- core/vector/vector_types.rs
This PR adds documentation and renames some functions. Among other things, I renamed everything that was still called `owned_value` to either `db_value` or `value` (after https://github.com/tursodatabase/turso/pull/1488).
> Add documentation and rename functions

- core/storage/wal.rs
Currently during `Restart|Truncate` modes we properly restart the WAL header in the `WalFileShared`, but keep a stale one on the current `WalFile` instance.
> Update stale in memory wal header after restarting log

- core/vdbe/execute.rs
We have halt and op_halt, doing essentially the same thing.
This PR unifies them. There is a minor difference between them now in the way halt() handles auto-commit. My current understanding of the code is that what we have in halt *is a bug*, which is already one bad consequence of the duplication.
> unify halts

- core/translate/view.rs
SetCookie is necessary to invalidate prepared statements in the connection after DDL expressions.
> emit SetCookie when creating a view

- simulator/generation/plan.rs
- simulator/generation/query.rs
Closes #2618 (sufficiently for now, IMO)
Prevents simulator from creating malformed queries which we don't notice (ref e.g. #2609 , #2611, #2616)
> Fail simulator on parse errors

- simulator/generation/plan.rs
- simulator/generation/table.rs
- simulator/model/query/create_index.rs
- simulator/model/table.rs
We recently merged a change that panics the sim on parse errors, because not doing so has masked many scenarios where the sim unintentionally creates incorrect sql and we just ignore it.
The aforementioned change also surfaced that the sim can try to create a table that already exists, which now makes us panic and fail the sim. So in this PR, we make sure that doesn't happen.
We already have Property::DoubleCreateFailure to assert that the same table cannot be created twice, so this should not hide any bugs.
> fix/sim: prevent sim from trying to create an existing table or index

- README.md
Right now it is buried under "console".
We have also not updated the list of commands when we added two more, and this is done in this PR.
> make the MCP server instructions more visible on the README

- cli/app.rs
- cli/commands/args.rs
- cli/commands/mod.rs
- cli/input.rs
- core/lib.rs
- core/translate/emitter.rs
- core/translate/insert.rs
- core/vdbe/execute.rs
- core/vdbe/metrics.rs
- core/vdbe/mod.rs
This adds basic statement and connection metrics like SQLite (and libSQL) have.
This is particularly useful to show that materialized views are working:
turso> create table t(a);
turso> insert into t(a) values (1) , (2), (3), (4), (5), (6), (7), (8), (9), (10); turso> create materialized view v as select count(*) from t; turso> .stats on
Stats display enabled.
turso> select count(*) from t;
┌───────────┐
│ count (*) │
├───────────┤
│        10 │
└───────────┘
Statement Metrics:
Row Operations:
Rows read:        10
Rows written:     0
[ ... other metrics ... ]
turso> select * from v;
┌───────────┐
│ count (*) │
├───────────┤
│        10 │
└───────────┘
Statement Metrics:
Row Operations:
Rows read:        1
Rows written:     0
[ ... other metrics ... ]
> add metrics and implement the .stats command

- core/lib.rs
- core/storage/pager.rs
- core/vdbe/execute.rs
- simulator/generation/plan.rs
- simulator/generation/property.rs
Closes #2657 
Closes #2659 
Closes #2660 
Closes #2661
1. In simulator, do not assume every error that happens after fault injection has the literal error message `"Injected fault"`. If an error happened, all we need to do is not shadow the query into the in-memory simulator environment -- in other words, we assume whatever the statement did failed and was rolled back.
2. Do not begin or end transactions inside a nested statement. Nested statements generally only occur when `ParseSchema` is invoked, which runs the equivalent of `SELECT * FROM sqlite_schema`. This does not need a new transaction nor does it need to end the transaction on error, since the parent statement will handle it.
> Do not begin or end transactions in nested statement

- core/io/unix.rs
- core/lib.rs
- core/storage/sqlite3_ondisk.rs
- core/storage/wal.rs
- core/types.rs
- core/vdbe/mod.rs
Clear locked pages when read completions callback fail. Also, we need to abort I/O Completions in `stmt.run_once()` so that we do not raise errors in `rollback` when clearing the page cache.
Fixes #2658
Fixes #2675
Fixes #2680
Fixes #2682
> Fix page locked panic

- .github/workflows/rust.yml
- Cargo.lock
- bindings/javascript/Cargo.toml
- bindings/javascript/src/lib.rs
- core/Cargo.toml
- core/io/mod.rs
- core/lib.rs
- core/pragma.rs
- core/storage/btree.rs
- core/storage/database.rs
- core/storage/encryption.rs
- core/storage/mod.rs
- core/storage/pager.rs
- core/storage/sqlite3_ondisk.rs
- core/storage/wal.rs
- core/translate/pragma.rs
- tests/Cargo.toml
- tests/integration/query_processing/encryption.rs
- tests/integration/query_processing/mod.rs
- vendored/sqlite3-parser/src/parser/ast/mod.rs
This patch adds support for per page encryption. The code is of alpha quality, was to test my hypothesis. All the encryption code is gated behind a `encryption` flag. To play with it, you can do:
```sh
cargo run --features encryption -- database.db
turso> PRAGMA key='turso_test_encryption_key_123456';
turso> CREATE TABLE t(v);
```
Right now, most stuff is hard coded. We use AES GCM 256. This information is not stored anywhere, but in future versions we will start saving this info in the file. When writing to disk, we will generate a cryptographically secure random salt, use that to encrypt the page. Then we will store the authentication tag and the salt in the page itself. To accommodate this encryption hardcodes reserved space of 28 bytes. 
Once the key is set in the connection, we …
> Initial pass to support per page encryption

- Cargo.lock
- bindings/rust/src/lib.rs
- core/lib.rs
- core/storage/pager.rs
- core/storage/wal.rs
- core/translate/pragma.rs
- core/types.rs
- sqlite3/src/lib.rs
- sync/engine/src/database_sync_engine.rs
- sync/engine/src/database_sync_operations.rs
- sync/engine/src/database_tape.rs
- tests/Cargo.toml
- tests/integration/functions/mod.rs
- tests/integration/functions/test_wal_api.rs
- tests/integration/query_processing/test_write_path.rs
This PR adds information about checkpoint sequence number to the WAL raw API. Will be used in the sync engine.
Depends on the #2699
> Wal api checkpoint seq

- core/io/unix.rs
The Unix backend is a syscall()-based, blocking implementation. The O_NONBLOCK adds nothing.
> core/io: Don't open file as non-blocking in Unix backend

- bindings/rust/src/lib.rs
- core/lib.rs
- core/storage/mod.rs
- core/storage/page_cache.rs
- core/storage/pager.rs
- sync/engine/src/wal_session.rs
- tests/integration/functions/test_wal_api.rs
- tests/integration/query_processing/test_write_path.rs
This PR make it possible to do 2 pretty crazy things with turso-db:
1. Now we can mix WAL frames inserts with SQL execution within same transaction. This will allow sync engine to execute rebase of local changes within atomically over main database file (the operation first require us to push new frames to physically revert local changes and then we need to replay local logical changes on top of the modified DB state)
2. Under `conn_raw_api` Cargo feature turso-db now expose method which allow caller to specify WAL file path. This dangerous capability exposed for sync-engine which maintain 2 databases: main one and "revert"-DB which shares same DB file but has it's own separate WAL. As sync-engine has full control over checkpoint - it can guarantee that DB file will be consistent with …
> wal-api: allow to mix frames insert with SQL execution

- core/storage/wal.rs
Removed the redundant `#![allow(clippy::arc_with_non_send_sync)]` from wal.rs, since it’s already defined in `mod.rs`.
> Remove duplicated attribute in `wal.rs`

- core/json/jsonb.rs
- core/json/mod.rs
This PR removes `Result<()>` from `Jsonb::write_to_string()`, since it wasn't required. The method now returns `()`.
> Remove Result from signature

- flake.nix
`make test` fails when using the nix-shell environment due to `uv` not being included in the list of dependencies with
`make: uv: No such file or directory
make: *** [Makefile:55: uv-sync-test] Error 127`
simple fix adding it to `nativeBuildInputs` of the shell. after that runs as expected.
> flake.nix: add uv dependency to nativeBuildInputs

- scripts/merge-pr.py
Resolves #2778.
I think this issue is probably because backticks in shell end up causing the command-line to attempt to resolve whatever was inside it as a command.
Added `shlex.quote` to the commit title in order to hopefully fix this.
> ci: fix merge-pr issue to escape command-line backticks

- core/incremental/expr_compiler.rs
- core/translate/display.rs
- core/translate/expr.rs
- core/translate/group_by.rs
- core/translate/insert.rs
- core/translate/optimizer/lift_common_subexpressions.rs
- core/translate/optimizer/mod.rs
- core/translate/optimizer/order.rs
- core/translate/order_by.rs
- core/translate/plan.rs
- core/translate/planner.rs
- core/translate/select.rs
- core/translate/update.rs
- core/util.rs
- parser/src/ast.rs
- parser/src/parser.rs
Sometimes in the parser we had enum Variants that contained `Vec<Box<Expr>>` which is unnecessary and inefficient.
> Remove double indirection in the Parser

- core/lib.rs
- core/pragma.rs
- core/storage/encryption.rs
- core/storage/pager.rs
- core/translate/pragma.rs
- parser/src/ast.rs
- tests/integration/query_processing/encryption.rs
This patch brings a bunch of quality of life improvements to encryption:
1. Previously, we just let any string to be used as a key. I have updated the `PRAGMA hexkey=''` to get the key in hex. I have also renamed from `key`, because that will be used to get passphrase 
2. Added `PRAGMA cipher` so that now users can select which cipher they want to use (for now, either `aegis256` or `aes256gcm`)
3. We now set the encryption context when both cipher and key are set
I also updated tests to reflect this.
> Improve encryption API

- core/schema.rs
- core/vdbe/execute.rs
If we get a table name for in memory structure, it's safe to assume it's already normalized.
> core/schema: get_dependent_materialized_views_unnormalized

- core/storage/btree.rs
- core/storage/pager.rs
- core/storage/sqlite3_ondisk.rs
it wasn't used for anything. no more `page.get().get().id`.
i did this simply to clean up the code (we haven't needed BTreePageInner in probably at least 8 months or more?), but it also:
- makes practically every tpc-h query faster due to removing indirection and refcell runtime borrowing every time the btree stack is accessed etc
- makes every SELECT * FROM users bench query faster
- drops the count() benchmark runtime by like half
> refactor/perf: remove BTreePageInner

- core/storage/btree.rs
- core/storage/pager.rs
- core/storage/sqlite3_ondisk.rs
I think the `try_into()` is probably expensive. we can use the fact that both interior page types are `<=5` to our advantage for a little perf boost in these hot path function calls
Based on #2836 (just to see aggregate perf difference in benchmarks)
> perf: avoid constructing PageType in helper methods

- core/vdbe/execute.rs
- core/vdbe/mod.rs
It's a hot instruction for TPC-H, for example, so worth optimizing. Reduces op_zero_or_null() from 5.6% to 2.4% in CPU flamegraph for TCP-H Q1.
> core/vdbe: Micro-optimize "zero_or_null" opcode

- core/translate/select.rs
```
Prepare `SELECT first_name, count(1) FROM users GROUP BY first_name HAVING count(1) > 1 ORDER BY cou...
time:   [3.9978 µs 4.0085 µs 4.0193 µs]
change: [-5.0734% -4.6271% -4.1644%] (p = 0.00 < 0.05)
```
> core/translate: remove unneessary agg clones

- core/translate/planner.rs
```
Benchmarking Prepare `SELECT first_name, count(1) FROM users GROUP BY first_name HAVING count(1) > 1 ORDER BY cou...: Collecting 100 samples in estimated 5.008
Prepare `SELECT first_name, count(1) FROM users GROUP BY first_name HAVING count(1) > 1 ORDER BY cou...
time:   [4.0081 µs 4.0223 µs 4.0364 µs]
change: [-2.9298% -2.2538% -1.6786%] (p = 0.00 < 0.05)
```
>  core/translate: parse_table remove unnecessary clone of table name 

- core/vdbe/execute.rs
- testing/insert.test
closes: #2822
```
turso> insert into strict_table values (1);
turso>
```
> Fix column case sensitivity on strict table

- parser/src/parser.rs
- testing/insert.test
- testing/null.test
Adds tests for edgecases for the insane cases where someone might want to name a table `true` :)
> Parse booleans to integer literals in expressions

- core/functions/printf.rs
- core/types.rs
Some progress working on `printf` support.
(relevant issue https://github.com/tursodatabase/turso/issues/885)
Implementation of the basic substitution types cited in the `TODO` comment on the beginning of the file (%i, %x, %X, %o, %e, %E, %c). There are some others in the sqlite spec which I will implement in a future PR.
I tried to pay attention to the specific behaviors from sqlite as much as possible while testing this, but if there's something I missed please tell me.
Also, I see this code needs to be reorganized already, I'm still thinking on the best approach to do that without affecting the ergonomics of new implementations, I'm still learning Rust so this is not obvious for me right now. I'm open to suggestions about it.
> core/printf: support for more basic substitution types

- core/translate/aggregation.rs
- core/translate/group_by.rs
- core/translate/main_loop.rs
- core/translate/plan.rs
- core/translate/planner.rs
- core/translate/select.rs
- testing/agg-functions.test
- testing/cli_tests/extensions.py
- testing/collate.test
- testing/groupby.test
The initial commits fix issues and plug gaps between ungrouped and grouped aggregations.
The final commit consolidates the code that emits `AggStep` to prevent future disparities between the two.
> Unify handling of grouped and ungrouped aggregations

- .github/workflows/napi-sync.yml
- .github/workflows/napi.yml
- bindings/javascript/.gitignore
- bindings/javascript/Makefile
- bindings/javascript/package.browser.json
- sync/javascript/.gitignore
- sync/javascript/Makefile
- sync/javascript/package.browser.json
This PR introduces separate `package.browser.json` file for `*-browser` npm packages (`@tursodatabase/sync-browser` and `@tursodatabase/database-browser`).
The packages are nearly identical and the only change is `package.json` content (browser package mentions only WASM optional dependency which shouldn't confuse NPM and force it to download WASM dep package instead of native one).
Due to that, innocent "hack" is implemented which swap `package.json` with `package.browser.json` before publish of `browser` package.
> introduce package.json for separate *-browser package (both database and sync)

- core/io/mod.rs
- otherwise, in multi-threading environment, other thread can think that completion is finished and start execution
- this can lead to violated assertions (for example, page must be loaded, but as callback is not executed yet assert will be fired)
Failing scenario:
1. main thread wants to execute pread - so it schedule IO and return control to the caller
2. IO thread read data from the disk
3. IO thread executes complete(result)
4. complete func set result of the completion to Ok
5. main thread enter into the step loop again and check completion status
6. completion marked as finished/is_completed - so main thread continue execution
7. main thread check that page is loaded and fails with assertion - because it's not loaded yet
8. IO thread executed the callback and finished the completion
> mark completion as done only after callback will be executed

- core/schema.rs
- core/translate/alter.rs
- core/translate/delete.rs
- core/translate/insert.rs
- core/translate/update.rs
SQLite does not allow us to modify system tables, but we do. Let's fix it.
> prevent modification to system tables.

- cli/app.rs
fix #2937 , we dont need to check comment in cli because parser already handled it (i guest).
How to reproduce:
```sh
turso> --whatCREATE TABLE users (
id INT PRIMARY KEY,
first_name VARCHAR(50),
age INT
);
```
> Fix infinite loop when query starts comment token ("--")

- core/storage/sqlite3_ondisk.rs
Add handling malformed inputs to function `read_varint` and test cases.
```
read_varint(&[0x81, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80]) 
before -> panic index out of bounds: the len is 8 but the index is 8
after -> LimboError
read_varint(&[0x80; 9]) 
before -> Ok((128, 9))
after -> LimboError
```
> core: handle edge cases for read_varint

- core/lib.rs
- core/storage/btree.rs
- core/storage/page_cache.rs
- core/storage/pager.rs
- core/vdbe/execute.rs
This PR replaces the existing LRU cache implementation with the sieve algo, providing better performance and simpler code.
Same intrusive linked-list without pointer chasing and no per-page/insert heap allocations.
Benchmarks look really good so far, although some did show some regression (I think it's more likely that they were flakey and its not representative on either end, but I do believe this to be considerably more performant) 
Best numbers I have seen yet on Mobibench locally, with 1473 tx/s.
> Page Cache: optimize and use sieve/Gclock hybird algorithm in place of LRU

- core/storage/btree.rs
- core/types.rs
- core/vdbe/execute.rs
- core/vdbe/mod.rs
- tests/integration/common.rs
- tests/integration/functions/mod.rs
- tests/integration/mod.rs
Attempt to improve performance of `SELECT COUNT(*) FROM t WHERE 1 = 1` (redundant filter added to force sqlite and tursodb to iterate over rows instead of applying count optimization).
Before that PR turso with hot cache runs for ~440ms.
After that PR turso with hot cache runs for ~200ms.
This PR eliminates small things on a hot path and also introduce separate flow for `get_next_record` which just increment cell idx if its safe to do that - without much additional overhead.
Also, this PR eliminates RefCell/Cell from PageStack because there were completely unnecessary.
> Small fixes

- core/translate/expr.rs
Closes #2946 
currently we always evaluate the binary expression, then coerce it to zero/null with the `ZeroOrNull` instruction, and then emit a separate jump.
this is fine for non-conditional expressions where we are using the value itself (e.g. in a SELECT result column), but in conditionals we don't care about that at all and just want to either jump or not jump.
so: try to keep the spirit of code reuse, but still have distinct implementations for conditionals and non-conditionals.
> expr: use more efficient implementation for binary condition exprs

- cli/app.rs
SQLite emits a semicolon after "PRAGMA foreign_keys=OFF" so let's do th same.
> cli: Fix dump compatibility in "PRAGMA foreign_keys"

- core/storage/btree.rs
only use `self.stack.top()` when we need to store `Arc<Page>` in struct
```sh
Execute `SELECT count() FROM users`/limbo_execute_select_count
time:   [5.3733 µs 5.3801 µs 5.3881 µs]
change: [-34.047% -33.949% -33.851%] (p = 0.00 < 0.05)
Found 1 outliers among 100 measurements (1.00%)
1 (1.00%) high severe
```
> reduce cloning `Arc<Page>`

- core/vdbe/execute.rs
- testing/join.test
current code is incorrectly assuming that `index_cursor.rowid()` always finds a rowid, but this is not the case when `NullRow` has previously been called.
> Handle case where null flag is set in op_column

- cli/app.rs
different between output modes is how we handle `Ok(StepResult::Row)` so let introduce `row_step_result_query` macro to reduce duplicated code.
> clean `print_query_result`

- core/vdbe/execute.rs
- tests/integration/fuzz_transaction/mod.rs
- tests/integration/query_processing/test_transactions.rs
If upgrade from read to write transaction fails, don't roll back the transaction. Instead restore the transaction into its original state, which allows deferred transactions that have not read anything to restart automatically.
Fixes #2984
> core/vdbe: Don't rollback transaction when write upgrade fails

- core/storage/pager.rs
When we use a freelist trunk page, the freelist count should decrease, not increase
file under: lmao
Closes #2992
> pager: fix incorrect freelist page count bookkeeping

- COMPAT.md
- core/functions/datetime.rs
- testing/scalar-functions-datetime.test
Resolves #2677
- Implements the modifier for Floor on the datetime object.
- Implements the modifier for Ceiling on the datetime object.
- Includes additional testing changes in testing/scalar-functions-datetime.test to test the sql functionality.
Consolidation PR of #2678 and #2679 since the functions ended up being much more complicated than I initially thought and had to be done in a single PR.
> core: Support ceiling modifier in datetime

- simulator/runner/file.rs
As we are in rust 1.88 rn, we can safely use extract_if
> simulator: Clean up code to use extract_if()

- .gitignore
- scripts/clean_interactions.sh
- scripts/corruption_bisecter.py
1. Add script that cleans simulator logs into just the SQL statements
2. Add script that bisects a set of SQL statements to find the minimal prefix set of statements that fails SQLite integrity check
> Add scripts that help debug bugs from simulator

- core/lib.rs
- core/pragma.rs
- core/storage/pager.rs
- core/translate/pragma.rs
- parser/src/ast.rs
Retrying fsync() on error was historically not safe ("fsyncgate") and Postgres still defaults to panicing on fsync(). Therefore, add a "data_sync_retry" pragma (disabled by default) and use it to determine whether to panic on fsync() error or not.
> core: Panic on fsync() error by default

- perf/throughput/rusqlite/src/main.rs
- perf/throughput/turso/src/main.rs
With `BEGIN CONCURRENT`, we should also take advantage of async transaction processing to maximize concurrency.
> perf/throughput/turso: Async transactions with concurrent mode

- perf/throughput/turso/Cargo.lock
- perf/throughput/turso/Cargo.toml
- perf/throughput/turso/src/main.rs
Looping through the futures means we're essentially executing them serially.
> perf/throughput/turso: Don't execute futures serially

- tests/integration/fuzz_transaction/mod.rs
**test/fuzz: introduce fuzzoptions to tx isolation test**
this makes it significantly easier to tweak the tx isolation test parameters, and also makes it much easier to run the MVCC version of the test without manually tweaking code inline to make it work.
introduces default options for the non-mvcc and mvcc test variants.
---
**test/fuzz: improve error handling in tx isolation fuzz test**
- extract out common behavior for checking acceptable errors
- add functionality to check which errors require rolling back
a transaction
> test/fuzz: improve maintainability/usability of tx isolation test

- bindings/rust/src/lib.rs
- core/io/clock.rs
- core/lib.rs
- perf/throughput/turso/src/main.rs
I searched using deepwiki how SQLite implements their busy handler. They use a callback system with exponential backoff, where it stores the callback in the pager and in the database. I confess I found this slightly confusing, so I just implemented a simple exponential backoff directly in the `Statement` struct. I imagine SQLite does this in a more convoluted manner, as they do not have a concept of yielding as we do.
https://deepwiki.com/search/where-is-the-code-for-the-busy_4a5ed006-4eed-479f-80c3-dd038832831b
I also fixed the rust bindings so that it yields when we return `StepResult::IO`, instead of just blocking the async function. To achieve this I implemented the `Stream` trait for `Rows` struct, which unfortunately came with a slight change to the function signature of …
> Busy handler

- core/translate/alter.rs
- testing/alter_table.test
Resolves #2093
There is a small incompatibility on how we quote the added column on the final schema, but doesn't change any behavior.
> Add quoted identifier test cases for `ALTER TABLE`

- cli/app.rs
- core/incremental/compiler.rs
- core/incremental/operator.rs
- core/incremental/persistence.rs
- core/incremental/view.rs
- core/schema.rs
- core/translate/view.rs
- core/util.rs
We have not implemented them before because they require the raw elements to be kept. It is easy to see why in the following example:
```
current_min = 3;
insert(2) => current_min = 2 // can be done without state
delete(2) => needs to look at the state to determine new min!
```
The aggregator state was a very simple key-value structure. To accomodate for min/max, we will make it into a more complex table, where we can encode a more complex structure.
The key insight is that we can use a primary key composed of:
```
1) storage_id
2) zset_id,
3) element
```
The storage_id and zset_id are our previous key, except they are now exploded to support a larger range of storage_id. With more bits available in the storage_id, we can encode information about which column we are storing. For …
> Implement Min/Max aggregators

- core/mvcc/database/mod.rs
- core/mvcc/database/tests.rs
- core/storage/wal.rs
- core/vdbe/execute.rs
Currently header changes are tracked through pager by reading page 1. MVCC has it's own layer to track changes during txn so this commit makes it so that headers are tracked by each txn separately.
On commit we update the _global_ header which is used to update `database_size` because pager commits require it to be up to date. This also makes it _simpler_ to keep track of header updates and update pager's header accordingly.
This PR is needed in order to make logical log work because we don't want to rely on pager as much as possible!
> core/mvcc: introduce with_header for MVCC header update tracking

- core/translate/schema.rs
- core/translate/upsert.rs
- core/util.rs
- testing/create_table.test
Ongoing tests for [turso-go](https://github.com/tursodatabase/turso-go) have unearthed a couple more issues
closes #3187
We were getting something like:
```sql
sqlite_autoindex_`databases`_2
```
when creating autoindex for table in Gorm (gorm is notorious for backticks everywhere), because of not normalizing the column name when creating autoindex.
When creating table with `PRIMARY KEY AUTOINCREMENT`, we were still creating the index, but it wasn't properly handled in    `populate_indices`, because we are doing the following:
```rust
if column.primary_key && unique_set.is_primary_key {
if column.is_rowid_alias {
// rowid alias, no index needed
continue; // continues, but doesn't consume it..
}
```
So if we created such an index entry for the AUTOINCREMENT... we would trip this:
```rust …
```
> translate: couple fixes from testing with Gorm

- CONTRIBUTING.md
- Cargo.lock
- core/lib.rs
- whopper/Cargo.toml
- whopper/bin/explore
- whopper/bin/run
- whopper/main.rs
If encryption is arg is passed, then we run whopper tests with encryptions. We randomly generate cipher and key, and run whopper. They are also printed for debugging and analysis.
Also, updated the corresponding scripts. So now you can do: 
```bash
./whopper/bin/run --enable-encryption
or 
./whopper/bin/explore --enable-encryption
```
> Enable encryption option in Whopper 

- stress/main.rs
Commit eeab6d5ce ("stress: Retry sync on error to avoid a panic") only enabled sync retry in the schema creation path. Let's add it to the stress test loop too.
Spotted during Antithesis runs.
> stress: Retry sync on error to avoid a panic, take 2

- core/io/mod.rs
- core/lib.rs
- core/storage/buffer_pool.rs
- core/storage/page_cache.rs
- core/storage/pager.rs
- core/storage/sqlite3_ondisk.rs
- core/storage/wal.rs
- core/vtab.rs
We use relaxed ordering in a lot of places where we really need to ensure all CPUs see the write. Switch to sequential consistency, unless acquire/release is explicitly used. If there are places that can be optimized, we can switch to relaxed case-by-case, but have a comment explaning *why* it is safe.
> core: Use sequential consistency for atomics by default

- core/translate/insert.rs
closes #3206 and https://github.com/tursodatabase/turso-go/issues/21
What happens is the coroutine overwrites the program state.. so the `RETURNING` result columns are from the `translate_select` that happens when we insert multiple rows.
```rust
let result = translate_select(schema, select, syms, program, query_destination, connection)?;
// overwrites program.result_columns
```
> translate/insert: fix `program.result_columns` when inserting multiple rows

- simulator/generation/plan.rs
- simulator/shrink/plan.rs
When shrinking, the depending table should first start with the dependencies from the overall property first. I broke this in my previous Sim Connections PR.
> simulator: Fix shrinking

- core/storage/btree.rs
I keep getting these warnings and it slightly annoys me:
```rust
warning: unused variable: `overflow_cell_count_before`
--> core/storage/btree.rs:3634:29
|
3634 |                         let overflow_cell_count_before = parent_contents.overflow_cells.len();
|                             ^^^^^^^^^^^^^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_overflow_cell_count_before`
|
= note: `#[warn(unused_variables)]` on by default
warning: unused variable: `overflow_cell_count_after`
--> core/storage/btree.rs:3641:29
|
3641 |                         let overflow_cell_count_after = parent_contents.overflow_cells.len();
|                             ^^^^^^^^^^^^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_overflow_cell_count_after`
```
> Put the unused variable behind a flag as intended

- core/translate/delete.rs
- core/translate/expr.rs
- core/translate/insert.rs
- core/translate/optimizer/mod.rs
- core/translate/planner.rs
- core/translate/select.rs
- core/translate/update.rs
Previously we were rewriting/traversing the AST in a couple different places, each of these added kinda ad-hoc as we needed them. This attempts to do the binding of column references as well as the rewriting of anonymous `Expr::Variable` -> `__param_N` that we use to maintain the order of bound variables, also normalizes the Qualified Name's.
Also we previously weren't accepting Variable (or at least they wouldn't work) in places like `LIMIT ? OFFSET ?`, which this PR adds.
I kinda want to keep refactoring translation a bit, and try to break plan building up into more easy-to-digest chunks.. but I will resist the urge right now as it's definitely not high priority pre-beta
> translate/optimize: centralize AST/expr traversal

- bindings/rust/src/lib.rs
- core/lib.rs
- core/pragma.rs
- core/translate/pragma.rs
- parser/src/ast.rs
Expose busy_timeout added in #3067 as a `PRAGMA busy_timeout=<ms duration>`
https://www.sqlite.org/pragma.html#pragma_busy_timeout
> Pragma busy timeout

- Cargo.lock
- Cargo.toml
- bindings/rust/Cargo.toml
- perf/encryption/Cargo.toml
- perf/encryption/README.md
- perf/encryption/src/main.rs
```
cargo run --release -- -b 100 -i 100000 --read-ratio 75
cargo run --release -- -b 100 -i 100000 --read-ratio 75 --encryption
```
```
Total time: 629.51s
Transaction throughput: 158.85 txns/sec
Operation throughput: 15885.37 ops/sec
- Read operations: 7500165 (7500165 found, 0 not found)
- Read throughput: 11914.29 reads/sec
- Write operations: 2499835
- Write throughput: 3971.08 writes/sec
```
vs
```
Total time: 665.05s
Transaction throughput: 150.36 txns/sec
Operation throughput: 15036.47 ops/sec
- Read operations: 7500165 (7500165 found, 0 not found)
- Read throughput: 11277.60 reads/sec
- Write operations: 2499835
- Write throughput: 3758.87 writes/sec
```
> Add encryption throughput test

- core/incremental/compiler.rs
- core/incremental/merge_operator.rs
- core/incremental/mod.rs
- core/incremental/operator.rs
- core/incremental/view.rs
- testing/materialized_views.test
UNION queries, while useful on their own, are a cornerstone of recursive CTEs.
This PR implements:
* the merge operator, required to merge both sides of a union query.
* the circuitry necessary to issue the Merge operator.
* extraction of tables mentioned in union and CTE expressions, so we can correctly populate tables that contain them.
> Support UNION queries in DBSP-based Materialized Views

- Cargo.lock
- simulator/Cargo.toml
- simulator/generation/mod.rs
- simulator/generation/plan.rs
- simulator/generation/property.rs
- simulator/main.rs
- simulator/model/mod.rs
- simulator/runner/differential.rs
- simulator/runner/doublecheck.rs
- simulator/runner/env.rs
- simulator/runner/execution.rs
- simulator/shrink/plan.rs
- sql_generation/model/query/transaction.rs
- Made the code around snapshot isolation more ergonomic with each connections having its own transaction state. Also when shadowing, we pass a ShadowTablesMut object that dynamically uses the committed tables or the connection tables depending on the transaction state. 
- added begin concurrent transaction before every property when mvcc is enabled (this is just so we can have some mvcc code be tested using the simulator under Begin Concurrent, I have not yet implemented the logic to have concurrent transactions in the simulator)
- some small enhancements to shrinking
TODOs
- have proper logic to have concurrent transactions without WriteWrite conflicts. This means when generating the plans we need to make sure that we do not generate rows that will conflict with rows in other …
> Enhancement to Sim Snapshot isolation code

- core/error.rs
- core/incremental/operator.rs
- core/schema.rs
- core/storage/btree.rs
- core/translate/compound_select.rs
- core/translate/delete.rs
- core/translate/emitter.rs
- core/translate/expr.rs
- core/translate/index.rs
- core/translate/insert.rs
- core/translate/main_loop.rs
- core/translate/mod.rs
- core/translate/optimizer/constraints.rs
- core/translate/optimizer/join.rs
- core/translate/optimizer/mod.rs
- core/translate/plan.rs
- core/translate/select.rs
- core/translate/update.rs
- core/translate/upsert.rs
- core/util.rs
- core/vdbe/execute.rs
- testing/all.test
- testing/partial_idx.test
- tests/integration/fuzz/mod.rs
This PR adds support for partial indexes, e.g. `CREATE INDEX` with a provided predicate
```sql
CREATE UNIQUE INDEX idx_expensive ON products(sku) where price > 100;
```
The PR does not yet implement support for using the partial indexes in the optimizer.
> translate/emitter: Implement partial indexes

- core/mvcc/database/mod.rs
This PR does not implement MVCC checkpoint yet, just adds a lock for it.
MVCC checkpoints are always TRUNCATE, plus they block all other transactions. This guarantees that never need to let transactions read from the SQLite WAL.
In MVCC, the checkpoint procedure is roughly as follows:
- Take the blocking_checkpoint_lock
- Write everything in the logical log to the pager, and from there commit to the SQLite WAL.
- Immediately TRUNCATE checkpoint the WAL into the database file.
- Release the blocking_checkpoint_lock.
> mvcc: add blocking checkpoint lock

- .github/workflows/napi.yml
- sync/engine/src/database_sync_operations.rs
- sync/engine/src/server_proto.rs
Use SQL over HTTP batch statement in the push logic of sync-engine with additional condition for `!auto_commit` for every step except from initial `BEGIN` of txn.
This is needed to avoid non-transactional update if SQLite will decide to close transaction due to some error and reset state to autocommit mode.
> Use SQL over HTTP batch statements for sync push

- simulator/generation/plan.rs
- simulator/main.rs
- simulator/runner/differential.rs
- simulator/runner/doublecheck.rs
- simulator/runner/env.rs
- simulator/runner/execution.rs
- simulator/shrink/plan.rs
Closes #3253 
Had to do some slight changes in how we shadow interactions and changed some of the execution code to accommodate both runtime generation and pre-run generation (pre-run generation is needed for instance when running the shrunk plans). This behavior is abstracted by the `InteractionPlanIterator` trait
> Simulator Runtime generation

- core/mvcc/persistent_storage/logical_log.rs
This format is based on previous discussions:
1. Log header
```rust
/// Log's Header, this will be the 64 bytes in any logical log file.
/// Log header is 64 bytes at maximum, fields added must not exceed that size. If it doesn't exceed
/// it, any bytes missing will be padded with zeroes.
struct LogHeader {
version: u8,
salt: u64,
encrypted: u8, // 0 is no
}
```
2. Transaction format:
* Transaction id
* Checksum u64
* Byte size of all rows combined
* Rows
* End marker (offset position after appending buffer) 
3. Row format:
```rust
/// Serialize a row_version into on disk format.
/// Format of a "row" (maybe we could change the name because row is not general enough for
/// future type of values):
///
/// * table_id (root page) -> u64
/// * row type -> u8
///
/// (by row type)
/// …
```
> core/mvcc/logical-log: on disk format for logical log

- Cargo.lock
- cli/Cargo.toml
- cli/app.rs
- cli/build.rs
- cli/commands/args.rs
- cli/commands/mod.rs
- cli/input.rs
- cli/main.rs
- cli/manual.rs
- cli/manuals/cdc.md
- cli/manuals/encryption.md
- cli/manuals/index.md
- cli/manuals/mcp.md
- cli/manuals/vector.md
In the hopes of doing a good job at teaching people what Turso can do, I am adding built-in manual pages. When the CLI starts, it picks a feature at random, and tells the user that the feature exists:
```
Turso v0.2.0-pre.8
Did you know that Turso supports Change Data Capture? Type .manual cdc to learn more.
This software is ALPHA, only use for development, testing, and experimentation.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database
```
There is a lot we can do to make this feature world class:
- we can automatically compile examples during compile time like rust-doc, to make sure examples used in the manuals always work
- we can implement scrolling and navigation
- we can document a lot more features
But …
> Add built-in manual pages for Turso

- simulator/runner/env.rs
Because `InteractionPlan::init_plan` and `gen_rng` used an rng with the same seed initially, it could happen that we could create the first create query in `init_plan`, and then generate a `DoubleCreateFailure` property that would generate the exact same previous query, due to the seed being the same. The easy and quick fix is just to use different seeds. 
Closes #3330
Closes #3329 
Closes #3327 
Closes #3326
Closes #3325 
Closes #3324
> use a different seed for `gen_rng`

- core/benches/mvcc_benchmark.rs
- core/mvcc/database/checkpoint_state_machine.rs
- core/mvcc/database/mod.rs
- core/mvcc/database/tests.rs
- core/mvcc/persistent_storage/logical_log.rs
- core/mvcc/persistent_storage/mod.rs
- core/vdbe/execute.rs
- core/vdbe/mod.rs
- tests/integration/fuzz_transaction/mod.rs
- tests/integration/query_processing/test_transactions.rs
mvcc: add blocking checkpoint
performs a blocking, truncating checkpoint:
- when started, blocks any other transactions from starting
- writes all row versions to pager that havent already been
checkpointed
- flushes them to wal
- checkpoints wal to db
in the case of added/deleted rows in table id 1 (sqlite schema),
also creates/destroys btrees accordingly
> mvcc: add blocking checkpoint

- core/schema.rs
- core/translate/expr.rs
- core/translate/insert.rs
- core/translate/planner.rs
- core/translate/select.rs
- core/translate/update.rs
- testing/groupby.test
- testing/orderby.test
- testing/where.test
In e.g. `SELECT x AS y, y AS x FROM t ORDER BY x;`, the `x` in the
`ORDER BY` should reference t.y, which has been aliased as `x` for this
query. The same goes for GROUP BY, JOIN ON etc. but NOT for WHERE.
Previously we had wrong precedence in `bind_and_rewrite_expr`.
Closes #3281
> Fix result columns binding precedence

- core/mvcc/database/mod.rs
- core/vdbe/execute.rs
- tests/integration/fuzz_transaction/mod.rs
- tests/integration/query_processing/test_transactions.rs
Changes ALTER TABLE operations to use only MV store and not go through pager, because pager is only used during checkpoint. 
- Exclusive transaction is required for DDL operations: trying to execute one inside a `BEGIN CONCURRENT` transaction will return an error. It's simply too complicated for now to try to make them concurrently transactional.
- Not doing schema changes via pager means that in MV rollback, the connection must rollback its private schema separately, since pager rollback is not invoked.
- To simplify MVCC semantics, if any transaction committed a schema change after a transaction started, it cannot commit and will abort with `SchemaUpdated` error
- To mimic regular SQLite transaction behavior, if a transaction tries to promote to exclusive transaction, it will fail with …
> MVCC: support alter table

- core/mvcc/database/mod.rs
- core/mvcc/persistent_storage/logical_log.rs
Read transactions from logical log and load mvcc store based on the contents onto transaction 0, which is the special transaction where we will load all row versions that can be read by all new transactions.
I was thinking to implement the rest on another pr to not increase load to review this one.
> core/mvcc/logical-log: load logical log from disk

- parser/src/parser.rs
- testing/offset.test
In this case x is the OFFSET and y is the LIMIT, not the other way around.
Closes #3303
> parser: fix incorrect LIMIT/OFFSET parsing of form LIMIT x,y

- core/translate/select.rs
> Disallow ORDER BY and LIMIT in a non-compound VALUES() statement

- COMPAT.md
- core/json/jsonb.rs
- core/json/vtab.rs
- core/vtab.rs
- testing/json.test
This PR implements the `json_tree` table-valued function.
It's not 100% compatible with SQLite, because SQLite does some iffy things with the `key` and `path` columns. I started a [thread](https://www.sqlite.org/forum/forumpost/48f5763d8c) on their forum and I linked it to the disabled tests in `json.test`.
> Implement json_tree

- core/translate/index.rs
- parser/src/parser.rs
- testing/all.test
- testing/create_index.test
Discovered this one while working on #3322
It was a bit more elusive because the original error was essentially a red herring:
```
turso> CREATE INDEX idx ON "t t" (`a a`);
× unexpected token at SourceSpan { offset: SourceOffset(22), length: 1 }
╭────
1 │ CREATE INDEX idx ON "t t" (`a a`);
·                       ┬
·                       ╰── here
╰────
help: expected [TK_LP] but found TK_ID
```
> Fix CREATE INDEX with quoted identifiers

- Cargo.lock
- core/Cargo.toml
- core/incremental/aggregate_operator.rs
- core/incremental/compiler.rs
- core/incremental/dbsp.rs
- core/incremental/join_operator.rs
- core/incremental/merge_operator.rs
- core/incremental/operator.rs
- core/incremental/persistence.rs
- core/schema.rs
- core/translate/delete.rs
- core/translate/insert.rs
- core/translate/planner.rs
- core/translate/update.rs
- core/translate/view.rs
Improve serialization for DBSP views.
The serialization code was written organically, without much forward thinking about stability as we evolved the table and operator format. Now that this is done, we are at at point where we can actually make it suck less and take a considerable step towards making this production ready.
We also add a simple version check (in the table name, because that is much easier than reading contents in parse_schema_row) to prevent views to be used if we had to do anything to evolve the format of the circuit (including the operators)
> Improve DBSP view serialization

- core/schema.rs
- core/translate/index.rs
- core/translate/schema.rs
edit: we can't disallow 'turso_' prefix though, because turso-sync-engine uses it
Closes #3313
> translate: disallow creating/dropping internal tables

- core/storage/btree.rs
Let's add more hints to hunt down the reason for #2896.
> core/storage: Display page category for rowid integrity check failure

- perf/tpc-h/queries/1.sql
- perf/tpc-h/queries/10.sql
- perf/tpc-h/queries/12.sql
- perf/tpc-h/queries/14.sql
- perf/tpc-h/queries/15.sql
- perf/tpc-h/queries/20.sql
- perf/tpc-h/queries/3.sql
- perf/tpc-h/queries/4.sql
- perf/tpc-h/queries/5.sql
- perf/tpc-h/queries/6.sql
- perf/tpc-h/queries/7.sql
- perf/tpc-h/queries/8.sql
- perf/tpc-h/run.sh
`CAST('yyyy-mm-dd' as datetime)` causes sqlite and tursodb to interpret the value as just 'yyyy', e.g. '1995-01-01' becomes '1995', causing a lot of the queries not to return any results, which is not what we want.
> bench/tpch: remove "cast('yyyy-mm-dd' as datetime)"

- .github/workflows/build-sim.yml
- .github/workflows/c-compat.yml
- .github/workflows/dart.yml
- .github/workflows/java.yml
- .github/workflows/labeler.yml
- .github/workflows/long_fuzz_tests_btree.yml
- .github/workflows/napi.yml
- .github/workflows/python.yml
- .github/workflows/rust.yml
- .github/workflows/rust_perf.yml
- .github/workflows/stale.yml
We're getting hit by macOS runner concurrency limits whenever some jobs get stuck (for example, because of a deadlock).
> github: Add 30 minute timeout to all jobs

- core/translate/expr.rs
Fixes https://github.com/tursodatabase/turso/issues/3295
> resolve column alias after rewritting column access in the expression in returning insert clause

- core/schema.rs
- core/translate/expr.rs
- core/translate/update.rs
- parser/src/parser.rs
- testing/create_table.test
closes #3282
includes minor refactor, removing `column_is_rowid_alias`, which is only checking the public field of the argument Column.
> core/translate: allow creating column called 'rowid'

- parser/src/ast.rs
- parser/src/ast/fmt.rs
- parser/src/parser.rs
`deref_clause` -> `defer_clause`
(Yes I'm implementing foreign keys)
> Correct spelling issue in ForeignKey ast node

- bindings/javascript/packages/native/promise.test.ts
- core/translate/compound_select.rs
- core/translate/emitter.rs
- tests/integration/query_processing/test_read_path.rs
Before, we validated that condition during program emit - which works for fixed values of parameters but doesn't work with variables provided externally to the prepared statement
> Fix zero limit

- core/lib.rs
- core/translate/index.rs
MVCC does currently not support indexes. Therefore,
- Fail if a database with indexes is opened with MVCC
- Disallow `CREATE INDEX` when MVCC is enabled
Fixes: #3108
> core: Disallow CREATE INDEX when MVCC is enabled

- core/translate/logical.rs
- testing/materialized_views.test
SQLite supports complex expressions in group by columns - because of course it does...
So we need to make sure that a column is created for this expression if it doesn't exist already, and compute it, the same way we compute pre-projections in the filter operator.
Fixes #3363
Fixes #3366
Fixes #3365
> Fix materialized views with complex expressions

- core/types.rs
- core/vdbe/execute.rs
- testing/scalar-functions.test
Closes #3306
Not only blobs, but numbers are also cast to text
> substr scalar should also work with non-text values

- .gitignore
- core/benches/mvcc_benchmark.rs
- core/lib.rs
- core/mvcc/cursor.rs
- core/mvcc/database/checkpoint_state_machine.rs
- core/mvcc/database/mod.rs
- core/mvcc/database/tests.rs
- core/mvcc/mod.rs
- core/mvcc/persistent_storage/logical_log.rs
- core/mvcc/persistent_storage/mod.rs
- core/schema.rs
- core/storage/btree.rs
- core/translate/schema.rs
- core/util.rs
- core/vdbe/execute.rs
- tests/integration/common.rs
- tests/integration/query_processing/test_transactions.rs
**Handle table ID / rootpages properly for both checkpointed and non-checkpointed tables**
Table ID is an opaque identifier that is only meaningful to the MV store.
Each checkpointed MVCC table corresponds to a single B-tree on the pager,
which naturally has a root page.
**We cannot use root page as the MVCC table ID directly because:**
- We assign table IDs during MVCC commit, but
- we commit pages to the pager only during checkpoint
which means the root page is not easily knowable ahead of time.
**Hence:**
- MVCC table ids are always negative
- sqlite_schema rows will have a negative rootpage column if the
table has not been checkpointed yet.
- on checkpoint when the table is allocated a real root page, we update the row in sqlite_schema and in MV store's internal mapping
**On …
> MVCC: Handle table ID / rootpages properly for both checkpointed and non-checkpointed tables

- core/translate/emitter.rs
- core/translate/insert.rs
- core/translate/plan.rs
- core/vdbe/builder.rs
- testing/insert.test
There were 2 problems:
1. The SELECT wasn't propagating which register it used for its results, so sometimes the INSERT read bad data.
2. `TableReferences::contains_table` was only checking the top-level tables, not the nested tables in FROM queries. This condition is used to emit "template 4", the bytecode template for self-inserts.
Closes https://github.com/tursodatabase/turso/issues/3312
> Fix self-insert with nested subquery

- Cargo.lock
- Cargo.toml
- simulator/Cargo.toml
- simulator/generation/plan.rs
- simulator/generation/property.rs
- simulator/model/mod.rs
- simulator/profiles/mod.rs
- simulator/runner/env.rs
- simulator/runner/execution.rs
- simulator/shrink/plan.rs
Depends on #3272.
First big step towards: #1851 
- Add ignore error flag to `Interaction` to ignore parse errors when needed, and still properly report other errors from intermediate queries.
- adjusted shrinking to accommodate transaction statements from different connections and properly remove extensional queries from some properties
- MVCC: generates `Begin Concurrent` and `Commit` statements that are interleaved to test snapshot isolation between connection transactions. 
- MVCC: if the next interactions are going to contain a DDL statement, we first commit all transaction and execute the DDL statements serially
> Simulator: Concurrent transactions

- core/mvcc/database/mod.rs
- core/mvcc/persistent_storage/logical_log.rs
otherwise we start overwriting existing log entries
Closes #3495
> fix/mvcc: set log offset to end of file after recovery finishes

- core/translate/update.rs
Before, FROM clauses were simply ignored:
```
turso> update t set a = b from (select random() as b);
× Parse error: no such column: b
```
Now, they will be rejected with a clear message. It also makes it clearer that they need to be implemented:
```
turso> update t set a = b from (select random() as b);
× Parse error: FROM clause is not supported in UPDATE
```
> Reject unsupported FROM clauses in UPDATE

- core/vdbe/execute.rs
- testing/scalar-functions.test
Fixes:
- `start_value` and `length_value` should be casted to integers
- proper handling of utf-8 characters
- do not need to cast blob to string, as substr in blobs refers to byte indexes and not char-indexes
> Substr fix UTF-8

- bindings/rust/tests/integration_tests.rs
- core/vdbe/execute.rs
essentially after the first runthrough of `op_transaction` per a given `ProgramState`, we weren't resetting the instruction state to `Start´ at all, which means we didn't do any transaction state checking/updating after that.
PR includes a rust bindings regression test that used to panic before this change, and I bet it also fixes this issue in turso-go:
https://github.com/tursodatabase/turso-go/issues/28
> fix/vdbe: reset op_transaction state properly

- Cargo.lock
- sync/engine/Cargo.toml
- sync/engine/src/database_replay_generator.rs
- sync/engine/src/database_tape.rs
In order to follow "last-push-wins" default conflict resolution strategy for DDL operations we must use `... IF NOT EXISTS ...` variant for them.
This PR enabled `if_not_exists` flag in the AST before emitting DDL operation for the remote in order to use `last-push-win` strategy for these operations instead of erroring out.
> apply create DDL operation with IF NOT EXISTS clause in order to make them idempotent

- core/mvcc/database/checkpoint_state_machine.rs
- core/mvcc/database/mod.rs
- core/mvcc/persistent_storage/logical_log.rs
- core/mvcc/persistent_storage/mod.rs
`IOResult` implies we have a state machine that needs to be polled to `Completion`, which is not the case here. We are just emitting the IO operation in this case. This led us to never reaching the `IOResult::Done` branch that actually fsynced the logical log in `Checkpoint`.
I also sprinkled some
```rust
if c.is_completed() {
Ok(TransitionResult::Continue)
} else {
Ok(TransitionResult::Io(IOCompletions::Single(c)))
}
```
just to be more efficient with sync IO, but it is not strictly necessary here.
> core/mvcc: Return completions from logical log methods

- core/translate/collate.rs
- core/translate/compound_select.rs
- core/translate/emitter.rs
- core/translate/group_by.rs
- core/translate/main_loop.rs
- core/translate/optimizer/constraints.rs
- core/translate/optimizer/mod.rs
- core/translate/order_by.rs
- core/translate/plan.rs
- core/translate/planner.rs
- core/translate/window.rs
- core/vdbe/execute.rs
- core/vdbe/explain.rs
- core/vdbe/insn.rs
- testing/collate.test
- tests/integration/fuzz/mod.rs
Fixes the following problems with COLLATE:
- Fix: incorrectly used e.g. `x COLLATE NOCASE = 'fOo'` as index constraint on an index whose column was not case-insensitively collated
- Fix: various ephemeral indexes (in GROUP BY, ORDER BY, DISTINCT) and subqueries did not retain proper collation information of columns
- Fix: collation of a given expression was not determined properly according to SQLite's rules
Adds TCL tests and fuzz test
Closes #3476
Closes #1524 
Closes #3305
> Fix COLLATE

- core/storage/wal.rs
Fixes a page cache staleness issue where connections could incorrectly believe the database hasn't changed after checkpointing. This can happen when writes following a checkpoint resulted in the same `max_frame value`, causing connections to miss updates since they only checked `max_frame` to detect changes.
> core/wal: check index header on begin_write_tx

- core/io/unix.rs
Fixes incorrect buffer length calculation in try_pwritev_raw when handling the first slice of the I/O vector.
Why:
With the faulty libc tests, a short write was simulated and the code incorrectly computed the length for the first buffer, leading to more bytes being written than expected, leading to a panic inside the completion.
How:
Adjusted the slice calculation to ensure only the intended range of bytes is written.
Backport: 0.2
> core/io/unix: Fix short writes in try_pwritev_raw()

- testing/unreliable-libc/file.c
Add short writes in the faulty_libc
As @PThorpe92 stated in #3209, this should be implemented here instead of the memory io in the simulator. Running this in the stress test I caught a logic bug in the try_pwritev_raw I will create a pr for that small fix. I will close #3209 in favor of this pr.
> Add short writes to unreliable-libc

- core/mvcc/database/checkpoint_state_machine.rs
- core/mvcc/database/mod.rs
- core/mvcc/database/tests.rs
- core/mvcc/persistent_storage/logical_log.rs
- core/mvcc/persistent_storage/mod.rs
- core/vdbe/execute.rs
On reaching 8 MiB checkpoint threshold we perform a blocking checkpoint on the logical log. These changes modified how transaction_state is tracked so that on a regular transaction we don't update it checkpoint's state machine.
I wonder if checkpoint should stay inside commit's transaction locks or like I did, where checkpoint happens right after committing transaction but this happens on the same query during halt.
> core/mvcc: automatic logical log checkpointing on commit

- core/vdbe/execute.rs
- testing/materialized_views.test
There is currently a bug found in our materialized view implementation that happens when we delete a row, and then re-insert another row with the same primary key.
Our insert code needs to detect updates and generate a DELETE + INSERT. But in this case, after the initial DELETE, the fresh insert generates another delete.
We ended up with the wrong response for aggregations (and I am pretty sure even filter-only views would manifest the bug as well), where groups that should still be present just disappeared because of the extra delete.
A new test case is added that fails without the fix.
> core/incremental: Fix re-insertion of data with same key

- core/error.rs
- core/lib.rs
- core/mvcc/database/mod.rs
- core/storage/pager.rs
- lock() return error in case when another thread panicked while holding the same lock
- we better to just panic too in any such case
> remove unnecessary SchemaLocked error

- perf/throughput/rusqlite/scripts/bench.sh
- perf/throughput/turso/scripts/bench.sh
Let's reduce variance between benchmark runs by starting with an empty database.
> perf/throughput: Delete database before benchmark run

- core/storage/btree.rs
- core/translate/integrity_check.rs
- core/vdbe/execute.rs
- add index root pages to list of root pages to check
- check for dangling (unused) pages
```sql
$ cargo run wut.db 
turso> .mode list
turso> pragma integrity_check;
Page 3: never used
Page 4: never used
Page 7: never used
Page 8: never used
```
```sql
$ sqlite3 wut.db 'pragma integrity_check;'
*** in database main ***
Page 3: never used
Page 4: never used
Page 7: never used
Page 8: never used
```
> Integrity check enhancements

- bindings/rust/README.md
Make it clear that the Turso rust binding is not a drop-in replacement for rusqlite. Turso is async and rusqlite isn't
> Fix rusqlite compatibility claim
