Cargo.lock
Cargo.toml
bindings/wasm/lib.rs
core/io/darwin.rs
core/io/linux.rs
core/io/mod.rs
core/io/windows.rs
core/storage.rs
simulator/Cargo.toml
simulator/main.rs

The simulator does not do much, but does discover failures on Linux with io_uring, though, so it's a start.

Initial pass on deterministic simulator

---

core/translate.rs
core/types.rs
core/vdbe.rs
testing/gen-database.py

Simple implementation for aggregation functions. The code added is
purposely so that we can add things like `CEILING(avg(n))` in the future. Aggregation function
impose a higher level of complexity that requires us to plan ahead
several things:
* simple avg: `select avg(id) from users`
* nested avg: `select ceiling(avg(id)) from users`
* avg with other columns: `select ceiling(avg(id)), * from users` (yes,
this is valid sqllite). For now I'm nullifying extra columns for
simplicity.
* avg with other agg functions: `select avg(id), sum(id) from users`.
This should be supported.
* At last -- Order By is a painful enough case to treat alone (not done
in this pr)
example:
```bash
> select avg(id),avg(age) from users
5000.5|48.101
```
```bash
> explain select avg(id),avg(age) from users
addr …
```

core: Avg aggregation function

---

core/lib.rs
core/schema.rs
core/translate.rs
core/util.rs

```
> select AVG(age) from users;
50.4915
```
Fixes #59

core: fix agg function uppercase parsing

---

core/translate.rs

This pull request refactors translate() and friends to make it easier on the eyes and hopefully more extensible to things like `ORDER BY`.

Refactor translate

---

cli/main.rs

closes #54 
I'm just starting out with Rust and found this project interesting. 
so thought why not contribute, but I'm not sure about best practices. I'm open to any feedback or suggestions for improvement. 
one known bug:
```sql
Welcome to Limbo SQL shell!
> .schema u
CREATE TABLE users (
id INTEGER PRIMARY KEY,
first_name TEXT,
last_name TEXT,
email TEXT,
phone_number TEXT,
address TEXT,
city TEXT,
state TEXT,
zipcode TEXT,
age INTEGER
);
> .schema user
CREATE TABLE users (
id INTEGER PRIMARY KEY,
first_name TEXT,
last_name TEXT,
email TEXT,
phone_number TEXT,
address TEXT,
city TEXT,
state TEXT,
zipcode TEXT,
age INTEGER
);
>
```

added .schema command in cli

---

cli/main.rs

```sql
> .schema
CREATE TABLE users (
id INTEGER PRIMARY KEY,
first_name TEXT,
last_name TEXT,
email TEXT,
phone_number TEXT,
address TEXT,
city TEXT,
state TEXT,
zipcode TEXT,
age INTEGER
);
```

.schema without args shows all tables

---

core/schema.rs
core/translate.rs

Remove incorrect Column::is_rowid_alias

---

.gitignore
Cargo.lock
core/Cargo.toml
core/pager.rs
core/storage.rs

Replace unwrap() in PageIO.get() with proper error handling

---

core/schema.rs

Fix primary key handling in BTreeTable

---

cli/main.rs
cli/opcodes_dictionary.rs
core/io/linux.rs
core/io/mod.rs
core/lib.rs
core/schema.rs
core/sqlite3_ondisk.rs
core/storage.rs
core/translate.rs
core/types.rs
core/vdbe.rs
sqlite3/src/lib.rs

These are the fixes of `clippy` lint warnings. 
There are few remaining which are all basically "Never used" and "Never read". 
all tests passes.

fix: lint warnings

---

core/translate.rs
core/types.rs
core/vdbe.rs
testing/all.test

Added max aggregate functionality 😄 
Newbie to both rust and contributing to database systems, do let me know if I can improve on anything further!

Add MAX aggregate function

---

core/translate.rs
core/types.rs
core/vdbe.rs
testing/all.test

Similar to [PR#105](https://github.com/penberg/limbo/pull/105), I've attempted to implement the min aggregate function. As always, let me know if there's anything to improve on!

Add MIN aggregate function

---

Cargo.lock
core/Cargo.toml
core/io/linux.rs

This PR enables read operations with O_DIRECT mode and Fixes #46

use O_DIRECT for file read operations

---

core/vdbe.rs

Fixes #108 
With this change, the `EXPLAIN` output looks like below:
```
> EXPLAIN SELECT id FROM users;
addr  opcode         p1    p2    p3    p4             p5  comment
----  -------------  ----  ----  ----  -------------  --  -------
0    Init           0     10    0       0   Start at 10
1    OpenReadAsync  0     2     0       0   root=2
2    OpenReadAwait  0     0     0       0
3    RewindAsync    0     0     0       0
4    RewindAwait    0     9     0       0
5      RowId          0     0     0       0
6      ResultRow      0     1     0       0   output=r[0..1]
7    NextAsync      0     0     0       0
8    NextAwait      0     4     0       0
9    Halt           0     0     0       0
10   Transaction    0     0     0       0
11   Goto           0     1     0       0
```

Fixes EXPLAIN to indent loops like SQLite does

---

core/translate.rs

We can use Select to keep track of loops and stuff. Having a separate SelectContext just means we need to pass around more objects to functions.

Fold SelectContext to Select

---

core/translate.rs

It's a special-case so let's make it special like SQLite does. Simplifies the logic in `translate_select()` quite a bit.

Simplify `LIMIT 0` handling in translate_select()

---

core/vdbe.rs

Fix avg(), total(), count() default value on empty set

---

core/translate.rs
core/vdbe.rs
testing/all.test

Sorry, I didn't realize @Feilkin had expressed interest in implementing this (#80) until I was mostly done... anyway, here's some kind of attempt. My bytecode/assembly-fu is quite basic 🍝

Basic where clause support

---

cli/main.rs

add help message to CLI

---

Pipfile
Pipfile.lock
README.md

Introduces a Pipfile to manage dependencies for the `gen-database.py` script, as well as any future Python scripts in the project.

Added a pipfile for the python dependencies

---

core/Cargo.toml
core/io/darwin.rs
core/io/generic.rs
core/io/mod.rs

Use kqueue for Darwin IO

---

core/translate.rs
core/types.rs
core/vdbe.rs
testing/all.test

Implements the remaining aggregate functions part of #93:
group_concat(x)
group_concat(x, y)
string_agg(x, y)
@penberg @pereman2 I'm fairly new to both Rust and database internals, so please do let me know if I need to change the solution approach (specifically the introduction of the delimiter param for the AggStep enum and assigning 0 for other aggregate operations).
```
> explain select group_concat(name) from products;
0     Init               0     13    0                    0   Start at 13
1     OpenReadAsync      0     3     0                    0   root=3
2     OpenReadAwait      0     0     0                    0
3     RewindAsync        0 …
```

Adds group_concat and string_agg aggregate functions

---

core/schema.rs
core/translate.rs
core/vdbe.rs

- Resolve cursor ID to table name and get column name from index
- Since we change the type of BranchOffset to i64, add assertions in Program.step() function
- opcode generation compatibility with sqlite: change register number to start from 1
- Improve Column,Rowid comment, Add DecrJumpZero comment, Fix Integer comment
- Fix typos in code comments

Improve explain comments

---

flake.lock
flake.nix

im excited to explore and contribute to this project
It would be great if we could have a nix flake
Im definitely not a nix expert so open to feedback for sure, but after running `nix develop` on my system which does not have the rust toolchain installed at all `make` and `cargo test` ran fine
its mainly based of the [nixos wiki](https://nixos.wiki/wiki/Rust#Installation_via_rustup)
no worries if this is not something you want to add just thought i'd ask since I will be using it

add nix flake

---

core/translate.rs
core/vdbe.rs

Move where clause literal out of loop. Related #122 
Previous:
```
> explain select * from products where name = 'hat';
0     Init               0     16    0                    0   Start at 16
1     OpenReadAsync      0     3     0                    0   root=3
3     RewindAsync        0     0     0                    0   
4     RewindAwait        0     15    0                    0   
5       Column           0     1     1                    0   r[1]=products.name
6       String8          2     0     0     hat            0   r[2]= 'hat'
7       Ne               1     2     13 …
```

Optimize literal in loop

---

core/schema.rs
core/translate.rs
core/vdbe.rs
testing/all.test

- Inner join with unqualified names (`select foo_col, bar_col from foo join bar on foo_col = bar_col`)
- Inner join with qualified names (`select foo.col, bar.col from foo join bar on foo.col = bar.col`)
- Inner join with table aliases (`select f.col, b.col from foo f join bar b on f.col = b.col`)
- Inner self join (`select f1.col, f2.col from foo f1 join foo f2 on f1.col = f2.col + 1`)
- No support in joins for: logical ops `AND` etc, multiple joins `JOIN ... JOIN`, `LEFT JOIN` etc
---
- Cursor references are now a tuple of `(table_identifier: String, table: Table)`; allows duplicates -- raises an error if `resolve_ident_table` is ambiguous
- Combine handling of `where` and `join`
- Support `Insn::Add`
- Remove unnecessary `GOTO` instruction from `translate_expr` binary expression cases …

Inner join, table aliases, qualified column names

---

core/translate.rs
core/vdbe.rs
testing/all.test

this also fixes NULL print to empty string

core: implement AND and OR + complex conditions.

---

Cargo.lock
core/Cargo.toml
core/function.rs
core/translate.rs
core/vdbe.rs
testing/all.test
testing/like.test

Implement LIKE

---

core/io/linux.rs

Small contribution to validate result from CQ and to add debug info if O_DIRECT flag cannot be used

core: validate result from CQ

---

flake.lock
flake.nix

sorry for making another flake pr before a real pr but the way I was doing it before was so bad it really bothered me
now its using [fenix](https://github.com/nix-community/fenix) and is much more robust
after `nix develop` all make commands run successfully

improve nix flake by moving to fenix

---

core/benches/benchmark.rs

Conditionally disable rusqlite benchmark

---

Cargo.lock
sqlite3/Cargo.toml
sqlite3/src/lib.rs
sqlite3/tests/Makefile
sqlite3/tests/main.c
sqlite3/tests/test-aux.c
sqlite3/tests/test-open.c
sqlite3/tests/test-prepare.c

This improve the `sqlite3` C API enough to make Python build pass.

sqlite3 improvements

---

COMPAT.md
Cargo.lock
core/Cargo.toml
core/expr.rs
core/function.rs
core/vdbe.rs

This is related to the issue https://github.com/penberg/limbo/issues/144.  Add the scalar function `random`

 implementation of scalar function `random`

---

cli/main.rs
core/translate/where_clause.rs
testing/all.test
testing/cmdlineshell.test

- Add tests for .schema
- Make command line sql arguments to allow .commands
- Fix #192

Fix .schema

---

core/schema.rs
core/translate/expr.rs
core/translate/mod.rs
testing/select.test

Fix #193 
```
Welcome to Limbo SQL shell!
> explain SELECT l_returnflag, l_linestatus FROM lineitem GROUP BY l_returnflag, l_linestatus ORDER BY l_returnflag, l_linestatus;
0     Init               0     22    0                    0   Start at 22
1     SorterOpen         0     3     0     k(3,B,B)       0   cursor=0
2     OpenReadAsync      1     10    0                    0   root=10
3     OpenReadAwait      0     0     0                    0   
4     RewindAsync        1     0     0                    0   
5     RewindAwait        1     14    0                    0   
6       Column           1     8     1                    0 …
```

Case insensitive column lookup

---

COMPAT.md
Cargo.lock
core/Cargo.toml
core/datetime.rs
core/function.rs
core/lib.rs
core/translate/expr.rs
core/vdbe/mod.rs
testing/scalar-functions.test

Implements partial support for the Date() method as per the [SQLite date and time functions](https://sqlite.org/lang_datefunc.html).
- Supports Time Value arguments.
- Modifiers are not yet supported.

Implement Date

---

core/function.rs
core/translate/expr.rs
core/translate/mod.rs
core/translate/where_clause.rs
core/vdbe/mod.rs

sorry this took so long I was have [editor](https://x.com/ethanniser/status/1816137663227044293) [issues](https://github.com/rust-lang/rust-analyzer/issues/17615)
this is the rename from #173 
Ill do the unicode func in a seperate pr, will be much eaiser now that I have #197 to base it off of

rename SingleRow -> Scalar

---

core/pager.rs

- Add some inline docs for `Pager` for better explanation

Add docs to `Pager`

---

core/translate/select.rs
core/translate/where_clause.rs

This is background restructuring work to enable us to change the loop order (or change the way a given loop is handled) based on what the WHERE and JOIN clauses contain.
Changes:
- `process_where()` called before opening table loops
- Due to the above, `WhereTerm` now refers to table identifiers instead of cursor IDs because the cursors have not been allocated yet at that point
- `ProcessedWhereClause` now contains a `loop_order`, which just defaults to the order in the SQL query for now. In the future the loop order may change depending on the query.
- `loops` removed from `Select` struct; a `LoopInfo` vector is now returned from `translate_tables_begin()`

Process where clause and joins before opening loops

---

core/translate/select.rs
core/vdbe/builder.rs
core/vdbe/explain.rs
core/vdbe/mod.rs

Similar to what SQLite does.
```
limbo> EXPLAIN SELECT u.age, p.name FROM users u LEFT JOIN products p ON u.first_name = p.name;
0     Init               0     25    0                    0   Start at 25 
1     OpenReadAsync      0     2     0                    0   table=u, root=2 
2     OpenReadAwait      0     0     0                    0    
3     OpenReadAsync      1     3     0                    0   table=p, root=3 
4     OpenReadAwait      0     0     0                    0    
5     RewindAsync        0     0     0                    0    
6     RewindAwait        0     -5    0                    0   Rewind table u 
7       Integer          0 …
```

Add ability to annotate instructions with comments

---

Cargo.lock
bindings/wasm/Cargo.toml
bindings/wasm/examples/example.js
bindings/wasm/lib.rs
bindings/wasm/vfs.js

Just some basic plumbing to call Node filesystem API from Rust.

First pass on WebAssembly I/O

---

core/Cargo.toml
core/pseudo.rs
core/storage/btree.rs
core/translate/insert.rs
core/types.rs
core/vdbe/explain.rs
core/vdbe/mod.rs
core/vdbe/sorter.rs

Fixes https://github.com/penberg/limbo/issues/275

Implement NewRowid

---

Cargo.lock
sqlite3/Cargo.toml

Update cbindgen dependency

---

COMPAT.md
core/function.rs
core/translate/expr.rs
core/vdbe/mod.rs
testing/scalar-functions.test

Add support for quote scalar function. Related issue: #144

Add support for quote scalar function

---

core/translate/plan.rs

Mimics SQLite's EXPLAIN QUERY PLAN pretty printer.
Example run on a preexisting db:
```
$ cargo run /tmp/srn "explain query plan select * from t natural join t join t2 on t.id = 2*t2.id where t.id in (select * from t);"
QUERY PLAN
`--JOIN ON t.id = 2 * t2.id
|--JOIN
|  |--SCAN t FILTER t.id IN (SELECT * FROM t)
|  `--SCAN t
`--SCAN t2
```
Fixes https://github.com/penberg/limbo/issues/295

core: pretty-print EXPLAIN QUERY PLAN

---

bindings/wasm/lib.rs
core/io/darwin.rs
core/io/generic.rs
core/io/linux.rs
core/io/mod.rs
core/io/windows.rs
simulator/main.rs

Follow-up PR to this [issue](https://github.com/penberg/limbo/issues/272), let me know if there's anything to be improved/reworked!

Add time querying to I/O trait for deterministic simulation

---

core/storage/btree.rs
core/storage/pager.rs
core/storage/sqlite3_ondisk.rs
test/src/lib.rs

This PR adds support for traversing overflow payloads and inserting them too. The test added is a simple one and must be tested with higher degree of stress in the future.

core,btree: support overflow pages

---

core/storage/sqlite3_ondisk.rs
core/translate/expr.rs
testing/where.test

Add support for WHERE parenthesized conditions 
- closes #153

Add support for parenthesized conditions

---

core/types.rs
testing/scalar-functions.test

Closes https://github.com/penberg/limbo/issues/339

fix: cmp integer/float

---

COMPAT.md
core/function.rs
core/translate/expr.rs
core/vdbe/mod.rs
testing/scalar-functions.test

Add `zeroblob(N)` scalar function

---

core/translate/emitter.rs

Closes #351
NextAwait's next instruction was pointing to RewindAwait earlier which is not current. The instruction now points to the instruction after RewindAwait, which will be the loop body. Hence, rename rewind_labels to scan_loop_body_labels to make it clearer

Fix NextAwait's next instruction; rename rewind_labels

---

bindings/wasm/lib.rs
bindings/wasm/vfs.js
core/lib.rs
core/storage/btree.rs
core/storage/pager.rs
core/storage/sqlite3_ondisk.rs

Behold, the database emerges from within.

core: create databases from limbo

---

Cargo.toml

Apply some more tricks from to reduce text size by 1 MB:
https://github.com/johnthagen/min-sized-rust
Before:
penberg@vonneumann sqlite3 % ls -lh ../target/release/liblimbo_sqlite3.a
-rw-r--r--  1 penberg  staff   6,7M 16 Mar 09:52 ../target/release/liblimbo_sqlite3.a
After:
penberg@vonneumann sqlite3 % ls -lh ../target/release/liblimbo_sqlite3.a
-rw-r--r--  1 penberg  staff   5,6M 16 Mar 09:50 ../target/release/liblimbo_sqlite3.a

core: Reduce library text size some more

---

core/translate/emitter.rs
core/translate/planner.rs
testing/groupby.test

Fix `COUNT(*)` panic

---

Cargo.lock
cli/main.rs
core/lib.rs
core/storage/btree.rs
core/storage/pager.rs
core/storage/sqlite3_ondisk.rs
core/vdbe/mod.rs
simulator/Cargo.toml
simulator/main.rs
test/src/lib.rs

Newly improved simulator with CREATE TABLE, INSERT, SELECT, connection management, etc...
This new simulator is finding a bunch of bugs with write path so after this PR I will start fixing those.

sim: improve simulator

---

.github/workflows/python.yml

github: Add Python package publish workflow

---

COMPAT.md
core/translate/optimizer.rs
core/translate/plan.rs
core/translate/planner.rs
testing/join.test

Support JOIN USING and NATURAL JOIN

---

COMPAT.md

- Its added in https://github.com/tursodatabase/limbo/pull/430

Change `octet_length` to yes in COMPAT.md

---

cli/main.rs

This PR prevents input from being evaluated in the case of an incomplete statement entered, allowing the user to continue the query on following lines.
This matches the behavior of the sqlite CLI by alerting the user how many parenthesis are currently open (up to 9) `(x1...`, or too many closed `(!...` and only processes `.`commands when they are the only input.
>sqlite
fixes #450

Add buffered cli input and match sqlite cli repl

---

core/translate/expr.rs
testing/agg-functions.test
testing/scalar-functions.test

Add support for the unary positive operator

Add support for unary positive

---

docs/internals/typical_query.md

I'd love to contribute to Limbo, but wrapping my head around the whole project is hard.
I decided to start by creating a diagram of a typical flow so that other potential contributors might have an easier time :)
LMK if this is useful, I can create more of those when I dig deeper.

Document typical code flow with charts

---

core/lib.rs

if somehow this doesn't finish in a single loop, do more just in case

loop writing header while initializing

---

core/translate/emitter.rs
core/translate/optimizer.rs
core/translate/plan.rs
core/translate/planner.rs
testing/agg-functions.test
testing/join.test
testing/where.test

support TRUE and FALSE in predicates

---

core/storage/btree.rs

core: update btree.rs

---

.github/workflows/rust.yml
Cargo.lock
Makefile
sqlite3/Cargo.toml
sqlite3/build.rs

Minimal cargo-c support

---

cli/app.rs
cli/main.rs

Add display message for in-memory database

---

core/translate/emitter.rs
core/translate/plan.rs
core/translate/planner.rs
testing/groupby.test

fix: core/translate: Dont assume GROUP BY has aggregates

---

cli/app.rs
testing/cmdlineshell.test
testing/shelltests.py

This PR adds the `.tables` command. I use it a lot in sqlite and I noticed it was missing from here so I decided to contribute.
Let me know if any changes or improvements are required.

cli: added .tables command

---

sqlite3/src/lib.rs

This wires up checkpointing to the SQLite C API. We don't respect the checkpointing mode because core does not have that nor do we report back some stats.

sqlite3: Add sqlite3_wal_checkpoint_*() API

---

core/json/de.rs
core/json/ser.rs
core/storage/btree.rs
core/translate/emitter.rs
core/translate/expr.rs
core/translate/insert.rs
core/translate/optimizer.rs
core/translate/planner.rs
core/types.rs
core/vdbe/likeop.rs
core/vdbe/mod.rs

I ran `cargo clippy --fix` and also fixed some issues manually.
Clippy still warns about some issues - especially in Simulator code.

Clean up more Clippy warnings

---

core/lib.rs
core/translate/delete.rs
core/translate/insert.rs
core/translate/planner.rs
core/translate/select.rs

Some random cleanups to make planner.rs smaller.

Codegen cleanups

---

core/io/windows.rs

Just fixes a few clippy errors on the windows platform

Minor clippy fixes for windows platform

---

CONTRIBUTING.md
README.md

* add description of workaround for running coverage with Rust 1.83

Add tests prerequisites to README and CONTRIBUTING

---

core/storage/sqlite3_ondisk.rs

- Removed unecessary clones
- Got rid of uneeded scoping in read_complete callback
- Use more rusty syntax e.g. std::cell::RefCell::borrow_mut(&buffer) -> buffer.borrow_mut()
- Changed write_page.unwrap() to write_page()? to match run_once and read_page()
No functional change.

refactor: simplify database header write logic

---

CONTRIBUTING.md

These are not hard rules in the project, but describe what the ideal pull request looks like.

Improve CONTRIBUTING on pull requests

---

core/translate/expr.rs

Taking advantage of macros added by @madejejej

expr: add expect_arguments_min!() and use expect_arguments_* macros more universally

---

COMPAT.md
core/translate/expr.rs
core/vdbe/explain.rs
core/vdbe/insn.rs
core/vdbe/mod.rs
testing/math.test

This PR adds support for ShiftRight operator and Opcode.

Implement ShiftRight

---

COMPAT.md
Cargo.lock
Cargo.toml
core/translate/expr.rs
extensions/regexp/Cargo.toml
extensions/regexp/src/lib.rs
testing/extensions.py

Implements some of the regexp functions as an extension from [sqlean](https://github.com/nalgeon/sqlean/blob/main/docs/regexp.md)

Add regexp extension

---

cli/app.rs
testing/shelltests.py

This PR improves comment handling in Limbo to precisely match SQLite's behavior:
Fixes some edge cases involving #711 
Inline comments mess up queries --
Query in the left terminal is current limbo state, upper right is limbo in the state of this PR
and lower right is sqlite behavior. 
Added support for inline comments using "--" syntax
Comments are now properly stripped before query execution
Maintains correct query execution when comments appear mid-query
Preserves multiline query functionality with comments
Ensures consistent behavior between pasted and typed queries
Testing:
Added test cases for single-line comments
Added test cases for inline comments
Added test cases for multiline queries with comments
Verified behavior matches SQLite CLI

Fix SQL comment handling Limbo shell

---

extensions/core/README.md

At some point we can probably move this out and publish the crate.
The docs referenced here is pretty much reliant on #721, still need to go and doc/comment a bunch there.

Add documentation for extensions/core

---

COMPAT.md
core/translate/expr.rs
core/vdbe/explain.rs
core/vdbe/insn.rs
core/vdbe/mod.rs
testing/compare.test

In limbo when we do any compare operations like `Eq, gt, lt, gte, lte` with nulls , we were actually giving the result as true where as sqlite3 gives null. This is because if we had a null, we were incorrectly going to conditional branch and not increment program by 1. Also the sqlite generates `ZeroOrNull` op in these cases (https://github.com/sqlite/sqlite/blob/version-3.45.3/src/expr.c#L4644) but we were generating a Integer instruction. The below outputs can give a clearer picture.
This PR aims to fix this.
sqlite3 output
```
SQLite version 3.48.0
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> select 8 = null;
sqlite> select 8 > null;
sqlite> explain select 8 > null;
addr  opcode         p1 …
```

Fix null compare operations not giving null

---

NOTICE.md
bindings/java/build.gradle.kts
licenses/bindings/java/spotless-license.md

- Add bindings/java project level formatting style 
- Add spotless as the formatting tool 
- USe Makefile to run lint on CI 
- [Corresponding PR](https://github.com/tursodatabase/limbo/pull/761) should be merged first
- [Related Issue](https://github.com/tursodatabase/limbo/issues/615)

bindings/java: Add auto formatting for java bindings project 

---

bindings/go/rs_src/rows.rs
bindings/rust/src/lib.rs
cli/app.rs
cli/import.rs
core/benches/benchmark.rs
core/lib.rs
core/util.rs
core/vdbe/mod.rs
perf/latency/limbo/src/main.rs
simulator/generation/plan.rs
tests/integration/functions/test_function_rowid.rs
tests/integration/query_processing/test_write_path.rs

It's just an useless wrapper, kill it.

core: Kill Rows wrapper struct

---

Cargo.lock
bindings/go/Cargo.toml
bindings/go/go.mod
bindings/go/limbo.go
bindings/go/rs_src/lib.rs
bindings/go/rs_src/rows.rs
bindings/go/rs_src/statement.rs
bindings/go/rs_src/types.rs
bindings/go/stmt.go
bindings/go/types.go

...we'll likely call this Turso eventually, but right now, let's keep the code consistent.

bindings/go: Rename to Limbo

---

bindings/java/README.md

- Add README.md for bindings/java 

bindings/java: Add README.md for bindings/java

---

COMPAT.md
simulator/README.md

Improving docs
1. adding journaling modes in compat
2. reformat the tables in compat
3. adding ref resources for DST

Improve docs

---

COMPAT.md

it seems like it is supported now

update COMPAT matrix for journal_mod pragma

---

COMPAT.md
core/function.rs
core/json/json_operations.rs
core/json/json_path.pest
core/json/mod.rs
core/translate/expr.rs
core/vdbe/mod.rs
testing/json.test

Uses already implemented json path parser so shares limitations with json_extract()

json_remove() function implementation

---

COMPAT.md

It is partially supported - only on the existing database.

add compat statement about CreateBTree opcode

---

core/translate/mod.rs

Make query_pragma use enum instead of &str

---

core/storage/btree.rs

This is mostly refactoring Cursor.write_info to instead be an enum, where one of the options is a WriteInfo.  This permits one to add other state machines to Cursor, and I added the state needed for Count as an example, but all the testing for count's implementation depends on ANALYZE #656 working end-to-end (to some degree) so that one can write a SQL test for it.
But this code seems conflict-prone, so it seems better to get it in sooner than later.
I also finally understood what the point of RefCell is from fighting with rust on this, so that was nice.

Refactor cursor to support multiple state machines

---

COMPAT.md
core/schema.rs
core/translate/group_by.rs
core/translate/mod.rs
core/translate/order_by.rs
core/translate/plan.rs
testing/pragma.test
vendored/sqlite3-parser/src/parser/ast/mod.rs

This implements the table_info pragma, allowing us to fetch information about columns present in a table.

Table info

---

COMPAT.md

Those two expr seem to be supported

update compat list

---

.github/workflows/labeler.yml

This fix was suggested by @seonWKim.

github: Configure labeler workflow environment

---

COMPAT.md
core/error.rs
core/function.rs
core/translate/expr.rs
core/vdbe/mod.rs
core/vdbe/printf.rs
testing/all.test
testing/scalar-functions-printf.test

Add basic printf function support in limbo

Add Printf Support

---

core/vdbe/mod.rs

This saves a few more nanoseconds:
```
Execute `SELECT 1`/Limbo
time:   [44.964 ns 45.064 ns 45.160 ns]
change: [-14.371% -13.724% -13.214%] (p = 0.00 < 0.05)
```

core/vdbe: Lazy cursor borrowing

---

core/json/json_operations.rs
core/json/mod.rs
core/types.rs
core/vdbe/insn.rs

Just some random cleanups I did while attempting to optimizing things and failing.

Random Text related cleanups

---

Cargo.lock
Cargo.toml
core/Cargo.toml
core/ext/mod.rs
extensions/core/src/types.rs
extensions/crypto/Cargo.toml
extensions/crypto/src/crypto.rs
extensions/crypto/src/lib.rs
testing/extensions.py

Introduces a new `crypto` extension, compatible with the Sqlean [crypto extension](https://github.com/nalgeon/sqlean/blob/main/docs/crypto.md).

Sqlean Crypto extension

---

Cargo.lock
README.md
bindings/java/Cargo.toml

Added a section for java in README.md

Add java section in README.md

---

CHANGELOG.md
CONTRIBUTING.md
bindings/python/pyproject.toml
bindings/wasm/package.json
core/benches/benchmark.rs

Adjust all the references since they were broken

github.com/penberg/limbo was moved to github.com/tursodatabase/limbo

---

simulator/generation/plan.rs
simulator/main.rs
simulator/runner/execution.rs

Fixes https://github.com/tursodatabase/limbo/issues/924

simulator: fix shrinking bug

---

Cargo.lock
core/Cargo.toml
extensions/core/Cargo.toml
extensions/regexp/Cargo.toml
extensions/series/Cargo.toml
tests/Cargo.toml

chore: remove unused dependencies

---

CHANGELOG.md
README.md
bindings/go/limbo_test.go
bindings/go/rs_src/statement.rs
bindings/rust/src/params.rs
core/storage/btree.rs
core/translate/expr.rs
core/translate/main_loop.rs
core/translate/mod.rs
core/util.rs
core/vdbe/mod.rs
extensions/time/src/lib.rs
simulator/generation/mod.rs
simulator/main.rs
simulator/runner/cli.rs
simulator/runner/env.rs
testing/json.test
testing/scalar-functions.test
tests/integration/fuzz/mod.rs
vendored/sqlite3-parser/src/parser/ast/mod.rs

I noticed the README had a prominent typo ("workin on"), so I decided to run [crate-ci/typos](https://github.com/crate-ci/typos) on the repo and fix what it flagged.

Fix a handful of typos

---

Cargo.lock
core/Cargo.toml
core/json/ser.rs
testing/json.test

Fix floating point truncation in JSON #877

---

cli/app.rs
cli/main.rs

cli: handle remaining input on EOF

---

cli/app.rs

cli: Add newline characters on multiline prompts

---

cli/app.rs

Basic dump support
This is a basic support for the very useful .dump command. It doesn't yet implement any of the dump options sqlite has, and it doesn't add some of the logic for things like indexes, since we don't have them.

cli: Basic dump support

---

bindings/go/rs_src/lib.rs

Extensive uri parsing was added to core and this will be handled there.

Remove uri/dsn parsing in Go bindings

---

docs/CODEOWNERS

@PThorpe92 @penberg @jussisaurio please let me know if you want any change, this is just a simple way for me to know if a pr is made in core, maybe I should have a `/core/translate` and `/core/storage` too.

CODEOWNERS

---

bindings/java/rs_src/limbo_statement.rs
bindings/java/src/main/java/tech/turso/JDBC.java
bindings/java/src/main/java/tech/turso/core/LimboPropertiesHolder.java
bindings/java/src/main/java/tech/turso/core/LimboStatement.java
bindings/java/src/main/java/tech/turso/jdbc4/JDBC4DatabaseMetaData.java
bindings/java/src/main/java/tech/turso/jdbc4/JDBC4Statement.java
bindings/java/src/test/java/tech/turso/JDBCTest.java
bindings/java/src/test/java/tech/turso/jdbc4/JDBC4StatementTest.java

- Do some minor nits 
- Implement logic that returns updated count when running executeUpdate 
- Implement version related functions 

bindings/java: Implement returning updated counts and version information 

---

core/translate/expr.rs
core/vdbe/explain.rs
testing/like.test

Escape character is ignored in LIKE function

---

docs/CODEOWNERS

Last matched pattern is the one that will be used, this fixes it.

Adjust codeowners order

---

core/Cargo.toml
core/benches/json_benchmark.rs
core/json/jsonb.rs
core/json/mod.rs

Added bench to see how far i am from SQLite. If ~~Cloude~~ I did benches correct moving from iterator to slice and cursor gives crazy performance bump where we are almost on par with SLQLite when we are not talking about huge jsons, but i suspect SQLite do some trickery there.

Add jsonb bench and rewrite jsonb parser to use slice and cursor

---

core/vdbe/mod.rs
testing/all.test

IDK if I'm being naive here but it was the easiest way that I found to handle it.
closes #1004

Fix AutoCommit for IO halting

---

COMPAT.md
core/function.rs
core/json/json_operations.rs
core/json/json_path.rs
core/json/jsonb.rs
core/json/mod.rs
core/translate/expr.rs
core/types.rs
core/vdbe/mod.rs
testing/json.test

Made a jsonb traversal by json path. 
Changed some ordinary json functions to use jsonb under the hood, so now behavior of our json module more like sqlite.
Found and fixed some bugs on the way.

Jsonb extract

---

core/io/io_uring.rs

When using the `io_uring` backend, WAL file writes were corrupted: the submitted buffer data (e.g., WAL header magic `37 7f 06 82`) was correct in logs, but the file on disk showed incorrect data (e.g., `00 18 27 xx`). This occurred because the `Arc<RefCell<Buffer>>` was dropped before the asynchronous `io_uring` write completed, allowing the kernel to write stale or freed memory.
In `UringFile::pwrite`, the `buffer` was passed to `io_uring` via an `iovec`, but the `Arc<RefCell<Buffer>>` wasn’t guaranteed to live until the write finished. Unlike synchronous `UnixIO`, where the buffer persists during the `pwrite` call, `io_uring`’s async nature exposed this lifetime issue.
Modified `UringFile::pwrite` to hold a reference to the `buffer` in the completion callback by calling …

Fix io_uring WAL write corruption by ensuring buffer lifetime

---

cli/app.rs
cli/helper.rs

...let's aim for a green color scheme that is easy on the eyes.

Improve CLI color scheme

---

Makefile
cli/app.rs
scripts/limbo-sqlite3
testing/cli_tests/extensions.py
testing/cli_tests/test_limbo_cli.py

Enable pretty mode in shell by default

---

core/types.rs
testing/math.test

Fix `SELECT 0.0 = 0` returning false

---

COMPAT.md
core/function.rs
core/json/json_operations.rs
core/json/jsonb.rs
core/json/mod.rs
core/translate/expr.rs
core/vdbe/mod.rs

Added jsonb_object, jsonb_array, json_insert, jsonb_insert.
MongoDB is sweating now.

Various JSON improvements

---

COMPAT.md
core/storage/btree.rs
core/translate/expr.rs
core/translate/mod.rs
core/translate/update.rs
core/vdbe/mod.rs
testing/all.test
testing/update.test

This PR is to support `Update` queries. Follows sqlite behavior as much as possible.
```console
limbo> create table t (a,b,c);
limbo> explain update t set a = 1 where b = 2;
0     Init               0     18    0                    0   Start at 18
1     OpenWriteAsync     0     2     0                    0
2     OpenWriteAwait     0     0     0                    0
3     RewindAsync        0     0     0                    0
4     RewindAwait        0     17    0                    0   Rewind table t
5       Column           0     1     4                    0   r[4]=t.b
6       Ne               4     5     15                   0   if r[4]!=r[5] goto 15 …
```

Initial pass at `UPDATE` support

---

core/storage/pager.rs
core/storage/sqlite3_ondisk.rs
core/storage/wal.rs

WAL frame checksum support

---

core/util.rs
testing/select.test

Fix numeric conversion in `SELECT -'e'`

---

core/translate/emitter.rs

closes #1190 
Don't emit full query plan and open table if 0 `LIMIT` 
```console
limbo> explain select * from t limit 0;
0     Init               0     2     0                    0   Start at 2
1     Halt               0     0     0                    0
2     Transaction        0     0     0                    0   write=false
3     Goto               0     1     0                    0
```
Surprisingly, sqlite will still emit the Open/Rewind/Column/etc, etc for this case. Definitely feels super unnecessary.

Handle limit zero case in query plan emitter

---

core/fast_lock.rs

Currently we can create two guards and unlock one of them and still have two mutable references to the same data.
By being able to unlock only via guard we prevent unsafe scenarios.
Currently, the test below will pass and shows that we can hold two mutable references to the same data. After this fix, this would result in a deadlock (have to remove `lock.unlock()`)
```rust
#[test]
fn two_mutable_reference() {
let lock = SpinLock::new(42);
let guard = lock.lock();
lock.unlock();
let guard2 = lock.lock();
// two mutable references to same data
*guard = 10;
*guard2 = 20;
assert_eq!(*guard, 20);
assert_eq!(*guard2, 20); 
}
```
Note: The javascript action failure is unrelated to this PR.

Remove public unlock method from `SpinLock` to prevent unsafe aliasing

---

.github/workflows/rust_perf.yml

...not sure why we added it in the first place, but it spams PRs all the time.

Kill test environment

---

core/vdbe/insn.rs

Also I added more tests for exec_add, exec_subtract, exec_multiply, exec_divide, exec_remainder.

Let remainder (%) accept textual arguments

---

README.md

docs(readme): update discord link

---

core/types.rs
core/vdbe/execute.rs

Allow reading altered tables by defaulting to null in Column insn

---

Cargo.lock
cli/Cargo.toml
cli/app.rs
cli/commands/args.rs
cli/commands/import.rs
cli/commands/mod.rs
cli/helper.rs

Dot command completion

---

core/storage/btree.rs

This pr sprinkles debug compile check to ensure things stay in a reliable state.

Improve validation of btree balancing

---

core/storage/btree.rs

* Comment how decrease of pages happen while balancing
* Free pages no longer used after balancing finished.

Decrease page count on balancing fixes

---

core/schema.rs
core/translate/emitter.rs
core/translate/insert.rs
core/types.rs
core/vdbe/execute.rs
core/vdbe/explain.rs
core/vdbe/insn.rs
testing/insert.test
testing/tester.tcl

Closes #884
Support for 
```CREATE TABLE test(id INTEGER) STRICT;```

Strict table support

---

cli/app.rs

Fix `EXPLAIN` to be case insensitive

---

cli/input.rs
core/ext/mod.rs
core/io/mod.rs

context: https://github.com/tursodatabase/limbo/issues/1275

io/linux: make syscallio the default (io_uring is really slow)

---

core/translate/expr.rs
core/util.rs

Enhance robusteness of optimization for Binary expressions

---

.gitignore
core/schema.rs
core/storage/btree.rs
core/storage/pager.rs
core/translate/index.rs
core/translate/schema.rs
core/vdbe/execute.rs
core/vdbe/explain.rs
core/vdbe/insn.rs

While developing I found that some things could be improved :)

Code clean-ups

---

core/vdbe/execute.rs
fuzz/Cargo.lock
testing/math.test

Me and @diegoreis42 were late at night, running the new fuzzer and saw some errors with `Bit-Not` and `Not` operations. Added some tests as well for those fixes.

Fuzz fix some operations

---

bindings/javascript/src/lib.rs
bindings/wasm/lib.rs
core/io/generic.rs
core/io/io_uring.rs
core/io/memory.rs
core/io/mod.rs
core/io/unix.rs
core/io/vfs.rs
core/io/windows.rs
core/lib.rs
core/storage/btree.rs
core/storage/database.rs
core/storage/pager.rs
core/vdbe/execute.rs
core/vdbe/explain.rs
core/vdbe/insn.rs
simulator/runner/io.rs

First ~actual~ step to close #741, this time I'm following an approach way closer to what SQLite does by just creating a normal `BTreeCursor` and using an in-memory pager (thanks @krishvishal for the insight :handshake:).

Add support for OpenEphemeral bytecode

---

core/translate/expr.rs
testing/math.test
testing/select.test

Fixes #1304 
Maybe I should add tests?

Parse hexidecimal integers

---

core/schema.rs
core/translate/index.rs
core/translate/optimizer.rs
core/util.rs

Extracted a few commits out from #1351 which are also going to be useful elsewhere

Index utils

---

testing/cli_tests/test_limbo_cli.py

When the python tests fail, they will sometimes truncate the output if it is smaller than the `PIPE_BUFF` size. With this fix we can now properly print the backtrace, when the program panics.
This is the problematic CI output from #1331  that led me to fix this. In this case, it was already truncating the output of the `assert` prints.
```
./testing/cli_tests/extensions.py
Extension ./target/debug/liblimbo_regexp loaded successfully.
Testing: uuid functions are registered properly with ext loaded
Testing: scalar alias's are registered properly
Testing: median agg function returns null when ext not loaded
Testing: median agg function works
Testing: median agg function works with odd number of elements
Testing: test aggregate percentile function with 2 arguments works
Testing: test …
```

Fix truncation of error output in tests

---

core/translate/delete.rs
core/translate/plan.rs
core/translate/planner.rs
core/translate/select.rs
core/translate/update.rs
core/vdbe/builder.rs
core/vdbe/execute.rs
core/vdbe/explain.rs
core/vdbe/insn.rs

Some more helper utilities extracted out from #1351 to make the surface area of that PR smaller

More index utils

---

core/translate/expr.rs
testing/math.test
testing/select.test

Parse hex integers 2

---

core/util.rs

Fix out of bounds access on `parse_numeric_str`

---

core/storage/btree.rs
core/storage/sqlite3_ondisk.rs

This PR is based on #1357 and further improves performance:
```sql
limbo> select l_orderkey, 3 as revenue, o_orderdate, o_shippriority from lineitem, orders, customer where c_mktsegment = 'FURNITURE' and c_custkey = o_custkey and l_orderkey = o_orderkey and o_orderdate < cast('1995-03-29' as datetime) and l_shipdate > cast('1995-03-29' as datetime);
┌────────────┬─────────┬─────────────┬────────────────┐
│ l_orderkey │ revenue │ o_orderdate │ o_shippriority │
├────────────┼─────────┼─────────────┼────────────────┤
└────────────┴─────────┴─────────────┴────────────────┘
Command stats:
----------------------------
total: 3.728050958 s (this includes parsing/coloring of cli app)
```

btree: avoid reading entire cell when only rowid needed

---

pyproject.toml
scripts/pyproject.toml
uv.lock

mainly so i don't have to install pygithub every time i want to `uv run scripts/merge-pr.py`

python: add UV project for 'scripts'

---

core/storage/sqlite3_ondisk.rs
core/types.rs

basically serialtype got slower in #1398, maybe because of the wasted space of `enum SerialType` being 16 bytes, so i've now refactored `SerialType` to be a transparent newtype wrapper over `u64` and introduced a separate `SerialTypeKind` enum
at least on my machine the perf regression was nullified, if not even a bit better

types: refactor serialtype again to make it faster

---

bindings/javascript/src/lib.rs
bindings/wasm/lib.rs
core/lib.rs

refactor database open_file and open

---

cli/app.rs
cli/commands/args.rs
cli/commands/mod.rs
cli/input.rs

Adds ability to view database indices using the `.indexes ?TABLE?` command.

Add the .indexes command

---

testing/insert.test

Let's add some missing tests for the INSERT statement.

Add tests for INSERT with specified column-name list

---

core/schema.rs
core/translate/emitter.rs
core/translate/index.rs
core/translate/mod.rs
core/translate/plan.rs
core/translate/schema.rs
core/translate/update.rs
core/types.rs
core/vdbe/execute.rs
core/vdbe/explain.rs
core/vdbe/insn.rs
testing/alter_table.test

Initial implementation of `ALTER TABLE RENAME`

---

core/translate/expr.rs
testing/all.test
testing/null.test

Limbo `isnull` output:
```
limbo> explain select 1 isnull;
0     Init               0     3     0                    0   Start at 3
1     ResultRow          1     1     0                    0   output=r[1]
2     Halt               0     0     0                    0
3     Integer            1     2     0                    0   r[2]=1
4     Integer            1     1     0                    0   r[1]=1
5     IsNull             2     7     0                    0   if (r[2]==NULL) goto 7
6     Integer            0     1     0                    0   r[1]=0
7     Goto               0     1     0                    0
```
Sqlite `isnull` output:
```
sqlite> …
```

Support isnull and notnull expr

---

core/storage/btree.rs

Coalesce adjacent free blocks during `page_free_array()` in `core/storage/btree`.
Instead of immediately passing free cells to `free_cell_range()`, buffer up to 10 free cells and try to merge adjacent free blocks. Break on the first merge to avoid time complexity, `free_cell_range()` coalesces blocks afterwards anyways. This follows SQLite's [`pageFreeArray()`](https://github.com/sqlite/sqlite/blob/d7324103b196c572a98724a5658970b4000b8c39/src/btree.c#L7729) implementation. 
Removed this TODO:
```rust
fn page_free_array( . . )
.
.
// TODO: implement fancy smart free block coalescing procedure instead of dumb free to
// then defragment
```

btree: Coalesce free blocks in `page_free_array()`

---

core/storage/btree.rs

Simply add a fuzz test to test free_array works as intended

test page_free_array

---

.github/workflows/rust_perf.yml
perf/tpc-h/benchmark.sh
perf/tpc-h/queries/1.sql
perf/tpc-h/queries/10.sql
perf/tpc-h/queries/11.sql
perf/tpc-h/queries/12.sql
perf/tpc-h/queries/13.sql
perf/tpc-h/queries/14.sql
perf/tpc-h/queries/15.sql
perf/tpc-h/queries/16.sql
perf/tpc-h/queries/17.sql
perf/tpc-h/queries/18.sql
perf/tpc-h/queries/19.sql
perf/tpc-h/queries/2.sql
perf/tpc-h/queries/20.sql
perf/tpc-h/queries/21.sql
perf/tpc-h/queries/22.sql
perf/tpc-h/queries/3.sql
perf/tpc-h/queries/4.sql
perf/tpc-h/queries/5.sql
perf/tpc-h/queries/6.sql
perf/tpc-h/queries/7.sql
perf/tpc-h/queries/8.sql
perf/tpc-h/queries/9.sql
perf/tpc-h/run.sh

Doesn't seem to work in CI yet properly (probably `time` utility output is different on linux), but here's an example local run output on mac. Notice we panic in `btree.rs` in one of the queries:
```bash
Using existing TPC-H.db file
Running TPC-H benchmark...
Starting TPC-H query timing comparison...
The script might ask you to enter the password for sudo, in order to clear system caches.
Running 1.sql with Limbo...
Running 1.sql with SQLite3...
Limbo real time: 2.21
SQLite3 real time: 1.96
Limbo output:
SQLite3 output:
No output difference
-----------------------------------------------------------
Skipping 2.sql, reason: subquery in where not supported
-----------------------------------------------------------
Running 3.sql with Limbo...
Running 3.sql with SQLite3...
Limbo real time: …
```

perf/ci: add basic tpc-h benchmark

---

testing/cli_tests/test_limbo_cli.py

Output rust backtrace in python tests

---

cli/app.rs

cli/fix: Apply default config for app

---

core/error.rs
core/lib.rs
core/storage/btree.rs
core/storage/page_cache.rs
core/storage/pager.rs
core/translate/pragma.rs
core/vdbe/execute.rs

This PR builds on top of https://github.com/tursodatabase/limbo/pull/1368 and adds few things like allowing inserting pages with the same page key, fix fuzz tests by adding transactions and some minor improvements to cacheflush.

Page cache fixes

---

Cargo.lock
sqlite3/Cargo.toml
sqlite3/src/lib.rs

...we now actually see logging from core too.

sqlite3: Switch to tracing logger

---

core/translate/emitter.rs
core/translate/mod.rs
core/translate/plan.rs
core/translate/select.rs
core/translate/values.rs
core/vdbe/execute.rs
testing/all.test
testing/values.test

Close: #866
**limbo output**: 
```
limbo> explain values(1, 2);
0     Init               0     5     0                    0   Start at 5
1     Integer            1     1     0                    0   r[1]=1
2     Integer            2     2     0                    0   r[2]=2
3     ResultRow          1     2     0                    0   output=r[1..2]
4     Halt               0     0     0                    0
5     Goto               0     1     0                    0
limbo> explain values(1, 2), (3, 4);
0     Init …
```

Support values statement and values in select

---

COMPAT.md
core/storage/sqlite3_ondisk.rs
core/translate/pragma.rs
testing/pragma.test

It also changes the type from u32 to i32 since
sqlite supports negative values

core/pragma: Add support for update user_version

---

.github/workflows/rust_perf.yml
Makefile
core/Cargo.toml
core/benches/tpc_h_benchmark.rs

Added a benchmark to bench TPC-H with criterion and have it uploaded to Nyrkio. I did not delete the other tpc-h job because maybe someone uses it and I'm not aware of it.

TPC-H with criterion and nyrkio

---

core/lib.rs

Shared cache requires more locking mechasnisms. We still have multi threading issues not related to shared cache so it is wise to first fix those and then once they are fixed, we can incrementally add shared cache back with locking in place.

set non-shared cache by default

---

bindings/rust/src/lib.rs
core/storage/sqlite3_ondisk.rs

Fix off-by-one error in max_frame after WAL load

---

bindings/javascript/__test__/better-sqlite3.spec.mjs
bindings/javascript/__test__/limbo.spec.mjs
bindings/javascript/src/lib.rs
bindings/javascript/wrapper.js

EDIT: This PR also adds support for the `pluck()` logic in all methods

bind/js: Add support for bind() method and reduce boilerplate

---

.github/workflows/long_fuzz_tests_btree.yml
stress/main.rs
stress/opts.rs

Add simple stress test run with 10k iteration to test `Delete`, `Update` and `Insert` together.

add stress test with 1 thread 10k iterations to ci

---

core/lib.rs
core/mvcc/database/mod.rs
core/mvcc/mod.rs
core/storage/btree.rs
core/storage/sqlite3_ondisk.rs
core/types.rs
core/vdbe/execute.rs
core/vdbe/mod.rs
testing/insert.test
tests/integration/functions/test_function_rowid.rs

Rowids can be negative, therefore let's swap to i64
Fixes: #1631

Convert u64 rowid to i64

---

simulator/main.rs
simulator/runner/cli.rs

we will soon run the sim on AWS where we don't need bugbase

simulator: add option to disable BugBase

---

core/translate/emitter.rs
core/translate/main_loop.rs
testing/delete.test

Fix cursors not being opened for indexes in DELETE

---

cli/app.rs
core/storage/pager.rs
core/storage/sqlite3_ondisk.rs
core/translate/pragma.rs
core/vdbe/execute.rs

Write database header via normal pager route

---

.gitignore
simulator/generation/mod.rs
simulator/generation/plan.rs
simulator/generation/property.rs
simulator/model/query/create_index.rs
simulator/model/query/mod.rs
simulator/runner/cli.rs
simulator/runner/differential.rs
simulator/runner/env.rs

Adds CREATE INDEX as a potential interaction.
Kudos to @alpaylan - I've been sleeping on the simulator a bit lately -- incredibly easy to add new stuff here

simulator: add CREATE INDEX to interactions

---

simulator/runner/execution.rs

I think this is useful to see, without having to drop down to DEBUG and seeing all the other stuff.

simulator: log the interaction about to be executed with INFO

---

bindings/javascript/README.md
bindings/javascript/__test__/better-sqlite3.spec.mjs
bindings/javascript/__test__/limbo.spec.mjs
bindings/javascript/docs/API.md
bindings/javascript/docs/CONTRIBUTING.md
bindings/javascript/src/lib.rs

Throughout the cleaning I discovered that the current pluck mode is broken, so I took the lead and also fixed it.
EDIT: Address comments on #1620 by improving our documentation

bindings/javascript: Refactor presentation mode and enhance test suite

---

bindings/javascript/__test__/better-sqlite3.spec.mjs
bindings/javascript/__test__/limbo.spec.mjs
bindings/javascript/wrapper.js

Let's you get the source string that was used to create the prepared statement.

bindings/javascript: Add source property to Statement

---

core/translate/optimizer/mod.rs
vendored/sqlite3-parser/src/to_sql_string/expr.rs

Addresses the panic encountered here: https://github.com/tursodatabase/limbo/pull/1690 . Sorry about that.

Fix rowid to_sql_string

---

core/translate/emitter.rs
core/translate/expr.rs
testing/update.test

fix: Incorrect placeholder label in where clause translation

---

core/storage/wal.rs
core/translate/pragma.rs

Only supported mode is PASSIVE

Implement pragma wal_checkpoint(<MODE>)

---

Dockerfile.antithesis
simulator-docker-runner/Dockerfile.simulator
testing/cli_tests/extensions.py

Fix CI errors caused by https://github.com/tursodatabase/limbo/pull/1741

Fix CI errors

---

simulator/runner/execution.rs

Now that we have our own integrity check, we can also execute it per query to catch bugs earlier. We could use `Sqlite`s integrity check instead of the one @pereman2 implemented, but I think this could also help us battle test the integrity check he wrote.
Motivation for this PR came from this issue #1781 . I wanted to find a minimal repo for that problem, so I introduced this check per query. The nice thing is that we get some shrinking as well by using the simulator instead of `limbo_stress`. 
The following command will allow you to find the failing seed I posted in the issue: 
`cargo run -p limbo_sim -- --minimum-tests 10 --maximum-tests 100 --disable-create-index --seed 17321136847878547364`

simulator: integrity check per query

---

.github/workflows/antithesis.yml

I want to be notified on Antithesis test stuff. I want to understand more how their stuff works and what fails and how in their platform.

Add Pedro to email recipients for antithesis

---

stress/main.rs

Closes #1821 
Two caveats:
- I wouldn't merge this before #1761 since it fails constantly against `main` code
- Not sure if this works as intended with multiple threads, but we don't support that in `stress` yet anyway

stress: reopen db / reconnect to db every now and then

---

core/lib.rs
tests/integration/query_processing/test_write_path.rs

Fix executing multiple statements

---

bindings/javascript/__test__/better-sqlite3.spec.mjs

This PR adds tests for the [`expand()`](https://github.com/WiseLibs/better-sqlite3/blob/master/docs/api.md#expandtogglestate---this) method of the better-sqlite3 API.
It can't be implemented in limbo right now, because the table names aren't surfaced in the `Statement` object (in core).

bind/js: add tests for expand

---

README.md

There is confusion (one could say, discord) between discords.

clarify discord situation

---

core/storage/btree.rs

Let's help out Antithesis to find interesting bugs.

core/storage: Switch to turso_assert in btree.rs

---

bindings/java/src/test/java/tech/turso/jdbc4/JDBC4StatementTest.java

In reponse to [discord discussion](https://discord.com/channels/1258658826257961020/1385754749634084885/1390535068401012858), I thought it would be better to add a test to show how JDBC4Statement can be used.

Add multi select test in JDBC4StatementTest

---

core/storage/btree.rs
core/storage/sqlite3_ondisk.rs
core/translate/compound_select.rs
core/translate/emitter.rs
core/translate/plan.rs
core/translate/result_row.rs
core/translate/select.rs
core/vdbe/execute.rs
core/vdbe/explain.rs
core/vdbe/insn.rs
testing/insert.test
testing/select.test
tests/integration/fuzz/mod.rs

Support except operator for Compound select 

---

Makefile

The compatibility test suite fails on older versions of TCL, because they didn't handle characters outside the Basic Multilingual Plane (BMP) properly. TCL 8.6 fixed this problem ([source](https://wiki.tcl-lang.org/page/emoji+with+Tcl%2FTk+8.6)).
MacOS comes with an older TCL 8.5.9, so running compatibility tests locally on the default TCL will give this error:
```
(testing/testing.db)                        Running test: unicode-emoji
Test FAILED: SELECT unicode('ð   ');
returned '240'
expected '128522'
make: *** [test-compat] Error 1
```
This PR adds a target in the Makefile to enforce that TCL 8.6+ is used. If not, it will fail with a message like this:
```
tclsh 9.0.2 found — need 11.12.13+
make: *** [check-tcl-version] Error 1
```

Enforce TCL 8.6+ in compatibility tests

---

core/storage/btree.rs
core/storage/sqlite3_ondisk.rs

Continuation from #2031 -- some variable extractions and comments

Btree: more balance docs

---

core/translate/schema.rs

This PR normalizes the table name identifier by removing quotes to improve SQLite compatibility. Fixes https://github.com/tursodatabase/turso/issues/1964

Ignore double quotes around table names

---

cli/commands/import.rs

SQLite creates a table if it does not exists, but we just silently ignore the data. Let's add an error if table does not exist until we fix this.
Refs #2079

cli: Fail import command if table does not exists

---

README.md

Biologically gopher is closer to beavers, than to hamsters, so it will be much more correct to use beaver emoji.
And yes, if you merge this MR I would be proud of my contribution into open source.

Gopher is biologically closer to beavers than hamsters

---

bindings/javascript/__test__/better-sqlite3.spec.mjs
bindings/javascript/__test__/sync.spec.mjs
bindings/javascript/index.d.ts
bindings/javascript/src/lib.rs
bindings/javascript/wrapper.js
core/lib.rs

Six more tests passing on Turso. The commits can be reviewed separately.

bindings/js: fix more tests

---

simulator/generation/plan.rs
simulator/generation/property.rs

Instead of e.g.:
> Error: failed with error: 'InternalError("`SELECT * FROM sparkling_kuh WHERE (sparkling_kuh.warmhearted_bowden > 'givhaqhwibn') ` should return no values for table `sparkling_kuh`")'
Now you get:
> Error: failed with error: 'InternalError("Assertion '`SELECT * FROM sparkling_kuh WHERE (sparkling_kuh.warmhearted_bowden > 'givhaqhwibn') ` should return no values for table `sparkling_kuh`' failed: expected no rows but got 1 rows: \"-37703991.25525856, sleek_leeder, passionate_deleuze, -2463056772.592847, shining_kuo, polite_mcbarron, X'616D626974696F75735F647261676F6E6F776C', warmhearted_bekken\"")'

sim: provide additional context in assertion failures

---

simulator/generation/query.rs

simulator: Disable `INSERT INTO .. SELECT` for being slow

---

core/io/unix.rs
core/storage/btree.rs
core/storage/database.rs
core/storage/pager.rs
core/storage/sqlite3_ondisk.rs
core/storage/wal.rs
core/translate/compound_select.rs
core/translate/emitter.rs
core/translate/expr.rs
core/translate/mod.rs
core/vdbe/builder.rs
core/vdbe/mod.rs

Span creation in debug mode is very slow and impacts our ability to run the Simulator faster.

make most instrumentation levels to be Debug or Trace instead

---

core/io/io_uring.rs
core/io/mod.rs
core/storage/btree.rs
core/storage/sqlite3_ondisk.rs
core/storage/wal.rs
tests/integration/query_processing/test_btree.rs

one of the last remnants of some original verbosity

Replace verbose IO Completion methods with helpers

---

Makefile
core/mvcc/cursor.rs
core/mvcc/database/mod.rs
core/mvcc/database/tests.rs
core/storage/btree.rs
core/storage/pager.rs
core/vdbe/execute.rs
testing/cli_tests/mvcc.py
testing/pyproject.toml

Bit-rot happened. Bring MVCC back from the dead.

Reanimate MVCC

---

core/schema.rs
core/storage/btree.rs
core/storage/pager.rs
core/util.rs

This PR make it simpler to block async operations instead of creating sync equivalent functions. eg.: `get_page_size` and `get_page_size_async`. All functions should be async by default, and making them block should more explicit.
Also makes it easier to grep for top-level uses of blocking code without needing to "go to definition".

Simplify blocking operations – add `io.block(fn)` for IO trait implementors

---

core/storage/pager.rs
core/storage/wal.rs
tests/integration/common.rs

Closes #2188 
Closes #2194 
Doesn't fix #2192 but adds an ignored test

fix/pager/cacheflush: cacheflush shouldn't commit

---

COMPAT.md

page_size pragma: #2053
RowData opcode: #1756

compat: change page_size pragma and RowData opcode to yes

---

core/schema.rs
testing/alter_table.test

BTreeTable::to_sql: wrap special column names in brackets

---

antithesis-tests/stress-composer/first_setup.py
antithesis-tests/stress-composer/parallel_driver_alter_table.py
antithesis-tests/stress-composer/parallel_driver_create_index.py
antithesis-tests/stress-composer/parallel_driver_create_table.py
antithesis-tests/stress-composer/parallel_driver_delete.py
antithesis-tests/stress-composer/parallel_driver_drop_index.py
antithesis-tests/stress-composer/parallel_driver_drop_table.py
antithesis-tests/stress-composer/parallel_driver_insert.py
antithesis-tests/stress-composer/parallel_driver_integritycheck.py
antithesis-tests/stress-composer/parallel_driver_rollback.py
antithesis-tests/stress-composer/parallel_driver_schema_rollback.py
antithesis-tests/stress-composer/parallel_driver_update.py
antithesis-tests/stress-composer/shuffle-run.sh
bindings/python/src/lib.rs

Improve the Antithesis parallel drivers:
* Enable indexes in the runs.
* Add `CREATE INDEX` and `DROP INDEX` parallel drivers.
* Add `CREATE TABLE`, `DROP TABLE`, and `ALTER TABLE` parallel drivers.

Improve Antithesis tests

---

core/storage/btree.rs
core/storage/header_accessor.rs
core/storage/pager.rs

Make `add_dirty` helper to set flag and add page to the dirt list. This makes API safer as now its harder to do one thing and forget about another (which can lead to DB corruption).

make add dirty to change flag and also add page to the dirty list

---

core/lib.rs
core/storage/page_cache.rs
core/storage/pager.rs
core/storage/wal.rs
core/vdbe/mod.rs

Let's make sure we don't end up in a weird situation by appending frames one by one and we can later think of optimizations.

Append WAL frames one by one

---

packages/turso-serverless/src/compat.ts
packages/turso-serverless/src/error.ts
packages/turso-serverless/src/index.ts
packages/turso-serverless/src/protocol.ts
packages/turso-serverless/src/session.ts
packages/turso-serverless/src/statement.ts

Add an explicit error type so application can actually do error handling...

serverless: Add DatabasError type

---

COMPAT.md

There's no such statement in SQLite.

remove upsert statement from COMPAT.md

---

COMPAT.md
core/pragma.rs
core/storage/sqlite3_ondisk.rs
core/translate/pragma.rs
vendored/sqlite3-parser/src/parser/ast/mod.rs

Do not allow setting it. That ship has sailed around 2005.

implement the pragma encoding

---

core/io/io_uring.rs

trying to pull bite sized adjustments out of other open PR's

io_uring: use Arc pointer for user data of entries

---

core/translate/planner.rs
core/translate/update.rs
testing/cli_tests/extensions.py
testing/update.test

Fix error handling when binding column references while translating the UPDATE statement

---

COMPAT.md
core/translate/delete.rs
core/translate/emitter.rs
core/translate/expr.rs
core/translate/insert.rs
core/translate/mod.rs
core/translate/update.rs
core/vdbe/execute.rs
testing/insert.test
testing/update.test

They are very similar. DELETE is very different, so that one we'll do it later.

Implement the Returning statement for inserts and updates

---

scripts/merge-pr.py

The script as it is now, about ~50% of the time will incorrectly mark contributor PR's as `Closed` instead of `Merged` after merging.
We are super fortunate to have such an awesome community here working on this project, let's make sure that all our contributors github profiles are reflecting the work they are putting in :smile:

Fix merge script to prevent incorrectly marking merged contributor PRs as closed

---

core/error.rs
core/vdbe/execute.rs
core/vdbe/mod.rs

vdbe: Disallow checkpointing in transaction

---

COMPAT.md
core/translate/expr.rs
core/vdbe/execute.rs
core/vdbe/explain.rs
core/vdbe/insn.rs
testing/select.test

Implement IN queries.
It is currently as todo!(), but my main motivation is that scavenging for EXPLAINs, that pattern, at least in simple queries like SELECT ... IN (1,2,3) uses the AddImm instruction we just added.

IN queries

---

Makefile
scripts/merge-pr.py
scripts/pyproject.toml
uv.lock

Fix merge-py.py script to use github CLI and add makefile command

---

core/benches/mvcc_benchmark.rs
core/lib.rs
core/mvcc/cursor.rs
core/mvcc/database/mod.rs
core/mvcc/database/tests.rs
core/mvcc/mod.rs
core/storage/btree.rs
core/storage/wal.rs
core/types.rs
core/vdbe/execute.rs
core/vdbe/mod.rs

**draft** because I need to fix tests now since they can't work with random payloads without properly serialize them.

core/mvcc: Persist changes through pager on commit

---

bindings/rust/tests/transaction_isolation_fuzz.rs

This PR is now ready, since i cannot find any new bugs with the fuzzer.
- adds `PRAGMA wal_checkpoint` to transaction isolation fuzz test
#2360    
#2362 
#2365 
#2366 
#2367
#2380

test/fuzz/transactions: add "PRAGMA wal_checkpoint" to txn isolation fuzz test

---

core/storage/wal.rs

Closes #2421
We have some kind of transaction-local hack (`start_pages_in_frames`) for bookkeeping how many pages are currently in the in-memory WAL frame cache, I assume for performance reasons or whatever.
`wal.rollback()` clears all the frames from `shared.frame_cache` that the rollbacking tx is allowed to clear, and then truncates `shared.pages_in_frames` to however much its local `start_pages_in_frames` value was.
In `complete_append_frame`, we check if `frame_cache` has that key (page) already, and if not, we add it to `pages_in_frames`.
However, `wal.rollback()` never _removes_ the key (page) if its value is empty, so we can end up in a scenario where the `frame_cache` key for `page P` exists but has no frames, and so `page P` does not get added to `pages_in_frames` in …

fix/wal: remove start_pages_in_frames_hack to prevent checkpoint data loss

---

Cargo.lock
core/io/mod.rs
tests/Cargo.toml

Relax I/O configuration attribute to cover all Unixes

---

core/vdbe/execute.rs

The built-in `unreachable!` macro, believe it or not is just an alias for `panic!` and does not actually provide the compiler with a hint that the path is not reachable.
This provides a wrapper around the actual `std::hint::unreachable_unchecked()`, to be used only in the very hot path of `execute` where it is not possible to be the incorrect variant.

Add load_insn macro for compiler hint in vdbe::execute hot path

---

COMPAT.md
extensions/regexp/src/lib.rs
testing/cli_tests/extensions.py

This PR adds RegExp Capture to regexp module

Add regexp capture

---

core/ext/dynamic.rs
testing/cli_tests/extensions.py

Fix panic on loading extension on brand new connection

---

core/translate/alter.rs
core/vdbe/execute.rs
core/vdbe/explain.rs
core/vdbe/insn.rs

```
`ALTER TABLE _ ADD COLUMN _`/limbo_add_column/
time:   [2.1199 ms 2.1921 ms 2.2756 ms]
change: [-85.983% -85.416% -84.716%] (p = 0.00 < 0.05)
Found 13 outliers among 100 measurements (13.00%)
6 (6.00%) high mild
7 (7.00%) high severe
`ALTER TABLE _ ADD COLUMN _`/sqlite_add_column/
time:   [10.358 ms 10.404 ms 10.469 ms]
change: [-6.2566% -2.3515% +0.2046%] (p = 0.21 > 0.05)
No change in performance detected.
Found 14 outliers among 100 measurements (14.00%)
2 (2.00%) high mild
12 (12.00%) high severe
```

Direct schema mutation – add `AddColumn` instruction

---

core/storage/buffer_pool.rs
core/storage/mod.rs
core/storage/slot_bitmap.rs

No semantic changes here, just name changing for to prevent confusion as @sivukhin pointed out.

Rename page -> slot for arenas + buffer pool

---

core/benches/mvcc_benchmark.rs
core/lib.rs
core/mvcc/database/mod.rs
core/mvcc/database/tests.rs
core/storage/btree.rs
core/storage/state_machines.rs
core/vdbe/execute.rs
core/vdbe/mod.rs

Adds more state machines and does some minor adjustments in some other functions like `commit_tx` and `execute`.

More State machines

---

docs/manual.md

I modified the `docs/manual.md` file to store the current I/O model that Turso follows. I want some feedback on the text and on the design as well!

Document the I/O model

---

core/storage/btree.rs
core/storage/pager.rs
core/storage/sqlite3_ondisk.rs

Otherwise page size 65536 will not work as casting to u16 will make it wrap around to 0.

Fix: do computations on usable_space as usize, not as u16

---

README.md

should have been added to the previous commit

add missing closing tag

---

core/schema.rs
testing/insert.test

Fix column nullability constraint

---

core/lib.rs

- for example CDC pragma execute create table under the hood

properly execute pragmas - they may require some IO

---

.github/workflows/napi-sync.yml
.github/workflows/napi.yml
.github/workflows/python.yml

They're very close to end of life and we're having macOS runner availability problems.

github: Remove Intel Mac support

---

bindings/javascript/src/lib.rs
core/lib.rs
core/storage/database.rs
core/storage/encryption.rs
core/storage/pager.rs
core/storage/sqlite3_ondisk.rs
core/storage/wal.rs
core/translate/pragma.rs

Previously, the encryption module had hardcoded a lot of things. This refactor makes it slightly nice and makes it configurable. 
Right now cipher algorithm is assumed and hardcoded, I will make that configurable in the upcoming PR

refactor encryption module and make it configurable

---

core/io/unix.rs

Switch to F_FULLSYNC on Darwin

---

core/storage/btree.rs

Things that were just wrong:
1. No pages other than the root page were checked, because no looping was done. Add a loop.
2. Rightmost child page was never added to page stack. Add it.
New integrity check features:
- Add overflow pages to stack as well
- Check that no page is referenced more than once in the tree

Fix several issues with integrity_check

---

PERF.md

Update TPC-H running instructions in PERF.md

---

.github/workflows/go.yml
Cargo.lock
README.md
bindings/go/Cargo.toml
bindings/go/README.md
bindings/go/build_lib.sh
bindings/go/connection.go
bindings/go/embedded.go
bindings/go/rows.go
bindings/go/rs_src/lib.rs
bindings/go/rs_src/rows.rs
bindings/go/rs_src/statement.rs
bindings/go/rs_src/types.rs
bindings/go/stmt.go
bindings/go/turso_test.go
bindings/go/turso_unix.go
bindings/go/turso_windows.go
bindings/go/types.go

Also rename Limbo -> Turso while we are here..

Rename Go driver to `turso` to not conflict with sqlite3

---

simulator/main.rs
simulator/runner/watch.rs

add sqlite integrity check back

---

COMPAT.md
core/translate/insert.rs
core/translate/mod.rs
core/translate/upsert.rs
testing/all.test
testing/upsert.test

This PR closes #2019
Implements https://sqlite.org/lang_upsert.html

Implement UPSERT

---

core/lib.rs
core/util.rs
tests/integration/query_processing/encryption.rs

Support cipher and encryption key URI options

---

core/storage/wal.rs

Fixes https://github.com/tursodatabase/turso/issues/2704
The PR decrypts the page referred to by the WAL frame while reading raw frames.

Support encryption for raw WAL frames

---

simulator-docker-runner/Dockerfile.simulator

otherwise simulator profiles will not build as it uses the new if let syntax

Upgrade Rust version in simulator build Dockerfile

---

core/vdbe/execute.rs

needed to support opening in Gorm

Return sqlite_version() without being initialized

---

Makefile
core/function.rs
core/schema.rs
core/translate/alter.rs
core/util.rs
core/vdbe/execute.rs
core/vdbe/explain.rs
core/vdbe/insn.rs
parser/src/ast.rs
parser/src/ast/fmt.rs
parser/src/lexer.rs
parser/src/parser.rs
testing/alter_column.test
testing/alter_table.test

Implement `ALTER COLUMN` as described here: https://github.com/tursodatabase/libsql/blob/main/libsql-sqlite3/doc/libsql_extensions.md#altering-columns

Implement libSQL's `ALTER COLUMN` extension

---

COMPAT.md
bindings/python/src/lib.rs
cli/app.rs
cli/mcp_server.rs
core/lib.rs
core/translate/mod.rs
core/translate/pragma.rs
core/translate/schema.rs
scripts/limbo-sqlite3
sync/engine/src/database_sync_engine.rs
tests/integration/common.rs
tests/integration/functions/test_wal_api.rs
tests/integration/query_processing/encryption.rs
tests/integration/query_processing/test_write_path.rs

It's not tested properly so let's mark it as experimental for now.
Fixes #2775

core: Make strict schema support experimental

---

.github/workflows/napi-sync.yml
.github/workflows/napi.yml
bindings/javascript/README.md
bindings/javascript/package.json
sync/javascript/package.json

I have ARM locally and absence of package complicates local testing and development

build native package for ARM64

---

Cargo.lock
simulator/generation/plan.rs
simulator/model/mod.rs
simulator/runner/env.rs
sql_generation/Cargo.toml
sql_generation/generation/query.rs
sql_generation/generation/table.rs
sql_generation/model/query/select.rs

Use IndexSet for order preserving iteration instead of HashSet

Fix non-determinism in simulator 

---

core/lib.rs
core/storage/pager.rs

Fixes https://github.com/tursodatabase/turso/issues/2883

Prevent setting of encryption keys if already set

---

core/translate/optimizer/mod.rs

Convert `LEFT JOIN` to `INNER JOIN` when the result of `LEFT JOIN` can never be different from the result of an `INNER JOIN`
This is useful because 1. it uses less instructions and 2. it allows for join reordering due to inner join commutativity

optimizer: convert outer join to inner join if possible

---

tests/integration/common.rs
tests/integration/fuzz/mod.rs

Our current UPDATE/DELETE fuzz tests are coupled to the btree and do not exercise the VDBE code paths at all, so a separate one makes sense.
This test repeats the following:
- Creates one table with n columns
- Creates (0..=n) indexes
- Executes UPDATE/DELETE statements
- Asserts that both sqlite and tursodb have the same DB state after each stmt

test/fuzz: add UPDATE/DELETE fuzz test

---

bindings/javascript/packages/browser/package.json

add missing module type for browser package

---

core/types.rs
testing/compare.test

core: Fix integer/float comparison

---

core/json/jsonb.rs
core/json/mod.rs
testing/json.test

closes: #2820 
```
turso> select user->>'age' as age from json_user;
┌─────┐
│ age │
├─────┤
│  30 │
└─────┘
```

Fix jsonb functions check valid json string binary

---

packages/turso-serverless/src/connection.ts

serverless: Add Connection.reconnect() method

---

perf/throughput/turso/src/main.rs

perf/throughput/turso: Don't use spawn_blocking()

---

core/mvcc/database/mod.rs
tests/integration/fuzz_transaction/mod.rs

Commit messages contain explanations of each change.
Closes #3129 
Closes #3128

Fix 3 different MVCC bugs

---

core/storage/encryption.rs

...happens when encryption feature is disabled.

core/storage: Clean up unused import warning in encryption.rs

---

core/ext/mod.rs
core/lib.rs
core/vdbe/execute.rs

core: Wrap symbol table with RwLock

---

core/vtab.rs

core/vtab: Use AtomicPtr for table_ptr

---

core/schema.rs
core/storage/btree.rs
core/vdbe/execute.rs

core: Wrap MvCursor in Arc<RwLock<>>

---

core/storage/pager.rs

core: Wrap Pager dirty_pages in RwLock

---

core/incremental/cursor.rs
core/lib.rs
core/mvcc/persistent_storage/logical_log.rs
core/mvcc/persistent_storage/mod.rs

We don't need it for anything.

core/mvcc: Kill noop storage

---

core/mvcc/database/mod.rs
core/mvcc/persistent_storage/mod.rs
core/vdbe/execute.rs

mvcc: remove unused code related to is_logical_log()

---

core/storage/btree.rs
core/storage/encryption.rs

bugfix: clear reserved space for a reused page

---

core/vdbe/execute.rs

it's not emitted anywhere yet but still saw this bug

Fix program counter update in sequence test op

---

bindings/python/src/lib.rs
cli/app.rs
parser/src/parser.rs
whopper/main.rs

Fix .schema command for empty databases

---

core/translate/aggregation.rs
testing/offset.test

Fix ungrouped aggregate with offset clause

---

core/vdbe/execute.rs
testing/scalar-functions.test

length shall not count when it sees nullc

---

core/schema.rs

core/translate: rewrite default column value from identifier to string literal

---

core/translate/optimizer/mod.rs
testing/cli_tests/cli_test_cases.py
testing/cli_tests/extensions.py
testing/cli_tests/memory.py
testing/default_value.test
testing/select.test

Closes #3301
Not every identifier should be double-quoted

Remove double-quoted identifier assert

---

core/vdbe/execute.rs
tests/integration/functions/mod.rs
tests/integration/functions/test_sum.rs

sum() can throw integer overflow

---

stress/main.rs

Before, it omitted BEGIN/COMMIT/ROLLBACK statements which affects reproducibility

small improvement of stress testing tool

---

core/translate/alter.rs
core/vdbe/execute.rs
testing/alter_table.test
tests/integration/fuzz/mod.rs

Closes #3448. Nasty bug - see issue for details

Fix index bookkeeping in DROP COLUMN

---

core/lib.rs

Needed Elsewhere ™️ for fixing simulator `reopen_database()`

Add Database::indexes_enabled()

---

core/functions/printf.rs
testing/agg-functions.test

closes https://github.com/tursodatabase/turso/issues/3308

printf should truncates floats

---

core/translate/expr.rs

closes https://github.com/tursodatabase/turso/issues/3512

Resolve appropriate column name for rowid alias/PK

---

core/storage/encryption.rs
docs/manual.md

preview - https://github.com/tursodatabase/turso/blob/8d2ef700c9b087a7e2904c25052e4365395b33b3/docs/manual.md#encryption-1

Add encryption internals docs

---

core/translate/expr.rs
testing/join.test

Fix: JOIN USING should pick columns from left table, not right

---

core/translate/expr.rs
testing/affinity.test

closes https://github.com/tursodatabase/turso/issues/3478

core/translate: fix rowid affinity

---

.gitignore
core/lib.rs
core/mvcc/database/tests.rs
tests/integration/query_processing/test_transactions.rs

core/mvcc: Rename "-lg" to "-log"

---

core/translate/planner.rs
core/translate/select.rs

Disallow INDEXED BY / NOT INDEXED in select

---

core/mvcc/database/checkpoint_state_machine.rs

For insert-heavy checkpoints this gives a much higher chance of using the balance-quick subalgorithm instead of the more complex and slower balance-nonroot.

MVCC: do checkpoint writes in ascending order of rowid

---

core/incremental/compiler.rs
core/incremental/filter_operator.rs

Just overlook on our side that they were not generated before.

core/incremental: Implement "is null" and "is not null" tests for view filter
